package org.jetbrains.plugins.scala.testingSupport.specs2.specs2_2_12_4_0_0

import org.jetbrains.plugins.scala.testingSupport.specs2.Spec2ExampleUnitSpec

class Spec2_2_12_4_0_0_ExampleUnitSpec extends Spec2ExampleUnitSpec with Specs2_2_12_4_0_0_Base