package org.jetbrains.plugins.cbt.project

import com.intellij.openapi.externalSystem.service.task.ui.AbstractExternalSystemToolWindowFactory

class CbtTooolWindowFactory extends AbstractExternalSystemToolWindowFactory(CbtProjectSystem.Id)