package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_11.scalatest2_2_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestIgnoredSpecTest

class Scalate2_11_2_2_1_IgnoredTestTest extends Scalatest2_11_2_2_1_Base with ScalaTestIgnoredSpecTest