package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_11.scalatest2_2_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestDuplicateConfigTest

class Scalatest2_11_2_2_1_DuplicateConfigTest extends Scalatest2_11_2_2_1_Base with ScalaTestDuplicateConfigTest
