package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_2_2.scala_2_11

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestPackageTest

class Scalatest_2_2_Scala_2_11_PackageTest extends Scalatest_2_2_Scala_2_11_Base
  with ScalaTestPackageTest
