package org.jetbrains.sbt.shell.process.utils

import com.intellij.execution.configurations.*
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.Project
import com.intellij.platform.eel.EelDescriptor
import com.intellij.platform.eel.provider.EelProviderUtil
import com.intellij.platform.eel.provider.utils.EelProjectUtils
import org.jetbrains.annotations.NonNls
import org.jetbrains.plugins.scala.extensions.*
import org.jetbrains.plugins.scala.project.Version
import org.jetbrains.sbt.SbtUtil.{detectSbtVersion as _, *}
import org.jetbrains.sbt.buildinfo.BuildInfo
import org.jetbrains.sbt.{Sbt, SbtUtil, SbtVersion, SbtVersionCapabilities, normalizedLocalPath}

import java.io.IOException
import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}

//noinspection ApiStatus,UnstableApiUsage
private[shell] class SbtSettingsInjector(project: Project) {

  private val Log = Logger.getInstance(getClass)
  private val eelDescriptor = EelProviderUtil.getEelDescriptor(project)

  @NonNls private def pluginResolverSetting: String = {
    val repoPath: String = SbtUtil.getRepoDir(eelDescriptor).normalizedLocalPath
    raw"""resolvers += MavenCache("Scala Plugin Bundled Repository", file(raw"$repoPath"))
         |""".stripMargin
  }

  def getOrCreateSettingsFileWithInjectedSettings(
    runId: SbtShellRunId,
    projectSbtVersion: SbtVersion,
    addPluginCommandSupported: Boolean,
    vmOptions: ParametersList
  ): Path = {
    val settingsFile: Path =
      getOrCreateExtraSbtSettingsFile(
        addPluginCommandSupported,
        vmOptions,
        projectSbtVersion.binaryVersion,
        eelDescriptor
      )

    val settingsAll: Seq[String] = getSettingsToInject(projectSbtVersion)
    // caution! writes injected plugin settings to the user's global sbt config if addPlugin command is not supported
    injectSettings(
      projectSbtVersion,
      runId,
      !addPluginCommandSupported,
      settingsFile,
      settingsAll
    )

    settingsFile
  }

  private def getSettingsToInject(projectSbtVersion: SbtVersion): Seq[String] = {
    val injectPluginsSettings = getInjectedPluginsCommands(projectSbtVersion)
    pluginResolverSetting +: injectPluginsSettings
  }

  /** Plugins injected into user's global sbt build. */
  // TODO add configurable plugins somewhere for users and via API; factor this stuff out
  // this *might* get messy if multiple IDEA projects start messing with the global settings.
  // but we should be fine since it is written before every sbt boot
  private def getInjectedPluginsCommands(sbtVersion: SbtVersion): Seq[String] = {
    val sbtBinaryVersion = sbtVersion.binaryVersion
    val sbtStructureVersion = BuildInfo.sbtStructureVersion
    val sbtIdeaShellVersion = BuildInfo.sbtIdeaShellVersion

    val sbtStructurePluginBinVersion = structurePluginBinaryVersion(sbtVersion)
    Log.debug(s"sbtBinVersion = $sbtBinaryVersion")
    Log.debug(s"sbtStructurePluginBinVersion = $sbtStructurePluginBinVersion")
    Log.debug(s"sbtIdeaShellBinVersion = $sbtBinaryVersion")

    sbtBinaryVersion.presentation match {
      case _ =>
        Seq(
          s"""addSbtPlugin("org.jetbrains.scala" % "sbt-structure-extractor" % "$sbtStructureVersion", "$sbtStructurePluginBinVersion")""",
          s"""addSbtPlugin("org.jetbrains.scala" % "sbt-idea-shell" % "$sbtIdeaShellVersion", "$sbtBinaryVersion")""",
        )
      // SCL-22858 compiler bytecode indices are disabled in sbt shell
      // ++ compilerIndicesPlugin // works for 0.13.5+, for older versions it will be ignored
    }
  }

  private def getOrCreateExtraSbtSettingsFile(
    addPluginCommandSupported: Boolean,
    vmParametersList: ParametersList,
    sbtBinVersion: Version,
    eelDescriptor: EelDescriptor
  ): Path = {
    val globalPluginsDir = globalPluginsDirectory(SbtVersion(sbtBinVersion), vmParametersList, eelDescriptor)
    // workaround: --addPluginSbtFile fails if global plugins dir does not exist. https://youtrack.jetbrains.com/issue/SCL-14415
    if (!globalPluginsDir.exists) {
      Files.createDirectories(globalPluginsDir)
    }

    if (addPluginCommandSupported)
      EelProjectUtils.createTemporaryFile(project, "idea", Sbt.Extension, true).toRealPath()
    else
      globalPluginsDir / "idea.sbt"
  }

  /**
   * Inject custom settings or plugins into an sbt directory.
   * This seems to be the most straightforward way to add our own sbt settings
   */
  private def injectSettings(
    sbtVersion: SbtVersion,
    runId: SbtShellRunId,
    guardSettings: Boolean,
    settingsFile: Path,
    settings: Seq[String]
  ): Unit = {
    @NonNls
    val header =
      """// Generated by IntelliJ-IDEA Scala plugin.
        |// Adds settings when starting sbt from IDEA.
        |// Manual changes to this file will be lost.
        |""".stripMargin
    val SeqFqn = SbtVersionCapabilities.collectionsSeqClassFqn(sbtVersion)
    val settingsString = settings.mkString(s"$SeqFqn(\n", ",\n", "\n)")

    // any idea-specific settings should be added conditional on sbt being started from idea
    val guardedSettings: String =
      if (guardSettings)
        s"""if (java.lang.System.getProperty("${SpecialSbtVmOptions.IdeaRunIdVmOption}", "false") == "$runId") $settingsString else $SeqFqn.empty"""
      else
        settingsString

    val content = header + "\n" + guardedSettings

    try {
      Files.writeString(settingsFile, content, StandardCharsets.UTF_8)
    } catch {
      case x: IOException =>
        Log.error(s"unable to write ${settingsFile.toCanonicalPath} which is required for sbt shell support", x)
        throw x
    }
  }
}