package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_10.scalatest1_9_2

import org.jetbrains.plugins.scala.testingSupport.scalatest.ScalaTestDuplicateConfigTest

class Scalatest2_10_1_9_2_DuplicateConfigTest extends Scalatest2_10_1_9_2_Base with ScalaTestDuplicateConfigTest
