package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_10.scalatest1_9_2

import org.jetbrains.plugins.scala.testingSupport.scalatest.ScalaTestPackageTest

class Scalatest2_10_1_9_2_PackageTest extends Scalatest2_10_1_9_2_Base with ScalaTestPackageTest
