package scala.tasty.reflect

trait CompilerInterface {
  type Context <: AnyRef
  type Settings <: AnyRef
  type Tree <: AnyRef
  type PackageClause <: Tree
  type Statement <: Tree
  type Import <: Statement
  type Definition <: Statement
  type PackageDef <: Definition
  type ClassDef <: Definition
  type TypeDef <: Definition
  type DefDef <: Definition
  type ValDef <: Definition
  type Term <: Statement
  type Ref <: Term
  type Ident <: Ref
  type Select <: Ref
  type Literal <: Term
  type This <: Term
  type New <: Term
  type NamedArg <: Term
  type Apply <: Term
  type TypeApply <: Term
  type Super <: Term
  type Typed <: Term
  type Assign <: Term
  type Block <: Term
  type Closure <: Term
  type If <: Term
  type Match <: Term
  type GivenMatch <: Term
  type Try <: Term
  type Return <: Term
  type Repeated <: Term
  type Inlined <: Term
  type SelectOuter <: Term
  type While <: Term
  type TypeTree <: Tree
  type Inferred <: TypeTree
  type TypeIdent <: TypeTree
  type TypeSelect <: TypeTree
  type Projection <: TypeTree
  type Singleton <: TypeTree
  type Refined <: TypeTree
  type Applied <: TypeTree
  type Annotated <: TypeTree
  type MatchTypeTree <: TypeTree
  type ByName <: TypeTree
  type LambdaTypeTree <: TypeTree
  type TypeBind <: TypeTree
  type TypeBlock <: TypeTree
  type TypeBoundsTree <: Tree
  type WildcardTypeTree <: Tree
  type CaseDef <: Tree
  type TypeCaseDef <: Tree
  type Bind <: Tree
  type Unapply <: Tree
  type Alternatives <: Tree
  type TypeOrBounds <: AnyRef
  type NoPrefix <: TypeOrBounds
  type TypeBounds <: TypeOrBounds
  type Type <: TypeOrBounds
  type ConstantType <: Type
  type TermRef <: Type
  type TypeRef <: Type
  type SuperType <: Type
  type Refinement <: Type
  type AppliedType <: Type
  type AnnotatedType <: Type
  type AndType <: Type
  type OrType <: Type
  type MatchType <: Type
  type ByNameType <: Type
  type ParamRef <: Type
  type ThisType <: Type
  type RecursiveThis <: Type
  type RecursiveType <: Type
  type LambdaType[ParamInfo] <: Type
  type MethodType <: LambdaType[Type]
  type PolyType <: LambdaType[TypeBounds]
  type TypeLambda <: LambdaType[TypeBounds]
  type ImportSelector <: AnyRef
  type SimpleSelector <: ImportSelector
  type RenameSelector <: ImportSelector
  type OmitSelector <: ImportSelector
  type Id <: AnyRef
  type Signature <: AnyRef
  type Position <: AnyRef
  type SourceFile <: AnyRef
  type Comment <: AnyRef
  type Constant <: AnyRef
  type Symbol <: AnyRef
  type Flags
  type ImplicitSearchResult <: AnyRef
  type ImplicitSearchSuccess <: ImplicitSearchResult
  type ImplicitSearchFailure <: ImplicitSearchResult
  type DivergingImplicit <: ImplicitSearchFailure
  type NoMatchingImplicits <: ImplicitSearchFailure
  type AmbiguousImplicits <: ImplicitSearchFailure
}
