package org.jetbrains.plugins.scala.testingSupport.utest.utest_0_9.scala2_13_old_syntax

import org.jetbrains.plugins.scala.testingSupport.utest.utest_0_9.scala2_13.UTest_0_9_Scala_2_13_TestBase

abstract class UTest_0_9_Scala_2_13_TestBase_old_syntax extends UTest_0_9_Scala_2_13_TestBase
