package org.jetbrains.plugins.scala.testingSupport.utest.utest_0_9.scala2_13_old_syntax

import org.jetbrains.plugins.scala.testingSupport.utest.utest_0_8.UTest_0_8_BeforeAfterTest
import org.jetbrains.plugins.scala.testingSupport.utest.utest_0_9.scala2_13.UTest_0_9_Scala_2_13_TestBase

class UTest_0_9_Scala_2_13_BeforeAfterTest_old_syntax
  extends UTest_0_9_Scala_2_13_TestBase_old_syntax
    with UTest_0_8_BeforeAfterTest