package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_0.scala_2_12

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestWholeSuiteTest

class Scalatest_3_0_Scala_2_12_WholeSuiteTest extends Scalatest_3_0_Scala_2_12_Base
  with ScalaTestWholeSuiteTest
