package org.jetbrains.plugins.scala.lang.psi.light

import com.intellij.psi._
import org.jetbrains.plugins.scala.extensions._
import org.jetbrains.plugins.scala.lang.psi.api.statements.ScFunction
import org.jetbrains.plugins.scala.lang.psi.api.toplevel.typedef.ScTrait
import org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef.TypeDefinitionMembers
import org.jetbrains.plugins.scala.lang.psi.types._
import org.jetbrains.plugins.scala.lang.psi.types.api.designator.ScDesignatorType
import org.jetbrains.plugins.scala.lang.psi.types.recursiveUpdate.ScSubstitutor

/**
 * Represents Scala functions for Java.
 *
 * @param cClass Concrete class for which the inherited function is materialized in this wrapper.
 *               It's empty (None) if the original `delegate` function exists physically in the source code of the class.
 *               It contains Some method when the method is generated by the compiler.
 *
 *               These are known cases when that can happen: (the list might be not exhaustive)
 *               - The method was mixed-in from some trait (methods with bodies).<br>
 *                 Example: {{{
 *                     trait T { def foo: Int ; def bar: Int = 42 }
 *                     abstract class C extends T
 *                 }}}
 *                 Here the compiler will insert a copy of method `def bar` to class `C` at one of the later compilation phases.<br>
 *                 (calculated in [[PsiClassExt.processWrappersForSignature]] in `concreteClassFor`)
 *               - The method was exported using "export" statement.<br>
 *                 Example: {{{
 *                     object O { def foo: Int = 23}
 *                     class C { export O.foo }
 *                 }}}
 *                 Here the compiler will insert a forwarder method `def foo: Int = O.foo` to class `C`<br>
 *                 (calculated in [[PsiClassExt.processWrappersForSignature]] in `concreteClassFor`)
 *               - Secondary scala constructors
 *
 * @param substitutor member type substitution as seen from the class where this method is materialized
 *
 */
class ScFunctionWrapper(
  override val delegate:     ScFunction,
  isStatic:                  Boolean,
  isAbstract:                Boolean,
  val isExportForwarder:     Boolean,
  private[scala] val cClass: Option[PsiClass],
  substitutor:               ScSubstitutor,
  isJavaVarargs:             Boolean = false
) extends PsiMethodWrapper(
  delegate,
  delegate.getName,
  PsiMethodWrapper.containingClass(delegate, cClass, isStatic)
) {

  /**
   * @return true - if the method represents a method in a class that was mixed-in from a trait and does not exist in the class sources.
   *         Note, such methods will still physically exist in the class byte code. This is because under the hood
   *         scala compiled copies bodies of mixed in methods with bodies to the class to which the trait is mixed
   * @note I am not 100% sure in the implementation whether all the assumptions are correct.
   *       It seems the more reliable approach would be to propagate this information from the place where the wrapper is created
   *       (Somewhere in [[PsiClassExt.processWrappersForSignature]]?)
   */
  def isMixedInSyntheticMethod: Boolean = {
    cClass.isDefined &&
      !isExportForwarder &&
      !isConstructor &&
      // handle classes with companions - ignore generated static forwarders for object methods in the companion class
      // See org.jetbrains.plugins.scala.javaHighlighting.JavaHighlightingTest.testUsingMixedInMethodsInObjectWithCompanionClass
      !isStatic
  }

  override def isConstructor: Boolean = delegate.isConstructor

  override protected def modifierList: PsiModifierList = {
    def isSyntheticMethodFromTrait = cClass.nonEmpty && delegate.containingClass.isInstanceOf[ScTrait]

    val isOverride = !isStatic && (isSyntheticMethodFromTrait || delegate.hasModifierProperty("override"))
    ScLightModifierList(delegate, isStatic, isAbstract, getContainingClass.isInstanceOf[ScTrait], isOverride)
  }

  override protected def parameters: Seq[PsiParameter] =
    delegate.parameterClausesWithExtension()
      .flatMap(_.effectiveParameters)
      .map(ScLightParameter.from(_, substitutor.followed(methodTypeParamsSubstitutor), isJavaVarargs))

  override protected def typeParameters: Seq[PsiTypeParameter] =
    delegate.typeParameters.map(new ScLightTypeParam(_, substitutor))

  override protected def returnScType: ScType = {
    val isConstructor = delegate.isConstructor
    if (isConstructor) null
    else {
      val originalReturnType = delegate.returnType.getOrAny
      val inheritedReturnType = PsiMethodWrapper.substituteReturnType(
        originalReturnType,
        substitutor,
        isInheritedStaticForwarder = isStatic && cClass.nonEmpty
      )
      methodTypeParamsSubstitutor(inheritedReturnType)
    }
  }

  private def methodTypeParamsSubstitutor: ScSubstitutor =
    ScSubstitutor.bind(delegate.typeParameters, this.getTypeParameters.map(ScDesignatorType(_)))

  override def getNameIdentifier: PsiIdentifier = delegate.getNameIdentifier

  override def isWritable: Boolean = getContainingFile.isWritable

  override def setName(name: String): PsiElement = {
    if (!delegate.isConstructor) delegate.setName(name)
    else this
  }

  override def isVarArgs: Boolean = isJavaVarargs

  override def findSuperMethods(): Array[PsiMethod] = {
    if (isStatic)
      return PsiMethod.EMPTY_ARRAY

    def wrap(superSig: PhysicalMethodSignature): PsiMethod = superSig.method match {
      case f: ScFunction =>
        new ScFunctionWrapper(
          delegate = f,
          isStatic = isStatic,
          isAbstract = f.isAbstractMember,
          isExportForwarder = superSig.exportedInfo.isDefined,
          cClass = None,
          substitutor = superSig.substitutor,
          isJavaVarargs = isJavaVarargs
        )
      case m => m
    }

    val superSignatures =
      TypeDefinitionMembers.getSignatures(getContainingClass)
        .forName(delegate.name)
        .findNode(delegate)
        .map(_.supers.map(_.info).filterByType[PhysicalMethodSignature])

    superSignatures.getOrElse(Seq.empty).mapToArray(wrap)(PsiMethod.ARRAY_FACTORY)
  }

  override def copy(): PsiElement =
    new ScFunctionWrapper(
      delegate = delegate.copy().asInstanceOf[ScFunction],
      isStatic = isStatic,
      isAbstract = isAbstract,
      isExportForwarder = isExportForwarder,
      cClass = cClass,
      substitutor = substitutor,
      isJavaVarargs = isJavaVarargs
    )
}

object ScFunctionWrapper {
  def unapply(wrapper: ScFunctionWrapper): Option[ScFunction] = Some(wrapper.delegate)
}
