package org.jetbrains.plugins.scala.testingSupport.utest.scala2_13.utest_0_7_1

import org.jetbrains.plugins.scala.testingSupport.utest.UTestNewSyntaxPackageTest

class UTestPackageTest_2_13_0_7_1 extends UTestTestBase_2_13_0_7_1 with UTestNewSyntaxPackageTest