package org.jetbrains.plugins.scala.testingSupport.utest.scala2_13

import org.jetbrains.plugins.scala.testingSupport.utest.UTestNewSyntaxPackageTest

class UTestPackageTest_2_13 extends UTestTestBase_2_13 with UTestNewSyntaxPackageTest