package org.jetbrains.plugins.scala.externalHighlighters

import com.intellij.openapi.vfs.VirtualFile

/**
 * @param files state for each file generated by compiler
 * @param progress the progress of the compilation
 * @param highlightOnCompilationFinished files that we must highlight only when compilation finished
 */
case class CompilerGeneratedState(files: Map[VirtualFile, FileCompilerGeneratedState],
                                  progress: Double,
                                  highlightOnCompilationFinished: Set[VirtualFile]) {

  def toHighlightingState: HighlightingState =
    files.view.mapValues(_.highlightings).toMap
}
