package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_1.scala_2_13

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestGoToSourceTest

class Scalatest_3_1_Scala_2_13_GoToSourceTest extends Scalatest_3_1_Scala_2_13_Base
  with ScalaTestGoToSourceTest
