package org.jetbrains.plugins.scala.testingSupport.utest.utest_0_8.scala2_13

import org.jetbrains.plugins.scala.testingSupport.utest.utest_0_8.UTest_0_8_BeforeAfterTest

class UTest_0_8_Scala_2_13_BeforeAfterTest extends UTest_0_8_Scala_2_13_TestBase with UTest_0_8_BeforeAfterTest