package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.given
import org.junit.Test

class AkkaHttpSemanticTest extends SemanticTestBase("com.typesafe.akka" %% "akka-http" % "10.5.3")("akka.http") {
  @Test def test(): Unit = doTest("""
    //akka.http.ParsingErrorHandler
    //akka.http.ccompat.MapHelpers
    akka.http.ccompat.QuerySeqOptimized
    akka.http.ccompat.pre213
    akka.http.ccompat.since213
    //akka.http.impl.engine.HttpIdleTimeoutException
    //akka.http.impl.engine.client.PoolFlow
    //akka.http.impl.engine.client.PoolId
    //akka.http.impl.engine.client.PoolMaster
    akka.http.impl.engine.client.ProxyConnectionFailedException
    //akka.http.impl.engine.client.pool.SlotContext
    //akka.http.impl.engine.client.pool.SlotState
    //akka.http.impl.engine.http2.BufferedOutlet
    //akka.http.impl.engine.http2.BufferedOutletExtended
    //akka.http.impl.engine.http2.ByteFlag
    //akka.http.impl.engine.http2.FrameEvent
    //akka.http.impl.engine.http2.GenericOutlet
    //akka.http.impl.engine.http2.GenericOutletSupport
    //akka.http.impl.engine.http2.Http2AlpnSupport
    //akka.http.impl.engine.http2.Http2ClientDemux
    //akka.http.impl.engine.http2.Http2Compliance
    //akka.http.impl.engine.http2.Http2Multiplexer
    //akka.http.impl.engine.http2.Http2MultiplexerSupport
    //akka.http.impl.engine.http2.Http2ServerDemux
    //akka.http.impl.engine.http2.HttpMessageRendering
    //akka.http.impl.engine.http2.IncomingFlowController
    //akka.http.impl.engine.http2.PriorityNode
    //akka.http.impl.engine.http2.PriorityTree
    //akka.http.impl.engine.http2.PullFrameResult
    //akka.http.impl.engine.http2.RequestRendering
    //akka.http.impl.engine.http2.ResponseRendering
    //akka.http.impl.engine.http2.StreamPrioritizer
    //akka.http.impl.engine.http2.hpack.ByteStringInputStream
    //akka.http.impl.engine.http2.hpack.HandleOrPassOnStage
    //akka.http.impl.engine.http2.hpack.Http2HeaderParsing
    //akka.http.impl.engine.http2.util.AsciiTreeLayout
    //akka.http.impl.engine.parsing.BoyerMoore
    //akka.http.impl.engine.parsing.NotEnoughDataException
    //akka.http.impl.engine.parsing.ParserOutput
    //akka.http.impl.engine.parsing.ParsingException
    //akka.http.impl.engine.parsing.SpecializedHeaderValueParsers
    //akka.http.impl.engine.rendering.RequestRenderingContext
    //akka.http.impl.engine.rendering.ResponseRenderingContext
    //akka.http.impl.engine.rendering.ResponseRenderingOutput
    //akka.http.impl.engine.server.InternalCustomHeader
    //akka.http.impl.engine.server.ServerTerminationDeadlineReached
    //akka.http.impl.engine.server.ServerTerminator
    //akka.http.impl.engine.server.UpgradeToOtherProtocolResponseHeader
    //akka.http.impl.engine.ws.FrameData
    akka.http.impl.engine.ws.FrameError
    akka.http.impl.engine.ws.FrameEventOrError
    //akka.http.impl.engine.ws.FrameHeader
    //akka.http.impl.engine.ws.FrameStart
    //akka.http.impl.engine.ws.Protocol
    //akka.http.impl.engine.ws.ProtocolException
    //akka.http.impl.engine.ws.Randoms
    //akka.http.impl.engine.ws.StreamingCharsetDecoder
    //akka.http.impl.engine.ws.StreamingCharsetDecoderInstance
    //akka.http.impl.engine.ws.UpgradeToWebSocketLowLevel
    //akka.http.impl.engine.ws.Utf8Decoder
    //akka.http.impl.model.JavaUri
    //akka.http.impl.model.UriJavaAccessor
    //akka.http.impl.model.parser.AcceptCharsetHeader
    //akka.http.impl.model.parser.AcceptEncodingHeader
    //akka.http.impl.model.parser.AcceptHeader
    //akka.http.impl.model.parser.AcceptLanguageHeader
    //akka.http.impl.model.parser.Base64Parsing
    //akka.http.impl.model.parser.CacheControlHeader
    //akka.http.impl.model.parser.CharacterClasses
    //akka.http.impl.model.parser.CommonActions
    //akka.http.impl.model.parser.CommonRules
    //akka.http.impl.model.parser.ContentDispositionHeader
    //akka.http.impl.model.parser.IpAddressParsing
    //akka.http.impl.model.parser.SimpleHeaders
    //akka.http.impl.model.parser.StringBuilding
    //akka.http.impl.model.parser.UriParser
    //akka.http.impl.model.parser.WebSocketHeaders
    //akka.http.impl.settings.ConnectionPoolSetup
    akka.http.impl.settings.HostConnectionPoolSetup
    //akka.http.impl.settings.HttpsProxySettingsImpl
    //akka.http.impl.settings.PreviewServerSettingsImpl
    //akka.http.impl.settings.RoutingSettingsImpl
    //akka.http.impl.settings.ServerSentEventSettingsImpl
    //akka.http.impl.util.ByteStringParserInput
    //akka.http.impl.util.DefaultNoLogging
    //akka.http.impl.util.EnhancedByteArray
    //akka.http.impl.util.EnhancedConfig
    //akka.http.impl.util.EnhancedRegex
    //akka.http.impl.util.EnhancedString
    //akka.http.impl.util.EventStreamLogger
    //akka.http.impl.util.J2SMapping
    //akka.http.impl.util.JavaAccessors
    //akka.http.impl.util.JavaVersion
    //akka.http.impl.util.LogMessages
    //akka.http.impl.util.ObjectRegistry
    //akka.http.impl.util.Renderable
    //akka.http.impl.util.S2JMapping
    //akka.http.impl.util.SingletonException
    //akka.http.impl.util.Timestamp
    //akka.http.impl.util.ToStringRenderable
    //akka.http.impl.util.ValueRenderable
    //akka.http.javadsl.ConnectHttpImpl
    //akka.http.javadsl.ConnectHttpsImpl
    //akka.http.javadsl.ConnectWithHttps
    //akka.http.javadsl.HandlerProvider
    //akka.http.javadsl.HostConnectionPool
    //akka.http.javadsl.HttpConnectionContext
    //akka.http.javadsl.HttpTerminated
    //akka.http.javadsl.HttpsConnectionContext
    akka.http.javadsl.OutgoingConnection
    //akka.http.javadsl.OutgoingConnectionBuilder
    //akka.http.javadsl.common.CsvEntityStreamingSupport
    //akka.http.javadsl.common.EntityStreamingSupport
    //akka.http.javadsl.common.JsonEntityStreamingSupport
    //akka.http.javadsl.common.PartialApplication
    //akka.http.javadsl.marshalling.Marshaller
    //akka.http.javadsl.marshalling.sse.EventStreamMarshalling
    akka.http.javadsl.model.ContentType
    akka.http.javadsl.model.MediaType
    //akka.http.javadsl.model.RequestResponseAssociation
    akka.http.javadsl.model.ResponseFuture
    //akka.http.javadsl.model.SslSessionInfo
    //akka.http.javadsl.model.Trailer
    //akka.http.javadsl.model.ws.Message
    akka.http.javadsl.model.ws.PeerClosedConnectionException
    //akka.http.javadsl.model.ws.WebSocketRequest
    //akka.http.javadsl.model.ws.WebSocketUpgrade
    akka.http.javadsl.model.ws.WebSocketUpgradeResponse
    akka.http.javadsl.server.AllDirectives
    //akka.http.javadsl.server.AuthenticationFailedRejection
    //akka.http.javadsl.server.AuthorizationFailedRejection
    //akka.http.javadsl.server.CircuitBreakerOpenRejection
    akka.http.javadsl.server.Complete
    akka.http.javadsl.server.CustomRejection
    //akka.http.javadsl.server.Directives
    //akka.http.javadsl.server.ExceptionHandler
    //akka.http.javadsl.server.ExpectedWebSocketRequestRejection
    //akka.http.javadsl.server.InvalidOriginRejection
    //akka.http.javadsl.server.InvalidRequiredValueForQueryParamRejection
    //akka.http.javadsl.server.JavaPathMatchers
    //akka.http.javadsl.server.MalformedFormFieldRejection
    //akka.http.javadsl.server.MalformedHeaderRejection
    //akka.http.javadsl.server.MalformedQueryParamRejection
    //akka.http.javadsl.server.MalformedRequestContentRejection
    //akka.http.javadsl.server.MethodRejection
    //akka.http.javadsl.server.MissingAttributeRejection
    //akka.http.javadsl.server.MissingCookieRejection
    //akka.http.javadsl.server.MissingFormFieldRejection
    //akka.http.javadsl.server.MissingHeaderRejection
    //akka.http.javadsl.server.MissingQueryParamRejection
    //akka.http.javadsl.server.PathMatcher0
    //akka.http.javadsl.server.PathMatcher1
    //akka.http.javadsl.server.PathMatcher10
    //akka.http.javadsl.server.PathMatcher11
    //akka.http.javadsl.server.PathMatcher12
    //akka.http.javadsl.server.PathMatcher13
    //akka.http.javadsl.server.PathMatcher14
    //akka.http.javadsl.server.PathMatcher15
    //akka.http.javadsl.server.PathMatcher16
    //akka.http.javadsl.server.PathMatcher17
    //akka.http.javadsl.server.PathMatcher18
    //akka.http.javadsl.server.PathMatcher19
    //akka.http.javadsl.server.PathMatcher2
    //akka.http.javadsl.server.PathMatcher20
    //akka.http.javadsl.server.PathMatcher21
    //akka.http.javadsl.server.PathMatcher22
    //akka.http.javadsl.server.PathMatcher3
    //akka.http.javadsl.server.PathMatcher4
    //akka.http.javadsl.server.PathMatcher5
    //akka.http.javadsl.server.PathMatcher6
    //akka.http.javadsl.server.PathMatcher7
    //akka.http.javadsl.server.PathMatcher8
    //akka.http.javadsl.server.PathMatcher9
    //akka.http.javadsl.server.PathMatchers
    akka.http.javadsl.server.Rejected
    akka.http.javadsl.server.Rejection
    akka.http.javadsl.server.RejectionError
    //akka.http.javadsl.server.RejectionHandler
    //akka.http.javadsl.server.RejectionHandlerBuilder
    //akka.http.javadsl.server.RequestEntityExpectedRejection
    akka.http.javadsl.server.RouteResult
    //akka.http.javadsl.server.SchemeRejection
    //akka.http.javadsl.server.TooManyRangesRejection
    //akka.http.javadsl.server.TransformationRejection
    //akka.http.javadsl.server.UnacceptedResponseContentTypeRejection
    //akka.http.javadsl.server.UnacceptedResponseEncodingRejection
    //akka.http.javadsl.server.UnsatisfiableRangeRejection
    //akka.http.javadsl.server.UnsupportedRequestContentTypeRejection
    //akka.http.javadsl.server.UnsupportedRequestEncodingRejection
    //akka.http.javadsl.server.UnsupportedWebSocketSubprotocolRejection
    //akka.http.javadsl.server.ValidationRejection
    //akka.http.javadsl.server.directives.CacheConditionDirectives
    //akka.http.javadsl.server.directives.CodingDirectives
    //akka.http.javadsl.server.directives.CookieDirectives
    //akka.http.javadsl.server.directives.DebuggingDirectives
    akka.http.javadsl.server.directives.DirectoryListing
    akka.http.javadsl.server.directives.DirectoryRenderer
    //akka.http.javadsl.server.directives.ExecutionDirectives
    //akka.http.javadsl.server.directives.FileAndResourceDirectives
    akka.http.javadsl.server.directives.FileInfo
    //akka.http.javadsl.server.directives.HostDirectives
    //akka.http.javadsl.server.directives.MarshallingDirectives
    //akka.http.javadsl.server.directives.MethodDirectives
    //akka.http.javadsl.server.directives.MiscDirectives
    //akka.http.javadsl.server.directives.PathDirectives
    //akka.http.javadsl.server.directives.RangeDirectives
    //akka.http.javadsl.server.directives.RespondWithDirectives
    //akka.http.javadsl.server.directives.SchemeDirectives
    //akka.http.javadsl.server.directives.TimeoutDirectives
    //akka.http.javadsl.server.directives.WebSocketDirectives
    //akka.http.javadsl.settings.Http2ClientSettings
    //akka.http.javadsl.settings.ServerSentEventSettings
    //akka.http.javadsl.settings.WebSocketSettings
    akka.http.javadsl.unmarshalling.StringUnmarshaller
    //akka.http.javadsl.unmarshalling.StringUnmarshallerPredef
    akka.http.javadsl.unmarshalling.UnmarshallerBase
    //akka.http.scaladsl.ConnectionContext
    akka.http.scaladsl.HttpConnectionContext
    //akka.http.scaladsl.OutgoingConnectionBuilder
    //akka.http.scaladsl.TimeoutAccess
    //akka.http.scaladsl.client.TransformerAux
    akka.http.scaladsl.coding.Coder
    //akka.http.scaladsl.coding.Coders
    //akka.http.scaladsl.coding.Compressor
    //akka.http.scaladsl.coding.Deflate
    //akka.http.scaladsl.coding.Gzip
    //akka.http.scaladsl.coding.NoCoding
    akka.http.scaladsl.common.NameDefaultReceptacle
    akka.http.scaladsl.common.NameDefaultUnmarshallerReceptacle
    akka.http.scaladsl.common.NameOptionReceptacle
    akka.http.scaladsl.common.NameOptionUnmarshallerReceptacle
    //akka.http.scaladsl.common.NameReceptacle
    //akka.http.scaladsl.common.NameUnmarshallerReceptacle
    akka.http.scaladsl.common.RepeatedValueReceptacle
    akka.http.scaladsl.common.RepeatedValueUnmarshallerReceptacle
    akka.http.scaladsl.common.RequiredValueReceptacle
    akka.http.scaladsl.common.RequiredValueUnmarshallerReceptacle
    //akka.http.scaladsl.common.ToNameReceptacleEnhancements
    //akka.http.scaladsl.marshalling.ContentTypeOverrider
    //akka.http.scaladsl.marshalling.EmptyValue
    //akka.http.scaladsl.marshalling.GenericMarshallers
    //akka.http.scaladsl.marshalling.Marshal
    //akka.http.scaladsl.marshalling.Marshaller
    akka.http.scaladsl.marshalling.Marshalling
    //akka.http.scaladsl.marshalling.NoStrictlyCompatibleElementMarshallingAvailableException
    //akka.http.scaladsl.marshalling.PredefinedToRequestMarshallers
    //akka.http.scaladsl.marshalling.ToResponseMarshallable
    akka.http.scaladsl.model.AttributeKey
    akka.http.scaladsl.model.AttributeKeys
    akka.http.scaladsl.model.BodyPartEntity
    //akka.http.scaladsl.model.ContentTypes
    akka.http.scaladsl.model.EntityStreamException
    //akka.http.scaladsl.model.EntityStreamSizeException
    //akka.http.scaladsl.model.ErrorInfo
    //akka.http.scaladsl.model.ExceptionWithErrorInfo
    //akka.http.scaladsl.model.HttpCharset
    //akka.http.scaladsl.model.HttpCharsets
    //akka.http.scaladsl.model.HttpMethods
    akka.http.scaladsl.model.HttpProtocol
    //akka.http.scaladsl.model.HttpProtocols
    akka.http.scaladsl.model.IllegalHeaderException
    akka.http.scaladsl.model.IllegalRequestException
    akka.http.scaladsl.model.IllegalResponseException
    akka.http.scaladsl.model.IllegalUriException
    akka.http.scaladsl.model.InvalidContentLengthException
    //akka.http.scaladsl.model.MediaRanges
    //akka.http.scaladsl.model.MediaTypes
    //akka.http.scaladsl.model.OptHttpRequest
    //akka.http.scaladsl.model.OptHttpResponse
    akka.http.scaladsl.model.ParsingException
    //akka.http.scaladsl.model.RequestEntity
    akka.http.scaladsl.model.RequestEntityAcceptance
    //akka.http.scaladsl.model.RequestResponseAssociation
    akka.http.scaladsl.model.RequestTimeoutException
    akka.http.scaladsl.model.ResponsePromise
    //akka.http.scaladsl.model.SensitiveHttpHeader
    //akka.http.scaladsl.model.SimpleRequestResponseAttribute
    //akka.http.scaladsl.model.SslSessionInfo
    //akka.http.scaladsl.model.StatusCode
    //akka.http.scaladsl.model.StatusCodes
    //akka.http.scaladsl.model.Trailer
    akka.http.scaladsl.model.TransferEncoding
    akka.http.scaladsl.model.UniversalEntity
    //akka.http.scaladsl.model.Uri
    akka.http.scaladsl.model.WithQValue
    akka.http.scaladsl.model.headers.ContentDispositionType
    //akka.http.scaladsl.model.headers.Date
    //akka.http.scaladsl.model.headers.EmptyCompanion
    //akka.http.scaladsl.model.headers.EmptyHeader
    //akka.http.scaladsl.model.headers.Expires
    //akka.http.scaladsl.model.headers.HttpChallenges
    akka.http.scaladsl.model.headers.HttpCredentials
    akka.http.scaladsl.model.headers.HttpEncoding
    //akka.http.scaladsl.model.headers.HttpEncodings
    akka.http.scaladsl.model.headers.IgnoredDirective
    akka.http.scaladsl.model.headers.IncludeSubDomains
    //akka.http.scaladsl.model.headers.LinkParam
    akka.http.scaladsl.model.headers.MaxAge
    //akka.http.scaladsl.model.headers.ModeledCustomHeader
    //akka.http.scaladsl.model.headers.ModeledCustomHeaderCompanion
    //akka.http.scaladsl.model.headers.ModeledHeader
    akka.http.scaladsl.model.headers.RangeUnit
    //akka.http.scaladsl.model.headers.RequestHeader
    //akka.http.scaladsl.model.headers.RequestResponseHeader
    //akka.http.scaladsl.model.headers.ResponseHeader
    akka.http.scaladsl.model.headers.RetryAfterDateTime
    akka.http.scaladsl.model.headers.RetryAfterDuration
    akka.http.scaladsl.model.headers.RetryAfterParameter
    //akka.http.scaladsl.model.headers.StrictTransportSecurityDirective
    //akka.http.scaladsl.model.headers.SyntheticHeader
    //akka.http.scaladsl.model.headers.`If-Modified-Since`
    //akka.http.scaladsl.model.headers.`If-Unmodified-Since`
    //akka.http.scaladsl.model.headers.`Last-Modified`
    //akka.http.scaladsl.model.http2.Http2Exception
    //akka.http.scaladsl.model.http2.PeerClosedStreamException
    akka.http.scaladsl.model.ws.InvalidUpgradeResponse
    akka.http.scaladsl.model.ws.Message
    //akka.http.scaladsl.model.ws.PeerClosedConnectionException
    akka.http.scaladsl.model.ws.ValidUpgrade
    //akka.http.scaladsl.model.ws.WebSocketRequest
    akka.http.scaladsl.model.ws.WebSocketUpgradeResponse
    akka.http.scaladsl.server.AuthenticationFailedRejection
    akka.http.scaladsl.server.AuthorizationFailedRejection
    //akka.http.scaladsl.server.CharsetNegotiator
    //akka.http.scaladsl.server.CircuitBreakerOpenRejection
    //akka.http.scaladsl.server.ConjunctionMagnet
    //akka.http.scaladsl.server.ContentNegotiator
    //akka.http.scaladsl.server.Directive
    akka.http.scaladsl.server.Directives
    //akka.http.scaladsl.server.EncodingNegotiator
    akka.http.scaladsl.server.ExpectedWebSocketRequestRejection
    //akka.http.scaladsl.server.ImplicitPathMatcherConstruction
    akka.http.scaladsl.server.InvalidOriginRejection
    akka.http.scaladsl.server.InvalidRequiredValueForQueryParamRejection
    //akka.http.scaladsl.server.LanguageNegotiator
    //akka.http.scaladsl.server.LowerPriorityRoutingLogImplicits
    //akka.http.scaladsl.server.MalformedFormFieldRejection
    //akka.http.scaladsl.server.MalformedHeaderRejection
    //akka.http.scaladsl.server.MalformedQueryParamRejection
    akka.http.scaladsl.server.MalformedRequestContentRejection
    //akka.http.scaladsl.server.MediaTypeNegotiator
    akka.http.scaladsl.server.MethodRejection
    akka.http.scaladsl.server.MissingAttributeRejection
    akka.http.scaladsl.server.MissingCookieRejection
    akka.http.scaladsl.server.MissingFormFieldRejection
    akka.http.scaladsl.server.MissingHeaderRejection
    akka.http.scaladsl.server.MissingQueryParamRejection
    //akka.http.scaladsl.server.PathMatcher
    //akka.http.scaladsl.server.PathMatchers
    akka.http.scaladsl.server.Rejection
    //akka.http.scaladsl.server.RejectionError
    //akka.http.scaladsl.server.RequestContext
    akka.http.scaladsl.server.RequestEntityExpectedRejection
    //akka.http.scaladsl.server.RouteConcatenation
    //akka.http.scaladsl.server.RouteResult
    //akka.http.scaladsl.server.RoutingLog
    akka.http.scaladsl.server.SchemeRejection
    //akka.http.scaladsl.server.StandardRoute
    akka.http.scaladsl.server.TooManyRangesRejection
    akka.http.scaladsl.server.UnacceptedResponseContentTypeRejection
    akka.http.scaladsl.server.UnacceptedResponseEncodingRejection
    akka.http.scaladsl.server.UnsatisfiableRangeRejection
    //akka.http.scaladsl.server.UnsupportedRequestContentTypeRejection
    akka.http.scaladsl.server.UnsupportedRequestEncodingRejection
    akka.http.scaladsl.server.UnsupportedWebSocketSubprotocolRejection
    //akka.http.scaladsl.server.ValidationRejection
    //akka.http.scaladsl.server.directives.AttributeDirectives
    //akka.http.scaladsl.server.directives.AuthenticationDirective
    //akka.http.scaladsl.server.directives.AuthenticationResult
    //akka.http.scaladsl.server.directives.CacheConditionDirectives
    //akka.http.scaladsl.server.directives.CompleteOrRecoverWithMagnet
    //akka.http.scaladsl.server.directives.ContentTypeResolver
    //akka.http.scaladsl.server.directives.CookieDirectives
    //akka.http.scaladsl.server.directives.Credentials
    //akka.http.scaladsl.server.directives.DebuggingDirectives
    //akka.http.scaladsl.server.directives.DirectoryListing
    //akka.http.scaladsl.server.directives.ExecutionDirectives
    akka.http.scaladsl.server.directives.FileInfo
    //akka.http.scaladsl.server.directives.FormFieldDirectives
    //akka.http.scaladsl.server.directives.FormFieldDirectivesInstances
    //akka.http.scaladsl.server.directives.HeaderDirectives
    //akka.http.scaladsl.server.directives.HeaderMagnet
    //akka.http.scaladsl.server.directives.HostDirectives
    //akka.http.scaladsl.server.directives.LowPriorityHeaderMagnetImplicits
    //akka.http.scaladsl.server.directives.MarshallingDirectives
    //akka.http.scaladsl.server.directives.MethodDirectives
    //akka.http.scaladsl.server.directives.MiscDirectives
    //akka.http.scaladsl.server.directives.OnSuccessMagnet
    //akka.http.scaladsl.server.directives.ParameterDirectives
    //akka.http.scaladsl.server.directives.ParameterDirectivesInstances
    //akka.http.scaladsl.server.directives.PathDirectives
    //akka.http.scaladsl.server.directives.RespondWithDirectives
    //akka.http.scaladsl.server.directives.RouteDirectives
    //akka.http.scaladsl.server.directives.SchemeDirectives
    //akka.http.scaladsl.server.directives.SecurityDirectives
    //akka.http.scaladsl.server.directives.TimeoutDirectives
    //akka.http.scaladsl.server.directives.WebSocketDirectives
    akka.http.scaladsl.server.util.ApplyConverter
    //akka.http.scaladsl.server.util.ApplyConverterInstances
    //akka.http.scaladsl.server.util.BinaryPolyFunc
    //akka.http.scaladsl.server.util.ClassMagnet
    //akka.http.scaladsl.server.util.ConstructFromTuple
    //akka.http.scaladsl.server.util.ConstructFromTupleInstances
    //akka.http.scaladsl.server.util.LowerPriorityTupler
    //akka.http.scaladsl.server.util.Tuple
    //akka.http.scaladsl.server.util.TupleAppendOneInstances
    //akka.http.scaladsl.server.util.TupleFoldInstances
    //akka.http.scaladsl.server.util.TupleOps
    akka.http.scaladsl.server.util.Tupler
    //akka.http.scaladsl.settings.Http2CommonSettings
    //akka.http.scaladsl.settings.Http2InternalClientSettings
    //akka.http.scaladsl.settings.Http2InternalServerSettings
    //akka.http.scaladsl.settings.WebSocketSettings
    //akka.http.scaladsl.unmarshalling.GenericUnmarshallers
    //akka.http.scaladsl.unmarshalling.LowerPriorityGenericUnmarshallers
    //akka.http.scaladsl.unmarshalling.Unmarshal
    //akka.http.scaladsl.util.FastFuture
  """)
}