package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.given
import org.junit.Test

class AkkaActorTypedSemanticTest extends SemanticTestBase("com.typesafe.akka" %% "akka-actor-typed" % "2.8.8")("akka.actor.typed", "akka.event.slf4j") {
//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    //akka.actor.typed.AbstractExtensionSetup
    //akka.actor.typed.ActorRef
    //akka.actor.typed.ActorRefResolver
    //akka.actor.typed.ActorRefResolverImpl
    akka.actor.typed.ActorRefResolverSetup
    //akka.actor.typed.ActorSystem
    //akka.actor.typed.ActorTags
    akka.actor.typed.BackoffSupervisorStrategy
    //akka.actor.typed.Behavior
    //akka.actor.typed.BehaviorInterceptor
    //akka.actor.typed.BehaviorSignalInterceptor
    //akka.actor.typed.ChildFailed
    akka.actor.typed.DeathPactException
    akka.actor.typed.DispatcherSelector
    //akka.actor.typed.Dispatchers
    akka.actor.typed.ExtensibleBehavior
    akka.actor.typed.Extension
    akka.actor.typed.ExtensionId
    akka.actor.typed.ExtensionSetup
    akka.actor.typed.Extensions
    //akka.actor.typed.LogOptions
    akka.actor.typed.MailboxSelector
    akka.actor.typed.MessageAdaptionFailure
    akka.actor.typed.PostStop
    akka.actor.typed.PreRestart
    //akka.actor.typed.Props
    //akka.actor.typed.RecipientRef
    akka.actor.typed.RestartSupervisorStrategy
    akka.actor.typed.Scheduler
    //akka.actor.typed.SerializedActorRef
    akka.actor.typed.Settings
    akka.actor.typed.Signal
    //akka.actor.typed.SpawnProtocol
    //akka.actor.typed.SupervisorStrategy
    //akka.actor.typed.Terminated
    akka.actor.typed.TypedActorContext
    //akka.actor.typed.delivery.ConsumerController
    //akka.actor.typed.delivery.DurableProducerQueue
    //akka.actor.typed.delivery.ProducerController
    //akka.actor.typed.delivery.WorkPullingProducerController
    //akka.actor.typed.delivery.internal.ChunkedMessage
    //akka.actor.typed.delivery.internal.ConsumerControllerImpl
    akka.actor.typed.delivery.internal.DeliverySerializable
    //akka.actor.typed.delivery.internal.ProducerControllerImpl
    //akka.actor.typed.delivery.internal.WorkPullingProducerControllerImpl
    //akka.actor.typed.eventstream.EventStream
    //akka.actor.typed.internal.AbstractSupervisor
    //akka.actor.typed.internal.ActorContextImpl
    akka.actor.typed.internal.ActorFlightRecorder
    akka.actor.typed.internal.ActorMdc
    //akka.actor.typed.internal.ActorRefImpl
    akka.actor.typed.internal.AdaptMessage
    akka.actor.typed.internal.AdaptWithRegisteredMessageAdapter
    //akka.actor.typed.internal.BehaviorImpl
    //akka.actor.typed.internal.BehaviorTags
    akka.actor.typed.internal.CachedProps
    akka.actor.typed.internal.Create
    akka.actor.typed.internal.DeathWatchNotification
    akka.actor.typed.internal.DeliveryFlightRecorder
    //akka.actor.typed.internal.EarliestFirstSystemMessageList
    //akka.actor.typed.internal.EventStreamExtension
    //akka.actor.typed.internal.ExtensionsImpl
    //akka.actor.typed.internal.InterceptorImpl
    akka.actor.typed.internal.InternalMessage
    //akka.actor.typed.internal.InternalRecipientRef
    //akka.actor.typed.internal.LatestFirstSystemMessageList
    //akka.actor.typed.internal.LogMessagesInterceptor
    //akka.actor.typed.internal.LoggerClass
    //akka.actor.typed.internal.MiscMessageSerializer
    //akka.actor.typed.internal.MonitorInterceptor
    akka.actor.typed.internal.NoMessage
    akka.actor.typed.internal.NoOpActorFlightRecorder
    akka.actor.typed.internal.NoOpDeliveryFlightRecorder
    akka.actor.typed.internal.PoisonPill
    akka.actor.typed.internal.PoisonPillInterceptor
    //akka.actor.typed.internal.PropsImpl
    //akka.actor.typed.internal.RestartSupervisor
    //akka.actor.typed.internal.ResumeSupervisor
    //akka.actor.typed.internal.SimpleSupervisor
    //akka.actor.typed.internal.StashBufferImpl
    //akka.actor.typed.internal.StopSupervisor
    akka.actor.typed.internal.Supervisor
    akka.actor.typed.internal.SystemMessage
    akka.actor.typed.internal.SystemMessageList
    akka.actor.typed.internal.Terminate
    akka.actor.typed.internal.TimerSchedulerCrossDslSupport
    //akka.actor.typed.internal.TimerSchedulerImpl
    //akka.actor.typed.internal.TransformMessagesInterceptor
    akka.actor.typed.internal.UnstashException
    akka.actor.typed.internal.Unwatch
    akka.actor.typed.internal.Watch
    //akka.actor.typed.internal.WithMdcBehaviorInterceptor
    //akka.actor.typed.internal.adapter.ActorAdapter
    //akka.actor.typed.internal.adapter.ActorContextAdapter
    //akka.actor.typed.internal.adapter.ActorRefAdapter
    //akka.actor.typed.internal.adapter.ActorRefFactoryAdapter
    //akka.actor.typed.internal.adapter.ActorSystemAdapter
    akka.actor.typed.internal.adapter.AdapterExtension
    //akka.actor.typed.internal.adapter.ComposedStoppingBehavior
    //akka.actor.typed.internal.adapter.EventStreamAdapter
    //akka.actor.typed.internal.adapter.GuardianStartupBehavior
    //akka.actor.typed.internal.adapter.GuardianStopInterceptor
    //akka.actor.typed.internal.adapter.PropsAdapter
    //akka.actor.typed.internal.adapter.SchedulerAdapter
    //akka.actor.typed.internal.pubsub.TopicImpl
    akka.actor.typed.internal.receptionist.AbstractServiceKey
    akka.actor.typed.internal.receptionist.DefaultServiceKey
    //akka.actor.typed.internal.receptionist.LocalReceptionist
    //akka.actor.typed.internal.receptionist.Platform
    akka.actor.typed.internal.receptionist.ReceptionistBehaviorProvider
    //akka.actor.typed.internal.receptionist.ReceptionistImpl
    //akka.actor.typed.internal.receptionist.ReceptionistMessages
    //akka.actor.typed.internal.receptionist.ServiceKeySerializer
    //akka.actor.typed.internal.routing.GroupRouterBuilder
    akka.actor.typed.internal.routing.GroupRouterHelper
    //akka.actor.typed.internal.routing.GroupRouterImpl
    //akka.actor.typed.internal.routing.InitialGroupRouterImpl
    //akka.actor.typed.internal.routing.PoolRouterBuilder
    //akka.actor.typed.internal.routing.PoolRouterImpl
    akka.actor.typed.internal.routing.RoutingLogic
    //akka.actor.typed.internal.routing.RoutingLogics
    //akka.actor.typed.javadsl.AbstractBehavior
    //akka.actor.typed.javadsl.AbstractOnMessageBehavior
    akka.actor.typed.javadsl.ActorContext
    //akka.actor.typed.javadsl.Adapter
    //akka.actor.typed.javadsl.AskPattern
    //akka.actor.typed.javadsl.BehaviorBuilder
    //akka.actor.typed.javadsl.Behaviors
    //akka.actor.typed.javadsl.BuiltBehavior
    //akka.actor.typed.javadsl.BuiltReceive
    akka.actor.typed.javadsl.GroupRouter
    akka.actor.typed.javadsl.PoolRouter
    akka.actor.typed.javadsl.Receive
    //akka.actor.typed.javadsl.ReceiveBuilder
    akka.actor.typed.javadsl.Routers
    akka.actor.typed.javadsl.StashBuffer
    akka.actor.typed.javadsl.StashOverflowException
    akka.actor.typed.javadsl.TimerScheduler
    akka.actor.typed.pubsub.Topic
    //akka.actor.typed.receptionist.Receptionist
    akka.actor.typed.receptionist.ReceptionistSetup
    akka.actor.typed.receptionist.ServiceKey
    //akka.actor.typed.scaladsl.AbstractBehavior
    akka.actor.typed.scaladsl.ActorContext
    //akka.actor.typed.scaladsl.AskPattern
    //akka.actor.typed.scaladsl.Behaviors
    akka.actor.typed.scaladsl.GroupRouter
    akka.actor.typed.scaladsl.PoolRouter
    akka.actor.typed.scaladsl.Routers
    akka.actor.typed.scaladsl.StashBuffer
    akka.actor.typed.scaladsl.StashOverflowException
    akka.actor.typed.scaladsl.TimerScheduler
    //akka.actor.typed.scaladsl.adapter.PropsAdapter
    akka.event.slf4j.Logger
    //akka.event.slf4j.SLF4JLogging
    //akka.event.slf4j.Slf4jLogMarker
    //akka.event.slf4j.Slf4jLogger
    //akka.event.slf4j.Slf4jLoggingFilter
  """)
}