package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.given
import org.junit.Test

class AkkaPersistenceSemanticTest extends SemanticTestBase("com.typesafe.akka" %% "akka-persistence" % "2.8.8")("akka.persistence") {
//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    akka.persistence.AbstractPersistentActor
    akka.persistence.AbstractPersistentActorLike
    akka.persistence.AbstractPersistentActorWithAtLeastOnceDelivery
    akka.persistence.AbstractPersistentActorWithTimers
    //akka.persistence.AtLeastOnceDelivery
    //akka.persistence.AtLeastOnceDeliveryLike
    //akka.persistence.AtomicWrite
    akka.persistence.DeleteMessagesFailure
    akka.persistence.DeleteMessagesSuccess
    akka.persistence.DeleteSnapshotFailure
    akka.persistence.DeleteSnapshotSuccess
    akka.persistence.DeleteSnapshotsFailure
    akka.persistence.DeleteSnapshotsSuccess
    akka.persistence.DiscardConfigurator
    akka.persistence.DiscardToDeadLetterStrategy
    //akka.persistence.Eventsourced
    akka.persistence.FilteredPayload
    akka.persistence.JournalProtocol
    akka.persistence.NonPersistentRepr
    //akka.persistence.Persistence
    akka.persistence.PersistenceIdentity
    //akka.persistence.PersistencePlugin
    akka.persistence.PersistenceRecovery
    akka.persistence.PersistenceSettings
    akka.persistence.PersistenceStash
    akka.persistence.PersistentActor
    akka.persistence.PersistentEnvelope
    //akka.persistence.PersistentImpl
    //akka.persistence.PersistentRepr
    akka.persistence.PluginProvider
    akka.persistence.Protocol
    //akka.persistence.Recovery
    akka.persistence.RecoveryCompleted
    //akka.persistence.RecoveryPermitter
    akka.persistence.RecoveryTimedOut
    akka.persistence.ReplyToStrategy
    akka.persistence.RuntimePluginConfig
    akka.persistence.SaveSnapshotFailure
    akka.persistence.SaveSnapshotSuccess
    akka.persistence.SelectedSnapshot
    //akka.persistence.SnapshotMetadata
    akka.persistence.SnapshotOffer
    akka.persistence.SnapshotProtocol
    //akka.persistence.SnapshotSelectionCriteria
    //akka.persistence.Snapshotter
    akka.persistence.StashOverflowStrategy
    akka.persistence.StashOverflowStrategyConfigurator
    akka.persistence.ThrowExceptionConfigurator
    akka.persistence.ThrowOverflowExceptionStrategy
    akka.persistence.TraitOrder
    //akka.persistence.fsm.AbstractPersistentFSM
    //akka.persistence.fsm.AbstractPersistentFSMBase
    akka.persistence.fsm.AbstractPersistentLoggingFSM
    //akka.persistence.fsm.LoggingPersistentFSM
    //akka.persistence.fsm.PersistentFSM
    //akka.persistence.fsm.PersistentFSMBase
    //akka.persistence.fsm.SnapshotAfter
    akka.persistence.journal.AsyncRecovery
    akka.persistence.journal.AsyncReplayTimeoutException
    //akka.persistence.journal.AsyncWriteJournal
    //akka.persistence.journal.AsyncWriteProxy
    akka.persistence.journal.AsyncWriteTarget
    akka.persistence.journal.EmptyEventSeq
    akka.persistence.journal.EventAdapter
    //akka.persistence.journal.EventAdapters
    akka.persistence.journal.EventSeq
    akka.persistence.journal.EventsSeq
    akka.persistence.journal.IdentityEventAdapter
    akka.persistence.journal.IdentityEventAdapters
    akka.persistence.journal.NoopReadEventAdapter
    akka.persistence.journal.NoopWriteEventAdapter
    //akka.persistence.journal.PersistencePluginProxy
    akka.persistence.journal.PersistencePluginProxyExtension
    //akka.persistence.journal.PersistencePluginProxyExtensionImpl
    akka.persistence.journal.ReadEventAdapter
    //akka.persistence.journal.ReplayFilter
    //akka.persistence.journal.ReplayMediator
    akka.persistence.journal.SingleEventSeq
    //akka.persistence.journal.Tagged
    akka.persistence.journal.WriteEventAdapter
    //akka.persistence.journal.WriteJournalBase
    //akka.persistence.journal.inmem.InmemJournal
    //akka.persistence.journal.inmem.InmemMessages
    //akka.persistence.journal.japi.AsyncRecovery
    //akka.persistence.journal.japi.AsyncWriteJournal
    //akka.persistence.journal.leveldb.CompactionSegmentManagement
    akka.persistence.journal.leveldb.Key
    //akka.persistence.journal.leveldb.LeveldbCompaction
    //akka.persistence.journal.leveldb.LeveldbJournal
    //akka.persistence.journal.leveldb.LeveldbRecovery
    //akka.persistence.journal.leveldb.SharedLeveldbJournal
    //akka.persistence.journal.leveldb.SharedLeveldbStore
    //akka.persistence.serialization.FilteredPayloadSerializer
    akka.persistence.serialization.Message
    //akka.persistence.serialization.MessageSerializer
    akka.persistence.serialization.Snapshot
    //akka.persistence.serialization.SnapshotSerializer
    //akka.persistence.snapshot.NoSnapshotStore
    //akka.persistence.snapshot.SnapshotStore
    //akka.persistence.snapshot.japi.SnapshotStore
    //akka.persistence.snapshot.local.LocalSnapshotStore
    akka.persistence.state.DurableStateStoreProvider
    //akka.persistence.state.DurableStateStoreRegistry
    akka.persistence.state.javadsl.DurableStateStore
    akka.persistence.state.javadsl.DurableStateUpdateStore
    akka.persistence.state.javadsl.GetObjectResult
    akka.persistence.state.scaladsl.DurableStateStore
    akka.persistence.state.scaladsl.DurableStateUpdateStore
    akka.persistence.state.scaladsl.GetObjectResult
  """)
}