package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.given
import org.junit.Test

class AkkaStreamSemanticTest extends SemanticTestBase("com.typesafe.akka" %% "akka-stream" % "2.8.8")("akka.stream") {
  @Test def test(): Unit = doTest("""
    akka.stream.AbruptIOTerminationException
    akka.stream.AbruptStageTerminationException
    akka.stream.AbruptTerminationException
    //akka.stream.AbstractShape
    //akka.stream.ActorAttributes
    //akka.stream.ActorMaterializer
    //akka.stream.ActorMaterializerHelper
    //akka.stream.ActorMaterializerSettings
    akka.stream.AmorphousShape
    //akka.stream.Attributes
    akka.stream.BackpressureTimeoutException
    //akka.stream.BidiShape
    akka.stream.BindFailedException
    akka.stream.BoundedSourceQueue
    akka.stream.BufferOverflowException
    akka.stream.Client
    akka.stream.ClosedShape
    akka.stream.CompletionStrategy
    akka.stream.CompletionTimeoutException
    akka.stream.ConnectionException
    akka.stream.DelayOverflowStrategy
    akka.stream.EagerClose
    //akka.stream.FanInShape
    //akka.stream.FanInShape10
    //akka.stream.FanInShape11
    //akka.stream.FanInShape12
    //akka.stream.FanInShape13
    //akka.stream.FanInShape14
    //akka.stream.FanInShape15
    //akka.stream.FanInShape16
    //akka.stream.FanInShape17
    //akka.stream.FanInShape18
    //akka.stream.FanInShape19
    //akka.stream.FanInShape2
    //akka.stream.FanInShape20
    //akka.stream.FanInShape21
    //akka.stream.FanInShape22
    //akka.stream.FanInShape3
    //akka.stream.FanInShape4
    //akka.stream.FanInShape5
    //akka.stream.FanInShape6
    //akka.stream.FanInShape7
    //akka.stream.FanInShape8
    //akka.stream.FanInShape9
    //akka.stream.FanOutShape
    //akka.stream.FanOutShape10
    //akka.stream.FanOutShape11
    //akka.stream.FanOutShape12
    //akka.stream.FanOutShape13
    //akka.stream.FanOutShape14
    //akka.stream.FanOutShape15
    //akka.stream.FanOutShape16
    //akka.stream.FanOutShape17
    //akka.stream.FanOutShape18
    //akka.stream.FanOutShape19
    //akka.stream.FanOutShape2
    //akka.stream.FanOutShape20
    //akka.stream.FanOutShape21
    //akka.stream.FanOutShape22
    //akka.stream.FanOutShape3
    //akka.stream.FanOutShape4
    //akka.stream.FanOutShape5
    //akka.stream.FanOutShape6
    //akka.stream.FanOutShape7
    //akka.stream.FanOutShape8
    //akka.stream.FanOutShape9
    akka.stream.FlowMonitor
    akka.stream.FlowMonitorState
    //akka.stream.FlowShape
    //akka.stream.Graph
    akka.stream.GraphDelegate
    //akka.stream.IOOperationIncompleteException
    //akka.stream.IOResult
    //akka.stream.IOSettings
    akka.stream.IgnoreBoth
    akka.stream.IgnoreCancel
    akka.stream.IgnoreComplete
    akka.stream.InPort
    akka.stream.InitialTimeoutException
    //akka.stream.Inlet
    //akka.stream.InvalidPartnerActorException
    //akka.stream.InvalidSequenceNumberException
    akka.stream.KillSwitch
    //akka.stream.KillSwitches
    akka.stream.MaterializationContext
    //akka.stream.MaterializationException
    //akka.stream.Materializer
    akka.stream.MaterializerLoggingProvider
    akka.stream.NeverMaterializedException
    akka.stream.OutPort
    //akka.stream.Outlet
    akka.stream.OverflowStrategies
    //akka.stream.OverflowStrategy
    akka.stream.QueueCompletionResult
    akka.stream.QueueOfferResult
    akka.stream.RateExceededException
    akka.stream.RemoteStreamRefActorTerminatedException
    //akka.stream.RestartSettings
    akka.stream.Server
    //akka.stream.Shape
    //akka.stream.SharedKillSwitch
    akka.stream.SinkRef
    //akka.stream.SinkShape
    akka.stream.SourceRef
    //akka.stream.SourceShape
    akka.stream.StreamDetachedException
    akka.stream.StreamIdleTimeoutException
    akka.stream.StreamLimitReachedException
    akka.stream.StreamRefAttributes
    akka.stream.StreamRefResolver
    //akka.stream.StreamRefSettings
    akka.stream.StreamRefSubscriptionTimeoutException
    //akka.stream.StreamSubscriptionTimeoutSettings
    akka.stream.StreamSubscriptionTimeoutTerminationMode
    akka.stream.StreamTcpException
    akka.stream.StreamTimeoutException
    akka.stream.SubscriptionWithCancelException
    akka.stream.SubstreamCancelStrategies
    akka.stream.SubstreamCancelStrategy
    //akka.stream.Supervision
    //akka.stream.SystemMaterializer
    akka.stream.TLSClientAuth
    akka.stream.TLSClosing
    //akka.stream.TLSProtocol
    akka.stream.TLSRole
    akka.stream.TargetRefNotInitializedYetException
    //akka.stream.TerminationSignal
    akka.stream.ThrottleMode
    akka.stream.TooManySubstreamsOpenException
    //akka.stream.UniformFanInShape
    //akka.stream.UniformFanOutShape
    //akka.stream.UniqueKillSwitch
    akka.stream.WatchedActorTerminatedException
    //akka.stream.impl.ActorProcessor
    //akka.stream.impl.ActorProcessorImpl
    //akka.stream.impl.ActorPublisher
    //akka.stream.impl.ActorRefBackpressureSinkStage
    //akka.stream.impl.ActorRefBackpressureSource
    //akka.stream.impl.ActorRefSinkStage
    //akka.stream.impl.ActorRefSource
    akka.stream.impl.ActorSubscriberMessage
    //akka.stream.impl.ActorSubscription
    akka.stream.impl.ActorSubscriptionWithCursor
    akka.stream.impl.Always
    akka.stream.impl.AppendTraversal
    //akka.stream.impl.AtomicTraversalBuilder
    //akka.stream.impl.BatchingInputBuffer
    //akka.stream.impl.BoundedBuffer
    //akka.stream.impl.BoundedSourceQueueStage
    akka.stream.impl.Buffer
    //akka.stream.impl.BuilderKey
    akka.stream.impl.Cancel
    akka.stream.impl.CancelSink
    akka.stream.impl.CancelledSubscription
    akka.stream.impl.CancellingSubscriber
    //akka.stream.impl.ChainedBuffer
    akka.stream.impl.CollectorState
    akka.stream.impl.Completed
    //akka.stream.impl.CompletedTraversalBuilder
    //akka.stream.impl.Compose
    //akka.stream.impl.CompositeTraversalBuilder
    akka.stream.impl.Concat
    akka.stream.impl.ContextPropagation
    akka.stream.impl.ContextPropagationImpl
    //akka.stream.impl.CoupledTerminationBidi
    akka.stream.impl.DefaultInputTransferStates
    akka.stream.impl.DefaultOutputTransferStates
    //akka.stream.impl.EmptyPublisher
    //akka.stream.impl.EmptySource
    akka.stream.impl.EmptyTraversal
    akka.stream.impl.EnterIsland
    //akka.stream.impl.ErrorPublisher
    akka.stream.impl.ExitIsland
    akka.stream.impl.ExposedPublisher
    //akka.stream.impl.ExposedPublisherReceive
    //akka.stream.impl.ExtendedActorMaterializer
    //akka.stream.impl.FailedSource
    //akka.stream.impl.FanIn
    //akka.stream.impl.FanOut
    //akka.stream.impl.FanoutOutputs
    //akka.stream.impl.FanoutProcessorImpl
    //akka.stream.impl.FanoutPublisherSink
    //akka.stream.impl.FirstCollectorState
    //akka.stream.impl.FirstReducerState
    //akka.stream.impl.FixedSizeBuffer
    akka.stream.impl.FlowNames
    akka.stream.impl.ForwardWire
    //akka.stream.impl.GraphStageIsland
    akka.stream.impl.GraphStageTag
    //akka.stream.impl.HeadOptionStage
    akka.stream.impl.Inputs
    akka.stream.impl.IslandTag
    //akka.stream.impl.IslandTracking
    //akka.stream.impl.JavaStreamSource
    //akka.stream.impl.JsonObjectParser
    //akka.stream.impl.LazySink
    //akka.stream.impl.LazySource
    //akka.stream.impl.LinearTraversalBuilder
    //akka.stream.impl.MaterializeAtomic
    akka.stream.impl.MaterializedValueOp
    //akka.stream.impl.MaterializerGuardian
    //akka.stream.impl.MaybeSource
    akka.stream.impl.MutableCollectorState
    akka.stream.impl.MutableReducerState
    akka.stream.impl.NotInitialized
    akka.stream.impl.Outputs
    //akka.stream.impl.PartitionedBuffer
    akka.stream.impl.Phase
    akka.stream.impl.PhaseIsland
    //akka.stream.impl.PhasedFusingActorMaterializer
    akka.stream.impl.Pop
    akka.stream.impl.PopAttributes
    //akka.stream.impl.ProcessorModule
    akka.stream.impl.ProcessorModuleIslandTag
    akka.stream.impl.ProcessorModulePhase
    //akka.stream.impl.PublisherSink
    akka.stream.impl.PublisherSource
    //akka.stream.impl.Pump
    akka.stream.impl.PushAttributes
    akka.stream.impl.PushNotUsed
    //akka.stream.impl.QueueSink
    //akka.stream.impl.QueueSource
    //akka.stream.impl.ReactiveStreamsCompliance
    akka.stream.impl.ReducerState
    //akka.stream.impl.RejectAdditionalSubscribers
    akka.stream.impl.RequestMore
    //akka.stream.impl.ResizableMultiReaderRingBuffer
    //akka.stream.impl.RetryFlowCoordinator
    akka.stream.impl.SavedIslandData
    akka.stream.impl.SegmentInfo
    //akka.stream.impl.SeqActorName
    akka.stream.impl.SeqActorNameImpl
    //akka.stream.impl.SeqStage
    //akka.stream.impl.SetupFlowStage
    //akka.stream.impl.SetupSourceStage
    akka.stream.impl.SetupStage
    //akka.stream.impl.SimpleOutputs
    //akka.stream.impl.SingleConcat
    //akka.stream.impl.SinkModule
    akka.stream.impl.SinkModuleIslandTag
    //akka.stream.impl.SinkModulePhase
    //akka.stream.impl.SinkholeSubscriber
    //akka.stream.impl.SnapshotCollector
    //akka.stream.impl.SoftShutdown
    //akka.stream.impl.SourceModule
    akka.stream.impl.SourceModuleIslandTag
    akka.stream.impl.SourceModulePhase
    //akka.stream.impl.Stages
    //akka.stream.impl.StreamLayout
    //akka.stream.impl.StreamSubscriptionTimeoutSupport
    //akka.stream.impl.StreamSupervisor
    akka.stream.impl.SubFlowImpl
    //akka.stream.impl.SubFusingActorMaterializerImpl
    akka.stream.impl.SubReceive
    akka.stream.impl.SubscribePending
    //akka.stream.impl.SubscriberManagement
    //akka.stream.impl.SubscriberSink
    akka.stream.impl.SubscriberSource
    akka.stream.impl.SubscriptionTimeoutException
    //akka.stream.impl.SubscriptionWithCursor
    //akka.stream.impl.TakeLastStage
    //akka.stream.impl.Throttle
    //akka.stream.impl.Timers
    akka.stream.impl.TlsModuleIslandTag
    //akka.stream.impl.TlsModulePhase
    akka.stream.impl.TransferPhase
    //akka.stream.impl.TransferState
    //akka.stream.impl.Transform
    //akka.stream.impl.Traversal
    akka.stream.impl.TraversalBuildStep
    //akka.stream.impl.TraversalBuilder
    //akka.stream.impl.Unfold
    //akka.stream.impl.UnfoldAsync
    //akka.stream.impl.UnfoldAsyncJava
    //akka.stream.impl.UnfoldResourceSource
    //akka.stream.impl.UnfoldResourceSourceAsync
    //akka.stream.impl.Unzip
    //akka.stream.impl.VirtualProcessor
    //akka.stream.impl.VirtualPublisher
    akka.stream.impl.WaitingForUpstreamSubscription
    //akka.stream.impl.fusing.ActorGraphInterpreter
    //akka.stream.impl.fusing.AggregateWithBoundary
    //akka.stream.impl.fusing.Batch
    //akka.stream.impl.fusing.Buffer
    //akka.stream.impl.fusing.Collect
    //akka.stream.impl.fusing.Delay
    //akka.stream.impl.fusing.Drop
    //akka.stream.impl.fusing.DropWhile
    //akka.stream.impl.fusing.DropWithin
    //akka.stream.impl.fusing.Expand
    //akka.stream.impl.fusing.Filter
    //akka.stream.impl.fusing.FlatMapPrefix
    //akka.stream.impl.fusing.FlattenMerge
    //akka.stream.impl.fusing.Fold
    //akka.stream.impl.fusing.FoldAsync
    //akka.stream.impl.fusing.FutureFlow
    //akka.stream.impl.fusing.GraphInterpreter
    //akka.stream.impl.fusing.GraphInterpreterShell
    //akka.stream.impl.fusing.GraphStageModule
    //akka.stream.impl.fusing.GraphStages
    //akka.stream.impl.fusing.GroupBy
    //akka.stream.impl.fusing.GroupedWeighted
    //akka.stream.impl.fusing.GroupedWeightedWithin
    //akka.stream.impl.fusing.Intersperse
    //akka.stream.impl.fusing.LimitWeighted
    //akka.stream.impl.fusing.Log
    //akka.stream.impl.fusing.LogWithMarker
    //akka.stream.impl.fusing.Map
    //akka.stream.impl.fusing.MapAsync
    //akka.stream.impl.fusing.MapAsyncPartitioned
    //akka.stream.impl.fusing.MapAsyncUnordered
    //akka.stream.impl.fusing.MapError
    //akka.stream.impl.fusing.PrefixAndTail
    //akka.stream.impl.fusing.Recover
    //akka.stream.impl.fusing.RecoverWith
    //akka.stream.impl.fusing.Reduce
    //akka.stream.impl.fusing.Scan
    //akka.stream.impl.fusing.ScanAsync
    //akka.stream.impl.fusing.Sliding
    //akka.stream.impl.fusing.Split
    //akka.stream.impl.fusing.StatefulMap
    //akka.stream.impl.fusing.StatefulMapConcat
    //akka.stream.impl.fusing.SubSink
    //akka.stream.impl.fusing.SubSource
    akka.stream.impl.fusing.SupervisedGraphStageLogic
    //akka.stream.impl.fusing.Take
    //akka.stream.impl.fusing.TakeWhile
    //akka.stream.impl.fusing.TakeWithin
    //akka.stream.impl.fusing.Watch
    //akka.stream.impl.io.ByteStringParser
    //akka.stream.impl.io.ConnectionSourceStage
    //akka.stream.impl.io.FileOutputStage
    //akka.stream.impl.io.FileSource
    akka.stream.impl.io.IncomingConnectionStage
    //akka.stream.impl.io.InputStreamAdapter
    //akka.stream.impl.io.InputStreamSinkStage
    //akka.stream.impl.io.InputStreamSource
    //akka.stream.impl.io.OutgoingConnectionStage
    //akka.stream.impl.io.OutputStreamAdapter
    //akka.stream.impl.io.OutputStreamGraphStage
    //akka.stream.impl.io.OutputStreamSourceStage
    //akka.stream.impl.io.TLSActor
    //akka.stream.impl.io.TcpConnectionStage
    //akka.stream.impl.io.TcpIdleTimeout
    //akka.stream.impl.io.TlsModule
    //akka.stream.impl.io.TlsUtils
    //akka.stream.impl.io.compression.CompressionUtils
    akka.stream.impl.io.compression.Compressor
    //akka.stream.impl.io.compression.DeflateCompressor
    //akka.stream.impl.io.compression.DeflateDecompressor
    akka.stream.impl.io.compression.DeflateDecompressorBase
    //akka.stream.impl.io.compression.GzipCompressor
    //akka.stream.impl.io.compression.GzipDecompressor
    //akka.stream.impl.streamref.SinkRefImpl
    //akka.stream.impl.streamref.SinkRefStageImpl
    //akka.stream.impl.streamref.SourceRefImpl
    //akka.stream.impl.streamref.SourceRefStageImpl
    //akka.stream.impl.streamref.StreamRefResolverImpl
    akka.stream.impl.streamref.StreamRefSettingsImpl
    akka.stream.impl.streamref.StreamRefsMaster
    akka.stream.impl.streamref.StreamRefsProtocol
    //akka.stream.javadsl.Balance
    //akka.stream.javadsl.BidiFlow
    //akka.stream.javadsl.Broadcast
    //akka.stream.javadsl.BroadcastHub
    //akka.stream.javadsl.Compression
    //akka.stream.javadsl.Concat
    //akka.stream.javadsl.DelayStrategy
    //akka.stream.javadsl.FileIO
    //akka.stream.javadsl.Flow
    //akka.stream.javadsl.FlowWithContext
    //akka.stream.javadsl.Framing
    //akka.stream.javadsl.GraphCreate
    //akka.stream.javadsl.GraphDSL
    akka.stream.javadsl.JsonFraming
    //akka.stream.javadsl.Keep
    //akka.stream.javadsl.Merge
    //akka.stream.javadsl.MergeHub
    //akka.stream.javadsl.MergeLatest
    //akka.stream.javadsl.MergePreferred
    //akka.stream.javadsl.MergePrioritized
    //akka.stream.javadsl.MergeSequence
    //akka.stream.javadsl.Partition
    //akka.stream.javadsl.PartitionHub
    //akka.stream.javadsl.RestartFlow
    //akka.stream.javadsl.RestartSink
    //akka.stream.javadsl.RestartSource
    //akka.stream.javadsl.RetryFlow
    //akka.stream.javadsl.RunnableGraph
    //akka.stream.javadsl.Sink
    akka.stream.javadsl.SinkQueue
    //akka.stream.javadsl.SinkQueueWithCancel
    //akka.stream.javadsl.Source
    akka.stream.javadsl.SourceQueue
    //akka.stream.javadsl.SourceQueueWithComplete
    //akka.stream.javadsl.SourceWithContext
    //akka.stream.javadsl.StreamConverters
    //akka.stream.javadsl.StreamRefs
    //akka.stream.javadsl.SubFlow
    //akka.stream.javadsl.SubSource
    //akka.stream.javadsl.TLS
    //akka.stream.javadsl.TLSPlacebo
    //akka.stream.javadsl.Tcp
    //akka.stream.javadsl.Unzip
    //akka.stream.javadsl.UnzipWith
    akka.stream.javadsl.Zip
    akka.stream.javadsl.ZipLatest
    //akka.stream.javadsl.ZipLatestWith
    akka.stream.javadsl.ZipN
    //akka.stream.javadsl.ZipWith
    //akka.stream.javadsl.ZipWithN
    //akka.stream.scaladsl.Balance
    //akka.stream.scaladsl.BidiFlow
    //akka.stream.scaladsl.Broadcast
    //akka.stream.scaladsl.BroadcastHub
    //akka.stream.scaladsl.Compression
    //akka.stream.scaladsl.Concat
    //akka.stream.scaladsl.DelayStrategy
    //akka.stream.scaladsl.FileIO
    //akka.stream.scaladsl.Flow
    //akka.stream.scaladsl.FlowOps
    //akka.stream.scaladsl.FlowOpsMat
    //akka.stream.scaladsl.FlowWithContext
    //akka.stream.scaladsl.FlowWithContextOps
    //akka.stream.scaladsl.Framing
    //akka.stream.scaladsl.GenericGraph
    //akka.stream.scaladsl.GenericGraphWithChangedAttributes
    //akka.stream.scaladsl.GraphApply
    //akka.stream.scaladsl.GraphDSL
    //akka.stream.scaladsl.Interleave
    //akka.stream.scaladsl.JsonFraming
    //akka.stream.scaladsl.Keep
    //akka.stream.scaladsl.Merge
    //akka.stream.scaladsl.MergeHub
    //akka.stream.scaladsl.MergeHubDrainingControlImpl
    //akka.stream.scaladsl.MergeLatest
    //akka.stream.scaladsl.MergePreferred
    //akka.stream.scaladsl.MergePrioritized
    //akka.stream.scaladsl.MergeSequence
    //akka.stream.scaladsl.MergeSorted
    //akka.stream.scaladsl.OrElse
    //akka.stream.scaladsl.Partition
    //akka.stream.scaladsl.PartitionHub
    //akka.stream.scaladsl.RestartFlow
    //akka.stream.scaladsl.RestartSink
    //akka.stream.scaladsl.RestartSource
    //akka.stream.scaladsl.RestartWithBackoffFlow
    //akka.stream.scaladsl.RestartWithBackoffLogic
    //akka.stream.scaladsl.RestartWithBackoffSink
    //akka.stream.scaladsl.RestartWithBackoffSource
    //akka.stream.scaladsl.RetryFlow
    //akka.stream.scaladsl.RunnableGraph
    //akka.stream.scaladsl.ScalaSessionAPI
    //akka.stream.scaladsl.Sink
    akka.stream.scaladsl.SinkQueue
    //akka.stream.scaladsl.SinkQueueWithCancel
    //akka.stream.scaladsl.Source
    akka.stream.scaladsl.SourceQueue
    //akka.stream.scaladsl.SourceQueueWithComplete
    //akka.stream.scaladsl.SourceWithContext
    //akka.stream.scaladsl.StreamConverters
    akka.stream.scaladsl.StreamRefs
    //akka.stream.scaladsl.SubFlow
    //akka.stream.scaladsl.TLS
    //akka.stream.scaladsl.TLSPlacebo
    //akka.stream.scaladsl.Tcp
    akka.stream.scaladsl.TcpAttributes
    //akka.stream.scaladsl.TcpIdleTimeoutException
    akka.stream.scaladsl.Unzip
    akka.stream.scaladsl.UnzipWith
    //akka.stream.scaladsl.UnzipWith10
    //akka.stream.scaladsl.UnzipWith11
    //akka.stream.scaladsl.UnzipWith12
    //akka.stream.scaladsl.UnzipWith13
    //akka.stream.scaladsl.UnzipWith14
    //akka.stream.scaladsl.UnzipWith15
    //akka.stream.scaladsl.UnzipWith16
    //akka.stream.scaladsl.UnzipWith17
    //akka.stream.scaladsl.UnzipWith18
    //akka.stream.scaladsl.UnzipWith19
    //akka.stream.scaladsl.UnzipWith2
    //akka.stream.scaladsl.UnzipWith20
    //akka.stream.scaladsl.UnzipWith21
    //akka.stream.scaladsl.UnzipWith22
    //akka.stream.scaladsl.UnzipWith3
    //akka.stream.scaladsl.UnzipWith4
    //akka.stream.scaladsl.UnzipWith5
    //akka.stream.scaladsl.UnzipWith6
    //akka.stream.scaladsl.UnzipWith7
    //akka.stream.scaladsl.UnzipWith8
    //akka.stream.scaladsl.UnzipWith9
    //akka.stream.scaladsl.UnzipWithApply
    //akka.stream.scaladsl.WireTap
    //akka.stream.scaladsl.Zip
    //akka.stream.scaladsl.ZipLatest
    akka.stream.scaladsl.ZipLatestWith
    //akka.stream.scaladsl.ZipLatestWith10
    //akka.stream.scaladsl.ZipLatestWith11
    //akka.stream.scaladsl.ZipLatestWith12
    //akka.stream.scaladsl.ZipLatestWith13
    //akka.stream.scaladsl.ZipLatestWith14
    //akka.stream.scaladsl.ZipLatestWith15
    //akka.stream.scaladsl.ZipLatestWith16
    //akka.stream.scaladsl.ZipLatestWith17
    //akka.stream.scaladsl.ZipLatestWith18
    //akka.stream.scaladsl.ZipLatestWith19
    //akka.stream.scaladsl.ZipLatestWith2
    //akka.stream.scaladsl.ZipLatestWith20
    //akka.stream.scaladsl.ZipLatestWith21
    //akka.stream.scaladsl.ZipLatestWith22
    //akka.stream.scaladsl.ZipLatestWith3
    //akka.stream.scaladsl.ZipLatestWith4
    //akka.stream.scaladsl.ZipLatestWith5
    //akka.stream.scaladsl.ZipLatestWith6
    //akka.stream.scaladsl.ZipLatestWith7
    //akka.stream.scaladsl.ZipLatestWith8
    //akka.stream.scaladsl.ZipLatestWith9
    akka.stream.scaladsl.ZipLatestWithApply
    akka.stream.scaladsl.ZipN
    akka.stream.scaladsl.ZipWith
    //akka.stream.scaladsl.ZipWith10
    //akka.stream.scaladsl.ZipWith11
    //akka.stream.scaladsl.ZipWith12
    //akka.stream.scaladsl.ZipWith13
    //akka.stream.scaladsl.ZipWith14
    //akka.stream.scaladsl.ZipWith15
    //akka.stream.scaladsl.ZipWith16
    //akka.stream.scaladsl.ZipWith17
    //akka.stream.scaladsl.ZipWith18
    //akka.stream.scaladsl.ZipWith19
    //akka.stream.scaladsl.ZipWith2
    //akka.stream.scaladsl.ZipWith20
    //akka.stream.scaladsl.ZipWith21
    //akka.stream.scaladsl.ZipWith22
    //akka.stream.scaladsl.ZipWith3
    //akka.stream.scaladsl.ZipWith4
    //akka.stream.scaladsl.ZipWith5
    //akka.stream.scaladsl.ZipWith6
    //akka.stream.scaladsl.ZipWith7
    //akka.stream.scaladsl.ZipWith8
    //akka.stream.scaladsl.ZipWith9
    akka.stream.scaladsl.ZipWithApply
    //akka.stream.scaladsl.ZipWithN
    //akka.stream.serialization.StreamRefSerializer
    //akka.stream.snapshot.ConnectionSnapshot
    akka.stream.snapshot.ConnectionSnapshotImpl
    //akka.stream.snapshot.HideImpl
    //akka.stream.snapshot.InterpreterSnapshot
    //akka.stream.snapshot.LogicSnapshot
    akka.stream.snapshot.LogicSnapshotImpl
    //akka.stream.snapshot.MaterializerState
    //akka.stream.snapshot.RunningInterpreter
    akka.stream.snapshot.RunningInterpreterImpl
    //akka.stream.snapshot.StreamSnapshot
    akka.stream.snapshot.StreamSnapshotImpl
    //akka.stream.snapshot.UninitializedInterpreter
    akka.stream.snapshot.UninitializedInterpreterImpl
    //akka.stream.stage.AbstractGraphStageWithMaterializedValue
    akka.stream.stage.AbstractInHandler
    akka.stream.stage.AbstractInOutHandler
    akka.stream.stage.AbstractOutHandler
    akka.stream.stage.AsyncCallback
    akka.stream.stage.ConcurrentAsyncCallbackState
    akka.stream.stage.GraphStage
    //akka.stream.stage.GraphStageLogic
    akka.stream.stage.GraphStageLogicWithLogging
    //akka.stream.stage.GraphStageWithMaterializedValue
    akka.stream.stage.InHandler
    //akka.stream.stage.OutHandler
    //akka.stream.stage.StageLogging
    //akka.stream.stage.TimerGraphStageLogic
    akka.stream.stage.TimerGraphStageLogicWithLogging
    akka.stream.stage.TimerMessages
  """)
}