package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.given
import org.junit.Test

class AkkaRemoteSemanticTest extends SemanticTestBase("com.typesafe.akka" %% "akka-remote" % "2.8.8")("akka.remote") {
  @Test def test(): Unit = doTest("""
    akka.remote.AddressUidExtension
    //akka.remote.BoundAddressesExtension
    //akka.remote.ByteStringUtils
    akka.remote.DaemonMsg
    akka.remote.DaemonMsgCreate
    //akka.remote.DeadlineFailureDetector
    //akka.remote.DefaultFailureDetectorRegistry
    //akka.remote.FailureDetector
    //akka.remote.FailureDetectorLoader
    akka.remote.FailureDetectorRegistry
    //akka.remote.HeartbeatHistory
    akka.remote.HeartbeatMessage
    //akka.remote.MessageSerializer
    //akka.remote.NotAllowedClassRemoteDeploymentAttemptException
    //akka.remote.PhiAccrualFailureDetector
    akka.remote.PriorityMessage
    akka.remote.RARP
    //akka.remote.RemoteActorRef
    //akka.remote.RemoteActorRefProvider
    //akka.remote.RemoteDeployer
    //akka.remote.RemoteDeploymentWatcher
    //akka.remote.RemoteLogMarker
    akka.remote.RemoteRef
    akka.remote.RemoteScope
    //akka.remote.RemoteSettings
    //akka.remote.RemoteSystemDaemon
    //akka.remote.RemoteTransport
    akka.remote.RemoteTransportException
    akka.remote.RemoteTransportExceptionNoStackTrace
    //akka.remote.RemoteWatcher
    akka.remote.UniqueAddress
    //akka.remote.artery.ActorRefResolveCacheWithAddress
    akka.remote.artery.ActorSystemTerminating
    akka.remote.artery.ActorSystemTerminatingAck
    akka.remote.artery.ArteryMessage
    //akka.remote.artery.ArterySettings
    //akka.remote.artery.ArteryTransport
    //akka.remote.artery.Association
    //akka.remote.artery.AssociationRegistry
    //akka.remote.artery.AssociationState
    //akka.remote.artery.ByteFlag
    akka.remote.artery.CacheStatistics
    akka.remote.artery.ControlMessage
    //akka.remote.artery.Decoder
    //akka.remote.artery.Deserializer
    //akka.remote.artery.DuplicateFlush
    //akka.remote.artery.DuplicateHandshakeReq
    //akka.remote.artery.Encoder
    //akka.remote.artery.EnvelopeBuffer
    akka.remote.artery.EnvelopeBufferPool
    //akka.remote.artery.FixedSizePartitionHub
    //akka.remote.artery.FixedSizePartitionQueue
    akka.remote.artery.Flush
    akka.remote.artery.FlushAck
    //akka.remote.artery.FlushBeforeDeathWatchNotification
    //akka.remote.artery.FlushOnShutdown
    //akka.remote.artery.GracefulShutdownQuarantinedEvent
    //akka.remote.artery.HeaderBuilder
    //akka.remote.artery.HeaderBuilderImpl
    //akka.remote.artery.ImmutableLongMap
    akka.remote.artery.InboundContext
    //akka.remote.artery.InboundControlJunction
    akka.remote.artery.InboundEnvelope
    //akka.remote.artery.InboundHandshake
    //akka.remote.artery.InboundQuarantineCheck
    //akka.remote.artery.InboundTestStage
    //akka.remote.artery.LoggingRemoteInstrument
    //akka.remote.artery.LruBoundedCache
    //akka.remote.artery.MessageDispatcher
    akka.remote.artery.NoOpRemotingFlightRecorder
    //akka.remote.artery.ObjectPool
    akka.remote.artery.OutOfBuffersException
    akka.remote.artery.OutboundContext
    //akka.remote.artery.OutboundControlJunction
    akka.remote.artery.OutboundEnvelope
    //akka.remote.artery.OutboundHandshake
    //akka.remote.artery.OutboundTestStage
    akka.remote.artery.OversizedPayloadException
    akka.remote.artery.Quarantined
    //akka.remote.artery.QuarantinedEvent
    akka.remote.artery.RemoteInstrument
    //akka.remote.artery.RemoteInstruments
    akka.remote.artery.RemotingFlightRecorder
    akka.remote.artery.Reply
    //akka.remote.artery.RestartCounter
    akka.remote.artery.ReusableInboundEnvelope
    akka.remote.artery.ReusableOutboundEnvelope
    //akka.remote.artery.SendQueue
    //akka.remote.artery.SerializationFormatCache
    //akka.remote.artery.SharedTestState
    //akka.remote.artery.SystemMessageAcker
    //akka.remote.artery.SystemMessageDelivery
    akka.remote.artery.TestManagementCommands
    akka.remote.artery.TestState
    akka.remote.artery.ThisActorSystemQuarantinedEvent
    //akka.remote.artery.aeron.AeronSource
    //akka.remote.artery.aeron.TaskRunner
    akka.remote.artery.compress.CompressionProtocol
    //akka.remote.artery.compress.CompressionTable
    //akka.remote.artery.compress.DecompressionTable
    //akka.remote.artery.compress.InboundActorRefCompression
    //akka.remote.artery.compress.InboundCompression
    akka.remote.artery.compress.InboundCompressions
    //akka.remote.artery.compress.InboundCompressionsImpl
    //akka.remote.artery.compress.InboundManifestCompression
    akka.remote.artery.compress.NoInboundCompressions
    //akka.remote.artery.compress.TopHeavyHitters
    //akka.remote.artery.compress.UnknownCompressedIdException
    //akka.remote.artery.tcp.ArteryTcpTransport
    //akka.remote.artery.tcp.ConfigSSLEngineProvider
    akka.remote.artery.tcp.SSLEngineProvider
    akka.remote.artery.tcp.SSLEngineProviderSetup
    //akka.remote.artery.tcp.SecureRandomFactory
    akka.remote.artery.tcp.SslTransportException
    //akka.remote.artery.tcp.TcpFraming
    akka.remote.artery.tcp.ssl.NoopSessionVerifier
    //akka.remote.artery.tcp.ssl.PeerSubjectVerifier
    akka.remote.artery.tcp.ssl.PemManagersProvider
    //akka.remote.artery.tcp.ssl.RotatingKeysSSLEngineProvider
    akka.remote.artery.tcp.ssl.SSLEngineConfig
    akka.remote.artery.tcp.ssl.SessionVerifier
    //akka.remote.artery.tcp.ssl.X509Readers
    //akka.remote.routing.RemoteRouterConfig
    akka.remote.security.provider.SeedSize
    //akka.remote.serialization.AbstractActorRefResolveCache
    //akka.remote.serialization.ActorRefResolveCache
    //akka.remote.serialization.ActorRefResolveThreadLocalCache
    //akka.remote.serialization.ArteryMessageSerializer
    akka.remote.serialization.ByteStringSerializer
    //akka.remote.serialization.DaemonMsgCreateSerializer
    akka.remote.serialization.IntSerializer
    akka.remote.serialization.LongSerializer
    //akka.remote.serialization.MessageContainerSerializer
    //akka.remote.serialization.MiscMessageSerializer
    //akka.remote.serialization.ProtobufSerializer
    akka.remote.serialization.StringSerializer
    //akka.remote.serialization.SystemMessageSerializer
    //akka.remote.serialization.ThrowableNotSerializableException
    //akka.remote.serialization.ThrowableSupport
    //akka.remote.serialization.WrappedPayloadSupport
    //akka.remote.testkit.Blackhole
    akka.remote.testkit.Direction
    akka.remote.testkit.ForceDisassociate
    akka.remote.testkit.ForceDisassociateAck
    akka.remote.testkit.SetThrottle
    akka.remote.testkit.SetThrottleAck
    akka.remote.testkit.ThrottleMode
    //akka.remote.testkit.TokenBucket
    //akka.remote.testkit.Unthrottled
  """)
}