package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.given
import org.junit.Test

class CatsCoreSemanticTest extends SemanticTestBase("org.typelevel" %% "cats-core" % "2.13.0")("cats") {
  override protected def enableKindProjectorPlugin = true

  @Test def test(): Unit = doTest("""
    //cats.Align
    //cats.Alternative
    cats.Always
    //cats.Applicative
    //cats.ApplicativeError
    //cats.ApplicativeMonoid
    //cats.Apply
    //cats.ApplyArityFunctions
    //cats.ApplySemigroup
    //cats.ArrowApplicative
    cats.Bifoldable
    //cats.Bifunctor
    cats.Bimonad
    //cats.Bitraverse
    cats.CoflatMap
    //cats.CommutativeApplicative
    //cats.CommutativeApply
    cats.CommutativeFlatMap
    cats.CommutativeMonad
    cats.Comonad
    cats.ComposedAlternative
    cats.ComposedApplicative
    //cats.ComposedApplicativeContravariantMonoidal
    //cats.ComposedApply
    cats.ComposedBifoldable
    cats.ComposedBifunctor
    cats.ComposedBitraverse
    cats.ComposedContravariant
    cats.ComposedContravariantCovariant
    cats.ComposedCovariantContravariant
    cats.ComposedDistributive
    //cats.ComposedFoldable
    cats.ComposedFunctor
    cats.ComposedFunctorBifunctor
    cats.ComposedInvariant
    //cats.ComposedInvariantApplySemigroupal
    cats.ComposedInvariantContravariant
    cats.ComposedInvariantCovariant
    cats.ComposedMonoidK
    cats.ComposedNonEmptyAlternative
    cats.ComposedNonEmptyTraverse
    //cats.ComposedReducible
    cats.ComposedSemigroupK
    //cats.ComposedSemigroupal
    cats.ComposedTraverse
    //cats.Contravariant
    //cats.ContravariantMonoidal
    cats.ContravariantMonoidalMonoid
    cats.ContravariantSemigroupal
    cats.ContravariantSemigroupalSemigroup
    //cats.Defer
    //cats.Distributive
    //cats.Eval
    //cats.EvalGroup
    //cats.EvalInstances
    cats.EvalInstances0
    cats.EvalInstances1
    cats.EvalMonoid
    cats.EvalSemigroup
    //cats.FlatMap
    //cats.FlatMapArityFunctions
    //cats.Foldable
    //cats.FoldableNFunctions
    //cats.Functor
    //cats.FunctorFilter
    cats.FunctorFilterInstances0
    cats.Inject
    //cats.InjectInstances
    cats.InjectK
    //cats.InjectKInstances
    //cats.Invariant
    cats.InvariantInstances0
    cats.InvariantInstances1
    cats.InvariantInstances2
    //cats.InvariantMonoidal
    //cats.InvariantMonoidalMonoid
    cats.InvariantSemigroupal
    //cats.InvariantSemigroupalSemigroup
    cats.Later
    //cats.LeftFunctor
    //cats.Monad
    //cats.MonadError
    cats.MonoidK
    cats.NonEmptyAlternative
    //cats.NonEmptyParallel
    //cats.NonEmptyReducible
    //cats.NonEmptyTraverse
    //cats.NotNull
    cats.Now
    //cats.Parallel
    //cats.ParallelArityFunctions
    //cats.ParallelArityFunctions2
    //cats.Reducible
    //cats.Representable
    //cats.RepresentableBimonad
    //cats.RepresentableDistributive
    //cats.RepresentableMonad
    //cats.RightFunctor
    cats.ScalaVersionSpecificAlignInstances
    cats.ScalaVersionSpecificInvariantInstances
    cats.ScalaVersionSpecificMonoidKInstances
    //cats.ScalaVersionSpecificParallelInstances
    cats.ScalaVersionSpecificSemigroupalInstances
    cats.ScalaVersionSpecificShowInstances
    cats.ScalaVersionSpecificTraverseFilterInstances
    cats.ScalaVersionSpecificTraverseInstances
    //cats.SemigroupK
    cats.SemigroupKInstances0
    //cats.Semigroupal
    //cats.SemigroupalArityFunctions
    //cats.Show
    cats.ShowInstances
    cats.ShowInstances0
    //cats.StackSafeMonad
    //cats.Traverse
    //cats.TraverseFilter
    cats.TupleInstances0
    cats.TupleInstances1
    cats.TupleInstances2
    //cats.UnorderedFoldable
    cats.UnorderedFoldableLowPriority
    //cats.UnorderedTraverse
    //cats.arrow.Arrow
    //cats.arrow.ArrowChoice
    cats.arrow.Category
    cats.arrow.Choice
    cats.arrow.CommutativeArrow
    //cats.arrow.Compose
    //cats.arrow.FunctionK
    //cats.arrow.FunctionKLift
    //cats.arrow.FunctionKMacroMethods
    //cats.arrow.Profunctor
    cats.arrow.Strong
    //cats.compat.FoldableCompat
    //cats.compat.Seq
    //cats.compat.SortedSet
    //cats.compat.Vector
    cats.conversions.AllConversions
    //cats.conversions.VarianceConversions
    cats.conversions.VarianceConversionsLowPriority
    //cats.data.AbstractNonEmptyInstances
    //cats.data.AndThen
    //cats.data.AndThenInstances0
    cats.data.AndThenInstances1
    //cats.data.AppFunc
    //cats.data.AppFuncApplicative
    //cats.data.AppFuncInstances
    cats.data.Binested
    cats.data.BinestedBifoldable
    cats.data.BinestedBitraverse
    cats.data.BinestedInstances
    cats.data.BinestedInstances0
    //cats.data.Chain
    cats.data.ChainCompanionCompat
    //cats.data.ChainCompat
    //cats.data.ChainInstances
    cats.data.ChainInstances1
    //cats.data.ChainInstances2
    //cats.data.ChainInstances3
    //cats.data.ChainPartialOrder
    //cats.data.Cokleisli
    //cats.data.CokleisliArrow
    cats.data.CokleisliCompose
    //cats.data.CokleisliInstances
    cats.data.CokleisliInstances0
    cats.data.CokleisliInstances1
    //cats.data.CokleisliMonad
    cats.data.CokleisliProfunctor
    //cats.data.CommonIRWSTConstructors
    //cats.data.CommonStateTConstructors
    cats.data.CommonStateTConstructors0
    //cats.data.Const
    cats.data.ConstApplicative
    cats.data.ConstApply
    cats.data.ConstContravariant
    cats.data.ConstFunctor
    //cats.data.ConstInstances
    //cats.data.ConstInstances0
    //cats.data.ConstInstances1
    cats.data.ConstInstances2
    //cats.data.ConstInstances3
    cats.data.ConstInstances4
    //cats.data.ContT
    //cats.data.EitherK
    //cats.data.EitherKCoflatMap
    //cats.data.EitherKComonad
    cats.data.EitherKContravariant
    //cats.data.EitherKFoldable
    cats.data.EitherKFunctor
    //cats.data.EitherKInstances
    //cats.data.EitherKInstances0
    //cats.data.EitherKInstances1
    cats.data.EitherKInstances2
    cats.data.EitherKInstances3
    cats.data.EitherKTraverse
    //cats.data.EitherT
    cats.data.EitherTBifoldable
    cats.data.EitherTBifunctor
    cats.data.EitherTBitraverse
    //cats.data.EitherTEq
    cats.data.EitherTFoldable
    cats.data.EitherTFunctor
    //cats.data.EitherTInstances
    //cats.data.EitherTInstances1
    cats.data.EitherTInstances2
    cats.data.EitherTInstances3
    //cats.data.EitherTMonad
    //cats.data.EitherTMonadError
    cats.data.EitherTMonadErrorF
    cats.data.EitherTMonoid
    cats.data.EitherTOrder
    cats.data.EitherTPartialOrder
    cats.data.EitherTSemigroup
    //cats.data.EitherTSemigroupK
    cats.data.EitherTTraverse
    cats.data.Func
    //cats.data.FuncApplicative
    //cats.data.FuncApply
    //cats.data.FuncContravariant
    //cats.data.FuncFunctor
    //cats.data.FuncInstances
    //cats.data.FuncInstances0
    //cats.data.FuncInstances1
    cats.data.IRWSTBifunctor
    cats.data.IRWSTContravariant
    cats.data.IRWSTFunctor
    cats.data.IRWSTInstances
    cats.data.IRWSTInstances1
    cats.data.IRWSTInstances2
    cats.data.IRWSTInstances3
    cats.data.IRWSTProfunctor
    cats.data.IRWSTSemigroupK
    //cats.data.IRWSTSemigroupK1
    //cats.data.IRWSTStrong
    cats.data.IdT
    cats.data.IdTApplicative
    cats.data.IdTApply
    cats.data.IdTContravariantMonoidal
    cats.data.IdTFlatMap
    cats.data.IdTFoldable
    cats.data.IdTFunctor
    cats.data.IdTInstances
    cats.data.IdTInstances0
    cats.data.IdTInstances1
    cats.data.IdTInstances2
    cats.data.IdTInstances3
    cats.data.IdTInstances4
    cats.data.IdTInstances5
    cats.data.IdTInstances6
    //cats.data.IdTInstances7
    //cats.data.IdTInstances8
    cats.data.IdTMonad
    cats.data.IdTNonEmptyTraverse
    //cats.data.IdTTraverse
    //cats.data.IndexedReaderWriterStateT
    //cats.data.IndexedStateFunctions
    //cats.data.IndexedStateT
    cats.data.IndexedStateTAlternative
    cats.data.IndexedStateTBifunctor
    cats.data.IndexedStateTContravariant
    //cats.data.IndexedStateTContravariantMonoidal
    cats.data.IndexedStateTFunctor
    //cats.data.IndexedStateTFunctorFilter
    cats.data.IndexedStateTInstances
    cats.data.IndexedStateTInstances1
    cats.data.IndexedStateTInstances2
    cats.data.IndexedStateTInstances3
    cats.data.IndexedStateTInstances4
    //cats.data.IndexedStateTMonad
    cats.data.IndexedStateTMonadError
    cats.data.IndexedStateTProfunctor
    cats.data.IndexedStateTSemigroupK
    //cats.data.IndexedStateTStrong
    //cats.data.Ior
    //cats.data.IorFunctions
    //cats.data.IorFunctions2
    //cats.data.IorInstances
    //cats.data.IorInstances0
    //cats.data.IorT
    //cats.data.IorTEq
    cats.data.IorTFoldable
    cats.data.IorTFunctor
    //cats.data.IorTInstances
    //cats.data.IorTInstances1
    cats.data.IorTInstances2
    cats.data.IorTInstances3
    //cats.data.IorTMonad
    //cats.data.IorTMonadError
    cats.data.IorTMonadErrorF
    cats.data.IorTMonoid
    cats.data.IorTOrder
    cats.data.IorTSemigroup
    cats.data.IorTTraverse
    //cats.data.Kleisli
    cats.data.KleisliAlign
    cats.data.KleisliAlternative
    cats.data.KleisliApplicative
    //cats.data.KleisliApplicativeError
    //cats.data.KleisliApply
    //cats.data.KleisliArrowChoice
    cats.data.KleisliCategory
    cats.data.KleisliChoice
    cats.data.KleisliCommutativeArrow
    cats.data.KleisliCompose
    //cats.data.KleisliContravariantMonoidal
    cats.data.KleisliDistributive
    //cats.data.KleisliExplicitInstances
    //cats.data.KleisliFlatMap
    cats.data.KleisliFromFunctionPartiallyApplied
    //cats.data.KleisliFunctions
    cats.data.KleisliFunctionsBinCompat
    //cats.data.KleisliFunctor
    //cats.data.KleisliFunctorFilter
    //cats.data.KleisliInstances
    //cats.data.KleisliInstances0
    //cats.data.KleisliInstances0_5
    cats.data.KleisliInstances1
    cats.data.KleisliInstances2
    //cats.data.KleisliInstances3
    cats.data.KleisliInstances4
    cats.data.KleisliInstances5
    cats.data.KleisliInstances6
    cats.data.KleisliInstances7
    //cats.data.KleisliInstances8
    cats.data.KleisliInstances9
    cats.data.KleisliMonad
    cats.data.KleisliMonadError
    //cats.data.KleisliMonoid
    //cats.data.KleisliMonoidK
    cats.data.KleisliSemigroup
    cats.data.KleisliSemigroupK
    cats.data.KleisliStrong
    cats.data.Nested
    //cats.data.NestedAlign
    cats.data.NestedAlternative
    cats.data.NestedApplicative
    //cats.data.NestedApplicativeError
    cats.data.NestedApply
    cats.data.NestedContravariant
    cats.data.NestedContravariantMonoidal
    //cats.data.NestedDistributive
    cats.data.NestedFoldable
    cats.data.NestedFunctor
    //cats.data.NestedFunctorFilter
    //cats.data.NestedInstances
    //cats.data.NestedInstances0
    cats.data.NestedInstances1
    cats.data.NestedInstances10
    cats.data.NestedInstances11
    cats.data.NestedInstances12
    cats.data.NestedInstances13
    cats.data.NestedInstances2
    cats.data.NestedInstances3
    cats.data.NestedInstances4
    //cats.data.NestedInstances5
    //cats.data.NestedInstances6
    cats.data.NestedInstances7
    cats.data.NestedInstances8
    cats.data.NestedInstances9
    cats.data.NestedInvariant
    cats.data.NestedInvariantSemigroupalApply
    cats.data.NestedMonoidK
    cats.data.NestedNonEmptyTraverse
    cats.data.NestedReducible
    cats.data.NestedSemigroupK
    //cats.data.NestedTraverse
    //cats.data.NestedTraverseFilter
    //cats.data.Newtype
    //cats.data.Newtype2
    //cats.data.NonEmptyChainImpl
    //cats.data.NonEmptyChainInstances
    //cats.data.NonEmptyChainInstances1
    //cats.data.NonEmptyChainInstances2
    //cats.data.NonEmptyChainInstances3
    //cats.data.NonEmptyChainOps
    cats.data.NonEmptyCollection
    //cats.data.NonEmptyLazyList
    //cats.data.NonEmptyLazyListInstances
    cats.data.NonEmptyLazyListInstances1
    cats.data.NonEmptyLazyListInstances2
    cats.data.NonEmptyLazyListInstances3
    //cats.data.NonEmptyLazyListOps
    //cats.data.NonEmptyList
    //cats.data.NonEmptyListEq
    //cats.data.NonEmptyListInstances
    cats.data.NonEmptyListInstances0
    cats.data.NonEmptyListInstances1
    cats.data.NonEmptyListOrder
    //cats.data.NonEmptyListPartialOrder
    //cats.data.NonEmptyMapImpl
    //cats.data.NonEmptyMapInstances
    //cats.data.NonEmptyMapInstances0
    //cats.data.NonEmptyMapOps
    //cats.data.NonEmptySeq
    //cats.data.NonEmptySeqInstances
    //cats.data.NonEmptySetEq
    //cats.data.NonEmptySetImpl
    //cats.data.NonEmptySetInstances
    //cats.data.NonEmptySetInstances0
    cats.data.NonEmptySetInstances1
    //cats.data.NonEmptySetOps
    cats.data.NonEmptySetOrder
    //cats.data.NonEmptyVector
    //cats.data.NonEmptyVectorInstances
    //cats.data.NonEmptyVectorInstances0
    //cats.data.NonEmptyVectorInstances1
    //cats.data.NonEmptyVectorInstances2
    //cats.data.OneAnd
    //cats.data.OneAndInstances
    //cats.data.OneAndLowPriority0
    //cats.data.OneAndLowPriority0_5
    //cats.data.OneAndLowPriority1
    //cats.data.OneAndLowPriority2
    cats.data.OneAndLowPriority3
    //cats.data.OneAndLowPriority4
    cats.data.Op
    cats.data.OpCategory
    cats.data.OpCompose
    cats.data.OpEq
    cats.data.OpInstances
    cats.data.OpInstances0
    //cats.data.OptionT
    cats.data.OptionTContravariant
    cats.data.OptionTContravariantMonoidal
    //cats.data.OptionTEq
    cats.data.OptionTFoldable
    cats.data.OptionTFunctor
    //cats.data.OptionTFunctorFilter
    //cats.data.OptionTInstances
    //cats.data.OptionTInstances0
    cats.data.OptionTInstances1
    cats.data.OptionTInstances2
    cats.data.OptionTInstances3
    cats.data.OptionTInvariant
    //cats.data.OptionTMonad
    cats.data.OptionTMonadError
    //cats.data.OptionTMonadErrorMonad
    cats.data.OptionTMonoid
    cats.data.OptionTMonoidK
    cats.data.OptionTOrder
    cats.data.OptionTPartialOrder
    cats.data.OptionTSemigroup
    //cats.data.OptionTSemigroupK
    cats.data.OptionTTraverse
    //cats.data.RWSFunctions
    cats.data.RWSTAlternative
    cats.data.RWSTAlternative1
    //cats.data.RWSTFunctions
    //cats.data.RWSTMonad
    //cats.data.RWSTMonadError
    //cats.data.RepresentableStore
    //cats.data.RepresentableStoreT
    //cats.data.RepresentableStoreTInstances1
    cats.data.RepresentableStoreTInstances2
    cats.data.ScalaVersionSpecificNonEmptyChainImpl
    //cats.data.ScalaVersionSpecificPackage
    //cats.data.StateFunctions
    //cats.data.StateTFunctions
    //cats.data.StrictConstFunction1
    //cats.data.Tuple2K
    //cats.data.Tuple2KAlternative
    //cats.data.Tuple2KApplicative
    //cats.data.Tuple2KApply
    //cats.data.Tuple2KContravariant
    //cats.data.Tuple2KContravariantMonoidal
    //cats.data.Tuple2KDistributive
    //cats.data.Tuple2KFoldable
    //cats.data.Tuple2KFunctor
    //cats.data.Tuple2KInstances
    //cats.data.Tuple2KInstances0
    //cats.data.Tuple2KInstances1
    //cats.data.Tuple2KInstances2
    //cats.data.Tuple2KInstances3
    //cats.data.Tuple2KInstances4
    //cats.data.Tuple2KInstances5
    //cats.data.Tuple2KInstances6
    //cats.data.Tuple2KInstances7
    //cats.data.Tuple2KInstances8
    //cats.data.Tuple2KMonad
    //cats.data.Tuple2KMonoidK
    cats.data.Tuple2KOrder
    //cats.data.Tuple2KSemigroupK
    //cats.data.Tuple2KSemigroupal
    //cats.data.Tuple2KShow
    //cats.data.Tuple2KTraverse
    //cats.data.Validated
    //cats.data.ValidatedApplicative
    //cats.data.ValidatedFunctions
    //cats.data.ValidatedFunctionsBinCompat0
    //cats.data.ValidatedInstances
    //cats.data.ValidatedInstances1
    //cats.data.ValidatedInstances2
    //cats.data.WriterT
    cats.data.WriterTAlternative
    cats.data.WriterTApplicative
    cats.data.WriterTApplicativeError
    //cats.data.WriterTApply
    //cats.data.WriterTCoflatMap
    cats.data.WriterTComonad
    cats.data.WriterTContravariant
    cats.data.WriterTContravariantMonoidal
    //cats.data.WriterTFlatMap1
    //cats.data.WriterTFlatMap2
    cats.data.WriterTFoldable
    cats.data.WriterTFunctions
    //cats.data.WriterTFunctions0
    cats.data.WriterTFunctor
    cats.data.WriterTInstances
    //cats.data.WriterTInstances0
    //cats.data.WriterTInstances1
    cats.data.WriterTInstances10
    cats.data.WriterTInstances11
    cats.data.WriterTInstances12
    cats.data.WriterTInstances13
    //cats.data.WriterTInstances2
    //cats.data.WriterTInstances3
    cats.data.WriterTInstances4
    cats.data.WriterTInstances5
    cats.data.WriterTInstances6
    cats.data.WriterTInstances7
    cats.data.WriterTInstances8
    cats.data.WriterTInstances9
    cats.data.WriterTInvariant
    cats.data.WriterTMonad
    cats.data.WriterTMonadError
    cats.data.WriterTMonoid
    cats.data.WriterTMonoidK
    cats.data.WriterTSemigroup
    cats.data.WriterTSemigroupK
    cats.data.WriterTTraverse
    //cats.data.ZipLazyList
    //cats.data.ZipList
    //cats.data.ZipSeq
    //cats.data.ZipStream
    //cats.data.ZipVector
    //cats.evidence.As
    cats.evidence.AsInstances
    //cats.evidence.AsSupport
    //cats.evidence.Is
    cats.evidence.IsInstances
    cats.evidence.IsSupport
    cats.implicits
    cats.instances.AllCoreDurationInstances
    cats.instances.AllInstances
    cats.instances.AllInstancesBinCompat
    cats.instances.AllInstancesBinCompat0
    cats.instances.AllInstancesBinCompat1
    cats.instances.AllInstancesBinCompat10
    cats.instances.AllInstancesBinCompat2
    cats.instances.AllInstancesBinCompat3
    cats.instances.AllInstancesBinCompat4
    cats.instances.AllInstancesBinCompat5
    cats.instances.AllInstancesBinCompat6
    cats.instances.AllInstancesBinCompat7
    cats.instances.AllInstancesBinCompat8
    cats.instances.AllInstancesBinCompat9
    cats.instances.AnyValInstances
    //cats.instances.ArraySeqInstances
    cats.instances.BigDecimalInstances
    cats.instances.BigIntInstances
    cats.instances.BitSetInstances
    cats.instances.BooleanInstances
    cats.instances.ByteInstances
    cats.instances.CharInstances
    cats.instances.CoreDurationInstances
    cats.instances.CoreFiniteDurationInstances
    cats.instances.DeadlineInstances
    cats.instances.DoubleInstances
    cats.instances.DurationInstances
    //cats.instances.EitherInstances
    //cats.instances.EqInstances
    //cats.instances.EquivInstances
    cats.instances.FiniteDurationInstances
    //cats.instances.FlatMapNTuple2
    //cats.instances.FlatMapTuple1
    //cats.instances.FlatMapTuple10
    //cats.instances.FlatMapTuple11
    //cats.instances.FlatMapTuple2
    //cats.instances.FlatMapTuple3
    //cats.instances.FlatMapTuple4
    //cats.instances.FlatMapTuple5
    //cats.instances.FlatMapTuple6
    //cats.instances.FlatMapTuple7
    //cats.instances.FlatMapTuple8
    //cats.instances.FlatMapTuple9
    cats.instances.FloatInstances
    //cats.instances.Function0Instances
    //cats.instances.Function0Instances0
    //cats.instances.Function1Instances
    //cats.instances.Function1Instances0
    cats.instances.FunctionInstances
    //cats.instances.FunctionInstancesBinCompat0
    //cats.instances.FutureCoflatMap
    //cats.instances.FutureInstances
    cats.instances.FutureInstances1
    cats.instances.FutureInstances2
    //cats.instances.FutureMonoid
    //cats.instances.FutureSemigroup
    //cats.instances.HashInstances
    cats.instances.IntInstances
    //cats.instances.InvariantInstances
    //cats.instances.InvariantInstancesBinCompat0
    //cats.instances.InvariantMonoidalInstances
    //cats.instances.LazyListInstances
    //cats.instances.ListInstances
    //cats.instances.ListInstancesBinCompat0
    cats.instances.LongInstances
    //cats.instances.LowPrioritySortedSetInstancesBinCompat1
    //cats.instances.MapInstances
    //cats.instances.MapInstancesBinCompat0
    //cats.instances.MapInstancesBinCompat1
    //cats.instances.NTupleBifunctorInstances
    //cats.instances.NTupleBitraverseInstances
    //cats.instances.NTupleMonadInstances
    //cats.instances.NTupleMonadInstances1
    //cats.instances.NTupleMonadInstances2
    //cats.instances.NTupleMonadInstances3
    cats.instances.NTupleMonadInstances4
    //cats.instances.NTupleMonadInstances5
    //cats.instances.NTupleShowInstances
    //cats.instances.NTupleUnorderedFoldableInstances
    //cats.instances.OptionInstances
    cats.instances.OptionInstancesBinCompat0
    //cats.instances.OrderInstances
    //cats.instances.OrderingInstances
    cats.instances.ParallelInstances
    cats.instances.ParallelInstances1
    //cats.instances.PartialFunctionInstances
    //cats.instances.PartialOrderInstances
    //cats.instances.PartialOrderingInstances
    //cats.instances.QueueInstances
    //cats.instances.ScalaVersionSpecificNumeric
    //cats.instances.SeqInstances
    //cats.instances.SetInstances
    cats.instances.ShortInstances
    //cats.instances.ShowInstances
    //cats.instances.SortedMapCommutativeMonoid
    //cats.instances.SortedMapEq
    //cats.instances.SortedMapHash
    //cats.instances.SortedMapInstances
    cats.instances.SortedMapInstances1
    cats.instances.SortedMapInstances2
    //cats.instances.SortedMapInstancesBinCompat0
    //cats.instances.SortedMapInstancesBinCompat1
    cats.instances.SortedMapInstancesBinCompat2
    //cats.instances.SortedMapMonoid
    //cats.instances.SortedSetHash
    //cats.instances.SortedSetInstances
    //cats.instances.SortedSetInstances1
    //cats.instances.SortedSetInstancesBinCompat0
    //cats.instances.SortedSetInstancesBinCompat1
    //cats.instances.SortedSetOrder
    //cats.instances.SortedSetSemilattice
    //cats.instances.StaticMethods
    //cats.instances.StreamInstances
    //cats.instances.StreamInstancesBinCompat0
    cats.instances.StringInstances
    cats.instances.SymbolInstances
    //cats.instances.TailRecInstances
    cats.instances.TryCoflatMap
    //cats.instances.TryInstances
    cats.instances.TryInstances1
    cats.instances.TryInstances2
    //cats.instances.TryMonoid
    //cats.instances.TrySemigroup
    //cats.instances.Tuple2Instances
    //cats.instances.Tuple2Instances1
    //cats.instances.Tuple2Instances2
    //cats.instances.Tuple2Instances3
    cats.instances.Tuple2Instances4
    //cats.instances.Tuple2InstancesBinCompat0
    cats.instances.TupleInstances
    cats.instances.UUIDInstances
    cats.instances.UnitInstances
    //cats.instances.VectorInstances
    //cats.instances.VectorInstancesBinCompat0
    //cats.kernel.Band
    cats.kernel.BandInstances
    //cats.kernel.BoundedEnumerable
    //cats.kernel.BoundedSemilattice
    cats.kernel.BoundedSemilatticeInstances
    //cats.kernel.CommutativeGroup
    //cats.kernel.CommutativeMonoid
    cats.kernel.CommutativeMonoidInstances
    //cats.kernel.CommutativeSemigroup
    cats.kernel.CommutativeSemigroupInstances
    //cats.kernel.Comparison
    //cats.kernel.Eq
    //cats.kernel.EqFunctions
    cats.kernel.EqInstances
    cats.kernel.EqInstances0
    //cats.kernel.EqToEquivConversion
    cats.kernel.FutureMonoid
    cats.kernel.FutureSemigroup
    //cats.kernel.Group
    //cats.kernel.GroupFunctions
    cats.kernel.GroupInstances
    //cats.kernel.Hash
    //cats.kernel.HashFunctions
    //cats.kernel.HashInstances
    cats.kernel.HashInstances0
    //cats.kernel.HashToHashingConversion
    //cats.kernel.LowerBounded
    //cats.kernel.LowerBoundedEnumerable
    //cats.kernel.LowerBoundedFunctions
    //cats.kernel.Monoid
    //cats.kernel.MonoidFunctions
    cats.kernel.MonoidInstances
    //cats.kernel.Next
    //cats.kernel.Order
    //cats.kernel.OrderFunctions
    cats.kernel.OrderInstances0
    cats.kernel.OrderInstances1
    cats.kernel.OrderToOrderingConversion
    //cats.kernel.PartialNext
    //cats.kernel.PartialNextLowerBounded
    //cats.kernel.PartialOrder
    //cats.kernel.PartialOrderFunctions
    cats.kernel.PartialOrderInstances
    cats.kernel.PartialOrderInstances0
    cats.kernel.PartialOrderInstances1
    cats.kernel.PartialOrderToPartialOrderingConversion
    //cats.kernel.PartialPrevious
    //cats.kernel.PartialPreviousUpperBounded
    //cats.kernel.Previous
    cats.kernel.ScalaVersionSpecificEqInstances
    cats.kernel.ScalaVersionSpecificHashInstances
    cats.kernel.ScalaVersionSpecificMonoidInstances
    cats.kernel.ScalaVersionSpecificOrderInstances
    cats.kernel.ScalaVersionSpecificPartialOrderInstances
    //cats.kernel.Semigroup
    //cats.kernel.SemigroupFunctions
    cats.kernel.SemigroupInstances
    //cats.kernel.Semilattice
    //cats.kernel.SemilatticeFunctions
    cats.kernel.SemilatticeInstances
    cats.kernel.TryMonoid
    cats.kernel.TrySemigroup
    //cats.kernel.UnboundedEnumerable
    //cats.kernel.UpperBounded
    //cats.kernel.UpperBoundedEnumerable
    //cats.kernel.UpperBoundedFunctions
    //cats.kernel.compat.HashCompat
    //cats.kernel.compat.WrappedMutableMapBase
    cats.kernel.compat.scalaVersionMoreSpecific
    //cats.kernel.compat.scalaVersionSpecific
    cats.kernel.instances.AllInstances
    cats.kernel.instances.AllInstancesBinCompat0
    cats.kernel.instances.AllInstancesBinCompat1
    cats.kernel.instances.AllInstancesBinCompat2
    //cats.kernel.instances.ArraySeqInstances
    cats.kernel.instances.BigDecimalGroup
    cats.kernel.instances.BigDecimalInstances
    //cats.kernel.instances.BigDecimalOrder
    //cats.kernel.instances.BigIntGroup
    cats.kernel.instances.BigIntInstances
    //cats.kernel.instances.BigIntOrder
    //cats.kernel.instances.BigIntUnboundedEnum
    cats.kernel.instances.BitSetInstances
    cats.kernel.instances.BitSetPartialOrder
    //cats.kernel.instances.BitSetSemilattice
    cats.kernel.instances.BooleanBounded
    cats.kernel.instances.BooleanEnumerable
    cats.kernel.instances.BooleanInstances
    cats.kernel.instances.BooleanOrder
    cats.kernel.instances.ByteBounded
    cats.kernel.instances.ByteEnumerable
    cats.kernel.instances.ByteGroup
    cats.kernel.instances.ByteInstances
    cats.kernel.instances.ByteOrder
    cats.kernel.instances.CharBounded
    cats.kernel.instances.CharEnumerable
    cats.kernel.instances.CharInstances
    cats.kernel.instances.CharOrder
    //cats.kernel.instances.CombineFunction0
    //cats.kernel.instances.CombineFunction1
    cats.kernel.instances.DeadlineBounded
    cats.kernel.instances.DeadlineInstances
    //cats.kernel.instances.DeadlineOrder
    cats.kernel.instances.DoubleGroup
    cats.kernel.instances.DoubleInstances
    cats.kernel.instances.DoubleOrder
    cats.kernel.instances.DurationBounded
    //cats.kernel.instances.DurationGroup
    cats.kernel.instances.DurationInstances
    //cats.kernel.instances.DurationOrder
    cats.kernel.instances.EitherEq
    //cats.kernel.instances.EitherHash
    //cats.kernel.instances.EitherInstances
    //cats.kernel.instances.EitherInstances0
    cats.kernel.instances.EitherInstances1
    cats.kernel.instances.EqInstances
    cats.kernel.instances.FiniteDurationBounded
    //cats.kernel.instances.FiniteDurationGroup
    cats.kernel.instances.FiniteDurationInstances
    //cats.kernel.instances.FiniteDurationOrder
    cats.kernel.instances.FloatGroup
    cats.kernel.instances.FloatInstances
    cats.kernel.instances.FloatOrder
    //cats.kernel.instances.Function0Group
    //cats.kernel.instances.Function0Monoid
    //cats.kernel.instances.Function0Semigroup
    //cats.kernel.instances.Function1Group
    //cats.kernel.instances.Function1Monoid
    //cats.kernel.instances.Function1Semigroup
    //cats.kernel.instances.FunctionInstances
    //cats.kernel.instances.FunctionInstances0
    //cats.kernel.instances.FunctionInstances1
    //cats.kernel.instances.FunctionInstances2
    //cats.kernel.instances.FunctionInstances3
    cats.kernel.instances.FunctionInstances4
    cats.kernel.instances.HashInstances
    cats.kernel.instances.IntBounded
    cats.kernel.instances.IntEnumerable
    cats.kernel.instances.IntGroup
    cats.kernel.instances.IntInstances
    cats.kernel.instances.IntOrder
    //cats.kernel.instances.LazyListEq
    cats.kernel.instances.LazyListHash
    cats.kernel.instances.LazyListInstances
    cats.kernel.instances.LazyListInstances1
    cats.kernel.instances.LazyListInstances2
    //cats.kernel.instances.LazyListMonoid
    //cats.kernel.instances.LazyListOrder
    //cats.kernel.instances.LazyListPartialOrder
    //cats.kernel.instances.ListEq
    cats.kernel.instances.ListHash
    cats.kernel.instances.ListInstances
    cats.kernel.instances.ListInstances1
    cats.kernel.instances.ListInstances2
    //cats.kernel.instances.ListMonoid
    //cats.kernel.instances.ListOrder
    //cats.kernel.instances.ListPartialOrder
    cats.kernel.instances.LongBounded
    cats.kernel.instances.LongEnumerable
    cats.kernel.instances.LongGroup
    cats.kernel.instances.LongInstances
    cats.kernel.instances.LongOrder
    //cats.kernel.instances.MapEq
    //cats.kernel.instances.MapHash
    //cats.kernel.instances.MapInstances
    cats.kernel.instances.MapInstances1
    //cats.kernel.instances.MapMonoid
    cats.kernel.instances.OptionCommutativeMonoid
    cats.kernel.instances.OptionEq
    cats.kernel.instances.OptionHash
    cats.kernel.instances.OptionInstances
    cats.kernel.instances.OptionInstances0
    cats.kernel.instances.OptionInstances1
    cats.kernel.instances.OptionInstances2
    cats.kernel.instances.OptionMonoid
    cats.kernel.instances.OptionOrder
    cats.kernel.instances.OptionPartialOrder
    cats.kernel.instances.OrderInstances
    cats.kernel.instances.PartialOrderInstances
    //cats.kernel.instances.QueueEq
    //cats.kernel.instances.QueueHash
    cats.kernel.instances.QueueInstances
    cats.kernel.instances.QueueInstances1
    cats.kernel.instances.QueueInstances2
    //cats.kernel.instances.QueueMonoid
    //cats.kernel.instances.QueueOrder
    //cats.kernel.instances.QueuePartialOrder
    //cats.kernel.instances.SeqEq
    //cats.kernel.instances.SeqHash
    cats.kernel.instances.SeqInstances
    cats.kernel.instances.SeqInstances1
    cats.kernel.instances.SeqInstances2
    //cats.kernel.instances.SeqMonoid
    //cats.kernel.instances.SeqOrder
    //cats.kernel.instances.SeqPartialOrder
    cats.kernel.instances.SetHash
    cats.kernel.instances.SetInstances
    cats.kernel.instances.SetInstances1
    cats.kernel.instances.SetPartialOrder
    //cats.kernel.instances.SetSemilattice
    cats.kernel.instances.ShortBounded
    cats.kernel.instances.ShortEnumerable
    cats.kernel.instances.ShortGroup
    cats.kernel.instances.ShortInstances
    cats.kernel.instances.ShortOrder
    //cats.kernel.instances.SortedMapCommutativeMonoid
    //cats.kernel.instances.SortedMapCommutativeSemigroup
    //cats.kernel.instances.SortedMapEq
    //cats.kernel.instances.SortedMapHash
    //cats.kernel.instances.SortedMapInstances
    //cats.kernel.instances.SortedMapInstances1
    cats.kernel.instances.SortedMapInstances2
    cats.kernel.instances.SortedMapInstances3
    //cats.kernel.instances.SortedMapMonoid
    //cats.kernel.instances.SortedMapOrder
    //cats.kernel.instances.SortedMapPartialOrder
    //cats.kernel.instances.SortedMapSemigroup
    //cats.kernel.instances.SortedSetHash
    //cats.kernel.instances.SortedSetInstances
    cats.kernel.instances.SortedSetInstances1
    //cats.kernel.instances.SortedSetOrder
    //cats.kernel.instances.SortedSetSemilattice
    //cats.kernel.instances.StaticMethods
    //cats.kernel.instances.StreamEq
    cats.kernel.instances.StreamHash
    cats.kernel.instances.StreamInstances
    cats.kernel.instances.StreamInstances1
    cats.kernel.instances.StreamInstances2
    //cats.kernel.instances.StreamMonoid
    //cats.kernel.instances.StreamOrder
    //cats.kernel.instances.StreamPartialOrder
    cats.kernel.instances.StringInstances
    cats.kernel.instances.StringLowerBounded
    //cats.kernel.instances.StringMonoid
    cats.kernel.instances.StringOrder
    cats.kernel.instances.SymbolInstances
    cats.kernel.instances.SymbolLowerBounded
    cats.kernel.instances.SymbolOrder
    //cats.kernel.instances.TupleBandInstances
    //cats.kernel.instances.TupleBoundedSemilatticeInstances
    //cats.kernel.instances.TupleCommutativeGroupInstances
    //cats.kernel.instances.TupleCommutativeMonoidInstances
    //cats.kernel.instances.TupleCommutativeSemigroupInstances
    //cats.kernel.instances.TupleEqInstances
    //cats.kernel.instances.TupleGroupInstances
    //cats.kernel.instances.TupleHashInstances
    //cats.kernel.instances.TupleInstances
    //cats.kernel.instances.TupleInstances1
    //cats.kernel.instances.TupleInstances2
    //cats.kernel.instances.TupleInstances3
    //cats.kernel.instances.TupleMonoidInstances
    //cats.kernel.instances.TupleOrderInstances
    //cats.kernel.instances.TuplePartialOrderInstances
    //cats.kernel.instances.TupleSemigroupInstances
    //cats.kernel.instances.TupleSemilatticeInstances
    cats.kernel.instances.UUIDBounded
    //cats.kernel.instances.UUIDInstances
    cats.kernel.instances.UnitAlgebra
    cats.kernel.instances.UnitBounded
    cats.kernel.instances.UnitEnumerable
    cats.kernel.instances.UnitInstances
    cats.kernel.instances.UnitOrder
    //cats.kernel.instances.VectorEq
    //cats.kernel.instances.VectorHash
    cats.kernel.instances.VectorInstances
    cats.kernel.instances.VectorInstances1
    cats.kernel.instances.VectorInstances2
    //cats.kernel.instances.VectorMonoid
    //cats.kernel.instances.VectorOrder
    //cats.kernel.instances.VectorPartialOrder
    cats.kernel.instances.eq
    cats.kernel.instances.hash
    cats.kernel.instances.order
    cats.kernel.instances.partialOrder
    cats.syntax.AlignSyntax
    cats.syntax.AllSyntax
    cats.syntax.AllSyntaxBinCompat
    cats.syntax.AllSyntaxBinCompat0
    cats.syntax.AllSyntaxBinCompat1
    cats.syntax.AllSyntaxBinCompat2
    cats.syntax.AllSyntaxBinCompat3
    cats.syntax.AllSyntaxBinCompat4
    cats.syntax.AllSyntaxBinCompat5
    cats.syntax.AllSyntaxBinCompat6
    cats.syntax.AllSyntaxBinCompat7
    cats.syntax.AlternativeSyntax
    //cats.syntax.ApplicativeByNameOps
    //cats.syntax.ApplicativeByValueOps
    cats.syntax.ApplicativeErrorExtension
    cats.syntax.ApplicativeErrorExtensionOps
    //cats.syntax.ApplicativeErrorFUnitOps
    //cats.syntax.ApplicativeErrorIdOps
    //cats.syntax.ApplicativeErrorOps
    cats.syntax.ApplicativeErrorSyntax
    //cats.syntax.ApplicativeIdOps
    //cats.syntax.ApplicativeOps
    cats.syntax.ApplicativeSyntax
    //cats.syntax.ApplyFABCOps
    //cats.syntax.ApplyFABOps
    //cats.syntax.ApplyOps
    cats.syntax.ApplySyntax
    cats.syntax.ApplySyntaxBinCompat0
    cats.syntax.ArrowChoiceSyntax
    cats.syntax.ArrowSyntax
    cats.syntax.BifoldableSyntax
    cats.syntax.BifunctorSyntax
    //cats.syntax.BinestedIdOps
    cats.syntax.BinestedSyntax
    //cats.syntax.BitraverseOps
    //cats.syntax.BitraverseOpsBinCompat0
    cats.syntax.BitraverseSyntax
    cats.syntax.BitraverseSyntax1
    cats.syntax.BitraverseSyntaxBinCompat0
    cats.syntax.ChoiceSyntax
    cats.syntax.CoflatMapSyntax
    cats.syntax.ComonadSyntax
    cats.syntax.ComposeSyntax
    cats.syntax.ContravariantMonoidalOps
    cats.syntax.ContravariantMonoidalSyntax
    cats.syntax.ContravariantSemigroupalSyntax
    cats.syntax.ContravariantSyntax
    //cats.syntax.DistributiveOps
    cats.syntax.DistributiveSyntax
    //cats.syntax.EitherIdOps
    //cats.syntax.EitherIdOpsBinCompat0
    //cats.syntax.EitherKOps
    cats.syntax.EitherKSyntax
    //cats.syntax.EitherObjectOps
    //cats.syntax.EitherOps
    //cats.syntax.EitherOpsBinCompat0
    //cats.syntax.EitherSyntax
    cats.syntax.EitherSyntaxBinCompat0
    //cats.syntax.EitherUtil
    //cats.syntax.EqOps
    cats.syntax.EqSyntax
    //cats.syntax.FlatMapIdOps
    //cats.syntax.FlatMapOps
    //cats.syntax.FlatMapOptionOps
    cats.syntax.FlatMapOptionSyntax
    cats.syntax.FlatMapSyntax
    //cats.syntax.FlattenOps
    //cats.syntax.FoldableOps
    //cats.syntax.FoldableOps0
    //cats.syntax.FoldableOps1
    cats.syntax.FoldableSyntax
    cats.syntax.FoldableSyntaxBinCompat0
    cats.syntax.FoldableSyntaxBinCompat1
    //cats.syntax.Function10ApplyOps
    //cats.syntax.Function11ApplyOps
    //cats.syntax.Function12ApplyOps
    //cats.syntax.Function13ApplyOps
    //cats.syntax.Function14ApplyOps
    //cats.syntax.Function15ApplyOps
    //cats.syntax.Function16ApplyOps
    //cats.syntax.Function17ApplyOps
    //cats.syntax.Function18ApplyOps
    //cats.syntax.Function19ApplyOps
    //cats.syntax.Function1ApplyOps
    //cats.syntax.Function1Syntax
    //cats.syntax.Function20ApplyOps
    //cats.syntax.Function21ApplyOps
    //cats.syntax.Function22ApplyOps
    //cats.syntax.Function2ApplyOps
    //cats.syntax.Function3ApplyOps
    //cats.syntax.Function4ApplyOps
    //cats.syntax.Function5ApplyOps
    //cats.syntax.Function6ApplyOps
    //cats.syntax.Function7ApplyOps
    //cats.syntax.Function8ApplyOps
    //cats.syntax.Function9ApplyOps
    cats.syntax.FunctionApplySyntax
    cats.syntax.FunctorFilterSyntax
    cats.syntax.FunctorSyntax
    //cats.syntax.FunctorTuple2Ops
    //cats.syntax.GroupOps
    cats.syntax.GroupSyntax
    //cats.syntax.GuardOps
    //cats.syntax.HashOps
    cats.syntax.HashSyntax
    //cats.syntax.IfApplyOps
    //cats.syntax.IfFOps
    //cats.syntax.IfMOps
    //cats.syntax.IndexOps
    cats.syntax.InvariantSyntax
    //cats.syntax.IorIdOps
    cats.syntax.IorSyntax
    //cats.syntax.LeftNestedBitraverseOps
    //cats.syntax.LeftOps
    //cats.syntax.ListOps
    //cats.syntax.ListOpsBinCompat0
    cats.syntax.ListSyntax
    cats.syntax.ListSyntaxBinCompat0
    //cats.syntax.MonadErrorOps
    //cats.syntax.MonadErrorRethrowOps
    cats.syntax.MonadErrorSyntax
    //cats.syntax.MonadIdOps
    //cats.syntax.MonadOps
    cats.syntax.MonadSyntax
    //cats.syntax.MonoidOps
    cats.syntax.MonoidSyntax
    //cats.syntax.NestedBitraverseOps
    //cats.syntax.NestedFoldableOps
    //cats.syntax.NestedIdOps
    //cats.syntax.NestedReducibleOps
    cats.syntax.NestedSyntax
    //cats.syntax.NonEmptyAlternativeOps
    cats.syntax.NonEmptyAlternativeSyntax
    //cats.syntax.NonEmptyParallelApOps
    //cats.syntax.NonEmptyParallelApplyOps
    cats.syntax.NonEmptyTraverseSyntax
    //cats.syntax.OptionIdOps
    //cats.syntax.OptionOps
    cats.syntax.OptionSyntax
    //cats.syntax.OrderOps
    cats.syntax.OrderSyntax
    //cats.syntax.ParallelApOps
    //cats.syntax.ParallelApOps1
    //cats.syntax.ParallelApplyOps
    cats.syntax.ParallelApplySyntax
    //cats.syntax.ParallelBisequenceOps
    //cats.syntax.ParallelBitraverseOps
    cats.syntax.ParallelBitraverseSyntax
    //cats.syntax.ParallelFlatSequenceOps
    //cats.syntax.ParallelFlatSequenceOps1
    cats.syntax.ParallelFlatSyntax
    //cats.syntax.ParallelFlatTraversableOps
    //cats.syntax.ParallelFlatTraversableOps1
    //cats.syntax.ParallelFoldMapAOps
    cats.syntax.ParallelFoldMapASyntax
    //cats.syntax.ParallelLeftSequenceOps
    //cats.syntax.ParallelLeftTraverseOps
    //cats.syntax.ParallelReduceMapAOps
    cats.syntax.ParallelReduceMapASyntax
    //cats.syntax.ParallelSequenceFilterOps
    //cats.syntax.ParallelSequenceOps
    //cats.syntax.ParallelSequenceOps1
    //cats.syntax.ParallelSequence_Ops
    cats.syntax.ParallelSyntax
    //cats.syntax.ParallelTraversableOps
    //cats.syntax.ParallelTraversableOps1
    //cats.syntax.ParallelTraversable_Ops
    //cats.syntax.ParallelTraverseFilterOps
    cats.syntax.ParallelTraverseFilterSyntax
    cats.syntax.ParallelTraverseSyntax
    //cats.syntax.ParallelUnorderedFlatSequenceOps
    //cats.syntax.ParallelUnorderedSequenceOps
    //cats.syntax.ParallelUnorderedTraverseOps
    cats.syntax.ParallelUnorderedTraverseSyntax
    cats.syntax.PartialOrderOps
    cats.syntax.PartialOrderSyntax
    cats.syntax.ProfunctorSyntax
    //cats.syntax.ReducibleOps0
    cats.syntax.ReducibleSyntax
    cats.syntax.ReducibleSyntaxBinCompat0
    cats.syntax.RepresentableSyntax
    //cats.syntax.RightOps
    cats.syntax.SemigroupKSyntax
    //cats.syntax.SemigroupOps
    cats.syntax.SemigroupSyntax
    cats.syntax.SemigroupalBuilder
    //cats.syntax.SemigroupalOps
    //cats.syntax.SemigroupalOps2
    cats.syntax.SemigroupalSyntax
    //cats.syntax.SeparateOps
    //cats.syntax.SeparateOpsBinCompat0
    //cats.syntax.SeqOps
    cats.syntax.SeqSyntax
    //cats.syntax.SequenceFilterOps
    //cats.syntax.SetOps
    cats.syntax.SetSyntax
    cats.syntax.ShowSyntax
    cats.syntax.StrongSyntax
    //cats.syntax.TabulateOps
    //cats.syntax.TraverseFilterOps
    cats.syntax.TraverseFilterSyntax
    cats.syntax.TraverseFilterSyntaxBinCompat0
    cats.syntax.TraverseSyntax
    //cats.syntax.TryOps
    cats.syntax.TrySyntax
    cats.syntax.Tuple10ParallelOps
    cats.syntax.Tuple10SemigroupalOps
    cats.syntax.Tuple11ParallelOps
    cats.syntax.Tuple11SemigroupalOps
    cats.syntax.Tuple12ParallelOps
    cats.syntax.Tuple12SemigroupalOps
    cats.syntax.Tuple13ParallelOps
    cats.syntax.Tuple13SemigroupalOps
    cats.syntax.Tuple14ParallelOps
    cats.syntax.Tuple14SemigroupalOps
    cats.syntax.Tuple15ParallelOps
    cats.syntax.Tuple15SemigroupalOps
    cats.syntax.Tuple16ParallelOps
    cats.syntax.Tuple16SemigroupalOps
    cats.syntax.Tuple17ParallelOps
    cats.syntax.Tuple17SemigroupalOps
    cats.syntax.Tuple18ParallelOps
    cats.syntax.Tuple18SemigroupalOps
    cats.syntax.Tuple19ParallelOps
    cats.syntax.Tuple19SemigroupalOps
    //cats.syntax.Tuple1ParallelOps
    //cats.syntax.Tuple1SemigroupalOps
    cats.syntax.Tuple20ParallelOps
    cats.syntax.Tuple20SemigroupalOps
    cats.syntax.Tuple21ParallelOps
    cats.syntax.Tuple21SemigroupalOps
    cats.syntax.Tuple22ParallelOps
    cats.syntax.Tuple22SemigroupalOps
    cats.syntax.Tuple2ParallelOps
    cats.syntax.Tuple2SemigroupalOps
    cats.syntax.Tuple3ParallelOps
    cats.syntax.Tuple3SemigroupalOps
    cats.syntax.Tuple4ParallelOps
    cats.syntax.Tuple4SemigroupalOps
    cats.syntax.Tuple5ParallelOps
    cats.syntax.Tuple5SemigroupalOps
    cats.syntax.Tuple6ParallelOps
    cats.syntax.Tuple6SemigroupalOps
    cats.syntax.Tuple7ParallelOps
    cats.syntax.Tuple7SemigroupalOps
    cats.syntax.Tuple8ParallelOps
    cats.syntax.Tuple8SemigroupalOps
    cats.syntax.Tuple9ParallelOps
    cats.syntax.Tuple9SemigroupalOps
    //cats.syntax.TupleParallelSyntax
    //cats.syntax.TupleSemigroupalSyntax
    //cats.syntax.UniteOps
    //cats.syntax.UniteOpsBinCompat0
    //cats.syntax.UnorderedFoldableOps
    cats.syntax.UnorderedFoldableSyntax
    cats.syntax.UnorderedTraverseSyntax
    //cats.syntax.ValidatedExtension
    cats.syntax.ValidatedExtensionSyntax
    //cats.syntax.ValidatedIdOpsBinCompat0
    //cats.syntax.ValidatedIdSyntax
    cats.syntax.ValidatedSyntax
    cats.syntax.ValidatedSyntaxBincompat0
    //cats.syntax.VectorOps
    cats.syntax.VectorSyntax
    //cats.syntax.WriterIdSyntax
    cats.syntax.WriterSyntax
  """)
}