package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.corpus.scala3.CatsTest
import org.jetbrains.plugins.scala.project.settings.ScalaCompilerConfiguration
import org.junit.Test

class CatsSemanticTest extends SemanticTestBase(CatsTest) {
  override protected def setUp(): Unit = {
    super.setUp()
    val profile = ScalaCompilerConfiguration.instanceIn(getProject).defaultProfile
    profile.setSettings(profile.getSettings.copy(additionalCompilerOptions = Seq("-Ykind-projector")))
  }

  @Test def test(): Unit = doTest("""
    //cats.Align
    //cats.Alternative
    cats.Always
    //cats.Applicative
    //cats.ApplicativeError
    //cats.ApplicativeMonoid
    //cats.Apply
    //cats.ApplyArityFunctions
    //cats.ApplySemigroup
    //cats.ArrowApplicative
    //cats.Bifoldable
    //cats.Bifunctor
    cats.Bimonad
    //cats.Bitraverse
    cats.CoflatMap
    //cats.CommutativeApplicative
    //cats.CommutativeApply
    cats.CommutativeFlatMap
    cats.CommutativeMonad
    cats.Comonad
    //cats.ComposedAlternative
    //cats.ComposedApplicative
    //cats.ComposedApplicativeContravariantMonoidal
    //cats.ComposedApply
    cats.ComposedBifoldable
    cats.ComposedBifunctor
    cats.ComposedBitraverse
    //cats.ComposedContravariant
    //cats.ComposedContravariantCovariant
    //cats.ComposedCovariantContravariant
    //cats.ComposedDistributive
    //cats.ComposedFoldable
    //cats.ComposedFunctor
    //cats.ComposedFunctorBifunctor
    //cats.ComposedInvariant
    //cats.ComposedInvariantApplySemigroupal
    //cats.ComposedInvariantContravariant
    //cats.ComposedInvariantCovariant
    //cats.ComposedMonoidK
    //cats.ComposedNonEmptyAlternative
    cats.ComposedNonEmptyTraverse
    //cats.ComposedReducible
    //cats.ComposedSemigroupK
    //cats.ComposedSemigroupal
    cats.ComposedTraverse
    //cats.Contravariant
    //cats.ContravariantMonoidal
    cats.ContravariantMonoidalMonoid
    //cats.ContravariantSemigroupal
    cats.ContravariantSemigroupalSemigroup
    //cats.Defer
    //cats.Distributive
    //cats.Eval
    //cats.EvalGroup
    //cats.EvalInstances
    cats.EvalInstances0
    cats.EvalInstances1
    cats.EvalMonoid
    cats.EvalSemigroup
    //cats.FlatMap
    //cats.FlatMapArityFunctions
    //cats.Foldable
    //cats.FoldableNFunctions
    //cats.Functor
    //cats.FunctorFilter
    cats.FunctorFilterInstances0
    cats.Inject
    //cats.InjectInstances
    cats.InjectK
    //cats.InjectKInstances
    //cats.Invariant
    cats.InvariantInstances0
    cats.InvariantInstances1
    cats.InvariantInstances2
    //cats.InvariantMonoidal
    //cats.InvariantMonoidalMonoid
    //cats.InvariantSemigroupal
    //cats.InvariantSemigroupalSemigroup
    //cats.Later
    //cats.LeftFunctor
    //cats.Monad
    //cats.MonadError
    //cats.MonoidK
    //cats.NonEmptyAlternative
    //cats.NonEmptyParallel
    //cats.NonEmptyReducible
    //cats.NonEmptyTraverse
    //cats.NotNull
    cats.Now
    //cats.Parallel
    //cats.ParallelArityFunctions
    //cats.ParallelArityFunctions2
    //cats.Reducible
    //cats.Representable
    //cats.RepresentableBimonad
    //cats.RepresentableDistributive
    //cats.RepresentableMonad
    //cats.RightFunctor
    cats.ScalaVersionSpecificAlignInstances
    cats.ScalaVersionSpecificInvariantInstances
    cats.ScalaVersionSpecificMonoidKInstances
    //cats.ScalaVersionSpecificParallelInstances
    cats.ScalaVersionSpecificSemigroupalInstances
    cats.ScalaVersionSpecificShowInstances
    cats.ScalaVersionSpecificTraverseFilterInstances
    cats.ScalaVersionSpecificTraverseInstances
    //cats.SemigroupK
    cats.SemigroupKInstances0
    //cats.Semigroupal
    //cats.SemigroupalArityFunctions
    //cats.Show
    cats.ShowInstances
    cats.ShowInstances0
    //cats.StackSafeMonad
    //cats.Traverse
    //cats.TraverseFilter
    cats.TupleInstances0
    cats.TupleInstances1
    cats.TupleInstances2
    //cats.UnorderedFoldable
    cats.UnorderedFoldableLowPriority
    //cats.UnorderedTraverse
    cats.implicits
    //cats.arrow.Arrow
    //cats.arrow.ArrowChoice
    //cats.arrow.Category
    cats.arrow.Choice
    cats.arrow.CommutativeArrow
    //cats.arrow.Compose
    //cats.arrow.FunctionK
    //cats.arrow.FunctionKLift
    //cats.arrow.FunctionKMacroMethods
    //cats.arrow.Profunctor
    cats.arrow.Strong
    //cats.compat.FoldableCompat
    //cats.compat.Seq
    //cats.compat.SortedSet
    //cats.compat.Vector
    cats.conversions.AllConversions
    //cats.conversions.VarianceConversions
    cats.conversions.VarianceConversionsLowPriority
    //cats.data.AbstractNonEmptyInstances
    //cats.data.AndThen
    //cats.data.AndThenInstances0
    cats.data.AndThenInstances1
    //cats.data.AppFunc
    //cats.data.AppFuncApplicative
    //cats.data.AppFuncInstances
    //cats.data.Binested
    cats.data.BinestedBifoldable
    cats.data.BinestedBitraverse
    cats.data.BinestedInstances
    cats.data.BinestedInstances0
    //cats.data.Chain
    cats.data.ChainCompanionCompat
    //cats.data.ChainCompat
    //cats.data.ChainInstances
    cats.data.ChainInstances1
    //cats.data.ChainInstances2
    //cats.data.ChainInstances3
    //cats.data.ChainPartialOrder
    //cats.data.Cokleisli
    //cats.data.CokleisliArrow
    cats.data.CokleisliCompose
    //cats.data.CokleisliInstances
    cats.data.CokleisliInstances0
    cats.data.CokleisliInstances1
    //cats.data.CokleisliMonad
    cats.data.CokleisliProfunctor
    //cats.data.CommonIRWSTConstructors
    //cats.data.CommonStateTConstructors
    cats.data.CommonStateTConstructors0
    //cats.data.Const
    cats.data.ConstApplicative
    cats.data.ConstApply
    cats.data.ConstContravariant
    cats.data.ConstFunctor
    //cats.data.ConstInstances
    //cats.data.ConstInstances0
    //cats.data.ConstInstances1
    cats.data.ConstInstances2
    //cats.data.ConstInstances3
    cats.data.ConstInstances4
    //cats.data.ContT
    //cats.data.EitherK
    //cats.data.EitherKCoflatMap
    //cats.data.EitherKComonad
    cats.data.EitherKContravariant
    //cats.data.EitherKFoldable
    cats.data.EitherKFunctor
    //cats.data.EitherKInstances
    //cats.data.EitherKInstances0
    //cats.data.EitherKInstances1
    cats.data.EitherKInstances2
    cats.data.EitherKInstances3
    cats.data.EitherKTraverse
    //cats.data.EitherT
    cats.data.EitherTBifoldable
    cats.data.EitherTBifunctor
    cats.data.EitherTBitraverse
    //cats.data.EitherTEq
    cats.data.EitherTFoldable
    cats.data.EitherTFunctor
    //cats.data.EitherTInstances
    //cats.data.EitherTInstances1
    cats.data.EitherTInstances2
    cats.data.EitherTInstances3
    //cats.data.EitherTMonad
    //cats.data.EitherTMonadError
    cats.data.EitherTMonadErrorF
    cats.data.EitherTMonoid
    cats.data.EitherTOrder
    cats.data.EitherTPartialOrder
    cats.data.EitherTSemigroup
    //cats.data.EitherTSemigroupK
    cats.data.EitherTTraverse
    //cats.data.Func
    //cats.data.FuncApplicative
    //cats.data.FuncApply
    //cats.data.FuncContravariant
    //cats.data.FuncFunctor
    //cats.data.FuncInstances
    //cats.data.FuncInstances0
    //cats.data.FuncInstances1
    cats.data.IRWSTBifunctor
    cats.data.IRWSTContravariant
    cats.data.IRWSTFunctor
    cats.data.IRWSTInstances
    cats.data.IRWSTInstances1
    cats.data.IRWSTInstances2
    cats.data.IRWSTInstances3
    cats.data.IRWSTProfunctor
    cats.data.IRWSTSemigroupK
    //cats.data.IRWSTSemigroupK1
    //cats.data.IRWSTStrong
    //cats.data.IdT
    cats.data.IdTApplicative
    cats.data.IdTApply
    cats.data.IdTContravariantMonoidal
    cats.data.IdTFlatMap
    cats.data.IdTFoldable
    cats.data.IdTFunctor
    cats.data.IdTInstances
    cats.data.IdTInstances0
    cats.data.IdTInstances1
    cats.data.IdTInstances2
    cats.data.IdTInstances3
    cats.data.IdTInstances4
    cats.data.IdTInstances5
    cats.data.IdTInstances6
    //cats.data.IdTInstances7
    //cats.data.IdTInstances8
    cats.data.IdTMonad
    cats.data.IdTNonEmptyTraverse
    //cats.data.IdTTraverse
    //cats.data.IndexedReaderWriterStateT
    //cats.data.IndexedStateFunctions
    //cats.data.IndexedStateT
    cats.data.IndexedStateTAlternative
    cats.data.IndexedStateTBifunctor
    cats.data.IndexedStateTContravariant
    //cats.data.IndexedStateTContravariantMonoidal
    cats.data.IndexedStateTFunctor
    //cats.data.IndexedStateTFunctorFilter
    cats.data.IndexedStateTInstances
    cats.data.IndexedStateTInstances1
    cats.data.IndexedStateTInstances2
    cats.data.IndexedStateTInstances3
    cats.data.IndexedStateTInstances4
    //cats.data.IndexedStateTMonad
    cats.data.IndexedStateTMonadError
    cats.data.IndexedStateTProfunctor
    cats.data.IndexedStateTSemigroupK
    //cats.data.IndexedStateTStrong
    //cats.data.Ior
    //cats.data.IorFunctions
    //cats.data.IorFunctions2
    //cats.data.IorInstances
    //cats.data.IorInstances0
    //cats.data.IorT
    //cats.data.IorTEq
    cats.data.IorTFoldable
    cats.data.IorTFunctor
    //cats.data.IorTInstances
    //cats.data.IorTInstances1
    cats.data.IorTInstances2
    cats.data.IorTInstances3
    //cats.data.IorTMonad
    //cats.data.IorTMonadError
    cats.data.IorTMonadErrorF
    cats.data.IorTMonoid
    cats.data.IorTOrder
    cats.data.IorTSemigroup
    cats.data.IorTTraverse
    //cats.data.Kleisli
    cats.data.KleisliAlign
    cats.data.KleisliAlternative
    cats.data.KleisliApplicative
    //cats.data.KleisliApplicativeError
    //cats.data.KleisliApply
    //cats.data.KleisliArrowChoice
    cats.data.KleisliCategory
    cats.data.KleisliChoice
    cats.data.KleisliCommutativeArrow
    cats.data.KleisliCompose
    //cats.data.KleisliContravariantMonoidal
    cats.data.KleisliDistributive
    //cats.data.KleisliExplicitInstances
    //cats.data.KleisliFlatMap
    cats.data.KleisliFromFunctionPartiallyApplied
    //cats.data.KleisliFunctions
    cats.data.KleisliFunctionsBinCompat
    //cats.data.KleisliFunctor
    //cats.data.KleisliFunctorFilter
    //cats.data.KleisliInstances
    //cats.data.KleisliInstances0
    //cats.data.KleisliInstances0_5
    cats.data.KleisliInstances1
    cats.data.KleisliInstances2
    //cats.data.KleisliInstances3
    cats.data.KleisliInstances4
    cats.data.KleisliInstances5
    cats.data.KleisliInstances6
    cats.data.KleisliInstances7
    //cats.data.KleisliInstances8
    cats.data.KleisliInstances9
    cats.data.KleisliMonad
    cats.data.KleisliMonadError
    //cats.data.KleisliMonoid
    //cats.data.KleisliMonoidK
    cats.data.KleisliSemigroup
    cats.data.KleisliSemigroupK
    cats.data.KleisliStrong
    //cats.data.Nested
    //cats.data.NestedAlign
    cats.data.NestedAlternative
    cats.data.NestedApplicative
    //cats.data.NestedApplicativeError
    cats.data.NestedApply
    cats.data.NestedContravariant
    cats.data.NestedContravariantMonoidal
    //cats.data.NestedDistributive
    cats.data.NestedFoldable
    cats.data.NestedFunctor
    //cats.data.NestedFunctorFilter
    //cats.data.NestedInstances
    //cats.data.NestedInstances0
    cats.data.NestedInstances1
    cats.data.NestedInstances10
    cats.data.NestedInstances11
    cats.data.NestedInstances12
    cats.data.NestedInstances13
    cats.data.NestedInstances2
    cats.data.NestedInstances3
    cats.data.NestedInstances4
    //cats.data.NestedInstances5
    //cats.data.NestedInstances6
    cats.data.NestedInstances7
    cats.data.NestedInstances8
    cats.data.NestedInstances9
    cats.data.NestedInvariant
    cats.data.NestedInvariantSemigroupalApply
    cats.data.NestedMonoidK
    cats.data.NestedNonEmptyTraverse
    cats.data.NestedReducible
    cats.data.NestedSemigroupK
    //cats.data.NestedTraverse
    //cats.data.NestedTraverseFilter
    //cats.data.Newtype
    //cats.data.Newtype2
    //cats.data.NonEmptyChainImpl
    //cats.data.NonEmptyChainInstances
    //cats.data.NonEmptyChainInstances1
    //cats.data.NonEmptyChainInstances2
    //cats.data.NonEmptyChainInstances3
    //cats.data.NonEmptyChainOps
    cats.data.NonEmptyCollection
    //cats.data.NonEmptyLazyList
    //cats.data.NonEmptyLazyListInstances
    cats.data.NonEmptyLazyListInstances1
    cats.data.NonEmptyLazyListInstances2
    cats.data.NonEmptyLazyListInstances3
    //cats.data.NonEmptyLazyListOps
    //cats.data.NonEmptyList
    //cats.data.NonEmptyListEq
    //cats.data.NonEmptyListInstances
    cats.data.NonEmptyListInstances0
    cats.data.NonEmptyListInstances1
    cats.data.NonEmptyListOrder
    //cats.data.NonEmptyListPartialOrder
    //cats.data.NonEmptyMapImpl
    //cats.data.NonEmptyMapInstances
    //cats.data.NonEmptyMapInstances0
    //cats.data.NonEmptyMapOps
    //cats.data.NonEmptySeq
    //cats.data.NonEmptySeqInstances
    //cats.data.NonEmptySetEq
    //cats.data.NonEmptySetImpl
    //cats.data.NonEmptySetInstances
    //cats.data.NonEmptySetInstances0
    cats.data.NonEmptySetInstances1
    //cats.data.NonEmptySetOps
    cats.data.NonEmptySetOrder
    //cats.data.NonEmptyVector
    //cats.data.NonEmptyVectorInstances
    //cats.data.NonEmptyVectorInstances0
    //cats.data.NonEmptyVectorInstances1
    //cats.data.NonEmptyVectorInstances2
    //cats.data.OneAnd
    //cats.data.OneAndInstances
    //cats.data.OneAndLowPriority0
    //cats.data.OneAndLowPriority0_5
    //cats.data.OneAndLowPriority1
    //cats.data.OneAndLowPriority2
    cats.data.OneAndLowPriority3
    //cats.data.OneAndLowPriority4
    //cats.data.Op
    cats.data.OpCategory
    cats.data.OpCompose
    cats.data.OpEq
    cats.data.OpInstances
    cats.data.OpInstances0
    //cats.data.OptionT
    cats.data.OptionTContravariant
    cats.data.OptionTContravariantMonoidal
    //cats.data.OptionTEq
    cats.data.OptionTFoldable
    cats.data.OptionTFunctor
    //cats.data.OptionTFunctorFilter
    //cats.data.OptionTInstances
    cats.data.OptionTInstances0
    cats.data.OptionTInstances1
    cats.data.OptionTInstances2
    cats.data.OptionTInstances3
    cats.data.OptionTInvariant
    //cats.data.OptionTMonad
    cats.data.OptionTMonadError
    //cats.data.OptionTMonadErrorMonad
    cats.data.OptionTMonoid
    cats.data.OptionTMonoidK
    cats.data.OptionTOrder
    cats.data.OptionTPartialOrder
    cats.data.OptionTSemigroup
    //cats.data.OptionTSemigroupK
    cats.data.OptionTTraverse
    //cats.data.RWSFunctions
    cats.data.RWSTAlternative
    cats.data.RWSTAlternative1
    //cats.data.RWSTFunctions
    //cats.data.RWSTMonad
    //cats.data.RWSTMonadError
    //cats.data.RepresentableStore
    //cats.data.RepresentableStoreT
    //cats.data.RepresentableStoreTInstances1
    cats.data.RepresentableStoreTInstances2
    cats.data.ScalaVersionSpecificNonEmptyChainImpl
    //cats.data.ScalaVersionSpecificPackage
    //cats.data.StateFunctions
    //cats.data.StateTFunctions
    //cats.data.StrictConstFunction1
    //cats.data.Tuple2K
    //cats.data.Tuple2KAlternative
    //cats.data.Tuple2KApplicative
    //cats.data.Tuple2KApply
    //cats.data.Tuple2KContravariant
    //cats.data.Tuple2KContravariantMonoidal
    //cats.data.Tuple2KDistributive
    //cats.data.Tuple2KFoldable
    //cats.data.Tuple2KFunctor
    //cats.data.Tuple2KInstances
    //cats.data.Tuple2KInstances0
    //cats.data.Tuple2KInstances1
    //cats.data.Tuple2KInstances2
    //cats.data.Tuple2KInstances3
    //cats.data.Tuple2KInstances4
    //cats.data.Tuple2KInstances5
    //cats.data.Tuple2KInstances6
    //cats.data.Tuple2KInstances7
    //cats.data.Tuple2KInstances8
    //cats.data.Tuple2KMonad
    //cats.data.Tuple2KMonoidK
    cats.data.Tuple2KOrder
    //cats.data.Tuple2KSemigroupK
    //cats.data.Tuple2KSemigroupal
    //cats.data.Tuple2KShow
    //cats.data.Tuple2KTraverse
    //cats.data.Validated
    //cats.data.ValidatedApplicative
    //cats.data.ValidatedFunctions
    //cats.data.ValidatedFunctionsBinCompat0
    //cats.data.ValidatedInstances
    //cats.data.ValidatedInstances1
    //cats.data.ValidatedInstances2
    //cats.data.WriterT
    cats.data.WriterTAlternative
    cats.data.WriterTApplicative
    cats.data.WriterTApplicativeError
    //cats.data.WriterTApply
    //cats.data.WriterTCoflatMap
    cats.data.WriterTComonad
    cats.data.WriterTContravariant
    cats.data.WriterTContravariantMonoidal
    //cats.data.WriterTFlatMap1
    //cats.data.WriterTFlatMap2
    cats.data.WriterTFoldable
    cats.data.WriterTFunctions
    //cats.data.WriterTFunctions0
    cats.data.WriterTFunctor
    cats.data.WriterTInstances
    //cats.data.WriterTInstances0
    //cats.data.WriterTInstances1
    cats.data.WriterTInstances10
    cats.data.WriterTInstances11
    cats.data.WriterTInstances12
    cats.data.WriterTInstances13
    //cats.data.WriterTInstances2
    //cats.data.WriterTInstances3
    cats.data.WriterTInstances4
    cats.data.WriterTInstances5
    cats.data.WriterTInstances6
    cats.data.WriterTInstances7
    cats.data.WriterTInstances8
    cats.data.WriterTInstances9
    cats.data.WriterTInvariant
    cats.data.WriterTMonad
    cats.data.WriterTMonadError
    cats.data.WriterTMonoid
    cats.data.WriterTMonoidK
    cats.data.WriterTSemigroup
    cats.data.WriterTSemigroupK
    cats.data.WriterTTraverse
    //cats.data.ZipLazyList
    //cats.data.ZipList
    //cats.data.ZipSeq
    //cats.data.ZipStream
    //cats.data.ZipVector
    //cats.effect.ArrayStack
    //cats.effect.ByteStack
    //cats.effect.CallbackStack
    //cats.effect.ContState
    //cats.effect.CpuStarvationCheck
    //cats.effect.CpuStarvationCheckPlatform
    //cats.effect.ExitCode
    //cats.effect.IO
    //cats.effect.IOApp
    //cats.effect.IOCompanionPlatform
    //cats.effect.IODeferred
    //cats.effect.IOFiber
    //cats.effect.IOFiberPlatform
    //cats.effect.IOLocal
    //cats.effect.IOLocalPlatform
    //cats.effect.IOLowPriorityImplicits
    //cats.effect.IOPlatform
    //cats.effect.LiftIO
    //cats.effect.NonDaemonThreadLogger
    //cats.effect.Platform
    //cats.effect.PlatformStatics
    //cats.effect.ResourceApp
    //cats.effect.Selector
    //cats.effect.SyncIO
    //cats.effect.SyncIOCompanionPlatform
    cats.effect.SyncIOLowPriorityImplicits
    //cats.effect.SyncStep
    //cats.effect.Trace
    cats.effect.implicits
    cats.effect.instances.AllInstances
    //cats.effect.kernel.Async
    //cats.effect.kernel.AsyncPlatform
    //cats.effect.kernel.CancelScope
    //cats.effect.kernel.Clock
    //cats.effect.kernel.ClockPlatform
    cats.effect.kernel.Cont
    //cats.effect.kernel.Deferred
    cats.effect.kernel.DeferredSink
    //cats.effect.kernel.DeferredSource
    //cats.effect.kernel.Fiber
    //cats.effect.kernel.GenConcurrent
    //cats.effect.kernel.GenSpawn
    //cats.effect.kernel.GenTemporal
    //cats.effect.kernel.LowPriorityImplicits
    //cats.effect.kernel.MiniSemaphore
    //cats.effect.kernel.MonadCancel
    //cats.effect.kernel.Outcome
    //cats.effect.kernel.Par
    cats.effect.kernel.Poll
    //cats.effect.kernel.Ref
    cats.effect.kernel.RefSink
    //cats.effect.kernel.RefSource
    //cats.effect.kernel.Resource
    //cats.effect.kernel.ResourceAsync
    cats.effect.kernel.ResourceClock
    //cats.effect.kernel.ResourceConcurrent
    //cats.effect.kernel.ResourceDefer
    //cats.effect.kernel.ResourceFOInstances0
    //cats.effect.kernel.ResourceFOInstances1
    cats.effect.kernel.ResourceHOInstances0
    //cats.effect.kernel.ResourceHOInstances1
    //cats.effect.kernel.ResourceHOInstances2
    cats.effect.kernel.ResourceHOInstances3
    cats.effect.kernel.ResourceHOInstances4
    //cats.effect.kernel.ResourceHOInstances5
    cats.effect.kernel.ResourceMonad
    //cats.effect.kernel.ResourceMonadCancel
    cats.effect.kernel.ResourceMonadError
    cats.effect.kernel.ResourceMonoid
    cats.effect.kernel.ResourcePlatform
    cats.effect.kernel.ResourceSemigroup
    cats.effect.kernel.ResourceSemigroupK
    cats.effect.kernel.ResourceSync
    cats.effect.kernel.ResourceTemporal
    //cats.effect.kernel.Sync
    //cats.effect.kernel.SyncRef
    cats.effect.kernel.Unique
    cats.effect.kernel.implicits
    cats.effect.kernel.instances.AllInstances
    //cats.effect.kernel.instances.GenSpawnInstances
    cats.effect.kernel.syntax.AllSyntax
    //cats.effect.kernel.syntax.AsyncOps
    cats.effect.kernel.syntax.AsyncSyntax
    //cats.effect.kernel.syntax.ClockOps
    cats.effect.kernel.syntax.ClockSyntax
    //cats.effect.kernel.syntax.ConcurrentParSequenceNOps
    //cats.effect.kernel.syntax.ConcurrentParTraverseNOps
    //cats.effect.kernel.syntax.EffectResourceOps
    //cats.effect.kernel.syntax.GenConcurrentOps_
    cats.effect.kernel.syntax.GenConcurrentSyntax
    //cats.effect.kernel.syntax.GenSpawnOps
    //cats.effect.kernel.syntax.GenSpawnOps_
    //cats.effect.kernel.syntax.GenSpawnSyntax
    //cats.effect.kernel.syntax.GenTemporalOps
    cats.effect.kernel.syntax.GenTemporalOpsCompanionCompat
    //cats.effect.kernel.syntax.GenTemporalOps_
    cats.effect.kernel.syntax.GenTemporalOps_CompanionCompat
    //cats.effect.kernel.syntax.GenTemporalSyntax
    //cats.effect.kernel.syntax.MonadCancelOps
    //cats.effect.kernel.syntax.MonadCancelOps_
    //cats.effect.kernel.syntax.MonadCancelSyntax
    cats.effect.kernel.syntax.ResourceSyntax
    cats.effect.metrics.CpuStarvationWarningMetrics
    //cats.effect.metrics.JvmCpuStarvationMetrics
    //cats.effect.std.AtomicCell
    //cats.effect.std.Backpressure
    //cats.effect.std.Console
    //cats.effect.std.ConsoleCompanionCrossPlatform
    //cats.effect.std.ConsoleCompanionPlatform
    //cats.effect.std.ConsoleCrossPlatform
    //cats.effect.std.CountDownLatch
    //cats.effect.std.CyclicBarrier
    //cats.effect.std.Dequeue
    //cats.effect.std.DequeueSink
    //cats.effect.std.DequeueSource
    //cats.effect.std.Dispatcher
    //cats.effect.std.DispatcherPlatform
    //cats.effect.std.Env
    //cats.effect.std.EnvCompanionPlatform
    cats.effect.std.FailureSignal
    //cats.effect.std.Hotswap
    //cats.effect.std.MapRef
    //cats.effect.std.MapRefCompanionPlatform
    //cats.effect.std.Mutex
    //cats.effect.std.PQueue
    //cats.effect.std.PQueueSink
    //cats.effect.std.PQueueSource
    //cats.effect.std.Queue
    //cats.effect.std.QueueSink
    //cats.effect.std.QueueSource
    //cats.effect.std.Random
    cats.effect.std.RandomCompanionPlatform
    //cats.effect.std.SecureRandom
    //cats.effect.std.SecureRandomCompanionPlatform
    //cats.effect.std.Semaphore
    //cats.effect.std.Supervisor
    //cats.effect.std.SystemProperties
    //cats.effect.std.UUIDGen
    cats.effect.std.UUIDGenCompanionPlatform
    cats.effect.std.UUIDGenCompanionPlatformLowPriority
    //cats.effect.std.UnsafeUnbounded
    //cats.effect.std.internal.BankersQueue
    //cats.effect.std.internal.BinomialHeap
    //cats.effect.std.internal.BinomialTree
    cats.effect.std.syntax.AllSyntax
    //cats.effect.std.syntax.BackpressureOps
    cats.effect.std.syntax.BackpressureSyntax
    //cats.effect.std.syntax.SupervisorOps
    cats.effect.std.syntax.SupervisorSyntax
    //cats.effect.std.unsafe.BoundedQueue
    cats.effect.std.unsafe.BoundedQueueSink
    //cats.effect.std.unsafe.UnboundedQueue
    cats.effect.std.unsafe.UnboundedQueueSink
    cats.effect.syntax.AllSyntax
    cats.effect.syntax.DispatcherSyntax
    //cats.effect.tracing.RingBuffer
    //cats.effect.tracing.Tracing
    cats.effect.tracing.TracingEvent
    //cats.effect.tracing.TracingPlatform
    //cats.effect.unsafe.BatchingMacrotaskExecutor
    //cats.effect.unsafe.FiberMonitor
    //cats.effect.unsafe.FiberMonitorShared
    //cats.effect.unsafe.IORuntime
    //cats.effect.unsafe.IORuntimeBuilder
    //cats.effect.unsafe.IORuntimeBuilderPlatform
    //cats.effect.unsafe.IORuntimeCompanionPlatform
    //cats.effect.unsafe.IORuntimeConfig
    //cats.effect.unsafe.IORuntimeConfigCompanionPlatform
    //cats.effect.unsafe.LocalQueue
    //cats.effect.unsafe.NoOpFiberMonitor
    //cats.effect.unsafe.ParkedSignal
    //cats.effect.unsafe.PollResult
    cats.effect.unsafe.PollingContext
    cats.effect.unsafe.PollingSystem
    //cats.effect.unsafe.ScalQueue
    cats.effect.unsafe.Scheduler
    //cats.effect.unsafe.SchedulerCompanionPlatform
    //cats.effect.unsafe.SelectorSystem
    //cats.effect.unsafe.SleepSystem
    cats.effect.unsafe.StripedHashtable
    //cats.effect.unsafe.ThreadSafeHashtable
    //cats.effect.unsafe.TimerHeap
    cats.effect.unsafe.UnsafeNonFatal
    cats.effect.unsafe.UnsealedPollingContext
    //cats.effect.unsafe.WeakBag
    //cats.effect.unsafe.WeakList
    //cats.effect.unsafe.WorkStealingThreadPool
    //cats.effect.unsafe.WorkerThread
    cats.effect.unsafe.implicits
    cats.effect.unsafe.metrics.ComputePoolSampler
    cats.effect.unsafe.metrics.ComputePoolSamplerMBean
    cats.effect.unsafe.metrics.CpuStarvation
    cats.effect.unsafe.metrics.CpuStarvationMBean
    cats.effect.unsafe.metrics.CpuStarvationMetrics
    //cats.effect.unsafe.metrics.CpuStarvationSampler
    cats.effect.unsafe.metrics.IORuntimeMetrics
    //cats.effect.unsafe.metrics.IORuntimeMetricsCompanionPlatform
    cats.effect.unsafe.metrics.IORuntimeMetricsPlatform
    //cats.effect.unsafe.metrics.LiveFiberSnapshotTrigger
    cats.effect.unsafe.metrics.LiveFiberSnapshotTriggerMBean
    cats.effect.unsafe.metrics.LocalQueueMetrics
    cats.effect.unsafe.metrics.LocalQueueSampler
    cats.effect.unsafe.metrics.LocalQueueSamplerMBean
    //cats.effect.unsafe.metrics.PollerMetrics
    cats.effect.unsafe.metrics.PollerSampler
    cats.effect.unsafe.metrics.PollerSamplerMBean
    cats.effect.unsafe.metrics.TimerHeapMetrics
    cats.effect.unsafe.metrics.TimerHeapSampler
    cats.effect.unsafe.metrics.TimerHeapSamplerMBean
    //cats.effect.unsafe.metrics.WorkStealingThreadPoolMetrics
    cats.effect.unsafe.metrics.WorkerThreadMetrics
    cats.effect.unsafe.metrics.WorkerThreadSampler
    cats.effect.unsafe.metrics.WorkerThreadSamplerMBean
    //cats.evidence.As
    cats.evidence.AsInstances
    //cats.evidence.AsSupport
    //cats.evidence.Is
    cats.evidence.IsInstances
    cats.evidence.IsSupport
    //cats.free.Cofree
    //cats.free.CofreeComonad
    cats.free.CofreeInstances
    cats.free.CofreeInstances1
    cats.free.CofreeInstances2
    //cats.free.CofreeReducible
    cats.free.CofreeTraverse
    //cats.free.ContravariantCoyoneda
    //cats.free.Coyoneda
    //cats.free.Free
    //cats.free.FreeApplicative
    //cats.free.FreeFoldStep
    cats.free.FreeFoldable
    //cats.free.FreeInstances
    cats.free.FreeInstances1
    //cats.free.FreeInvariantMonoidal
    cats.free.FreeStructuralInstances
    //cats.free.FreeStructuralInstances0
    //cats.free.FreeStructuralInstances1
    //cats.free.FreeStructuralInstances2
    //cats.free.FreeT
    cats.free.FreeTFlatMap
    //cats.free.FreeTInstances
    cats.free.FreeTInstances0
    cats.free.FreeTInstances1
    //cats.free.FreeTInstances2
    //cats.free.FreeTInstances3
    cats.free.FreeTMonad
    cats.free.FreeTMonoidK
    //cats.free.FreeTSemigroupK
    //cats.free.FreeTraverse
    //cats.free.InvariantCoyoneda
    cats.free.TrampolineFunctions
    //cats.free.Yoneda
    cats.instances.AllCoreDurationInstances
    cats.instances.AllInstances
    cats.instances.AllInstancesBinCompat
    cats.instances.AllInstancesBinCompat0
    cats.instances.AllInstancesBinCompat1
    cats.instances.AllInstancesBinCompat10
    cats.instances.AllInstancesBinCompat2
    cats.instances.AllInstancesBinCompat3
    cats.instances.AllInstancesBinCompat4
    cats.instances.AllInstancesBinCompat5
    cats.instances.AllInstancesBinCompat6
    cats.instances.AllInstancesBinCompat7
    cats.instances.AllInstancesBinCompat8
    cats.instances.AllInstancesBinCompat9
    cats.instances.AnyValInstances
    //cats.instances.ArraySeqInstances
    cats.instances.BigDecimalInstances
    cats.instances.BigIntInstances
    cats.instances.BitSetInstances
    cats.instances.BooleanInstances
    cats.instances.ByteInstances
    cats.instances.CharInstances
    cats.instances.CoreDurationInstances
    cats.instances.CoreFiniteDurationInstances
    cats.instances.DeadlineInstances
    cats.instances.DoubleInstances
    cats.instances.DurationInstances
    //cats.instances.EitherInstances
    //cats.instances.EqInstances
    //cats.instances.EquivInstances
    cats.instances.FiniteDurationInstances
    //cats.instances.FlatMapNTuple2
    //cats.instances.FlatMapTuple1
    //cats.instances.FlatMapTuple10
    //cats.instances.FlatMapTuple11
    //cats.instances.FlatMapTuple2
    //cats.instances.FlatMapTuple3
    //cats.instances.FlatMapTuple4
    //cats.instances.FlatMapTuple5
    //cats.instances.FlatMapTuple6
    //cats.instances.FlatMapTuple7
    //cats.instances.FlatMapTuple8
    //cats.instances.FlatMapTuple9
    cats.instances.FloatInstances
    //cats.instances.Function0Instances
    //cats.instances.Function0Instances0
    //cats.instances.Function1Instances
    //cats.instances.Function1Instances0
    cats.instances.FunctionInstances
    //cats.instances.FunctionInstancesBinCompat0
    //cats.instances.FutureCoflatMap
    //cats.instances.FutureInstances
    cats.instances.FutureInstances1
    cats.instances.FutureInstances2
    //cats.instances.FutureMonoid
    //cats.instances.FutureSemigroup
    //cats.instances.HashInstances
    cats.instances.IntInstances
    //cats.instances.InvariantInstances
    //cats.instances.InvariantInstancesBinCompat0
    //cats.instances.InvariantMonoidalInstances
    //cats.instances.LazyListInstances
    //cats.instances.ListInstances
    //cats.instances.ListInstancesBinCompat0
    cats.instances.LongInstances
    //cats.instances.LowPrioritySortedSetInstancesBinCompat1
    //cats.instances.MapInstances
    //cats.instances.MapInstancesBinCompat0
    //cats.instances.MapInstancesBinCompat1
    //cats.instances.NTupleBifunctorInstances
    //cats.instances.NTupleBitraverseInstances
    //cats.instances.NTupleMonadInstances
    //cats.instances.NTupleMonadInstances1
    //cats.instances.NTupleMonadInstances2
    //cats.instances.NTupleMonadInstances3
    cats.instances.NTupleMonadInstances4
    //cats.instances.NTupleMonadInstances5
    //cats.instances.NTupleShowInstances
    //cats.instances.NTupleUnorderedFoldableInstances
    //cats.instances.OptionInstances
    cats.instances.OptionInstancesBinCompat0
    //cats.instances.OrderInstances
    //cats.instances.OrderingInstances
    cats.instances.ParallelInstances
    cats.instances.ParallelInstances1
    //cats.instances.PartialFunctionInstances
    //cats.instances.PartialOrderInstances
    //cats.instances.PartialOrderingInstances
    //cats.instances.QueueInstances
    //cats.instances.ScalaVersionSpecificNumeric
    //cats.instances.SeqInstances
    //cats.instances.SetInstances
    cats.instances.ShortInstances
    //cats.instances.ShowInstances
    //cats.instances.SortedMapCommutativeMonoid
    //cats.instances.SortedMapEq
    //cats.instances.SortedMapHash
    //cats.instances.SortedMapInstances
    cats.instances.SortedMapInstances1
    cats.instances.SortedMapInstances2
    //cats.instances.SortedMapInstancesBinCompat0
    //cats.instances.SortedMapInstancesBinCompat1
    cats.instances.SortedMapInstancesBinCompat2
    //cats.instances.SortedMapMonoid
    //cats.instances.SortedSetHash
    //cats.instances.SortedSetInstances
    //cats.instances.SortedSetInstances1
    //cats.instances.SortedSetInstancesBinCompat0
    //cats.instances.SortedSetInstancesBinCompat1
    //cats.instances.SortedSetOrder
    //cats.instances.SortedSetSemilattice
    //cats.instances.StaticMethods
    //cats.instances.StreamInstances
    //cats.instances.StreamInstancesBinCompat0
    cats.instances.StringInstances
    cats.instances.SymbolInstances
    //cats.instances.TailRecInstances
    cats.instances.TryCoflatMap
    //cats.instances.TryInstances
    cats.instances.TryInstances1
    cats.instances.TryInstances2
    //cats.instances.TryMonoid
    //cats.instances.TrySemigroup
    //cats.instances.Tuple2Instances
    //cats.instances.Tuple2Instances1
    //cats.instances.Tuple2Instances2
    //cats.instances.Tuple2Instances3
    cats.instances.Tuple2Instances4
    //cats.instances.Tuple2InstancesBinCompat0
    cats.instances.TupleInstances
    cats.instances.UUIDInstances
    cats.instances.UnitInstances
    //cats.instances.VectorInstances
    //cats.instances.VectorInstancesBinCompat0
    //cats.kernel.Band
    cats.kernel.BandInstances
    //cats.kernel.BoundedEnumerable
    //cats.kernel.BoundedSemilattice
    cats.kernel.BoundedSemilatticeInstances
    //cats.kernel.CommutativeGroup
    //cats.kernel.CommutativeMonoid
    cats.kernel.CommutativeMonoidInstances
    //cats.kernel.CommutativeSemigroup
    cats.kernel.CommutativeSemigroupInstances
    //cats.kernel.Comparison
    //cats.kernel.Eq
    //cats.kernel.EqFunctions
    cats.kernel.EqInstances
    cats.kernel.EqInstances0
    //cats.kernel.EqToEquivConversion
    cats.kernel.FutureMonoid
    cats.kernel.FutureSemigroup
    //cats.kernel.Group
    //cats.kernel.GroupFunctions
    cats.kernel.GroupInstances
    //cats.kernel.Hash
    //cats.kernel.HashFunctions
    //cats.kernel.HashInstances
    cats.kernel.HashInstances0
    //cats.kernel.HashToHashingConversion
    //cats.kernel.LowerBounded
    //cats.kernel.LowerBoundedEnumerable
    //cats.kernel.LowerBoundedFunctions
    //cats.kernel.Monoid
    //cats.kernel.MonoidFunctions
    cats.kernel.MonoidInstances
    //cats.kernel.Next
    //cats.kernel.Order
    //cats.kernel.OrderFunctions
    cats.kernel.OrderInstances0
    cats.kernel.OrderInstances1
    cats.kernel.OrderToOrderingConversion
    //cats.kernel.PartialNext
    //cats.kernel.PartialNextLowerBounded
    //cats.kernel.PartialOrder
    //cats.kernel.PartialOrderFunctions
    cats.kernel.PartialOrderInstances
    cats.kernel.PartialOrderInstances0
    cats.kernel.PartialOrderInstances1
    cats.kernel.PartialOrderToPartialOrderingConversion
    //cats.kernel.PartialPrevious
    //cats.kernel.PartialPreviousUpperBounded
    //cats.kernel.Previous
    cats.kernel.ScalaVersionSpecificEqInstances
    cats.kernel.ScalaVersionSpecificHashInstances
    cats.kernel.ScalaVersionSpecificMonoidInstances
    cats.kernel.ScalaVersionSpecificOrderInstances
    cats.kernel.ScalaVersionSpecificPartialOrderInstances
    //cats.kernel.Semigroup
    //cats.kernel.SemigroupFunctions
    cats.kernel.SemigroupInstances
    //cats.kernel.Semilattice
    //cats.kernel.SemilatticeFunctions
    cats.kernel.SemilatticeInstances
    cats.kernel.TryMonoid
    cats.kernel.TrySemigroup
    //cats.kernel.UnboundedEnumerable
    //cats.kernel.UpperBounded
    //cats.kernel.UpperBoundedEnumerable
    //cats.kernel.UpperBoundedFunctions
    //cats.kernel.compat.HashCompat
    //cats.kernel.compat.WrappedMutableMapBase
    cats.kernel.compat.scalaVersionMoreSpecific
    //cats.kernel.compat.scalaVersionSpecific
    cats.kernel.instances.AllInstances
    cats.kernel.instances.AllInstancesBinCompat0
    cats.kernel.instances.AllInstancesBinCompat1
    cats.kernel.instances.AllInstancesBinCompat2
    //cats.kernel.instances.ArraySeqInstances
    cats.kernel.instances.BigDecimalGroup
    cats.kernel.instances.BigDecimalInstances
    //cats.kernel.instances.BigDecimalOrder
    //cats.kernel.instances.BigIntGroup
    cats.kernel.instances.BigIntInstances
    //cats.kernel.instances.BigIntOrder
    //cats.kernel.instances.BigIntUnboundedEnum
    cats.kernel.instances.BitSetInstances
    cats.kernel.instances.BitSetPartialOrder
    //cats.kernel.instances.BitSetSemilattice
    cats.kernel.instances.BooleanBounded
    cats.kernel.instances.BooleanEnumerable
    cats.kernel.instances.BooleanInstances
    //cats.kernel.instances.BooleanOrder
    cats.kernel.instances.ByteBounded
    cats.kernel.instances.ByteEnumerable
    cats.kernel.instances.ByteGroup
    cats.kernel.instances.ByteInstances
    //cats.kernel.instances.ByteOrder
    cats.kernel.instances.CharBounded
    cats.kernel.instances.CharEnumerable
    cats.kernel.instances.CharInstances
    //cats.kernel.instances.CharOrder
    //cats.kernel.instances.CombineFunction0
    //cats.kernel.instances.CombineFunction1
    cats.kernel.instances.DeadlineBounded
    cats.kernel.instances.DeadlineInstances
    //cats.kernel.instances.DeadlineOrder
    cats.kernel.instances.DoubleGroup
    cats.kernel.instances.DoubleInstances
    cats.kernel.instances.DoubleOrder
    cats.kernel.instances.DurationBounded
    //cats.kernel.instances.DurationGroup
    cats.kernel.instances.DurationInstances
    //cats.kernel.instances.DurationOrder
    cats.kernel.instances.EitherEq
    //cats.kernel.instances.EitherHash
    //cats.kernel.instances.EitherInstances
    //cats.kernel.instances.EitherInstances0
    cats.kernel.instances.EitherInstances1
    cats.kernel.instances.EqInstances
    cats.kernel.instances.FiniteDurationBounded
    //cats.kernel.instances.FiniteDurationGroup
    cats.kernel.instances.FiniteDurationInstances
    //cats.kernel.instances.FiniteDurationOrder
    cats.kernel.instances.FloatGroup
    cats.kernel.instances.FloatInstances
    cats.kernel.instances.FloatOrder
    //cats.kernel.instances.Function0Group
    //cats.kernel.instances.Function0Monoid
    //cats.kernel.instances.Function0Semigroup
    //cats.kernel.instances.Function1Group
    //cats.kernel.instances.Function1Monoid
    //cats.kernel.instances.Function1Semigroup
    //cats.kernel.instances.FunctionInstances
    //cats.kernel.instances.FunctionInstances0
    //cats.kernel.instances.FunctionInstances1
    //cats.kernel.instances.FunctionInstances2
    //cats.kernel.instances.FunctionInstances3
    cats.kernel.instances.FunctionInstances4
    cats.kernel.instances.HashInstances
    cats.kernel.instances.IntBounded
    cats.kernel.instances.IntEnumerable
    cats.kernel.instances.IntGroup
    cats.kernel.instances.IntInstances
    //cats.kernel.instances.IntOrder
    //cats.kernel.instances.LazyListEq
    cats.kernel.instances.LazyListHash
    cats.kernel.instances.LazyListInstances
    cats.kernel.instances.LazyListInstances1
    cats.kernel.instances.LazyListInstances2
    //cats.kernel.instances.LazyListMonoid
    //cats.kernel.instances.LazyListOrder
    //cats.kernel.instances.LazyListPartialOrder
    //cats.kernel.instances.ListEq
    cats.kernel.instances.ListHash
    cats.kernel.instances.ListInstances
    cats.kernel.instances.ListInstances1
    cats.kernel.instances.ListInstances2
    //cats.kernel.instances.ListMonoid
    //cats.kernel.instances.ListOrder
    //cats.kernel.instances.ListPartialOrder
    cats.kernel.instances.LongBounded
    cats.kernel.instances.LongEnumerable
    cats.kernel.instances.LongGroup
    cats.kernel.instances.LongInstances
    //cats.kernel.instances.LongOrder
    //cats.kernel.instances.MapEq
    //cats.kernel.instances.MapHash
    //cats.kernel.instances.MapInstances
    cats.kernel.instances.MapInstances1
    //cats.kernel.instances.MapMonoid
    cats.kernel.instances.OptionCommutativeMonoid
    cats.kernel.instances.OptionEq
    cats.kernel.instances.OptionHash
    cats.kernel.instances.OptionInstances
    cats.kernel.instances.OptionInstances0
    cats.kernel.instances.OptionInstances1
    cats.kernel.instances.OptionInstances2
    cats.kernel.instances.OptionMonoid
    cats.kernel.instances.OptionOrder
    cats.kernel.instances.OptionPartialOrder
    cats.kernel.instances.OrderInstances
    cats.kernel.instances.PartialOrderInstances
    //cats.kernel.instances.QueueEq
    //cats.kernel.instances.QueueHash
    cats.kernel.instances.QueueInstances
    cats.kernel.instances.QueueInstances1
    cats.kernel.instances.QueueInstances2
    //cats.kernel.instances.QueueMonoid
    //cats.kernel.instances.QueueOrder
    //cats.kernel.instances.QueuePartialOrder
    //cats.kernel.instances.SeqEq
    //cats.kernel.instances.SeqHash
    cats.kernel.instances.SeqInstances
    cats.kernel.instances.SeqInstances1
    cats.kernel.instances.SeqInstances2
    //cats.kernel.instances.SeqMonoid
    //cats.kernel.instances.SeqOrder
    //cats.kernel.instances.SeqPartialOrder
    cats.kernel.instances.SetHash
    cats.kernel.instances.SetInstances
    cats.kernel.instances.SetInstances1
    cats.kernel.instances.SetPartialOrder
    //cats.kernel.instances.SetSemilattice
    cats.kernel.instances.ShortBounded
    cats.kernel.instances.ShortEnumerable
    cats.kernel.instances.ShortGroup
    cats.kernel.instances.ShortInstances
    //cats.kernel.instances.ShortOrder
    //cats.kernel.instances.SortedMapCommutativeMonoid
    //cats.kernel.instances.SortedMapCommutativeSemigroup
    //cats.kernel.instances.SortedMapEq
    //cats.kernel.instances.SortedMapHash
    //cats.kernel.instances.SortedMapInstances
    //cats.kernel.instances.SortedMapInstances1
    cats.kernel.instances.SortedMapInstances2
    cats.kernel.instances.SortedMapInstances3
    //cats.kernel.instances.SortedMapMonoid
    //cats.kernel.instances.SortedMapOrder
    //cats.kernel.instances.SortedMapPartialOrder
    //cats.kernel.instances.SortedMapSemigroup
    //cats.kernel.instances.SortedSetHash
    //cats.kernel.instances.SortedSetInstances
    cats.kernel.instances.SortedSetInstances1
    //cats.kernel.instances.SortedSetOrder
    //cats.kernel.instances.SortedSetSemilattice
    //cats.kernel.instances.StaticMethods
    //cats.kernel.instances.StreamEq
    cats.kernel.instances.StreamHash
    cats.kernel.instances.StreamInstances
    cats.kernel.instances.StreamInstances1
    cats.kernel.instances.StreamInstances2
    //cats.kernel.instances.StreamMonoid
    //cats.kernel.instances.StreamOrder
    //cats.kernel.instances.StreamPartialOrder
    cats.kernel.instances.StringInstances
    cats.kernel.instances.StringLowerBounded
    //cats.kernel.instances.StringMonoid
    //cats.kernel.instances.StringOrder
    cats.kernel.instances.SymbolInstances
    cats.kernel.instances.SymbolLowerBounded
    //cats.kernel.instances.SymbolOrder
    //cats.kernel.instances.TupleBandInstances
    //cats.kernel.instances.TupleBoundedSemilatticeInstances
    //cats.kernel.instances.TupleCommutativeGroupInstances
    //cats.kernel.instances.TupleCommutativeMonoidInstances
    //cats.kernel.instances.TupleCommutativeSemigroupInstances
    //cats.kernel.instances.TupleEqInstances
    //cats.kernel.instances.TupleGroupInstances
    //cats.kernel.instances.TupleHashInstances
    //cats.kernel.instances.TupleInstances
    //cats.kernel.instances.TupleInstances1
    //cats.kernel.instances.TupleInstances2
    //cats.kernel.instances.TupleInstances3
    //cats.kernel.instances.TupleMonoidInstances
    //cats.kernel.instances.TupleOrderInstances
    //cats.kernel.instances.TuplePartialOrderInstances
    //cats.kernel.instances.TupleSemigroupInstances
    //cats.kernel.instances.TupleSemilatticeInstances
    cats.kernel.instances.UUIDBounded
    //cats.kernel.instances.UUIDInstances
    cats.kernel.instances.UnitAlgebra
    cats.kernel.instances.UnitBounded
    cats.kernel.instances.UnitEnumerable
    cats.kernel.instances.UnitInstances
    //cats.kernel.instances.UnitOrder
    //cats.kernel.instances.VectorEq
    //cats.kernel.instances.VectorHash
    cats.kernel.instances.VectorInstances
    cats.kernel.instances.VectorInstances1
    cats.kernel.instances.VectorInstances2
    //cats.kernel.instances.VectorMonoid
    //cats.kernel.instances.VectorOrder
    //cats.kernel.instances.VectorPartialOrder
    cats.kernel.instances.eq
    cats.kernel.instances.hash
    cats.kernel.instances.order
    cats.kernel.instances.partialOrder
    //cats.kernel.laws.BandLaws
    cats.kernel.laws.BoundedEnumerableLaws
    cats.kernel.laws.BoundedSemilatticeLaws
    cats.kernel.laws.CommutativeGroupLaws
    cats.kernel.laws.CommutativeMonoidLaws
    //cats.kernel.laws.CommutativeSemigroupLaws
    //cats.kernel.laws.EqLaws
    //cats.kernel.laws.GroupLaws
    //cats.kernel.laws.HashLaws
    cats.kernel.laws.IsEq
    //cats.kernel.laws.LowerBoundedLaws
    //cats.kernel.laws.MonoidLaws
    //cats.kernel.laws.OrderLaws
    //cats.kernel.laws.PartialNextBoundedLaws
    //cats.kernel.laws.PartialNextLaws
    //cats.kernel.laws.PartialOrderLaws
    //cats.kernel.laws.PartialPreviousBoundedLaws
    //cats.kernel.laws.PartialPreviousLaws
    //cats.kernel.laws.PartialPreviousNextLaws
    //cats.kernel.laws.SemigroupLaws
    cats.kernel.laws.SemilatticeLaws
    //cats.kernel.laws.SerializableLaws
    //cats.kernel.laws.UpperBoundedLaws
    //cats.kernel.laws.discipline.BandTests
    //cats.kernel.laws.discipline.BoundedEnumerableTests
    //cats.kernel.laws.discipline.BoundedSemilatticeTests
    //cats.kernel.laws.discipline.CommutativeGroupTests
    //cats.kernel.laws.discipline.CommutativeMonoidTests
    //cats.kernel.laws.discipline.CommutativeSemigroupTests
    //cats.kernel.laws.discipline.EqTests
    //cats.kernel.laws.discipline.GroupTests
    //cats.kernel.laws.discipline.HashTests
    //cats.kernel.laws.discipline.LowerBoundedTests
    //cats.kernel.laws.discipline.MonoidTests
    //cats.kernel.laws.discipline.OrderTests
    //cats.kernel.laws.discipline.PartialNextTests
    //cats.kernel.laws.discipline.PartialOrderTests
    //cats.kernel.laws.discipline.PartialPreviousTests
    //cats.kernel.laws.discipline.SemigroupTests
    //cats.kernel.laws.discipline.SemilatticeTests
    //cats.kernel.laws.discipline.SerializableTests
    //cats.kernel.laws.discipline.UpperBoundedTests
    //cats.laws.AlignLaws
    //cats.laws.AlternativeLaws
    //cats.laws.ApplicativeErrorLaws
    //cats.laws.ApplicativeLaws
    //cats.laws.ApplyLaws
    //cats.laws.ArrowChoiceLaws
    //cats.laws.ArrowLaws
    //cats.laws.BifoldableLaws
    //cats.laws.BifunctorLaws
    //cats.laws.BimonadLaws
    //cats.laws.BitraverseLaws
    //cats.laws.CategoryLaws
    //cats.laws.ChoiceLaws
    //cats.laws.CoflatMapLaws
    cats.laws.CommutativeApplicativeLaws
    //cats.laws.CommutativeApplyLaws
    //cats.laws.CommutativeArrowLaws
    //cats.laws.CommutativeFlatMapLaws
    cats.laws.CommutativeMonadLaws
    //cats.laws.ComonadLaws
    //cats.laws.ComposeLaws
    //cats.laws.ContravariantLaws
    //cats.laws.ContravariantMonoidalLaws
    //cats.laws.ContravariantSemigroupalLaws
    //cats.laws.DeferLaws
    //cats.laws.DistributiveLaws
    //cats.laws.FlatMapLaws
    //cats.laws.FoldableLaws
    //cats.laws.FunctorFilterLaws
    //cats.laws.FunctorLaws
    //cats.laws.InjectKLaws
    //cats.laws.InjectLaws
    //cats.laws.InvariantLaws
    //cats.laws.InvariantMonoidalLaws
    //cats.laws.InvariantSemigroupalLaws
    //cats.laws.MonadErrorLaws
    //cats.laws.MonadLaws
    //cats.laws.MonoidKLaws
    //cats.laws.NonEmptyAlternativeLaws
    //cats.laws.NonEmptyParallelLaws
    //cats.laws.NonEmptyTraverseLaws
    //cats.laws.ParallelLaws
    //cats.laws.ProfunctorLaws
    //cats.laws.ReducibleLaws
    //cats.laws.RepresentableLaws
    //cats.laws.SemigroupKLaws
    cats.laws.SemigroupalLaws
    //cats.laws.ShortCircuitingLaws
    //cats.laws.StrongLaws
    //cats.laws.TraverseFilterLaws
    //cats.laws.TraverseLaws
    //cats.laws.UnorderedFoldableLaws
    //cats.laws.UnorderedTraverseLaws
    //cats.laws.discipline.AlignTests
    //cats.laws.discipline.AlternativeTests
    //cats.laws.discipline.ApplicativeErrorTests
    //cats.laws.discipline.ApplicativeTests
    //cats.laws.discipline.ApplyTests
    //cats.laws.discipline.ArbitraryInstances0
    //cats.laws.discipline.ArrowChoiceTests
    //cats.laws.discipline.ArrowTests
    //cats.laws.discipline.BifoldableTests
    //cats.laws.discipline.BifunctorTests
    //cats.laws.discipline.BimonadTests
    //cats.laws.discipline.BitraverseTests
    //cats.laws.discipline.CategoryTests
    //cats.laws.discipline.ChoiceTests
    //cats.laws.discipline.CoflatMapTests
    //cats.laws.discipline.CommutativeApplicativeTests
    //cats.laws.discipline.CommutativeApplyTests
    //cats.laws.discipline.CommutativeArrowTests
    //cats.laws.discipline.CommutativeFlatMapTests
    //cats.laws.discipline.CommutativeMonadTests
    //cats.laws.discipline.ComonadTests
    //cats.laws.discipline.ComposeTests
    //cats.laws.discipline.ContravariantMonoidalTests
    //cats.laws.discipline.ContravariantSemigroupalTests
    //cats.laws.discipline.ContravariantTests
    //cats.laws.discipline.DeferTests
    //cats.laws.discipline.DeprecatedEqInstances
    //cats.laws.discipline.DistributiveTests
    //cats.laws.discipline.ExhaustiveCheck
    //cats.laws.discipline.FlatMapTests
    //cats.laws.discipline.FoldableTests
    //cats.laws.discipline.FunctorFilterTests
    //cats.laws.discipline.FunctorTests
    //cats.laws.discipline.InjectKTests
    //cats.laws.discipline.InjectTests
    //cats.laws.discipline.InvariantMonoidalTests
    //cats.laws.discipline.InvariantSemigroupalTests
    //cats.laws.discipline.InvariantTests
    //cats.laws.discipline.MiniInt
    //cats.laws.discipline.MonadErrorTests
    //cats.laws.discipline.MonadTests
    //cats.laws.discipline.MonoidKTests
    //cats.laws.discipline.NonEmptyAlternativeTests
    //cats.laws.discipline.NonEmptyParallelTests
    //cats.laws.discipline.NonEmptyTraverseTests
    //cats.laws.discipline.ParallelTests
    //cats.laws.discipline.ProfunctorTests
    //cats.laws.discipline.ReducibleTests
    //cats.laws.discipline.RepresentableTests
    //cats.laws.discipline.ScalaVersionSpecific
    //cats.laws.discipline.SemigroupKTests
    //cats.laws.discipline.SemigroupalTests
    //cats.laws.discipline.ShortCircuitingTests
    //cats.laws.discipline.StrongTests
    //cats.laws.discipline.TraverseFilterTests
    //cats.laws.discipline.TraverseTests
    //cats.laws.discipline.UnorderedFoldableTests
    //cats.laws.discipline.UnorderedTraverseTests
    //cats.laws.discipline.arbitrary
    //cats.laws.discipline.eq
    //cats.mtl.Ask
    cats.mtl.AskForMonadPartialOrder
    cats.mtl.AskInstances
    //cats.mtl.Censor
    //cats.mtl.CensorInstances
    //cats.mtl.Chronicle
    //cats.mtl.ChronicleInstances
    //cats.mtl.Handle
    //cats.mtl.HandleInstances
    cats.mtl.HandleLowPriorityInstances
    //cats.mtl.Listen
    //cats.mtl.ListenEitherT
    //cats.mtl.ListenInductiveRWST
    //cats.mtl.ListenInductiveWriterT
    //cats.mtl.ListenInstances
    //cats.mtl.ListenIorT
    //cats.mtl.ListenKleisli
    //cats.mtl.ListenOptionT
    //cats.mtl.ListenRWST
    //cats.mtl.ListenStateT
    //cats.mtl.ListenWriterT
    //cats.mtl.Local
    //cats.mtl.LocalInstances
    cats.mtl.LowPriorityAskInstances
    cats.mtl.LowPriorityAskInstancesCompat
    //cats.mtl.LowPriorityCensorInstances
    //cats.mtl.LowPriorityListenInstances
    cats.mtl.LowPriorityListenInstancesCompat
    //cats.mtl.LowPriorityLocalInstances
    cats.mtl.LowPriorityLocalInstancesCompat
    cats.mtl.LowPriorityRaiseInstances
    cats.mtl.LowPriorityStatefulInstances
    cats.mtl.LowPriorityTellInstances
    cats.mtl.LowPriorityTellInstancesCompat
    cats.mtl.MonadPartialOrder
    //cats.mtl.MonadPartialOrderInstances
    //cats.mtl.Raise
    cats.mtl.RaiseInstances
    cats.mtl.RaiseMonadPartialOrder
    //cats.mtl.Stateful
    //cats.mtl.StatefulInstances
    //cats.mtl.Tell
    //cats.mtl.TellInstances
    cats.mtl.TellMonadPartialOrder
    cats.mtl.syntax.AllSyntax
    cats.mtl.syntax.AskSyntax
    //cats.mtl.syntax.ChronicleIdOps
    //cats.mtl.syntax.ChronicleIorOps
    //cats.mtl.syntax.ChronicleOps
    cats.mtl.syntax.ChronicleSyntax
    //cats.mtl.syntax.HandleOps
    cats.mtl.syntax.HandleSyntax
    //cats.mtl.syntax.ListenOps
    cats.mtl.syntax.ListenSyntax
    //cats.mtl.syntax.LocalOps
    cats.mtl.syntax.LocalSyntax
    //cats.mtl.syntax.ModifyOps
    //cats.mtl.syntax.RaiseOps
    cats.mtl.syntax.RaiseSyntax
    //cats.mtl.syntax.ReaderOps
    //cats.mtl.syntax.SetOps
    cats.mtl.syntax.StateSyntax
    //cats.mtl.syntax.TellOps
    cats.mtl.syntax.TellSyntax
    //cats.mtl.syntax.TupleOps
    cats.mtl.syntax.all
    cats.mtl.syntax.ask
    cats.mtl.syntax.chronicle
    cats.mtl.syntax.handle
    cats.mtl.syntax.listen
    cats.mtl.syntax.local
    cats.mtl.syntax.raise
    cats.mtl.syntax.state
    cats.mtl.syntax.tell
    //cats.platform.Platform
    cats.syntax.AlignSyntax
    cats.syntax.AllSyntax
    cats.syntax.AllSyntaxBinCompat
    cats.syntax.AllSyntaxBinCompat0
    cats.syntax.AllSyntaxBinCompat1
    cats.syntax.AllSyntaxBinCompat2
    cats.syntax.AllSyntaxBinCompat3
    cats.syntax.AllSyntaxBinCompat4
    cats.syntax.AllSyntaxBinCompat5
    cats.syntax.AllSyntaxBinCompat6
    cats.syntax.AllSyntaxBinCompat7
    cats.syntax.AlternativeSyntax
    //cats.syntax.ApplicativeByNameOps
    //cats.syntax.ApplicativeByValueOps
    cats.syntax.ApplicativeErrorExtension
    cats.syntax.ApplicativeErrorExtensionOps
    //cats.syntax.ApplicativeErrorFUnitOps
    //cats.syntax.ApplicativeErrorIdOps
    //cats.syntax.ApplicativeErrorOps
    cats.syntax.ApplicativeErrorSyntax
    //cats.syntax.ApplicativeIdOps
    //cats.syntax.ApplicativeOps
    cats.syntax.ApplicativeSyntax
    //cats.syntax.ApplyFABCOps
    //cats.syntax.ApplyFABOps
    //cats.syntax.ApplyOps
    cats.syntax.ApplySyntax
    cats.syntax.ApplySyntaxBinCompat0
    cats.syntax.ArrowChoiceSyntax
    cats.syntax.ArrowSyntax
    cats.syntax.BifoldableSyntax
    cats.syntax.BifunctorSyntax
    //cats.syntax.BinestedIdOps
    cats.syntax.BinestedSyntax
    //cats.syntax.BitraverseOps
    //cats.syntax.BitraverseOpsBinCompat0
    cats.syntax.BitraverseSyntax
    cats.syntax.BitraverseSyntax1
    cats.syntax.BitraverseSyntaxBinCompat0
    cats.syntax.ChoiceSyntax
    cats.syntax.CoflatMapSyntax
    cats.syntax.ComonadSyntax
    cats.syntax.ComposeSyntax
    cats.syntax.ContravariantMonoidalOps
    cats.syntax.ContravariantMonoidalSyntax
    cats.syntax.ContravariantSemigroupalSyntax
    cats.syntax.ContravariantSyntax
    //cats.syntax.DistributiveOps
    cats.syntax.DistributiveSyntax
    //cats.syntax.EitherIdOps
    //cats.syntax.EitherIdOpsBinCompat0
    //cats.syntax.EitherKOps
    cats.syntax.EitherKSyntax
    //cats.syntax.EitherObjectOps
    //cats.syntax.EitherOps
    //cats.syntax.EitherOpsBinCompat0
    //cats.syntax.EitherSyntax
    cats.syntax.EitherSyntaxBinCompat0
    //cats.syntax.EitherUtil
    //cats.syntax.EqOps
    cats.syntax.EqSyntax
    //cats.syntax.FlatMapIdOps
    //cats.syntax.FlatMapOps
    //cats.syntax.FlatMapOptionOps
    cats.syntax.FlatMapOptionSyntax
    cats.syntax.FlatMapSyntax
    //cats.syntax.FlattenOps
    //cats.syntax.FoldableOps
    //cats.syntax.FoldableOps0
    //cats.syntax.FoldableOps1
    cats.syntax.FoldableSyntax
    cats.syntax.FoldableSyntaxBinCompat0
    cats.syntax.FoldableSyntaxBinCompat1
    //cats.syntax.Function10ApplyOps
    //cats.syntax.Function11ApplyOps
    //cats.syntax.Function12ApplyOps
    //cats.syntax.Function13ApplyOps
    //cats.syntax.Function14ApplyOps
    //cats.syntax.Function15ApplyOps
    //cats.syntax.Function16ApplyOps
    //cats.syntax.Function17ApplyOps
    //cats.syntax.Function18ApplyOps
    //cats.syntax.Function19ApplyOps
    //cats.syntax.Function1ApplyOps
    //cats.syntax.Function1Syntax
    //cats.syntax.Function20ApplyOps
    //cats.syntax.Function21ApplyOps
    //cats.syntax.Function22ApplyOps
    //cats.syntax.Function2ApplyOps
    //cats.syntax.Function3ApplyOps
    //cats.syntax.Function4ApplyOps
    //cats.syntax.Function5ApplyOps
    //cats.syntax.Function6ApplyOps
    //cats.syntax.Function7ApplyOps
    //cats.syntax.Function8ApplyOps
    //cats.syntax.Function9ApplyOps
    cats.syntax.FunctionApplySyntax
    cats.syntax.FunctorFilterSyntax
    cats.syntax.FunctorSyntax
    //cats.syntax.FunctorTuple2Ops
    //cats.syntax.GroupOps
    cats.syntax.GroupSyntax
    //cats.syntax.GuardOps
    //cats.syntax.HashOps
    cats.syntax.HashSyntax
    //cats.syntax.IfApplyOps
    //cats.syntax.IfFOps
    //cats.syntax.IfMOps
    //cats.syntax.IndexOps
    cats.syntax.InvariantSyntax
    //cats.syntax.IorIdOps
    cats.syntax.IorSyntax
    //cats.syntax.LeftNestedBitraverseOps
    //cats.syntax.LeftOps
    //cats.syntax.ListOps
    //cats.syntax.ListOpsBinCompat0
    cats.syntax.ListSyntax
    cats.syntax.ListSyntaxBinCompat0
    //cats.syntax.MonadErrorOps
    //cats.syntax.MonadErrorRethrowOps
    cats.syntax.MonadErrorSyntax
    //cats.syntax.MonadIdOps
    //cats.syntax.MonadOps
    cats.syntax.MonadSyntax
    //cats.syntax.MonoidOps
    cats.syntax.MonoidSyntax
    //cats.syntax.NestedBitraverseOps
    //cats.syntax.NestedFoldableOps
    //cats.syntax.NestedIdOps
    //cats.syntax.NestedReducibleOps
    cats.syntax.NestedSyntax
    //cats.syntax.NonEmptyAlternativeOps
    cats.syntax.NonEmptyAlternativeSyntax
    //cats.syntax.NonEmptyParallelApOps
    //cats.syntax.NonEmptyParallelApplyOps
    cats.syntax.NonEmptyTraverseSyntax
    //cats.syntax.OptionIdOps
    //cats.syntax.OptionOps
    cats.syntax.OptionSyntax
    //cats.syntax.OrderOps
    cats.syntax.OrderSyntax
    //cats.syntax.ParallelApOps
    //cats.syntax.ParallelApOps1
    //cats.syntax.ParallelApplyOps
    cats.syntax.ParallelApplySyntax
    //cats.syntax.ParallelBisequenceOps
    //cats.syntax.ParallelBitraverseOps
    cats.syntax.ParallelBitraverseSyntax
    //cats.syntax.ParallelFlatSequenceOps
    //cats.syntax.ParallelFlatSequenceOps1
    cats.syntax.ParallelFlatSyntax
    //cats.syntax.ParallelFlatTraversableOps
    //cats.syntax.ParallelFlatTraversableOps1
    //cats.syntax.ParallelFoldMapAOps
    cats.syntax.ParallelFoldMapASyntax
    //cats.syntax.ParallelLeftSequenceOps
    //cats.syntax.ParallelLeftTraverseOps
    //cats.syntax.ParallelReduceMapAOps
    cats.syntax.ParallelReduceMapASyntax
    //cats.syntax.ParallelSequenceFilterOps
    //cats.syntax.ParallelSequenceOps
    //cats.syntax.ParallelSequenceOps1
    //cats.syntax.ParallelSequence_Ops
    cats.syntax.ParallelSyntax
    //cats.syntax.ParallelTraversableOps
    //cats.syntax.ParallelTraversableOps1
    //cats.syntax.ParallelTraversable_Ops
    //cats.syntax.ParallelTraverseFilterOps
    cats.syntax.ParallelTraverseFilterSyntax
    cats.syntax.ParallelTraverseSyntax
    //cats.syntax.ParallelUnorderedFlatSequenceOps
    //cats.syntax.ParallelUnorderedSequenceOps
    //cats.syntax.ParallelUnorderedTraverseOps
    cats.syntax.ParallelUnorderedTraverseSyntax
    cats.syntax.PartialOrderOps
    cats.syntax.PartialOrderSyntax
    cats.syntax.ProfunctorSyntax
    //cats.syntax.ReducibleOps0
    cats.syntax.ReducibleSyntax
    cats.syntax.ReducibleSyntaxBinCompat0
    cats.syntax.RepresentableSyntax
    //cats.syntax.RightOps
    cats.syntax.SemigroupKSyntax
    //cats.syntax.SemigroupOps
    cats.syntax.SemigroupSyntax
    cats.syntax.SemigroupalBuilder
    //cats.syntax.SemigroupalOps
    //cats.syntax.SemigroupalOps2
    cats.syntax.SemigroupalSyntax
    //cats.syntax.SeparateOps
    //cats.syntax.SeparateOpsBinCompat0
    //cats.syntax.SeqOps
    cats.syntax.SeqSyntax
    //cats.syntax.SequenceFilterOps
    //cats.syntax.SetOps
    cats.syntax.SetSyntax
    cats.syntax.ShowSyntax
    cats.syntax.StrongSyntax
    //cats.syntax.TabulateOps
    //cats.syntax.TraverseFilterOps
    cats.syntax.TraverseFilterSyntax
    cats.syntax.TraverseFilterSyntaxBinCompat0
    cats.syntax.TraverseSyntax
    //cats.syntax.TryOps
    cats.syntax.TrySyntax
    cats.syntax.Tuple10ParallelOps
    cats.syntax.Tuple10SemigroupalOps
    cats.syntax.Tuple11ParallelOps
    cats.syntax.Tuple11SemigroupalOps
    cats.syntax.Tuple12ParallelOps
    cats.syntax.Tuple12SemigroupalOps
    cats.syntax.Tuple13ParallelOps
    cats.syntax.Tuple13SemigroupalOps
    cats.syntax.Tuple14ParallelOps
    cats.syntax.Tuple14SemigroupalOps
    cats.syntax.Tuple15ParallelOps
    cats.syntax.Tuple15SemigroupalOps
    cats.syntax.Tuple16ParallelOps
    cats.syntax.Tuple16SemigroupalOps
    cats.syntax.Tuple17ParallelOps
    cats.syntax.Tuple17SemigroupalOps
    cats.syntax.Tuple18ParallelOps
    cats.syntax.Tuple18SemigroupalOps
    cats.syntax.Tuple19ParallelOps
    cats.syntax.Tuple19SemigroupalOps
    //cats.syntax.Tuple1ParallelOps
    //cats.syntax.Tuple1SemigroupalOps
    cats.syntax.Tuple20ParallelOps
    cats.syntax.Tuple20SemigroupalOps
    cats.syntax.Tuple21ParallelOps
    cats.syntax.Tuple21SemigroupalOps
    cats.syntax.Tuple22ParallelOps
    cats.syntax.Tuple22SemigroupalOps
    cats.syntax.Tuple2ParallelOps
    cats.syntax.Tuple2SemigroupalOps
    cats.syntax.Tuple3ParallelOps
    cats.syntax.Tuple3SemigroupalOps
    cats.syntax.Tuple4ParallelOps
    cats.syntax.Tuple4SemigroupalOps
    cats.syntax.Tuple5ParallelOps
    cats.syntax.Tuple5SemigroupalOps
    cats.syntax.Tuple6ParallelOps
    cats.syntax.Tuple6SemigroupalOps
    cats.syntax.Tuple7ParallelOps
    cats.syntax.Tuple7SemigroupalOps
    cats.syntax.Tuple8ParallelOps
    cats.syntax.Tuple8SemigroupalOps
    cats.syntax.Tuple9ParallelOps
    cats.syntax.Tuple9SemigroupalOps
    //cats.syntax.TupleParallelSyntax
    //cats.syntax.TupleSemigroupalSyntax
    //cats.syntax.UniteOps
    //cats.syntax.UniteOpsBinCompat0
    //cats.syntax.UnorderedFoldableOps
    cats.syntax.UnorderedFoldableSyntax
    cats.syntax.UnorderedTraverseSyntax
    //cats.syntax.ValidatedExtension
    cats.syntax.ValidatedExtensionSyntax
    //cats.syntax.ValidatedIdOpsBinCompat0
    //cats.syntax.ValidatedIdSyntax
    cats.syntax.ValidatedSyntax
    cats.syntax.ValidatedSyntaxBincompat0
    //cats.syntax.VectorOps
    cats.syntax.VectorSyntax
    //cats.syntax.WriterIdSyntax
    cats.syntax.WriterSyntax
 """)
}