package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.given
import org.junit.Test

class CatsLawsSemanticTest extends SemanticTestBase("org.typelevel" %% "cats-laws" % "2.13.0")("cats.laws") {
  override protected def enableKindProjectorPlugin = true

  @Test def test(): Unit = doTest("""
    //cats.laws.AlignLaws
    //cats.laws.AlternativeLaws
    //cats.laws.ApplicativeErrorLaws
    //cats.laws.ApplicativeLaws
    //cats.laws.ApplyLaws
    //cats.laws.ArrowChoiceLaws
    //cats.laws.ArrowLaws
    //cats.laws.BifoldableLaws
    //cats.laws.BifunctorLaws
    //cats.laws.BimonadLaws
    //cats.laws.BitraverseLaws
    //cats.laws.CategoryLaws
    //cats.laws.ChoiceLaws
    //cats.laws.CoflatMapLaws
    cats.laws.CommutativeApplicativeLaws
    //cats.laws.CommutativeApplyLaws
    //cats.laws.CommutativeArrowLaws
    //cats.laws.CommutativeFlatMapLaws
    cats.laws.CommutativeMonadLaws
    //cats.laws.ComonadLaws
    //cats.laws.ComposeLaws
    //cats.laws.ContravariantLaws
    //cats.laws.ContravariantMonoidalLaws
    //cats.laws.ContravariantSemigroupalLaws
    //cats.laws.DeferLaws
    //cats.laws.DistributiveLaws
    //cats.laws.FlatMapLaws
    //cats.laws.FoldableLaws
    //cats.laws.FunctorFilterLaws
    //cats.laws.FunctorLaws
    //cats.laws.InjectKLaws
    //cats.laws.InjectLaws
    //cats.laws.InvariantLaws
    //cats.laws.InvariantMonoidalLaws
    //cats.laws.InvariantSemigroupalLaws
    //cats.laws.MonadErrorLaws
    //cats.laws.MonadLaws
    //cats.laws.MonoidKLaws
    //cats.laws.NonEmptyAlternativeLaws
    //cats.laws.NonEmptyParallelLaws
    //cats.laws.NonEmptyTraverseLaws
    //cats.laws.ParallelLaws
    //cats.laws.ProfunctorLaws
    //cats.laws.ReducibleLaws
    //cats.laws.RepresentableLaws
    //cats.laws.SemigroupKLaws
    cats.laws.SemigroupalLaws
    //cats.laws.ShortCircuitingLaws
    //cats.laws.StrongLaws
    //cats.laws.TraverseFilterLaws
    //cats.laws.TraverseLaws
    //cats.laws.UnorderedFoldableLaws
    //cats.laws.UnorderedTraverseLaws
    //cats.laws.discipline.AlignTests
    //cats.laws.discipline.AlternativeTests
    //cats.laws.discipline.ApplicativeErrorTests
    //cats.laws.discipline.ApplicativeTests
    //cats.laws.discipline.ApplyTests
    //cats.laws.discipline.ArbitraryInstances0
    //cats.laws.discipline.ArrowChoiceTests
    //cats.laws.discipline.ArrowTests
    //cats.laws.discipline.BifoldableTests
    //cats.laws.discipline.BifunctorTests
    //cats.laws.discipline.BimonadTests
    //cats.laws.discipline.BitraverseTests
    //cats.laws.discipline.CategoryTests
    //cats.laws.discipline.ChoiceTests
    //cats.laws.discipline.CoflatMapTests
    //cats.laws.discipline.CommutativeApplicativeTests
    //cats.laws.discipline.CommutativeApplyTests
    //cats.laws.discipline.CommutativeArrowTests
    //cats.laws.discipline.CommutativeFlatMapTests
    //cats.laws.discipline.CommutativeMonadTests
    //cats.laws.discipline.ComonadTests
    //cats.laws.discipline.ComposeTests
    //cats.laws.discipline.ContravariantMonoidalTests
    //cats.laws.discipline.ContravariantSemigroupalTests
    //cats.laws.discipline.ContravariantTests
    //cats.laws.discipline.DeferTests
    //cats.laws.discipline.DeprecatedEqInstances
    //cats.laws.discipline.DistributiveTests
    //cats.laws.discipline.ExhaustiveCheck
    //cats.laws.discipline.FlatMapTests
    //cats.laws.discipline.FoldableTests
    //cats.laws.discipline.FunctorFilterTests
    //cats.laws.discipline.FunctorTests
    //cats.laws.discipline.InjectKTests
    //cats.laws.discipline.InjectTests
    //cats.laws.discipline.InvariantMonoidalTests
    //cats.laws.discipline.InvariantSemigroupalTests
    //cats.laws.discipline.InvariantTests
    //cats.laws.discipline.MiniInt
    //cats.laws.discipline.MonadErrorTests
    //cats.laws.discipline.MonadTests
    //cats.laws.discipline.MonoidKTests
    //cats.laws.discipline.NonEmptyAlternativeTests
    //cats.laws.discipline.NonEmptyParallelTests
    //cats.laws.discipline.NonEmptyTraverseTests
    //cats.laws.discipline.ParallelTests
    //cats.laws.discipline.ProfunctorTests
    //cats.laws.discipline.ReducibleTests
    //cats.laws.discipline.RepresentableTests
    //cats.laws.discipline.ScalaVersionSpecific
    //cats.laws.discipline.SemigroupKTests
    //cats.laws.discipline.SemigroupalTests
    //cats.laws.discipline.ShortCircuitingTests
    //cats.laws.discipline.StrongTests
    //cats.laws.discipline.TraverseFilterTests
    //cats.laws.discipline.TraverseTests
    //cats.laws.discipline.UnorderedFoldableTests
    //cats.laws.discipline.UnorderedTraverseTests
    //cats.laws.discipline.arbitrary
    //cats.laws.discipline.eq
  """)
}