package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.corpus.scala3.ScalatestTest
import org.junit.Test

class ScalatestSemanticTest extends SemanticTestBase(ScalatestTest) {
  @Test def test(): Unit = doTest("""
    //org.scalatest.Alerter
    org.scalatest.Alerting
    //org.scalatest.AppendedClues
    //org.scalatest.Args
    //org.scalatest.Assertions
    //org.scalatest.AssertionsMacro
    org.scalatest.AsyncEngine
    org.scalatest.AsyncFixtureEngine
    org.scalatest.AsyncOutcome
    //org.scalatest.AsyncSuperEngine
    org.scalatest.AsyncTestHolder
    org.scalatest.AsyncTestRegistration
    //org.scalatest.AsyncTestSuite
    org.scalatest.AsyncTestSuiteMixin
    //org.scalatest.BeforeAndAfter
    //org.scalatest.BeforeAndAfterAll
    //org.scalatest.BeforeAndAfterAllConfigMap
    //org.scalatest.BeforeAndAfterEach
    //org.scalatest.BeforeAndAfterEachTestData
    //org.scalatest.CancelAfterFailure
    //org.scalatest.Canceled
    org.scalatest.CatchReporter
    //org.scalatest.Checkpoints
    //org.scalatest.CompleteLastly
    //org.scalatest.CompositeStatus
    //org.scalatest.ConcurrentAlerter
    //org.scalatest.ConcurrentDocumenter
    //org.scalatest.ConcurrentInformer
    //org.scalatest.ConcurrentLinkedQueue
    //org.scalatest.ConcurrentNotifier
    //org.scalatest.ConfigMap
    //org.scalatest.ConfigMapWrapperSuite
    //org.scalatest.CountDownLatch
    //org.scalatest.DeferredAbortedSuite
    //org.scalatest.DispatchReporter
    org.scalatest.DistributedSuiteSorter
    org.scalatest.DistributedTestSorter
    org.scalatest.Distributor
    //org.scalatest.Doc
    //org.scalatest.DocSpec
    //org.scalatest.DocSpecLike
    org.scalatest.Documenter
    org.scalatest.Documenting
    //org.scalatest.DynaTags
    //org.scalatest.EitherValues
    //org.scalatest.EncodedOrdering
    org.scalatest.Engine
    //org.scalatest.Entry
    //org.scalatest.Exceptional
    //org.scalatest.Fact
    //org.scalatest.Failed
    //org.scalatest.FailedStatus
    org.scalatest.FailureMessages
    //org.scalatest.Filter
    org.scalatest.FixtureAsyncTestRegistration
    //org.scalatest.FixtureAsyncTestSuite
    org.scalatest.FixtureContext
    org.scalatest.FixtureEngine
    //org.scalatest.FixtureSuite
    org.scalatest.FixtureTestRegistration
    //org.scalatest.FixtureTestSuite
    //org.scalatest.FutureAsyncOutcome
    //org.scalatest.FutureAsyncTestHolder
    //org.scalatest.FutureOutcome
    //org.scalatest.GivenWhenThen
    //org.scalatest.Informer
    org.scalatest.Informing
    org.scalatest.InsertionOrderSet
    //org.scalatest.Inside
    //org.scalatest.Inspectors
    org.scalatest.InspectorsHelper
    //org.scalatest.JSuite
    //org.scalatest.LinkedBlockingQueue
    //org.scalatest.LoneElement
    //org.scalatest.MessageRecorder
    org.scalatest.MessageRecordingDocumenter
    org.scalatest.MessageRecordingInformer
    org.scalatest.NameTransformer
    org.scalatest.NonImplicitAssertions
    //org.scalatest.Notifier
    org.scalatest.Notifying
    //org.scalatest.OneInstancePerTest
    //org.scalatest.OptionValues
    //org.scalatest.Outcome
    //org.scalatest.OutcomeOf
    //org.scalatest.ParallelTestExecution
    //org.scalatest.PartialFunctionValues
    //org.scalatest.PastAsyncOutcome
    //org.scalatest.PastAsyncTestHolder
    //org.scalatest.PathEngine
    //org.scalatest.PathMessageRecordingAlerter
    //org.scalatest.PathMessageRecordingDocumenter
    //org.scalatest.PathMessageRecordingInformer
    //org.scalatest.PathMessageRecordingNotifier
    //org.scalatest.Payloads
    //org.scalatest.Pending
    org.scalatest.PendingStatement
    //org.scalatest.PrivateMethodTester
    //org.scalatest.RandomTestOrder
    //org.scalatest.RecoverMethods
    //org.scalatest.Reporter
    //org.scalatest.Rerunner
    org.scalatest.ResourcefulReporter
    //org.scalatest.Resources
    //org.scalatest.Retries
    //org.scalatest.RunningTest
    //org.scalatest.ScalaTestStatefulStatus
    org.scalatest.ScalaTestVersions
    //org.scalatest.Sequential
    //org.scalatest.SequentialNestedSuiteExecution
    //org.scalatest.SeveredStackTraces
    //org.scalatest.Shell
    //org.scalatest.ShellImpl
    //org.scalatest.Slowpoke
    //org.scalatest.SlowpokeDetector
    //org.scalatest.StatefulStatus
    //org.scalatest.Status
    //org.scalatest.Stepwise
    //org.scalatest.StepwiseNestedSuiteExecution
    //org.scalatest.StopOnFailure
    org.scalatest.StopOnFailureReporter
    //org.scalatest.Stopper
    //org.scalatest.StreamlinedXmlEquality
    //org.scalatest.StreamlinedXmlNormMethods
    //org.scalatest.Succeeded
    //org.scalatest.SucceededStatus
    //org.scalatest.Suite
    //org.scalatest.SuiteHelpers
    org.scalatest.SuiteMixin
    //org.scalatest.SuiteRerunner
    //org.scalatest.Suites
    //org.scalatest.SuperEngine
    //org.scalatest.Tag
    org.scalatest.TestData
    org.scalatest.TestRegistration
    //org.scalatest.TestRerunner
    //org.scalatest.TestSuite
    org.scalatest.TestSuiteMixin
    //org.scalatest.TestsBeforeNestedSuites
    //org.scalatest.ThreadAwareness
    //org.scalatest.Timer
    //org.scalatest.TimerTask
    //org.scalatest.Tracker
    //org.scalatest.Transformer
    //org.scalatest.TryValues
    org.scalatest.UnquotedString
    //org.scalatest.WrapperCatchReporter
    //org.scalatest.run
    //org.scalatest.concurrent.AbstractPatienceConfiguration
    //org.scalatest.concurrent.AsyncCancelAfterFailure
    //org.scalatest.concurrent.AsyncTimeLimitedTests
    //org.scalatest.concurrent.ConductorFixture
    //org.scalatest.concurrent.ConductorMethods
    //org.scalatest.concurrent.Conductors
    //org.scalatest.concurrent.DoNotSignal
    //org.scalatest.concurrent.Eventually
    //org.scalatest.concurrent.Futures
    //org.scalatest.concurrent.IntegrationPatience
    //org.scalatest.concurrent.JavaFutures
    //org.scalatest.concurrent.PatienceConfiguration
    //org.scalatest.concurrent.PimpedReadWriteLock
    //org.scalatest.concurrent.PimpedThreadGroup
    //org.scalatest.concurrent.ScalaFutures
    org.scalatest.concurrent.ScaledTimeSpans
    //org.scalatest.concurrent.SelectorSignaler
    //org.scalatest.concurrent.SerialExecutionContext
    org.scalatest.concurrent.Signaler
    //org.scalatest.concurrent.SignalerTimeoutTask
    org.scalatest.concurrent.SleepHelper
    org.scalatest.concurrent.SocketSignaler
    //org.scalatest.concurrent.TestThreadsStartingCounter
    org.scalatest.concurrent.ThreadSignaler
    //org.scalatest.concurrent.TimeLimitedTests
    //org.scalatest.concurrent.TimeLimits
    //org.scalatest.concurrent.Waiters
    //org.scalatest.diagrams.AnchorValue
    //org.scalatest.diagrams.DiagrammedApplyExpr
    //org.scalatest.diagrams.DiagrammedAssertionsMacro
    //org.scalatest.diagrams.DiagrammedByNameExpr
    //org.scalatest.diagrams.DiagrammedExpr
    //org.scalatest.diagrams.DiagrammedSelectExpr
    //org.scalatest.diagrams.DiagrammedSimpleExpr
    //org.scalatest.diagrams.Diagrams
    org.scalatest.enablers.Aggregating
    //org.scalatest.enablers.AggregatingHighPriorityImplicits
    //org.scalatest.enablers.AggregatingImpls
    //org.scalatest.enablers.AggregatingJavaImplicits
    //org.scalatest.enablers.AggregatingStandardImplicits
    //org.scalatest.enablers.Collecting
    org.scalatest.enablers.Containing
    //org.scalatest.enablers.ContainingHighPriorityImplicits
    //org.scalatest.enablers.ContainingImpls
    //org.scalatest.enablers.ContainingStandardImplicits
    //org.scalatest.enablers.Definition
    //org.scalatest.enablers.Emptiness
    org.scalatest.enablers.Existence
    //org.scalatest.enablers.ExpectationWheneverAsserting
    //org.scalatest.enablers.Futuristic
    //org.scalatest.enablers.InspectorAsserting
    //org.scalatest.enablers.JavaContainingImplicits
    //org.scalatest.enablers.KeyMapping
    //org.scalatest.enablers.Length
    //org.scalatest.enablers.Messaging
    //org.scalatest.enablers.Readability
    //org.scalatest.enablers.Retrying
    //org.scalatest.enablers.Sequencing
    //org.scalatest.enablers.Size
    org.scalatest.enablers.Slicing
    //org.scalatest.enablers.Sortable
    //org.scalatest.enablers.TableAsserting
    //org.scalatest.enablers.Timed
    //org.scalatest.enablers.UnitInspectorAsserting
    //org.scalatest.enablers.UnitWheneverAsserting
    //org.scalatest.enablers.ValueMapping
    //org.scalatest.enablers.WheneverAsserting
    //org.scalatest.enablers.Writability
    //org.scalatest.events.AlertProvided
    //org.scalatest.events.DiscoveryCompleted
    //org.scalatest.events.DiscoveryStarting
    //org.scalatest.events.Event
    org.scalatest.events.ExceptionalEvent
    org.scalatest.events.Formatter
    //org.scalatest.events.IndentedText
    //org.scalatest.events.InfoProvided
    //org.scalatest.events.LineInFile
    org.scalatest.events.Location
    //org.scalatest.events.MarkupProvided
    //org.scalatest.events.MotionToSuppress
    //org.scalatest.events.NameInfo
    //org.scalatest.events.NoteProvided
    org.scalatest.events.NotificationEvent
    //org.scalatest.events.Ordinal
    org.scalatest.events.RecordableEvent
    //org.scalatest.events.RunAborted
    //org.scalatest.events.RunCompleted
    //org.scalatest.events.RunStarting
    //org.scalatest.events.RunStopped
    //org.scalatest.events.ScopeClosed
    //org.scalatest.events.ScopeOpened
    //org.scalatest.events.ScopePending
    //org.scalatest.events.SeeStackDepthException
    //org.scalatest.events.SuiteAborted
    //org.scalatest.events.SuiteCompleted
    //org.scalatest.events.SuiteStarting
    //org.scalatest.events.Summary
    //org.scalatest.events.TestCanceled
    //org.scalatest.events.TestFailed
    //org.scalatest.events.TestIgnored
    //org.scalatest.events.TestPending
    //org.scalatest.events.TestStarting
    //org.scalatest.events.TestSucceeded
    //org.scalatest.events.TopOfClass
    //org.scalatest.events.TopOfMethod
    org.scalatest.exceptions.DiscardedEvaluationException
    //org.scalatest.exceptions.DuplicateTestNameException
    //org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException
    org.scalatest.exceptions.ModifiableMessage
    org.scalatest.exceptions.ModifiablePayload
    //org.scalatest.exceptions.NotAllowedException
    //org.scalatest.exceptions.NotSerializableWrapperException
    org.scalatest.exceptions.PayloadField
    //org.scalatest.exceptions.PropertyCheckFailedException
    //org.scalatest.exceptions.StackDepth
    //org.scalatest.exceptions.StackDepthException
    //org.scalatest.exceptions.StackDepthExceptionHelper
    //org.scalatest.exceptions.TableDrivenPropertyCheckFailedException
    //org.scalatest.exceptions.TestCanceledException
    //org.scalatest.exceptions.TestFailedDueToTimeoutException
    //org.scalatest.exceptions.TestFailedException
    org.scalatest.exceptions.TestPendingException
    //org.scalatest.exceptions.TestRegistrationClosedException
    org.scalatest.exceptions.TimeoutField
    //org.scalatest.featurespec.AnyFeatureSpec
    //org.scalatest.featurespec.AnyFeatureSpecLike
    org.scalatest.featurespec.AsyncFeatureSpec
    //org.scalatest.featurespec.AsyncFeatureSpecLike
    //org.scalatest.featurespec.FixtureAnyFeatureSpec
    //org.scalatest.featurespec.FixtureAnyFeatureSpecLike
    org.scalatest.featurespec.FixtureAsyncFeatureSpec
    //org.scalatest.featurespec.FixtureAsyncFeatureSpecLike
    //org.scalatest.fixture.AsyncConfigMapFixture
    //org.scalatest.fixture.AsyncPendingTransformer
    //org.scalatest.fixture.AsyncTestDataFixture
    //org.scalatest.fixture.ConfigMapFixture
    //org.scalatest.fixture.FixtureNodeFamily
    //org.scalatest.fixture.NoArg
    //org.scalatest.fixture.NoArgTestWrapper
    //org.scalatest.fixture.TestDataFixture
    //org.scalatest.fixture.Transformer
    //org.scalatest.fixture.UnitFixture
    //org.scalatest.flatspec.AnyFlatSpec
    //org.scalatest.flatspec.AnyFlatSpecLike
    org.scalatest.flatspec.AsyncFlatSpec
    //org.scalatest.flatspec.AsyncFlatSpecLike
    //org.scalatest.flatspec.FixtureAnyFlatSpec
    //org.scalatest.flatspec.FixtureAnyFlatSpecLike
    org.scalatest.flatspec.FixtureAsyncFlatSpec
    //org.scalatest.flatspec.FixtureAsyncFlatSpecLike
    //org.scalatest.freespec.AnyFreeSpec
    //org.scalatest.freespec.AnyFreeSpecLike
    org.scalatest.freespec.AsyncFreeSpec
    //org.scalatest.freespec.AsyncFreeSpecLike
    //org.scalatest.freespec.FixtureAnyFreeSpec
    //org.scalatest.freespec.FixtureAnyFreeSpecLike
    org.scalatest.freespec.FixtureAsyncFreeSpec
    //org.scalatest.freespec.FixtureAsyncFreeSpecLike
    //org.scalatest.freespec.PathAnyFreeSpec
    //org.scalatest.freespec.PathAnyFreeSpecLike
    //org.scalatest.funspec.AnyFunSpec
    //org.scalatest.funspec.AnyFunSpecLike
    org.scalatest.funspec.AsyncFunSpec
    //org.scalatest.funspec.AsyncFunSpecLike
    //org.scalatest.funspec.FixtureAnyFunSpec
    //org.scalatest.funspec.FixtureAnyFunSpecLike
    org.scalatest.funspec.FixtureAsyncFunSpec
    //org.scalatest.funspec.FixtureAsyncFunSpecLike
    //org.scalatest.funspec.PathAnyFunSpec
    //org.scalatest.funspec.PathAnyFunSpecLike
    //org.scalatest.funsuite.AnyFunSuite
    //org.scalatest.funsuite.AnyFunSuiteLike
    //org.scalatest.funsuite.AsyncFunSuite
    //org.scalatest.funsuite.AsyncFunSuiteLike
    //org.scalatest.funsuite.FixtureAnyFunSuite
    //org.scalatest.funsuite.FixtureAnyFunSuiteLike
    //org.scalatest.funsuite.FixtureAsyncFunSuite
    //org.scalatest.funsuite.FixtureAsyncFunSuiteLike
    //org.scalatest.matchers.AMatcher
    //org.scalatest.matchers.AnMatcher
    //org.scalatest.matchers.BeMatcher
    //org.scalatest.matchers.BePropertyMatchResult
    //org.scalatest.matchers.BePropertyMatcher
    //org.scalatest.matchers.EqualMatchResult
    //org.scalatest.matchers.EqualMatcher
    //org.scalatest.matchers.FailureMessage
    //org.scalatest.matchers.HavePropertyMatchResult
    //org.scalatest.matchers.HavePropertyMatcher
    //org.scalatest.matchers.LazyArg
    org.scalatest.matchers.LazyMessage
    //org.scalatest.matchers.MatchFailed
    org.scalatest.matchers.MatchPatternHelper
    //org.scalatest.matchers.MatchPatternMacro
    //org.scalatest.matchers.MatchResult
    //org.scalatest.matchers.MatchSucceeded
    //org.scalatest.matchers.Matcher
    //org.scalatest.matchers.MatcherProducers
    //org.scalatest.matchers.MatchersHelper
    //org.scalatest.matchers.MidSentenceFailureMessage
    //org.scalatest.matchers.MidSentenceNegatedFailureMessage
    //org.scalatest.matchers.NegatedFailureMessage
    //org.scalatest.matchers.NotEqualMatchResult
    //org.scalatest.matchers.TypeMatcherHelper
    //org.scalatest.matchers.TypeMatcherMacro
    //org.scalatest.matchers.WillMatchersHelper
    //org.scalatest.matchers.dsl.BeWord
    //org.scalatest.matchers.dsl.ContainWord
    org.scalatest.matchers.dsl.DefinedWord
    org.scalatest.matchers.dsl.EmptyWord
    //org.scalatest.matchers.dsl.EndWithWord
    //org.scalatest.matchers.dsl.ExistWord
    //org.scalatest.matchers.dsl.FullyMatchWord
    //org.scalatest.matchers.dsl.HaveWord
    //org.scalatest.matchers.dsl.IncludeWord
    org.scalatest.matchers.dsl.LengthWord
    //org.scalatest.matchers.dsl.MatchPatternWord
    //org.scalatest.matchers.dsl.MatcherFactory1
    //org.scalatest.matchers.dsl.MatcherFactory2
    //org.scalatest.matchers.dsl.MatcherFactory3
    //org.scalatest.matchers.dsl.MatcherFactory4
    //org.scalatest.matchers.dsl.MatcherFactory5
    //org.scalatest.matchers.dsl.MatcherFactory6
    //org.scalatest.matchers.dsl.MatcherFactory7
    //org.scalatest.matchers.dsl.MatcherFactory8
    //org.scalatest.matchers.dsl.MatcherFactory9
    //org.scalatest.matchers.dsl.MatcherWords
    //org.scalatest.matchers.dsl.NoExceptionWord
    //org.scalatest.matchers.dsl.NotWord
    org.scalatest.matchers.dsl.PleaseUseNoExceptionShouldSyntaxInstead
    org.scalatest.matchers.dsl.ReadableWord
    //org.scalatest.matchers.dsl.RegexWithGroups
    //org.scalatest.matchers.dsl.ResultOfATypeInvocation
    org.scalatest.matchers.dsl.ResultOfAWordToAMatcherApplication
    org.scalatest.matchers.dsl.ResultOfAWordToBePropertyMatcherApplication
    org.scalatest.matchers.dsl.ResultOfAWordToSymbolApplication
    org.scalatest.matchers.dsl.ResultOfAllElementsOfApplication
    //org.scalatest.matchers.dsl.ResultOfAllOfApplication
    //org.scalatest.matchers.dsl.ResultOfAnTypeInvocation
    org.scalatest.matchers.dsl.ResultOfAnWordToAnMatcherApplication
    org.scalatest.matchers.dsl.ResultOfAnWordToBePropertyMatcherApplication
    org.scalatest.matchers.dsl.ResultOfAnWordToSymbolApplication
    org.scalatest.matchers.dsl.ResultOfAtLeastOneElementOfApplication
    //org.scalatest.matchers.dsl.ResultOfAtLeastOneOfApplication
    org.scalatest.matchers.dsl.ResultOfAtMostOneElementOfApplication
    //org.scalatest.matchers.dsl.ResultOfAtMostOneOfApplication
    //org.scalatest.matchers.dsl.ResultOfBeThrownBy
    //org.scalatest.matchers.dsl.ResultOfBeWordForAType
    //org.scalatest.matchers.dsl.ResultOfBeWordForAnType
    org.scalatest.matchers.dsl.ResultOfBeWordForNoException
    //org.scalatest.matchers.dsl.ResultOfContainWord
    org.scalatest.matchers.dsl.ResultOfDefinedAt
    //org.scalatest.matchers.dsl.ResultOfGreaterThanComparison
    //org.scalatest.matchers.dsl.ResultOfGreaterThanOrEqualToComparison
    //org.scalatest.matchers.dsl.ResultOfInOrderApplication
    org.scalatest.matchers.dsl.ResultOfInOrderElementsOfApplication
    //org.scalatest.matchers.dsl.ResultOfInOrderOnlyApplication
    org.scalatest.matchers.dsl.ResultOfKeyWordApplication
    //org.scalatest.matchers.dsl.ResultOfLengthWordApplication
    //org.scalatest.matchers.dsl.ResultOfLessThanComparison
    //org.scalatest.matchers.dsl.ResultOfLessThanOrEqualToComparison
    //org.scalatest.matchers.dsl.ResultOfMessageWordApplication
    org.scalatest.matchers.dsl.ResultOfNoElementsOfApplication
    //org.scalatest.matchers.dsl.ResultOfNoneOfApplication
    //org.scalatest.matchers.dsl.ResultOfNotExist
    //org.scalatest.matchers.dsl.ResultOfNotWordForAny
    org.scalatest.matchers.dsl.ResultOfOfTypeInvocation
    org.scalatest.matchers.dsl.ResultOfOneElementOfApplication
    //org.scalatest.matchers.dsl.ResultOfOneOfApplication
    //org.scalatest.matchers.dsl.ResultOfOnlyApplication
    //org.scalatest.matchers.dsl.ResultOfRegexWordApplication
    //org.scalatest.matchers.dsl.ResultOfSizeWordApplication
    org.scalatest.matchers.dsl.ResultOfTheSameElementsAsApplication
    org.scalatest.matchers.dsl.ResultOfTheSameElementsInOrderAsApplication
    org.scalatest.matchers.dsl.ResultOfTheSameInstanceAsApplication
    //org.scalatest.matchers.dsl.ResultOfTheTypeInvocation
    org.scalatest.matchers.dsl.ResultOfThrownByApplication
    org.scalatest.matchers.dsl.ResultOfValueWordApplication
    org.scalatest.matchers.dsl.SizeWord
    org.scalatest.matchers.dsl.SortedWord
    //org.scalatest.matchers.dsl.StartWithWord
    org.scalatest.matchers.dsl.WritableWord
    //org.scalatest.matchers.must.CompileMacro
    //org.scalatest.matchers.must.Matchers
    //org.scalatest.matchers.must.TypeMatcherMacro
    //org.scalatest.matchers.should.CompileMacro
    //org.scalatest.matchers.should.Matchers
    //org.scalatest.matchers.should.TypeMatcherMacro
    //org.scalatest.prop.Configuration
    //org.scalatest.prop.Seed
    org.scalatest.prop.TableDrivenPropertyChecks
    //org.scalatest.prop.TableFor1
    //org.scalatest.prop.TableFor10
    //org.scalatest.prop.TableFor11
    //org.scalatest.prop.TableFor12
    //org.scalatest.prop.TableFor13
    //org.scalatest.prop.TableFor14
    //org.scalatest.prop.TableFor15
    //org.scalatest.prop.TableFor16
    //org.scalatest.prop.TableFor17
    //org.scalatest.prop.TableFor18
    //org.scalatest.prop.TableFor19
    //org.scalatest.prop.TableFor2
    //org.scalatest.prop.TableFor20
    //org.scalatest.prop.TableFor21
    //org.scalatest.prop.TableFor22
    //org.scalatest.prop.TableFor3
    //org.scalatest.prop.TableFor4
    //org.scalatest.prop.TableFor5
    //org.scalatest.prop.TableFor6
    //org.scalatest.prop.TableFor7
    //org.scalatest.prop.TableFor8
    //org.scalatest.prop.TableFor9
    org.scalatest.prop.Tables
    org.scalatest.prop.Whenever
    //org.scalatest.propspec.AnyPropSpec
    //org.scalatest.propspec.AnyPropSpecLike
    //org.scalatest.propspec.FixtureAnyPropSpec
    //org.scalatest.propspec.FixtureAnyPropSpecLike
    //org.scalatest.refspec.RefSpec
    //org.scalatest.refspec.RefSpecLike
    org.scalatest.tagobjects.CPU
    org.scalatest.tagobjects.ChromeBrowser
    org.scalatest.tagobjects.Disk
    org.scalatest.tagobjects.FirefoxBrowser
    org.scalatest.tagobjects.HtmlUnitBrowser
    org.scalatest.tagobjects.InternetExplorerBrowser
    org.scalatest.tagobjects.Network
    org.scalatest.tagobjects.Retryable
    org.scalatest.tagobjects.SafariBrowser
    org.scalatest.tagobjects.Slow
    //org.scalatest.time.Day
    //org.scalatest.time.Days
    //org.scalatest.time.Hour
    //org.scalatest.time.Hours
    //org.scalatest.time.Microsecond
    //org.scalatest.time.Microseconds
    //org.scalatest.time.Millis
    //org.scalatest.time.Millisecond
    //org.scalatest.time.Milliseconds
    //org.scalatest.time.Minute
    //org.scalatest.time.Minutes
    //org.scalatest.time.Nanosecond
    //org.scalatest.time.Nanoseconds
    org.scalatest.time.Now
    //org.scalatest.time.Second
    //org.scalatest.time.Seconds
    //org.scalatest.time.Span
    //org.scalatest.time.SpanSugar
    org.scalatest.time.Units
    //org.scalatest.tools.AboutJDialog
    org.scalatest.tools.AnsiColor
    //org.scalatest.tools.AnsiCyan
    //org.scalatest.tools.AnsiGreen
    //org.scalatest.tools.AnsiRed
    //org.scalatest.tools.AnsiReset
    //org.scalatest.tools.AnsiYellow
    //org.scalatest.tools.ArgsParser
    //org.scalatest.tools.ColorBar
    //org.scalatest.tools.ConcurrentConfig
    //org.scalatest.tools.ConcurrentDistributor
    //org.scalatest.tools.CustomReporterConfiguration
    //org.scalatest.tools.DashboardReporter
    //org.scalatest.tools.DashboardReporterConfiguration
    //org.scalatest.tools.DiscoverySuite
    //org.scalatest.tools.DistributedTestRunnerSuite
    //org.scalatest.tools.Durations
    //org.scalatest.tools.EventHolder
    org.scalatest.tools.EventHolderDefaultListModel
    org.scalatest.tools.EventHolderJList
    //org.scalatest.tools.EventHolderListCellRenderer
    //org.scalatest.tools.EventToPresent
    org.scalatest.tools.FileReporter
    //org.scalatest.tools.FileReporterConfiguration
    //org.scalatest.tools.FilterAlertProvided
    //org.scalatest.tools.FilterInfoProvided
    //org.scalatest.tools.FilterMarkupProvided
    //org.scalatest.tools.FilterNoteProvided
    //org.scalatest.tools.FilterReporter
    //org.scalatest.tools.FilterScopeClosed
    //org.scalatest.tools.FilterScopeOpened
    //org.scalatest.tools.FilterScopePending
    //org.scalatest.tools.FilterSuiteCompleted
    //org.scalatest.tools.FilterSuiteStarting
    //org.scalatest.tools.FilterTestCanceled
    //org.scalatest.tools.FilterTestIgnored
    //org.scalatest.tools.FilterTestPending
    //org.scalatest.tools.FilterTestStarting
    //org.scalatest.tools.FilterTestSucceeded
    //org.scalatest.tools.Fragment
    //org.scalatest.tools.GraphicReporterConfiguration
    //org.scalatest.tools.HtmlReporterConfiguration
    //org.scalatest.tools.IconEmbellishedListCellRenderer
    //org.scalatest.tools.JUnitXmlReporter
    //org.scalatest.tools.JunitXmlReporterConfiguration
    //org.scalatest.tools.JvmArg
    //org.scalatest.tools.Memento
    //org.scalatest.tools.MemoryReporter
    //org.scalatest.tools.MemoryReporterConfiguration
    //org.scalatest.tools.NameValuePair
    org.scalatest.tools.NarrowJOptionPane
    //org.scalatest.tools.NestedSuiteElement
    //org.scalatest.tools.NestedSuiteParam
    //org.scalatest.tools.PackageElement
    //org.scalatest.tools.ParsedArgs
    //org.scalatest.tools.PresentAlertProvided
    //org.scalatest.tools.PresentAllDurations
    //org.scalatest.tools.PresentDiscoveryCompleted
    //org.scalatest.tools.PresentDiscoveryStarting
    //org.scalatest.tools.PresentFilePathname
    //org.scalatest.tools.PresentFullStackTraces
    //org.scalatest.tools.PresentInfoProvided
    //org.scalatest.tools.PresentJson
    //org.scalatest.tools.PresentMarkupProvided
    //org.scalatest.tools.PresentNoteProvided
    //org.scalatest.tools.PresentReminderWithFullStackTraces
    //org.scalatest.tools.PresentReminderWithShortStackTraces
    //org.scalatest.tools.PresentReminderWithoutCanceledTests
    //org.scalatest.tools.PresentReminderWithoutStackTraces
    //org.scalatest.tools.PresentRunAborted
    //org.scalatest.tools.PresentRunCompleted
    //org.scalatest.tools.PresentRunStarting
    //org.scalatest.tools.PresentRunStopped
    //org.scalatest.tools.PresentScopeClosed
    //org.scalatest.tools.PresentScopeOpened
    //org.scalatest.tools.PresentScopePending
    //org.scalatest.tools.PresentShortStackTraces
    //org.scalatest.tools.PresentSuiteAborted
    //org.scalatest.tools.PresentSuiteCompleted
    //org.scalatest.tools.PresentSuiteStarting
    //org.scalatest.tools.PresentTestCanceled
    //org.scalatest.tools.PresentTestFailed
    //org.scalatest.tools.PresentTestIgnored
    //org.scalatest.tools.PresentTestPending
    //org.scalatest.tools.PresentTestStarting
    //org.scalatest.tools.PresentTestSucceeded
    //org.scalatest.tools.PresentUnformatted
    //org.scalatest.tools.PresentWithoutColor
    //org.scalatest.tools.PrettyPrinter
    //org.scalatest.tools.PrintReporter
    //org.scalatest.tools.ProgressBarPanel
    org.scalatest.tools.ReStoppingState
    //org.scalatest.tools.ReadyState
    org.scalatest.tools.ReporterConfigParam
    org.scalatest.tools.ReporterConfiguration
    //org.scalatest.tools.ReporterConfigurations
    //org.scalatest.tools.ReporterElement
    //org.scalatest.tools.ReporterFactory
    org.scalatest.tools.RerunningState
    org.scalatest.tools.RunDoneListener
    //org.scalatest.tools.Runner
    org.scalatest.tools.RunnerGUI
    org.scalatest.tools.RunnerGUIState
    //org.scalatest.tools.RunnerJFrame
    org.scalatest.tools.RunningState
    //org.scalatest.tools.RunpathUrl
    org.scalatest.tools.SbtDispatchReporter
    //org.scalatest.tools.ScalaTestAntTask
    //org.scalatest.tools.SlowpokeConfig
    //org.scalatest.tools.SocketReporter
    //org.scalatest.tools.SocketReporterConfiguration
    //org.scalatest.tools.StandardErrReporter
    //org.scalatest.tools.StandardErrReporterConfiguration
    //org.scalatest.tools.StandardOutReporter
    //org.scalatest.tools.StandardOutReporterConfiguration
    //org.scalatest.tools.StatusJPanel
    org.scalatest.tools.StoppingState
    //org.scalatest.tools.StringReporter
    //org.scalatest.tools.StyleElement
    //org.scalatest.tools.SuiteConfig
    //org.scalatest.tools.SuiteDiscoveryHelper
    //org.scalatest.tools.SuiteElement
    //org.scalatest.tools.SuiteParam
    //org.scalatest.tools.SuiteResult
    //org.scalatest.tools.SuiteResultHolder
    //org.scalatest.tools.SuiteRunner
    //org.scalatest.tools.SuiteSortingReporter
    //org.scalatest.tools.TestElement
    //org.scalatest.tools.TestSortingReporter
    //org.scalatest.tools.TestSpec
    org.scalatest.tools.TestSpecificReporter
    //org.scalatest.tools.TestsfileElement
    //org.scalatest.tools.TextElement
    //org.scalatest.tools.Utils
    //org.scalatest.tools.XmlReporter
    //org.scalatest.tools.XmlReporterConfiguration
    //org.scalatest.tools.XmlSocketReporter
    //org.scalatest.tools.XmlSocketReporterConfiguration
    //org.scalatest.tools.XmlUtility
    //org.scalatest.verbs.ArrayWrapper
    org.scalatest.verbs.BehaveWord
    //org.scalatest.verbs.CanVerb
    org.scalatest.verbs.CompileWord
    //org.scalatest.verbs.MustVerb
    org.scalatest.verbs.ResultOfAfterWordApplication
    org.scalatest.verbs.ResultOfStringPassedToVerb
    org.scalatest.verbs.ResultOfTaggedAsInvocation
    //org.scalatest.verbs.ShouldVerb
    org.scalatest.verbs.StringVerbBehaveLikeInvocation
    org.scalatest.verbs.StringVerbBlockRegistration
    org.scalatest.verbs.StringVerbStringInvocation
    org.scalatest.verbs.SubjectWithAfterWordRegistration
    org.scalatest.verbs.TypeCheckWord
    //org.scalatest.verbs.WillVerb
    //org.scalatest.wordspec.AnyWordSpec
    //org.scalatest.wordspec.AnyWordSpecLike
    org.scalatest.wordspec.AsyncWordSpec
    //org.scalatest.wordspec.AsyncWordSpecLike
    //org.scalatest.wordspec.FixtureAnyWordSpec
    //org.scalatest.wordspec.FixtureAnyWordSpecLike
    org.scalatest.wordspec.FixtureAsyncWordSpec
    //org.scalatest.wordspec.FixtureAsyncWordSpecLike
  """)
}