package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.corpus.scala3.ZioTest
import org.junit.Test

class ZioSemanticTest extends SemanticTestBase(ZioTest) {
  @Test def test(): Unit = doTest("""
    //zio.=!=
    //zio.BuildFromCompat
    //zio.BuildInfo
    //zio.Cached
    //zio.CanFail
    //zio.CanFailLowPriority
    //zio.CancelableFuture
    //zio.Cause
    //zio.Chunk
    //zio.ChunkBuilder
    //zio.ChunkFactory
    //zio.ChunkLike
    //zio.ChunkPlatformSpecific
    //zio.Clock
    //zio.ClockPlatformSpecific
    //zio.ClockSyntaxPlatformSpecific
    //zio.Config
    //zio.ConfigProvider
    //zio.Console
    //zio.DefaultServices
    //zio.Dequeue
    //zio.Differ
    //zio.Duration
    zio.DurationModule
    //zio.DurationOps
    //zio.DurationSyntax
    zio.EitherCompat
    //zio.Enqueue
    //zio.ExecutionStrategy
    //zio.Executor
    //zio.ExecutorPlatformSpecific
    //zio.Exit
    //zio.ExitCode
    //zio.Experimental
    //zio.Fiber
    //zio.FiberFailure
    //zio.FiberId
    //zio.FiberPlatformSpecific
    //zio.FiberRef
    //zio.FiberRefs
    //zio.FunctionConstructor
    //zio.FutureTransformCompat
    //zio.HasNoScope
    //zio.HasNoScopeCompanionVersionSpecific
    //zio.HasNoScopeMacro
    //zio.Hub
    //zio.InterruptStatus
    //zio.IntersectionTypeCompat
    //zio.IsReloadable
    //zio.IsReloadableMacros
    //zio.IsReloadableVersionSpecific
    //zio.IsSubtypeOfError
    //zio.IsSubtypeOfOutput
    //zio.LogAnnotation
    //zio.LogLevel
    //zio.LogSpan
    //zio.NonEmptyChunk
    //zio.NonEmptyOps
    zio.NonEmptySeq
    //zio.Promise
    //zio.ProvideSomePartiallyApplied
    //zio.Queue
    zio.QueuePlatformSpecific
    //zio.Random
    //zio.Ref
    //zio.Reloadable
    //zio.Runtime
    //zio.RuntimeFlag
    //zio.RuntimeFlags
    //zio.RuntimePlatformSpecific
    //zio.Schedule
    //zio.Scheduler
    //zio.Scope
    //zio.ScopedRef
    //zio.Semaphore
    //zio.StackTrace
    //zio.Supervisor
    //zio.System
    //zio.SystemPlatformSpecific
    //zio.TagMacros
    //zio.TagVersionSpecific
    //zio.TaskPlatformSpecific
    //zio.ThreadLocalBridge
    //zio.Trace
    //zio.Unsafe
    //zio.UnsafeVersionSpecific
    zio.Unzippable
    zio.UnzippableLowPriority1
    zio.UnzippableLowPriority2
    zio.UnzippableLowPriority3
    zio.UpdateRuntimeFlagsWithinPlatformSpecific
    //zio.VersionSpecific
    //zio.WirePartiallyApplied
    //zio.WireSomePartiallyApplied
    //zio.ZEnvironment
    //zio.ZIO
    //zio.ZIOApp
    //zio.ZIOAppArgs
    //zio.ZIOAppDefault
    //zio.ZIOAppPlatformSpecific
    //zio.ZIOAppVersionSpecific
    //zio.ZIOAppVersionSpecificMacros
    //zio.ZIOAspect
    //zio.ZIOCompanionPlatformSpecific
    //zio.ZIOCompanionVersionSpecific
    //zio.ZIOFunctionConstructor
    //zio.ZIOPlatformSpecific
    //zio.ZIOPlatformSpecificJVM
    //zio.ZIOVersionSpecific
    //zio.ZInputStream
    //zio.ZKeyedPool
    //zio.ZLayer
    //zio.ZLayerAspect
    //zio.ZLayerCompanionVersionSpecific
    //zio.ZLayerVersionSpecific
    //zio.ZLogger
    //zio.ZOutputStream
    //zio.ZPool
    //zio.ZState
    //zio.Zippable
    //zio.ZippableLowPriority1
    zio.ZippableLowPriority2
    zio.ZippableLowPriority3
    //zio.internal.Blocking
    //zio.internal.BoundedHubArb
    //zio.internal.BoundedHubPow2
    //zio.internal.BoundedHubSingle
    //zio.internal.ConcurrentWeakHashSet
    //zio.internal.DefaultExecutors
    zio.internal.ExecutionMetrics
    //zio.internal.FastList
    //zio.internal.FiberMessage
    //zio.internal.FiberRenderer
    zio.internal.FiberRunnable
    //zio.internal.FiberRuntime
    //zio.internal.FiberScope
    //zio.internal.Hub
    //zio.internal.IsFatal
    //zio.internal.LinkedQueue
    //zio.internal.LoomSupport
    //zio.internal.MutableConcurrentQueue
    //zio.internal.MutableSetCompat
    //zio.internal.NamedThreadFactory
    //zio.internal.OneElementConcurrentQueue
    //zio.internal.OneShot
    //zio.internal.PartitionedLinkedQueue
    //zio.internal.PartitionedRingBuffer
    //zio.internal.PinchableArray
    zio.internal.Platform
    //zio.internal.PlatformSpecific
    //zio.internal.RingBuffer
    //zio.internal.RingBufferArb
    //zio.internal.RingBufferPow2
    //zio.internal.Signal
    //zio.internal.SingleThreadedRingBuffer
    //zio.internal.SpecializationHelpers
    //zio.internal.Stack
    //zio.internal.StackTraceBuilder
    //zio.internal.Sync
    //zio.internal.TerminalRendering
    //zio.internal.UnboundedHub
    zio.internal.UniqueKey
    //zio.internal.UpdateOrderLinkedMap
    //zio.internal.WeakConcurrentBag
    //zio.internal.WeakConcurrentBagGc
    //zio.internal.ZScheduler
    //zio.internal.ansi
    //zio.internal.macros.DummyK
    //zio.internal.macros.Graph
    //zio.internal.macros.GraphError
    //zio.internal.macros.LayerBuilder
    //zio.internal.macros.LayerMacroUtils
    //zio.internal.macros.LayerMacros
    //zio.internal.macros.LayerTree
    //zio.internal.macros.Node
    //zio.internal.macros.ProvideMethod
    //zio.internal.macros.RemainderMethod
    //zio.internal.macros.RenderedGraph
    //zio.internal.macros.StringUtils
    //zio.internal.macros.ZLayerDerivationMacros
    zio.internal.metrics.AddersVersionSpecific
    //zio.internal.metrics.AtomicDouble
    zio.internal.metrics.ConcurrentMetricHooks
    //zio.internal.metrics.ConcurrentMetricHooksPlatformSpecific
    //zio.internal.metrics.ConcurrentMetricRegistry
    //zio.internal.metrics.MetricEventType
    //zio.internal.metrics.MetricHook
    //zio.internal.stacktracer.BuildInfo
    //zio.internal.stacktracer.Macros
    //zio.internal.stacktracer.ParsedTrace
    //zio.internal.stacktracer.SourceLocation
    //zio.internal.stacktracer.Tracer
    //zio.internal.stacktracer.TracerUtils
    //zio.interop.javaz
    //zio.metrics.Metric
    zio.metrics.MetricClient
    //zio.metrics.MetricKey
    //zio.metrics.MetricKeyType
    //zio.metrics.MetricLabel
    zio.metrics.MetricListener
    //zio.metrics.MetricPair
    //zio.metrics.MetricState
    //zio.metrics.Metrics
    //zio.metrics.PollingMetric
    //zio.metrics.jvm.BufferPools
    //zio.metrics.jvm.ClassLoading
    //zio.metrics.jvm.DefaultJvmMetrics
    //zio.metrics.jvm.GarbageCollector
    //zio.metrics.jvm.JvmMetricsSchedule
    //zio.metrics.jvm.MemoryAllocation
    //zio.metrics.jvm.MemoryPools
    //zio.metrics.jvm.Standard
    //zio.metrics.jvm.Thread
    //zio.metrics.jvm.VersionInfo
    zio.stacktracer.DisableAutoTrace
    //zio.stacktracer.TracingImplicits
    //zio.stm.STM
    //zio.stm.TArray
    //zio.stm.TDequeue
    //zio.stm.TEnqueue
    //zio.stm.THub
    //zio.stm.TMap
    //zio.stm.TPriorityQueue
    //zio.stm.TPromise
    //zio.stm.TQueue
    //zio.stm.TRandom
    //zio.stm.TReentrantLock
    //zio.stm.TRef
    //zio.stm.TSemaphore
    //zio.stm.TSet
    //zio.stm.ZSTM
    //zio.stm.ZSTMLockSupport
    //zio.stm.ZSTMUtils
    //zio.stream.BuildInfo
    //zio.stream.Deflate
    //zio.stream.Gunzip
    //zio.stream.Gzip
    //zio.stream.Inflate
    //zio.stream.SubscriptionRef
    //zio.stream.Take
    //zio.stream.ZChannel
    //zio.stream.ZPipeline
    //zio.stream.ZPipelinePlatformSpecificConstructors
    //zio.stream.ZSink
    //zio.stream.ZSinkPlatformSpecificConstructors
    //zio.stream.ZStream
    //zio.stream.ZStreamAspect
    //zio.stream.ZStreamPlatformSpecificConstructors
    //zio.stream.ZStreamProvideMacro
    //zio.stream.ZStreamVersionSpecific
    //zio.stream.compression.CompressionException
    //zio.stream.compression.CompressionLevel
    //zio.stream.compression.CompressionParameters
    //zio.stream.compression.CompressionStrategy
    //zio.stream.compression.Deflate
    //zio.stream.compression.FlushMode
    //zio.stream.compression.Gunzipper
    //zio.stream.compression.Gzipper
    //zio.stream.encoding.EncodingException
    zio.stream.internal.AsyncInputConsumer
    zio.stream.internal.AsyncInputProducer
    //zio.stream.internal.ChannelExecutor
    //zio.stream.internal.CharacterSet
    //zio.stream.internal.SingleProducerAsyncInput
    //zio.stream.internal.ZInputStream
    //zio.stream.internal.ZReader
  """)
}