/* The following code was generated by JFlex 1.4.1 on 27.09.06 18:43 */

package org.jetbrains.plugins.scala.lang.lexer;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;
import java.util.*;
import java.lang.reflect.Field;
import org.jetbrains.annotations.NotNull;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 27.09.06 18:43 from the specification file
 * <tt>scala.flex</tt>
 */
public class _ScalaLexer implements FlexLexer, ScalaTokenTypes {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int IN_XML_STATE = 4;
  public static final int IN_STRING_STATE = 3;
  public static final int IN_LINE_COMMENT_STATE = 2;
  public static final int IN_BLOCK_COMMENT_STATE = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\0\1\50\1\0\1\51\1\47\22\0\1\32\1\0\1\46"+
    "\4\0\1\45\1\60\1\61\1\53\1\42\1\45\1\42\1\40\1\52"+
    "\1\34\7\36\2\35\1\0\1\45\5\0\3\37\1\43\1\41\1\43"+
    "\5\44\1\33\16\44\1\54\1\0\1\55\1\0\1\44\1\0\1\1"+
    "\1\2\1\6\1\12\1\7\1\13\1\30\1\10\1\17\1\25\1\27"+
    "\1\11\1\21\1\16\1\14\1\22\1\31\1\5\1\3\1\4\1\24"+
    "\1\26\1\23\1\15\1\20\1\44\1\56\1\45\1\57\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\22\1\1\2\2\3\2\4\1\5\1\1\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\3\14\2\15\1\16"+
    "\1\17\15\1\1\20\7\1\1\21\7\1\1\0\1\3"+
    "\1\22\1\0\1\3\1\0\1\22\1\0\1\23\1\24"+
    "\4\1\1\25\13\1\1\26\1\1\1\27\3\1\1\30"+
    "\10\1\1\31\1\32\1\22\1\0\1\3\1\0\4\1"+
    "\1\33\1\1\1\34\1\35\2\1\1\36\2\1\1\37"+
    "\5\1\1\40\14\1\1\41\1\42\1\43\2\1\1\44"+
    "\1\45\1\1\1\46\1\47\4\1\1\50\1\51\3\1"+
    "\1\52\1\53\1\1\1\54\1\55\3\1\1\56\2\1"+
    "\1\57\5\1\1\60\1\61\2\1\1\62\1\1\1\63"+
    "\1\64\1\65\1\66\1\67\1\1\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee"+
    "\0\u0320\0\u0352\0\u0384\0\u03b6\0\u03e8\0\u041a\0\u044c\0\310"+
    "\0\u047e\0\u04b0\0\u04e2\0\310\0\u0514\0\u0546\0\372\0\372"+
    "\0\372\0\372\0\310\0\310\0\310\0\u0578\0\u05aa\0\u05dc"+
    "\0\310\0\310\0\310\0\u060e\0\u0640\0\u0672\0\u06a4\0\u06d6"+
    "\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834\0\u0866"+
    "\0\u015e\0\u0898\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992\0\u09c4"+
    "\0\u015e\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22"+
    "\0\u0b54\0\310\0\310\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e"+
    "\0\372\0\372\0\u0c80\0\u0cb2\0\u0ce4\0\u0d16\0\u015e\0\u0d48"+
    "\0\u0d7a\0\u0dac\0\u0dde\0\u0e10\0\u0e42\0\u0e74\0\u0ea6\0\u0ed8"+
    "\0\u0f0a\0\u0f3c\0\u015e\0\u0f6e\0\u015e\0\u0fa0\0\u0fd2\0\u1004"+
    "\0\u015e\0\u1036\0\u1068\0\u109a\0\u10cc\0\u10fe\0\u1130\0\u1162"+
    "\0\u1194\0\u015e\0\u015e\0\u11c6\0\u11f8\0\u122a\0\u125c\0\u128e"+
    "\0\u12c0\0\u12f2\0\u1324\0\u015e\0\u1356\0\u015e\0\u015e\0\u1388"+
    "\0\u13ba\0\u015e\0\u13ec\0\u141e\0\u015e\0\u1450\0\u1482\0\u14b4"+
    "\0\u14e6\0\u1518\0\u015e\0\u154a\0\u157c\0\u15ae\0\u15e0\0\u1612"+
    "\0\u1644\0\u1676\0\u16a8\0\u16da\0\310\0\u170c\0\u173e\0\u015e"+
    "\0\u015e\0\u015e\0\u1770\0\u17a2\0\u015e\0\u015e\0\u17d4\0\u015e"+
    "\0\u1806\0\u1838\0\u186a\0\u189c\0\u18ce\0\u015e\0\u015e\0\u1900"+
    "\0\u1932\0\u1964\0\u015e\0\u015e\0\u1996\0\u015e\0\u015e\0\u19c8"+
    "\0\u19fa\0\u1a2c\0\u015e\0\u1a5e\0\u1a90\0\u015e\0\u1ac2\0\u1af4"+
    "\0\u1b26\0\u1b58\0\u1b8a\0\u015e\0\u015e\0\u1bbc\0\u1bee\0\u015e"+
    "\0\u1c20\0\u015e\0\u015e\0\u015e\0\u015e\0\u015e\0\u1c52\0\u015e";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\2\10\1\16\1\17\1\20\1\10\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\2\10\1\27\3\10\1\30\1\10"+
    "\1\31\2\32\1\10\1\33\1\10\1\6\2\10\1\34"+
    "\1\35\3\6\1\36\1\6\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\47\45\1\46\3\45\1\47\55\45\1\50"+
    "\2\51\10\45\46\52\1\53\1\52\1\0\11\52\62\0"+
    "\32\6\1\0\1\6\3\0\1\6\1\0\4\6\2\0"+
    "\11\6\2\0\1\6\1\10\1\54\27\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\31\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\6\10"+
    "\1\56\14\10\1\57\5\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\4\10\1\60\2\10\1\61\7\10\1\62\11\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\6\10\1\63\22\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\1\64\7\10\1\65\20\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\10\10\1\66\3\10\1\67\14\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\6\10\1\70\4\10\1\71\15\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\1\72\12\10\1\73\2\10"+
    "\1\74\12\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\1\10\1\75"+
    "\23\10\1\76\3\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\6\10"+
    "\1\77\14\10\1\100\5\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\12\10\1\101\5\10\1\102\10\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\16\10\1\103\12\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\1\104\30\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\1\105\3\10"+
    "\1\106\24\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\7\10\1\107"+
    "\21\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\1\110\30\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\11\0\1\111\1\0\1\112\2\113\1\0\1\114"+
    "\15\0\1\112\1\115\1\116\1\115\1\0\1\117\1\111"+
    "\1\0\1\113\25\0\1\111\1\0\1\112\2\113\17\0"+
    "\1\112\3\32\1\0\1\117\1\111\1\0\1\113\52\0"+
    "\3\117\71\0\1\120\13\0\32\6\1\0\1\6\3\0"+
    "\1\6\1\0\4\6\2\0\3\6\1\121\1\122\4\6"+
    "\52\0\1\45\63\0\1\51\57\0\1\51\11\0\1\6"+
    "\2\10\1\123\26\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\3\0\31\55\1\0"+
    "\5\55\1\0\1\55\1\0\2\55\15\0\1\6\1\124"+
    "\30\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\21\10\1\125\7\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\1\126\16\10\1\127\3\10"+
    "\1\130\5\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\4\10\1\131"+
    "\11\10\1\132\12\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\21\10"+
    "\1\133\7\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\3\10\1\134"+
    "\24\10\1\135\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\2\10\1\136"+
    "\1\137\25\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\1\140\30\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\2\10\1\141\26\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\3\10\1\142\25\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\12\10\1\143\16\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\10\10\1\144\20\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\4\10\1\145\24\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\15\10"+
    "\1\146\13\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\24\10\1\147"+
    "\4\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\6\10\1\150\22\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\22\10\1\151\6\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\10\10\1\152\20\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\21\10\1\153\7\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\6\10\1\154\22\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\3\10\1\155\25\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\5\10"+
    "\1\156\23\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\13\10\1\157"+
    "\2\10\1\160\12\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\16\10"+
    "\1\161\12\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\4\10\1\162"+
    "\3\10\1\163\20\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\36\0\3\164\3\0"+
    "\1\165\20\0\2\166\3\0\2\166\2\0\2\166\20\0"+
    "\4\166\1\0\1\166\1\0\1\166\25\0\1\111\1\0"+
    "\1\112\2\113\17\0\1\112\1\115\1\116\1\115\1\0"+
    "\1\117\1\111\1\0\1\113\25\0\1\111\2\0\2\113"+
    "\20\0\3\116\1\0\1\117\1\111\1\0\1\113\25\0"+
    "\1\111\2\0\2\113\20\0\3\117\2\0\1\111\1\0"+
    "\1\113\16\0\46\120\1\167\13\120\1\6\3\10\1\170"+
    "\25\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\10\10\1\171\20\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\6\10\1\172\22\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\16\10\1\173\12\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\6\10\1\174\22\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\13\10\1\175\15\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\2\10\1\176\26\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\6\10"+
    "\1\177\22\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\23\10\1\200"+
    "\5\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\23\10\1\201\5\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\6\10\1\202\22\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\5\10\1\203\23\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\2\10\1\204\26\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\6\10\1\205\22\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\6\10\1\206\22\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\2\10"+
    "\1\207\26\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\1\210\30\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\6\10\1\211\22\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\4\10\1\212\24\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\10\10\1\213\20\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\10\10\1\214\2\10\1\215\15\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\10\10\1\216\20\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\5\10\1\217\23\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\26\10\1\220\2\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\3\10"+
    "\1\221\25\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\25\10\1\222"+
    "\3\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\3\10\1\223\4\10"+
    "\1\224\20\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\14\0\2\113\20\0\3\164"+
    "\4\0\1\113\52\0\3\164\24\0\2\166\3\0\2\166"+
    "\1\0\1\112\2\166\17\0\1\112\4\166\1\0\1\166"+
    "\1\0\1\166\64\0\1\225\13\0\1\6\4\10\1\226"+
    "\24\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\6\10\1\227\22\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\4\10\1\230\24\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\3\10\1\231\25\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\22\10\1\232\6\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\4\10\1\233\24\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\16\10\1\234\12\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\7\10"+
    "\1\235\21\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\2\10\1\236"+
    "\26\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\15\10\1\237\13\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\6\10\1\240\22\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\10\10\1\241\20\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\5\10\1\242\23\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\4\10\1\243\24\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\16\10\1\244\12\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\4\10"+
    "\1\245\24\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\11\10\1\246"+
    "\17\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\7\10\1\247\21\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\1\250\30\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\6\10\1\251\22\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\1\252\30\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\7\10"+
    "\1\253\21\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\6\10\1\254"+
    "\22\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\1\255\30\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\11\10\1\256\17\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\15\10\1\257\13\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\4\10\1\260\24\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\11\10\1\261\17\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\10\10"+
    "\1\262\20\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\3\10\1\263"+
    "\25\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\16\10\1\264\12\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\5\10\1\265\23\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\3\10\1\266\25\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\27\10\1\267\1\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\5\10\1\270\23\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\3\10\1\271\25\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\5\10"+
    "\1\272\23\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\6\10\1\273"+
    "\22\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\2\10\1\274\26\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\17\10\1\275\11\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\11\10\1\276\17\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\16\10\1\277\12\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\6\10\1\300\22\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0\1\6"+
    "\3\10\1\301\25\10\1\0\1\10\3\55\1\10\1\0"+
    "\1\10\1\6\2\10\2\0\11\6\2\0\1\6\6\10"+
    "\1\302\22\10\1\0\1\10\3\55\1\10\1\0\1\10"+
    "\1\6\2\10\2\0\11\6\2\0\1\6\3\10\1\303"+
    "\25\10\1\0\1\10\3\55\1\10\1\0\1\10\1\6"+
    "\2\10\2\0\11\6\2\0\1\6\2\10\1\304\26\10"+
    "\1\0\1\10\3\55\1\10\1\0\1\10\1\6\2\10"+
    "\2\0\11\6\2\0\1\6\6\10\1\305\22\10\1\0"+
    "\1\10\3\55\1\10\1\0\1\10\1\6\2\10\2\0"+
    "\11\6\2\0\1\6\3\10\1\306\25\10\1\0\1\10"+
    "\3\55\1\10\1\0\1\10\1\6\2\10\2\0\11\6"+
    "\2\0\1\6\6\10\1\307\22\10\1\0\1\10\3\55"+
    "\1\10\1\0\1\10\1\6\2\10\2\0\11\6\2\0"+
    "\1\6\11\10\1\310\17\10\1\0\1\10\3\55\1\10"+
    "\1\0\1\10\1\6\2\10\2\0\11\6\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7300];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\10\22\1\1\11\3\1\1\11\6\1\3\11"+
    "\3\1\3\11\35\1\1\0\2\11\1\0\1\1\1\0"+
    "\1\1\1\0\44\1\1\0\1\1\1\0\35\1\1\11"+
    "\63\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[200];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private IElementType process(IElementType type){
        return type;
    }



  public _ScalaLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public _ScalaLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 138) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = zzLexicalState;


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 30: 
          { return process(kCASE);
          }
        case 57: break;
        case 29: 
          { return process(kTYPE);
          }
        case 58: break;
        case 48: 
          { return process(kEXTENDS);
          }
        case 59: break;
        case 31: 
          { return process(kELSE);
          }
        case 60: break;
        case 34: 
          { return process(kTRAIT);
          }
        case 61: break;
        case 38: 
          { return process(kFALSE);
          }
        case 62: break;
        case 33: 
          { return process(kSUPER);
          }
        case 63: break;
        case 7: 
          { return process(tRSQBRACKET);
          }
        case 64: break;
        case 26: 
          { return process(kVAL);
          }
        case 65: break;
        case 45: 
          { return process(kRETURN);
          }
        case 66: break;
        case 2: 
          { return tWHITE_SPACE_IN_LINE;
          }
        case 67: break;
        case 21: 
          { return process(kTRY);
          }
        case 68: break;
        case 37: 
          { return process(kCLASS);
          }
        case 69: break;
        case 4: 
          { return tSTUB;
          }
        case 70: break;
        case 28: 
          { return process(kTHIS);
          }
        case 71: break;
        case 52: 
          { return process(kABSTRACT);
          }
        case 72: break;
        case 16: 
          { return process(kDO);
          }
        case 73: break;
        case 46: 
          { return process(kOBJECT);
          }
        case 74: break;
        case 15: 
          { yybegin(YYINITIAL);
                                            return process(tSTRING);
          }
        case 75: break;
        case 9: 
          { return process(tRBRACE);
          }
        case 76: break;
        case 3: 
          { return process(tINTEGER);
          }
        case 77: break;
        case 13: 
          { yybegin(YYINITIAL);
                                            return process(tCOMMENT);
          }
        case 78: break;
        case 17: 
          { return process(kIF);
          }
        case 79: break;
        case 47: 
          { return process(kIMPORT);
          }
        case 80: break;
        case 49: 
          { return process(kFINALLY);
          }
        case 81: break;
        case 35: 
          { return process(kTHROW);
          }
        case 82: break;
        case 22: 
          { return process(kDEF);
          }
        case 83: break;
        case 50: 
          { return process(kPACKAGE);
          }
        case 84: break;
        case 40: 
          { return process(kYIELD);
          }
        case 85: break;
        case 25: 
          { return process(kVAR);
          }
        case 86: break;
        case 39: 
          { return process(kFINAL);
          }
        case 87: break;
        case 14: 
          { return process(tSTRING);
          }
        case 88: break;
        case 54: 
          { return process(kOVERRIDE);
          }
        case 89: break;
        case 53: 
          { return process(kREQUIRES);
          }
        case 90: break;
        case 18: 
          { return process(tFLOAT);
          }
        case 91: break;
        case 32: 
          { return process(kNULL);
          }
        case 92: break;
        case 5: 
          { yybegin(IN_STRING_STATE);
                                            return process(tSTRING);
          }
        case 93: break;
        case 23: 
          { return process(kFOR);
          }
        case 94: break;
        case 55: 
          { return process(kIMPLICIT);
          }
        case 95: break;
        case 42: 
          { return process(kWHITH);
          }
        case 96: break;
        case 10: 
          { return process(tLBRACKET);
          }
        case 97: break;
        case 44: 
          { return process(kSEALED);
          }
        case 98: break;
        case 24: 
          { return process(kNEW);
          }
        case 99: break;
        case 43: 
          { return process(kWHILE);
          }
        case 100: break;
        case 19: 
          { yybegin(IN_LINE_COMMENT_STATE);
                                            return process(tCOMMENT);
          }
        case 101: break;
        case 51: 
          { return process(kPRIVATE);
          }
        case 102: break;
        case 56: 
          { return process(kPROTECTED);
          }
        case 103: break;
        case 8: 
          { return process(tLBRACE);
          }
        case 104: break;
        case 1: 
          { return process(tIDENTIFIER);
          }
        case 105: break;
        case 6: 
          { return process(tLSQBRACKET);
          }
        case 106: break;
        case 11: 
          { return process(tRBRACKET);
          }
        case 107: break;
        case 12: 
          { return process(tCOMMENT);
          }
        case 108: break;
        case 20: 
          { yybegin(IN_BLOCK_COMMENT_STATE);
                                            return process(tCOMMENT);
          }
        case 109: break;
        case 36: 
          { return process(kCATCH);
          }
        case 110: break;
        case 27: 
          { return process(kTRUE);
          }
        case 111: break;
        case 41: 
          { return process(kMATCH);
          }
        case 112: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
