package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_0.scala_2_13

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestSelectedTests

class Scalatest_3_0_Scala_2_13_SelectedTestsTest extends Scalatest_3_0_Scala_2_13_Base
  with ScalaTestSelectedTests
