package org.jetbrains.plugins.scala
package testingSupport.scalatest.scala2_10.scalatest2_2_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.ScalaTestSelectedTests

class Scalatest2_10_2_2_1_SelectedTestsTest extends Scalatest2_10_2_2_1_Base with ScalaTestSelectedTests
