package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_10.scalatest2_2_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.ScalaTestWholeSuiteTest

class Scalatest2_10_2_2_1_WholeSuiteTest extends Scalatest2_10_2_2_1_Base with ScalaTestWholeSuiteTest
