package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_10.scalatest2_2_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.ScalaTestDuplicateConfigTest

class Scalatest2_10_2_2_1_DuplicateConfigTest extends Scalatest2_10_2_2_1_Base with ScalaTestDuplicateConfigTest
