package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_10.scalatest2_2_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.NestedSameNamesTest

class Scalatest2_10_2_2_1_NestedSameNamesTest extends Scalatest2_10_2_2_1_Base with NestedSameNamesTest
