package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.scalaVersion
import org.junit.Test

class AkkaHttpSemanticTest extends SemanticTestBase("com.typesafe.akka" %% "akka-http" % "10.5.3", "com.typesafe.akka" %% "akka-stream" % "2.7.0" /*% Provided*/)("akka.http") {
//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    //akka.http.DefaultParsingErrorHandler
    akka.http.ParsingErrorHandler
    //akka.http.ccompat.MapHelpers
    akka.http.ccompat.QuerySeqOptimized
    akka.http.ccompat.pre213
    akka.http.ccompat.since213
    //akka.http.impl.engine.HttpConnectionIdleTimeoutBidi
    //akka.http.impl.engine.HttpIdleTimeoutException
    //akka.http.impl.engine.client.HttpsProxyGraphStage
    //akka.http.impl.engine.client.OutgoingConnectionBlueprint
    akka.http.impl.engine.client.PoolFlow
    //akka.http.impl.engine.client.PoolId
    //akka.http.impl.engine.client.PoolInterface
    //akka.http.impl.engine.client.PoolMaster
    //akka.http.impl.engine.client.PoolMasterActor
    akka.http.impl.engine.client.ProxyConnectionFailedException
    //akka.http.impl.engine.client.pool.NewHostConnectionPool
    akka.http.impl.engine.client.pool.SlotContext
    //akka.http.impl.engine.client.pool.SlotState
    akka.http.impl.engine.http2.BufferedOutlet
    akka.http.impl.engine.http2.BufferedOutletExtended
    //akka.http.impl.engine.http2.ByteFlag
    akka.http.impl.engine.http2.ConfigurablePing
    //akka.http.impl.engine.http2.FrameEvent
    //akka.http.impl.engine.http2.FrameLogger
    akka.http.impl.engine.http2.GenericOutlet
    //akka.http.impl.engine.http2.GenericOutletSupport
    //akka.http.impl.engine.http2.Http2
    //akka.http.impl.engine.http2.Http2AlpnSupport
    //akka.http.impl.engine.http2.Http2Blueprint
    //akka.http.impl.engine.http2.Http2ClientDemux
    //akka.http.impl.engine.http2.Http2Compliance
    //akka.http.impl.engine.http2.Http2Demux
    //akka.http.impl.engine.http2.Http2Ext
    //akka.http.impl.engine.http2.Http2JDKAlpnSupport
    akka.http.impl.engine.http2.Http2Multiplexer
    //akka.http.impl.engine.http2.Http2MultiplexerSupport
    //akka.http.impl.engine.http2.Http2Protocol
    akka.http.impl.engine.http2.Http2ServerDemux
    //akka.http.impl.engine.http2.Http2StreamHandling
    //akka.http.impl.engine.http2.Http2SubStream
    //akka.http.impl.engine.http2.HttpMessageRendering
    //akka.http.impl.engine.http2.IncomingFlowController
    //akka.http.impl.engine.http2.MessageRendering
    akka.http.impl.engine.http2.NoOpTelemetry
    //akka.http.impl.engine.http2.OutgoingConnectionBuilderImpl
    akka.http.impl.engine.http2.PriorityNode
    //akka.http.impl.engine.http2.PriorityTree
    //akka.http.impl.engine.http2.ProtocolSwitch
    akka.http.impl.engine.http2.PullFrameResult
    //akka.http.impl.engine.http2.RequestErrorFlow
    //akka.http.impl.engine.http2.RequestParsing
    //akka.http.impl.engine.http2.RequestRendering
    //akka.http.impl.engine.http2.ResponseRendering
    //akka.http.impl.engine.http2.StreamPrioritizer
    akka.http.impl.engine.http2.TelemetryAttributes
    //akka.http.impl.engine.http2.TelemetrySpi
    //akka.http.impl.engine.http2.client.PersistentConnection
    //akka.http.impl.engine.http2.client.ResponseParsing
    //akka.http.impl.engine.http2.framing.FrameRenderer
    //akka.http.impl.engine.http2.framing.Http2FrameParsing
    //akka.http.impl.engine.http2.framing.RSTFrameLimit
    akka.http.impl.engine.http2.hpack.ByteStringInputStream
    //akka.http.impl.engine.http2.hpack.HandleOrPassOnStage
    //akka.http.impl.engine.http2.hpack.HeaderCompression
    //akka.http.impl.engine.http2.hpack.HeaderDecompression
    //akka.http.impl.engine.http2.hpack.Http2HeaderParsing
    //akka.http.impl.engine.http2.util.AsciiTreeLayout
    //akka.http.impl.engine.parsing.BodyPartParser
    //akka.http.impl.engine.parsing.BoyerMoore
    //akka.http.impl.engine.parsing.HttpHeaderParser
    //akka.http.impl.engine.parsing.HttpMessageParser
    //akka.http.impl.engine.parsing.HttpRequestParser
    //akka.http.impl.engine.parsing.HttpResponseParser
    //akka.http.impl.engine.parsing.NotEnoughDataException
    //akka.http.impl.engine.parsing.ParserOutput
    //akka.http.impl.engine.parsing.ParsingException
    //akka.http.impl.engine.parsing.SpecializedHeaderValueParsers
    //akka.http.impl.engine.rendering.BodyPartRenderer
    //akka.http.impl.engine.rendering.DateHeaderRendering
    //akka.http.impl.engine.rendering.HttpRequestRendererFactory
    //akka.http.impl.engine.rendering.HttpResponseRendererFactory
    //akka.http.impl.engine.rendering.RenderSupport
    //akka.http.impl.engine.rendering.RequestRenderingContext
    //akka.http.impl.engine.rendering.ResponseRenderingContext
    akka.http.impl.engine.rendering.ResponseRenderingOutput
    //akka.http.impl.engine.server.GracefulTerminatorStage
    akka.http.impl.engine.server.HttpAttributes
    //akka.http.impl.engine.server.HttpServerBluePrint
    akka.http.impl.engine.server.InternalCustomHeader
    //akka.http.impl.engine.server.MasterServerTerminator
    akka.http.impl.engine.server.ServerTerminationDeadlineReached
    akka.http.impl.engine.server.ServerTerminator
    akka.http.impl.engine.server.UpgradeToOtherProtocolResponseHeader
    akka.http.impl.engine.ws.FrameData
    akka.http.impl.engine.ws.FrameError
    //akka.http.impl.engine.ws.FrameEvent
    akka.http.impl.engine.ws.FrameEventOrError
    //akka.http.impl.engine.ws.FrameEventParser
    //akka.http.impl.engine.ws.FrameEventRenderer
    //akka.http.impl.engine.ws.FrameHandler
    //akka.http.impl.engine.ws.FrameHeader
    //akka.http.impl.engine.ws.FrameLogger
    //akka.http.impl.engine.ws.FrameOutHandler
    akka.http.impl.engine.ws.FrameStart
    //akka.http.impl.engine.ws.Handshake
    //akka.http.impl.engine.ws.Masking
    //akka.http.impl.engine.ws.MessageToFrameRenderer
    //akka.http.impl.engine.ws.Protocol
    akka.http.impl.engine.ws.ProtocolException
    //akka.http.impl.engine.ws.Randoms
    akka.http.impl.engine.ws.StreamingCharsetDecoder
    akka.http.impl.engine.ws.StreamingCharsetDecoderInstance
    akka.http.impl.engine.ws.UpgradeToWebSocketLowLevel
    //akka.http.impl.engine.ws.Utf8Decoder
    //akka.http.impl.engine.ws.Utf8Encoder
    //akka.http.impl.engine.ws.WebSocket
    //akka.http.impl.engine.ws.WebSocketClientBlueprint
    //akka.http.impl.model.JavaQuery
    //akka.http.impl.model.JavaUri
    //akka.http.impl.model.UriJavaAccessor
    //akka.http.impl.model.parser.AcceptCharsetHeader
    //akka.http.impl.model.parser.AcceptEncodingHeader
    //akka.http.impl.model.parser.AcceptHeader
    //akka.http.impl.model.parser.AcceptLanguageHeader
    //akka.http.impl.model.parser.Base64Parsing
    //akka.http.impl.model.parser.CacheControlHeader
    //akka.http.impl.model.parser.CharacterClasses
    //akka.http.impl.model.parser.CommonActions
    //akka.http.impl.model.parser.CommonRules
    //akka.http.impl.model.parser.ContentDispositionHeader
    //akka.http.impl.model.parser.HeaderParser
    //akka.http.impl.model.parser.IpAddressParsing
    //akka.http.impl.model.parser.SimpleHeaders
    //akka.http.impl.model.parser.StringBuilding
    //akka.http.impl.model.parser.UriParser
    //akka.http.impl.model.parser.WebSocketHeaders
    //akka.http.impl.settings.ClientConnectionSettingsImpl
    //akka.http.impl.settings.ConnectionPoolSettingsImpl
    //akka.http.impl.settings.ConnectionPoolSetup
    akka.http.impl.settings.HostConnectionPoolSetup
    akka.http.impl.settings.HttpsProxySettingsImpl
    //akka.http.impl.settings.ParserSettingsImpl
    akka.http.impl.settings.PreviewServerSettingsImpl
    //akka.http.impl.settings.RoutingSettingsImpl
    akka.http.impl.settings.ServerSentEventSettingsImpl
    //akka.http.impl.settings.ServerSettingsImpl
    //akka.http.impl.settings.WebSocketSettingsImpl
    //akka.http.impl.util.ByteArrayRendering
    akka.http.impl.util.ByteStringParserInput
    //akka.http.impl.util.ByteStringRendering
    //akka.http.impl.util.CustomCharsetByteStringRendering
    akka.http.impl.util.DefaultNoLogging
    //akka.http.impl.util.EnhancedByteArray
    //akka.http.impl.util.EnhancedByteStringSource
    //akka.http.impl.util.EnhancedByteStringTraversableOnce
    //akka.http.impl.util.EnhancedConfig
    //akka.http.impl.util.EnhancedRegex
    //akka.http.impl.util.EnhancedString
    //akka.http.impl.util.EventStreamLogger
    //akka.http.impl.util.ExposeAttributes
    akka.http.impl.util.J2SMapping
    //akka.http.impl.util.JavaAccessors
    //akka.http.impl.util.JavaMapping
    akka.http.impl.util.JavaVersion
    //akka.http.impl.util.LazyValueBytesRenderable
    //akka.http.impl.util.LogByteStringTools
    //akka.http.impl.util.LogMessages
    //akka.http.impl.util.ObjectRegistry
    //akka.http.impl.util.One2OneBidiFlow
    akka.http.impl.util.Renderable
    //akka.http.impl.util.Renderer
    //akka.http.impl.util.Rendering
    akka.http.impl.util.S2JMapping
    //akka.http.impl.util.SettingsCompanionImpl
    akka.http.impl.util.SingletonException
    //akka.http.impl.util.SingletonValueRenderable
    //akka.http.impl.util.SocketOptionSettings
    //akka.http.impl.util.StageLoggingWithOverride
    //akka.http.impl.util.StreamUtils
    //akka.http.impl.util.StringRendering
    akka.http.impl.util.StringTools
    //akka.http.impl.util.Timestamp
    //akka.http.impl.util.ToStrict
    akka.http.impl.util.ToStringRenderable
    akka.http.impl.util.ValueRenderable
    //akka.http.javadsl.ClientTransport
    //akka.http.javadsl.ConnectHttp
    //akka.http.javadsl.ConnectHttpImpl
    //akka.http.javadsl.ConnectHttpsImpl
    akka.http.javadsl.ConnectWithHttps
    //akka.http.javadsl.ConnectionContext
    akka.http.javadsl.HandlerProvider
    //akka.http.javadsl.HostConnectionPool
    //akka.http.javadsl.Http
    //akka.http.javadsl.HttpConnectionContext
    akka.http.javadsl.HttpTerminated
    //akka.http.javadsl.HttpsConnectionContext
    akka.http.javadsl.IncomingConnection
    akka.http.javadsl.OutgoingConnection
    //akka.http.javadsl.OutgoingConnectionBuilder
    akka.http.javadsl.ServerBinding
    //akka.http.javadsl.ServerBuilder
    akka.http.javadsl.common.CsvEntityStreamingSupport
    //akka.http.javadsl.common.EntityStreamingSupport
    akka.http.javadsl.common.JsonEntityStreamingSupport
    //akka.http.javadsl.common.PartialApplication
    //akka.http.javadsl.marshalling.Marshaller
    //akka.http.javadsl.marshalling.sse.EventStreamMarshalling
    akka.http.javadsl.model.ContentType
    akka.http.javadsl.model.MediaType
    //akka.http.javadsl.model.RequestResponseAssociation
    akka.http.javadsl.model.ResponseFuture
    //akka.http.javadsl.model.SslSessionInfo
    //akka.http.javadsl.model.Trailer
    //akka.http.javadsl.model.ws.BinaryMessage
    akka.http.javadsl.model.ws.Message
    akka.http.javadsl.model.ws.PeerClosedConnectionException
    //akka.http.javadsl.model.ws.TextMessage
    //akka.http.javadsl.model.ws.UpgradeToWebSocket
    akka.http.javadsl.model.ws.WebSocket
    //akka.http.javadsl.model.ws.WebSocketRequest
    akka.http.javadsl.model.ws.WebSocketUpgrade
    akka.http.javadsl.model.ws.WebSocketUpgradeResponse
    akka.http.javadsl.server.AllDirectives
    akka.http.javadsl.server.AuthenticationFailedRejection
    //akka.http.javadsl.server.AuthorizationFailedRejection
    akka.http.javadsl.server.CircuitBreakerOpenRejection
    akka.http.javadsl.server.Complete
    akka.http.javadsl.server.CustomRejection
    //akka.http.javadsl.server.Directives
    //akka.http.javadsl.server.ExceptionHandler
    //akka.http.javadsl.server.ExpectedWebSocketRequestRejection
    akka.http.javadsl.server.InvalidOriginRejection
    akka.http.javadsl.server.InvalidRequiredValueForQueryParamRejection
    //akka.http.javadsl.server.JavaPathMatchers
    akka.http.javadsl.server.MalformedFormFieldRejection
    akka.http.javadsl.server.MalformedHeaderRejection
    akka.http.javadsl.server.MalformedQueryParamRejection
    akka.http.javadsl.server.MalformedRequestContentRejection
    akka.http.javadsl.server.MethodRejection
    akka.http.javadsl.server.MissingAttributeRejection
    akka.http.javadsl.server.MissingCookieRejection
    akka.http.javadsl.server.MissingFormFieldRejection
    akka.http.javadsl.server.MissingHeaderRejection
    akka.http.javadsl.server.MissingQueryParamRejection
    //akka.http.javadsl.server.PathMatcher0
    //akka.http.javadsl.server.PathMatcher1
    //akka.http.javadsl.server.PathMatcher10
    //akka.http.javadsl.server.PathMatcher11
    //akka.http.javadsl.server.PathMatcher12
    //akka.http.javadsl.server.PathMatcher13
    //akka.http.javadsl.server.PathMatcher14
    //akka.http.javadsl.server.PathMatcher15
    //akka.http.javadsl.server.PathMatcher16
    //akka.http.javadsl.server.PathMatcher17
    //akka.http.javadsl.server.PathMatcher18
    //akka.http.javadsl.server.PathMatcher19
    //akka.http.javadsl.server.PathMatcher2
    //akka.http.javadsl.server.PathMatcher20
    //akka.http.javadsl.server.PathMatcher21
    //akka.http.javadsl.server.PathMatcher22
    //akka.http.javadsl.server.PathMatcher3
    //akka.http.javadsl.server.PathMatcher4
    //akka.http.javadsl.server.PathMatcher5
    //akka.http.javadsl.server.PathMatcher6
    //akka.http.javadsl.server.PathMatcher7
    //akka.http.javadsl.server.PathMatcher8
    //akka.http.javadsl.server.PathMatcher9
    //akka.http.javadsl.server.PathMatchers
    akka.http.javadsl.server.Rejected
    akka.http.javadsl.server.Rejection
    akka.http.javadsl.server.RejectionError
    //akka.http.javadsl.server.RejectionHandler
    //akka.http.javadsl.server.RejectionHandlerBuilder
    //akka.http.javadsl.server.Rejections
    //akka.http.javadsl.server.RequestContext
    //akka.http.javadsl.server.RequestEntityExpectedRejection
    akka.http.javadsl.server.Route
    akka.http.javadsl.server.RouteResult
    //akka.http.javadsl.server.RouteResults
    //akka.http.javadsl.server.RoutingJavaMapping
    akka.http.javadsl.server.SchemeRejection
    akka.http.javadsl.server.TooManyRangesRejection
    akka.http.javadsl.server.TransformationRejection
    akka.http.javadsl.server.UnacceptedResponseContentTypeRejection
    //akka.http.javadsl.server.UnacceptedResponseEncodingRejection
    akka.http.javadsl.server.UnsatisfiableRangeRejection
    akka.http.javadsl.server.UnsupportedRequestContentTypeRejection
    akka.http.javadsl.server.UnsupportedRequestEncodingRejection
    akka.http.javadsl.server.UnsupportedWebSocketSubprotocolRejection
    akka.http.javadsl.server.ValidationRejection
    //akka.http.javadsl.server.directives.AttributeDirectives
    //akka.http.javadsl.server.directives.BasicDirectives
    //akka.http.javadsl.server.directives.CacheConditionDirectives
    //akka.http.javadsl.server.directives.CodingDirectives
    //akka.http.javadsl.server.directives.CookieDirectives
    //akka.http.javadsl.server.directives.DebuggingDirectives
    akka.http.javadsl.server.directives.DirectoryListing
    akka.http.javadsl.server.directives.DirectoryRenderer
    //akka.http.javadsl.server.directives.ExecutionDirectives
    //akka.http.javadsl.server.directives.FileAndResourceDirectives
    akka.http.javadsl.server.directives.FileInfo
    //akka.http.javadsl.server.directives.FileUploadDirectives
    //akka.http.javadsl.server.directives.FormFieldDirectives
    //akka.http.javadsl.server.directives.FramedEntityStreamingDirectives
    //akka.http.javadsl.server.directives.FutureDirectives
    //akka.http.javadsl.server.directives.HeaderDirectives
    //akka.http.javadsl.server.directives.HostDirectives
    //akka.http.javadsl.server.directives.LogEntry
    //akka.http.javadsl.server.directives.MarshallingDirectives
    //akka.http.javadsl.server.directives.MethodDirectives
    //akka.http.javadsl.server.directives.MiscDirectives
    //akka.http.javadsl.server.directives.ParameterDirectives
    //akka.http.javadsl.server.directives.PathDirectives
    //akka.http.javadsl.server.directives.RangeDirectives
    //akka.http.javadsl.server.directives.RespondWithDirectives
    //akka.http.javadsl.server.directives.RouteAdapter
    //akka.http.javadsl.server.directives.RouteDirectives
    //akka.http.javadsl.server.directives.SchemeDirectives
    //akka.http.javadsl.server.directives.SecurityDirectives
    //akka.http.javadsl.server.directives.TimeoutDirectives
    //akka.http.javadsl.server.directives.WebSocketDirectives
    //akka.http.javadsl.settings.ClientConnectionSettings
    //akka.http.javadsl.settings.ConnectionPoolSettings
    //akka.http.javadsl.settings.Http2ClientSettings
    //akka.http.javadsl.settings.Http2ServerSettings
    //akka.http.javadsl.settings.HttpsProxySettings
    //akka.http.javadsl.settings.ParserSettings
    //akka.http.javadsl.settings.PreviewServerSettings
    //akka.http.javadsl.settings.RoutingSettings
    //akka.http.javadsl.settings.ServerSentEventSettings
    //akka.http.javadsl.settings.ServerSettings
    akka.http.javadsl.settings.SettingsCompanion
    //akka.http.javadsl.settings.WebSocketSettings
    akka.http.javadsl.unmarshalling.StringUnmarshaller
    akka.http.javadsl.unmarshalling.StringUnmarshallerPredef
    //akka.http.javadsl.unmarshalling.Unmarshaller
    akka.http.javadsl.unmarshalling.UnmarshallerBase
    akka.http.javadsl.unmarshalling.sse.EventStreamUnmarshalling
    //akka.http.scaladsl.ClientTransport
    //akka.http.scaladsl.ConnectionContext
    //akka.http.scaladsl.DefaultSSLContextCreation
    akka.http.scaladsl.DeprecatedSslContextParameters
    //akka.http.scaladsl.Http
    akka.http.scaladsl.HttpConnectionContext
    //akka.http.scaladsl.HttpExt
    //akka.http.scaladsl.HttpsConnectionContext
    //akka.http.scaladsl.OutgoingConnectionBuilder
    //akka.http.scaladsl.ServerBuilder
    akka.http.scaladsl.TimeoutAccess
    //akka.http.scaladsl.client.RequestBuilding
    //akka.http.scaladsl.client.TransformerAux
    //akka.http.scaladsl.client.TransformerPipelineSupport
    akka.http.scaladsl.coding.Coder
    //akka.http.scaladsl.coding.Coders
    akka.http.scaladsl.coding.Compressor
    akka.http.scaladsl.coding.DataMapper
    //akka.http.scaladsl.coding.Decoder
    //akka.http.scaladsl.coding.Deflate
    //akka.http.scaladsl.coding.DeflateCompressor
    //akka.http.scaladsl.coding.DeflateDecompressor
    //akka.http.scaladsl.coding.DeflateDecompressorBase
    //akka.http.scaladsl.coding.Encoder
    //akka.http.scaladsl.coding.Gzip
    //akka.http.scaladsl.coding.GzipCompressor
    //akka.http.scaladsl.coding.GzipDecompressor
    //akka.http.scaladsl.coding.NoCoding
    akka.http.scaladsl.coding.NoCodingCompressor
    //akka.http.scaladsl.coding.StreamDecoder
    //akka.http.scaladsl.common.CsvEntityStreamingSupport
    akka.http.scaladsl.common.EntityStreamingSupport
    //akka.http.scaladsl.common.JsonEntityStreamingSupport
    akka.http.scaladsl.common.NameDefaultReceptacle
    akka.http.scaladsl.common.NameDefaultUnmarshallerReceptacle
    akka.http.scaladsl.common.NameOptionReceptacle
    akka.http.scaladsl.common.NameOptionUnmarshallerReceptacle
    //akka.http.scaladsl.common.NameReceptacle
    //akka.http.scaladsl.common.NameUnmarshallerReceptacle
    akka.http.scaladsl.common.RepeatedValueReceptacle
    akka.http.scaladsl.common.RepeatedValueUnmarshallerReceptacle
    akka.http.scaladsl.common.RequiredValueReceptacle
    akka.http.scaladsl.common.RequiredValueUnmarshallerReceptacle
    //akka.http.scaladsl.common.StrictForm
    //akka.http.scaladsl.common.ToNameReceptacleEnhancements
    //akka.http.scaladsl.marshalling.ContentTypeOverrider
    //akka.http.scaladsl.marshalling.EmptyValue
    //akka.http.scaladsl.marshalling.GenericMarshallers
    //akka.http.scaladsl.marshalling.LowPriorityToResponseMarshallerImplicits
    //akka.http.scaladsl.marshalling.Marshal
    //akka.http.scaladsl.marshalling.Marshaller
    akka.http.scaladsl.marshalling.Marshalling
    //akka.http.scaladsl.marshalling.MultipartMarshallers
    //akka.http.scaladsl.marshalling.NoStrictlyCompatibleElementMarshallingAvailableException
    //akka.http.scaladsl.marshalling.PredefinedToEntityMarshallers
    //akka.http.scaladsl.marshalling.PredefinedToRequestMarshallers
    //akka.http.scaladsl.marshalling.PredefinedToResponseMarshallers
    //akka.http.scaladsl.marshalling.ToResponseMarshallable
    //akka.http.scaladsl.marshalling.sse.EventStreamMarshalling
    akka.http.scaladsl.model.AttributeKey
    akka.http.scaladsl.model.AttributeKeys
    akka.http.scaladsl.model.BodyPartEntity
    //akka.http.scaladsl.model.ByteContentRange
    //akka.http.scaladsl.model.ContentRange
    //akka.http.scaladsl.model.ContentType
    //akka.http.scaladsl.model.ContentTypeRange
    //akka.http.scaladsl.model.ContentTypes
    //akka.http.scaladsl.model.DateTime
    akka.http.scaladsl.model.EntityStreamException
    //akka.http.scaladsl.model.EntityStreamSizeException
    //akka.http.scaladsl.model.ErrorInfo
    //akka.http.scaladsl.model.ExceptionWithErrorInfo
    //akka.http.scaladsl.model.FormData
    //akka.http.scaladsl.model.HttpCharset
    //akka.http.scaladsl.model.HttpCharsetRange
    //akka.http.scaladsl.model.HttpCharsets
    //akka.http.scaladsl.model.HttpEntity
    //akka.http.scaladsl.model.HttpHeader
    //akka.http.scaladsl.model.HttpMessage
    //akka.http.scaladsl.model.HttpMethod
    //akka.http.scaladsl.model.HttpMethods
    akka.http.scaladsl.model.HttpProtocol
    //akka.http.scaladsl.model.HttpProtocols
    //akka.http.scaladsl.model.HttpRequest
    //akka.http.scaladsl.model.HttpResponse
    akka.http.scaladsl.model.IllegalHeaderException
    akka.http.scaladsl.model.IllegalRequestException
    akka.http.scaladsl.model.IllegalResponseException
    akka.http.scaladsl.model.IllegalUriException
    akka.http.scaladsl.model.InvalidContentLengthException
    //akka.http.scaladsl.model.MediaRange
    //akka.http.scaladsl.model.MediaRanges
    //akka.http.scaladsl.model.MediaType
    //akka.http.scaladsl.model.MediaTypes
    //akka.http.scaladsl.model.Multipart
    //akka.http.scaladsl.model.OptHttpRequest
    //akka.http.scaladsl.model.OptHttpResponse
    akka.http.scaladsl.model.ParsingException
    //akka.http.scaladsl.model.RemoteAddress
    akka.http.scaladsl.model.RequestEntity
    akka.http.scaladsl.model.RequestEntityAcceptance
    //akka.http.scaladsl.model.RequestResponseAssociation
    akka.http.scaladsl.model.RequestTimeoutException
    //akka.http.scaladsl.model.ResponseEntity
    akka.http.scaladsl.model.ResponsePromise
    //akka.http.scaladsl.model.SensitiveHttpHeader
    //akka.http.scaladsl.model.SimpleRequestResponseAttribute
    //akka.http.scaladsl.model.SslSessionInfo
    //akka.http.scaladsl.model.StatusCode
    //akka.http.scaladsl.model.StatusCodes
    //akka.http.scaladsl.model.Trailer
    akka.http.scaladsl.model.TransferEncoding
    //akka.http.scaladsl.model.TransferEncodings
    akka.http.scaladsl.model.UniversalEntity
    //akka.http.scaladsl.model.Uri
    //akka.http.scaladsl.model.UriRendering
    akka.http.scaladsl.model.WithQValue
    //akka.http.scaladsl.model.headers.Accept
    //akka.http.scaladsl.model.headers.Age
    //akka.http.scaladsl.model.headers.Allow
    //akka.http.scaladsl.model.headers.Authorization
    //akka.http.scaladsl.model.headers.BasicHttpCredentials
    //akka.http.scaladsl.model.headers.ByteRange
    //akka.http.scaladsl.model.headers.CacheDirective
    //akka.http.scaladsl.model.headers.CacheDirectives
    //akka.http.scaladsl.model.headers.Connection
    akka.http.scaladsl.model.headers.ContentDispositionType
    //akka.http.scaladsl.model.headers.ContentDispositionTypes
    //akka.http.scaladsl.model.headers.Cookie
    //akka.http.scaladsl.model.headers.CustomHeader
    //akka.http.scaladsl.model.headers.Date
    //akka.http.scaladsl.model.headers.ETag
    //akka.http.scaladsl.model.headers.EmptyCompanion
    akka.http.scaladsl.model.headers.EmptyHeader
    //akka.http.scaladsl.model.headers.EntityTag
    //akka.http.scaladsl.model.headers.EntityTagRange
    //akka.http.scaladsl.model.headers.Expect
    //akka.http.scaladsl.model.headers.Expires
    //akka.http.scaladsl.model.headers.GenericHttpCredentials
    //akka.http.scaladsl.model.headers.Host
    //akka.http.scaladsl.model.headers.HttpChallenge
    //akka.http.scaladsl.model.headers.HttpChallenges
    //akka.http.scaladsl.model.headers.HttpCookie
    //akka.http.scaladsl.model.headers.HttpCookiePair
    akka.http.scaladsl.model.headers.HttpCredentials
    akka.http.scaladsl.model.headers.HttpEncoding
    //akka.http.scaladsl.model.headers.HttpEncodingRange
    //akka.http.scaladsl.model.headers.HttpEncodings
    //akka.http.scaladsl.model.headers.HttpOrigin
    //akka.http.scaladsl.model.headers.HttpOriginRange
    akka.http.scaladsl.model.headers.IgnoredDirective
    akka.http.scaladsl.model.headers.IncludeSubDomains
    //akka.http.scaladsl.model.headers.Language
    //akka.http.scaladsl.model.headers.LanguageRange
    //akka.http.scaladsl.model.headers.Link
    //akka.http.scaladsl.model.headers.LinkParam
    //akka.http.scaladsl.model.headers.LinkParams
    //akka.http.scaladsl.model.headers.LinkValue
    //akka.http.scaladsl.model.headers.Location
    akka.http.scaladsl.model.headers.MaxAge
    //akka.http.scaladsl.model.headers.ModeledCompanion
    //akka.http.scaladsl.model.headers.ModeledCustomHeader
    //akka.http.scaladsl.model.headers.ModeledCustomHeaderCompanion
    //akka.http.scaladsl.model.headers.ModeledHeader
    //akka.http.scaladsl.model.headers.OAuth2BearerToken
    //akka.http.scaladsl.model.headers.Origin
    //akka.http.scaladsl.model.headers.ProductVersion
    //akka.http.scaladsl.model.headers.Range
    akka.http.scaladsl.model.headers.RangeUnit
    //akka.http.scaladsl.model.headers.RangeUnits
    //akka.http.scaladsl.model.headers.RawHeader
    //akka.http.scaladsl.model.headers.Referer
    //akka.http.scaladsl.model.headers.RequestHeader
    //akka.http.scaladsl.model.headers.RequestResponseHeader
    //akka.http.scaladsl.model.headers.ResponseHeader
    akka.http.scaladsl.model.headers.RetryAfterDateTime
    akka.http.scaladsl.model.headers.RetryAfterDuration
    akka.http.scaladsl.model.headers.RetryAfterParameter
    //akka.http.scaladsl.model.headers.SameSite
    //akka.http.scaladsl.model.headers.Server
    akka.http.scaladsl.model.headers.StrictTransportSecurityDirective
    //akka.http.scaladsl.model.headers.SyntheticHeader
    //akka.http.scaladsl.model.headers.TE
    //akka.http.scaladsl.model.headers.Upgrade
    //akka.http.scaladsl.model.headers.UpgradeProtocol
    //akka.http.scaladsl.model.headers.WebSocketExtension
    //akka.http.scaladsl.model.headers.`Accept-Charset`
    //akka.http.scaladsl.model.headers.`Accept-Encoding`
    //akka.http.scaladsl.model.headers.`Accept-Language`
    //akka.http.scaladsl.model.headers.`Accept-Ranges`
    //akka.http.scaladsl.model.headers.`Access-Control-Allow-Credentials`
    //akka.http.scaladsl.model.headers.`Access-Control-Allow-Headers`
    //akka.http.scaladsl.model.headers.`Access-Control-Allow-Methods`
    //akka.http.scaladsl.model.headers.`Access-Control-Allow-Origin`
    //akka.http.scaladsl.model.headers.`Access-Control-Expose-Headers`
    //akka.http.scaladsl.model.headers.`Access-Control-Max-Age`
    //akka.http.scaladsl.model.headers.`Access-Control-Request-Headers`
    //akka.http.scaladsl.model.headers.`Access-Control-Request-Method`
    //akka.http.scaladsl.model.headers.`Cache-Control`
    //akka.http.scaladsl.model.headers.`Content-Disposition`
    //akka.http.scaladsl.model.headers.`Content-Encoding`
    //akka.http.scaladsl.model.headers.`Content-Length`
    //akka.http.scaladsl.model.headers.`Content-Location`
    //akka.http.scaladsl.model.headers.`Content-Range`
    //akka.http.scaladsl.model.headers.`Content-Type`
    //akka.http.scaladsl.model.headers.`If-Match`
    //akka.http.scaladsl.model.headers.`If-Modified-Since`
    //akka.http.scaladsl.model.headers.`If-None-Match`
    //akka.http.scaladsl.model.headers.`If-Range`
    //akka.http.scaladsl.model.headers.`If-Unmodified-Since`
    //akka.http.scaladsl.model.headers.`Last-Event-ID`
    //akka.http.scaladsl.model.headers.`Last-Modified`
    //akka.http.scaladsl.model.headers.`Proxy-Authenticate`
    //akka.http.scaladsl.model.headers.`Proxy-Authorization`
    //akka.http.scaladsl.model.headers.`Raw-Request-URI`
    //akka.http.scaladsl.model.headers.`Remote-Address`
    //akka.http.scaladsl.model.headers.`Retry-After`
    //akka.http.scaladsl.model.headers.`Sec-WebSocket-Accept`
    //akka.http.scaladsl.model.headers.`Sec-WebSocket-Extensions`
    //akka.http.scaladsl.model.headers.`Sec-WebSocket-Key`
    //akka.http.scaladsl.model.headers.`Sec-WebSocket-Protocol`
    //akka.http.scaladsl.model.headers.`Sec-WebSocket-Version`
    //akka.http.scaladsl.model.headers.`Set-Cookie`
    //akka.http.scaladsl.model.headers.`Strict-Transport-Security`
    //akka.http.scaladsl.model.headers.`Timeout-Access`
    //akka.http.scaladsl.model.headers.`Tls-Session-Info`
    //akka.http.scaladsl.model.headers.`Transfer-Encoding`
    //akka.http.scaladsl.model.headers.`User-Agent`
    //akka.http.scaladsl.model.headers.`WWW-Authenticate`
    //akka.http.scaladsl.model.headers.`X-Forwarded-For`
    //akka.http.scaladsl.model.headers.`X-Forwarded-Host`
    //akka.http.scaladsl.model.headers.`X-Forwarded-Proto`
    //akka.http.scaladsl.model.headers.`X-Real-Ip`
    //akka.http.scaladsl.model.http2.Http2Exception
    akka.http.scaladsl.model.http2.Http2SettingsHeader
    //akka.http.scaladsl.model.http2.PeerClosedStreamException
    //akka.http.scaladsl.model.sse.ServerSentEvent
    akka.http.scaladsl.model.ws.BinaryMessage
    akka.http.scaladsl.model.ws.InvalidUpgradeResponse
    akka.http.scaladsl.model.ws.Message
    //akka.http.scaladsl.model.ws.PeerClosedConnectionException
    //akka.http.scaladsl.model.ws.TextMessage
    //akka.http.scaladsl.model.ws.UpgradeToWebSocket
    akka.http.scaladsl.model.ws.ValidUpgrade
    //akka.http.scaladsl.model.ws.WebSocketRequest
    //akka.http.scaladsl.model.ws.WebSocketUpgrade
    akka.http.scaladsl.model.ws.WebSocketUpgradeResponse
    akka.http.scaladsl.server.AuthenticationFailedRejection
    akka.http.scaladsl.server.AuthorizationFailedRejection
    //akka.http.scaladsl.server.CharsetNegotiator
    akka.http.scaladsl.server.CircuitBreakerOpenRejection
    //akka.http.scaladsl.server.ConjunctionMagnet
    //akka.http.scaladsl.server.ContentNegotiator
    //akka.http.scaladsl.server.Directive
    akka.http.scaladsl.server.Directives
    //akka.http.scaladsl.server.EncodingNegotiator
    //akka.http.scaladsl.server.ExceptionHandler
    akka.http.scaladsl.server.ExpectedWebSocketRequestRejection
    //akka.http.scaladsl.server.HttpApp
    //akka.http.scaladsl.server.ImplicitPathMatcherConstruction
    akka.http.scaladsl.server.InvalidOriginRejection
    akka.http.scaladsl.server.InvalidRequiredValueForQueryParamRejection
    //akka.http.scaladsl.server.LanguageNegotiator
    akka.http.scaladsl.server.LowerPriorityRouteResultImplicits
    akka.http.scaladsl.server.LowerPriorityRoutingLogImplicits
    //akka.http.scaladsl.server.MalformedFormFieldRejection
    //akka.http.scaladsl.server.MalformedHeaderRejection
    //akka.http.scaladsl.server.MalformedQueryParamRejection
    akka.http.scaladsl.server.MalformedRequestContentRejection
    //akka.http.scaladsl.server.MediaTypeNegotiator
    akka.http.scaladsl.server.MethodRejection
    akka.http.scaladsl.server.MissingAttributeRejection
    akka.http.scaladsl.server.MissingCookieRejection
    akka.http.scaladsl.server.MissingFormFieldRejection
    akka.http.scaladsl.server.MissingHeaderRejection
    akka.http.scaladsl.server.MissingQueryParamRejection
    //akka.http.scaladsl.server.PathMatcher
    //akka.http.scaladsl.server.PathMatchers
    akka.http.scaladsl.server.Rejection
    //akka.http.scaladsl.server.RejectionError
    //akka.http.scaladsl.server.RejectionHandler
    akka.http.scaladsl.server.RejectionWithOptionalCause
    akka.http.scaladsl.server.RequestContext
    //akka.http.scaladsl.server.RequestContextImpl
    akka.http.scaladsl.server.RequestEntityExpectedRejection
    //akka.http.scaladsl.server.Route
    //akka.http.scaladsl.server.RouteConcatenation
    //akka.http.scaladsl.server.RouteResult
    akka.http.scaladsl.server.RoutingLog
    akka.http.scaladsl.server.SchemeRejection
    //akka.http.scaladsl.server.StandardRoute
    akka.http.scaladsl.server.TooManyRangesRejection
    //akka.http.scaladsl.server.TransformationRejection
    akka.http.scaladsl.server.UnacceptedResponseContentTypeRejection
    akka.http.scaladsl.server.UnacceptedResponseEncodingRejection
    akka.http.scaladsl.server.UnsatisfiableRangeRejection
    //akka.http.scaladsl.server.UnsupportedRequestContentTypeRejection
    akka.http.scaladsl.server.UnsupportedRequestEncodingRejection
    akka.http.scaladsl.server.UnsupportedWebSocketSubprotocolRejection
    //akka.http.scaladsl.server.ValidationRejection
    //akka.http.scaladsl.server.directives.AttributeDirectives
    //akka.http.scaladsl.server.directives.AuthenticationDirective
    //akka.http.scaladsl.server.directives.AuthenticationResult
    //akka.http.scaladsl.server.directives.BasicDirectives
    //akka.http.scaladsl.server.directives.CacheConditionDirectives
    //akka.http.scaladsl.server.directives.CodingDirectives
    //akka.http.scaladsl.server.directives.CompleteOrRecoverWithMagnet
    //akka.http.scaladsl.server.directives.ContentTypeResolver
    //akka.http.scaladsl.server.directives.CookieDirectives
    //akka.http.scaladsl.server.directives.Credentials
    //akka.http.scaladsl.server.directives.DebuggingDirectives
    //akka.http.scaladsl.server.directives.DirectoryListing
    //akka.http.scaladsl.server.directives.ExecutionDirectives
    //akka.http.scaladsl.server.directives.FileAndResourceDirectives
    akka.http.scaladsl.server.directives.FileInfo
    //akka.http.scaladsl.server.directives.FileUploadDirectives
    //akka.http.scaladsl.server.directives.FormFieldDirectives
    //akka.http.scaladsl.server.directives.FormFieldDirectivesInstances
    //akka.http.scaladsl.server.directives.FramedEntityStreamingDirectives
    //akka.http.scaladsl.server.directives.FutureDirectives
    //akka.http.scaladsl.server.directives.HeaderDirectives
    //akka.http.scaladsl.server.directives.HeaderMagnet
    //akka.http.scaladsl.server.directives.HostDirectives
    //akka.http.scaladsl.server.directives.LogEntry
    //akka.http.scaladsl.server.directives.LoggingMagnet
    //akka.http.scaladsl.server.directives.LowPriorityHeaderMagnetImplicits
    //akka.http.scaladsl.server.directives.MarshallingDirectives
    //akka.http.scaladsl.server.directives.MethodDirectives
    //akka.http.scaladsl.server.directives.MiscDirectives
    //akka.http.scaladsl.server.directives.OnSuccessMagnet
    //akka.http.scaladsl.server.directives.ParameterDirectives
    //akka.http.scaladsl.server.directives.ParameterDirectivesInstances
    //akka.http.scaladsl.server.directives.PathDirectives
    //akka.http.scaladsl.server.directives.RangeDirectives
    //akka.http.scaladsl.server.directives.RespondWithDirectives
    //akka.http.scaladsl.server.directives.RouteDirectives
    //akka.http.scaladsl.server.directives.SchemeDirectives
    //akka.http.scaladsl.server.directives.SecurityDirectives
    //akka.http.scaladsl.server.directives.TimeoutDirectives
    //akka.http.scaladsl.server.directives.WebSocketDirectives
    akka.http.scaladsl.server.util.ApplyConverter
    //akka.http.scaladsl.server.util.ApplyConverterInstances
    //akka.http.scaladsl.server.util.BinaryPolyFunc
    //akka.http.scaladsl.server.util.ClassMagnet
    //akka.http.scaladsl.server.util.ConstructFromTuple
    //akka.http.scaladsl.server.util.ConstructFromTupleInstances
    //akka.http.scaladsl.server.util.LowerPriorityTupler
    //akka.http.scaladsl.server.util.Tuple
    //akka.http.scaladsl.server.util.TupleAppendOneInstances
    //akka.http.scaladsl.server.util.TupleFoldInstances
    //akka.http.scaladsl.server.util.TupleOps
    akka.http.scaladsl.server.util.Tupler
    //akka.http.scaladsl.settings.ClientConnectionSettings
    //akka.http.scaladsl.settings.ConnectionPoolSettings
    //akka.http.scaladsl.settings.Http2ClientSettings
    //akka.http.scaladsl.settings.Http2CommonSettings
    akka.http.scaladsl.settings.Http2InternalClientSettings
    akka.http.scaladsl.settings.Http2InternalServerSettings
    //akka.http.scaladsl.settings.Http2ServerSettings
    //akka.http.scaladsl.settings.HttpsProxySettings
    //akka.http.scaladsl.settings.ParserSettings
    //akka.http.scaladsl.settings.PreviewServerSettings
    //akka.http.scaladsl.settings.RoutingSettings
    //akka.http.scaladsl.settings.ServerSentEventSettings
    //akka.http.scaladsl.settings.ServerSettings
    //akka.http.scaladsl.settings.SettingsCompanion
    //akka.http.scaladsl.settings.WebSocketSettings
    //akka.http.scaladsl.unmarshalling.GenericUnmarshallers
    //akka.http.scaladsl.unmarshalling.LowerPriorityGenericUnmarshallers
    //akka.http.scaladsl.unmarshalling.MultipartUnmarshallers
    //akka.http.scaladsl.unmarshalling.PredefinedFromEntityUnmarshallers
    //akka.http.scaladsl.unmarshalling.PredefinedFromStringUnmarshallers
    akka.http.scaladsl.unmarshalling.Unmarshal
    //akka.http.scaladsl.unmarshalling.Unmarshaller
    //akka.http.scaladsl.unmarshalling.sse.EventStreamParser
    //akka.http.scaladsl.unmarshalling.sse.EventStreamUnmarshalling
    //akka.http.scaladsl.unmarshalling.sse.LineParser
    //akka.http.scaladsl.unmarshalling.sse.ServerSentEventParser
    //akka.http.scaladsl.util.FastFuture
  """)
}