package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.scalaVersion
import org.junit.Test

class AkkaActorSemanticTest extends SemanticTestBase("com.typesafe.akka" %% "akka-actor" % "2.8.8")("akka") {
//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    akka.AkkaException
    akka.AkkaVersion
    akka.ConfigurationException
    akka.Done
    //akka.Main
    akka.NotUsed
    //akka.OnlyCauseStackTrace
    akka.UnsupportedAkkaVersion
    //akka.Version
    akka.actor.AbstractActor
    akka.actor.AbstractActorWithStash
    akka.actor.AbstractActorWithTimers
    akka.actor.AbstractActorWithUnboundedStash
    akka.actor.AbstractActorWithUnrestrictedStash
    akka.actor.AbstractExtensionId
    //akka.actor.AbstractFSM
    akka.actor.AbstractFSMWithStash
    akka.actor.AbstractLoggingActor
    akka.actor.AbstractLoggingFSM
    //akka.actor.AbstractProps
    akka.actor.AbstractSchedulerBase
    //akka.actor.Actor
    //akka.actor.ActorCell
    //akka.actor.ActorContext
    akka.actor.ActorIdentity
    //akka.actor.ActorInitializationException
    //akka.actor.ActorInterruptedException
    akka.actor.ActorKilledException
    //akka.actor.ActorLogMarker
    //akka.actor.ActorLogging
    akka.actor.ActorNotFound
    //akka.actor.ActorPath
    //akka.actor.ActorPathExtractor
    akka.actor.ActorPaths
    //akka.actor.ActorRef
    akka.actor.ActorRefFactory
    akka.actor.ActorRefProvider
    akka.actor.ActorRefScope
    akka.actor.ActorRefWithCell
    //akka.actor.ActorSelection
    akka.actor.ActorSelectionMessage
    //akka.actor.ActorSystem
    //akka.actor.ActorSystemImpl
    //akka.actor.Address
    akka.actor.AddressFromURIString
    akka.actor.AddressTerminated
    akka.actor.AllDeadLetters
    //akka.actor.AllForOneStrategy
    //akka.actor.ArgsReflectConstructor
    akka.actor.AutoReceivedMessage
    //akka.actor.BootstrapSetup
    akka.actor.Cancellable
    //akka.actor.Cell
    //akka.actor.ChildActorPath
    akka.actor.ChildNameReserved
    //akka.actor.ChildRestartStats
    akka.actor.ChildStats
    akka.actor.ClassicActorContextProvider
    akka.actor.ClassicActorSystemProvider
    akka.actor.ContextualTypedActorFactory
    //akka.actor.CoordinatedShutdown
    //akka.actor.CoordinatedShutdownTerminationWatcher
    akka.actor.CreatorConsumer
    //akka.actor.CreatorFunctionConsumer
    akka.actor.DeadLetter
    //akka.actor.DeadLetterActorRef
    akka.actor.DeadLetterSuppression
    //akka.actor.DeathPactException
    akka.actor.DefaultSupervisorStrategy
    //akka.actor.Deploy
    //akka.actor.Deployer
    //akka.actor.DiagnosticActorLogging
    akka.actor.Dropped
    akka.actor.DynamicAccess
    //akka.actor.EmptyLocalActorRef
    akka.actor.ExtendedActorSystem
    akka.actor.Extension
    //akka.actor.ExtensionId
    akka.actor.ExtensionIdProvider
    //akka.actor.FSM
    //akka.actor.FunctionRef
    akka.actor.Identify
    //akka.actor.IgnoreActorRef
    akka.actor.IllegalActorStateException
    //akka.actor.IndirectActorProducer
    akka.actor.InternalActorRef
    akka.actor.InvalidActorNameException
    akka.actor.InvalidMessageException
    akka.actor.JVMShutdownHooks
    akka.actor.Kill
    //akka.actor.LightArrayRevolverScheduler
    //akka.actor.LocalActorRef
    //akka.actor.LocalActorRefProvider
    akka.actor.LocalRef
    akka.actor.LocalScope
    //akka.actor.LoggingFSM
    akka.actor.MinimalActorRef
    //akka.actor.NoArgsReflectConstructor
    akka.actor.NoScopeGiven
    akka.actor.NoSerializationVerificationNeeded
    akka.actor.Nobody
    akka.actor.NotInfluenceReceiveTimeout
    //akka.actor.OneForOneStrategy
    //akka.actor.OriginalRestartException
    //akka.actor.PathUtils
    akka.actor.PoisonPill
    akka.actor.PossiblyHarmful
    //akka.actor.PostRestartException
    //akka.actor.PreRestartException
    //akka.actor.Props
    akka.actor.ProviderSelection
    akka.actor.ReceiveTimeout
    //akka.actor.ReflectiveDynamicAccess
    //akka.actor.RelativeActorPath
    //akka.actor.RepointableActorRef
    akka.actor.RepointableRef
    //akka.actor.RootActorPath
    //akka.actor.ScalaActorRef
    //akka.actor.ScalaActorSelection
    //akka.actor.Scheduler
    akka.actor.SchedulerException
    akka.actor.Scope
    akka.actor.SelectChildName
    akka.actor.SelectChildPattern
    akka.actor.SelectParent
    akka.actor.SelectionPathElement
    //akka.actor.SerializedActorRef
    akka.actor.SerializedIgnore
    akka.actor.SerializedNobody
    akka.actor.Stash
    akka.actor.StashFactory
    //akka.actor.StashOverflowException
    //akka.actor.StashSupport
    akka.actor.Status
    akka.actor.StopChild
    akka.actor.StoppingSupervisorStrategy
    //akka.actor.SupervisorStrategy
    akka.actor.SupervisorStrategyConfigurator
    //akka.actor.SupervisorStrategyLowPriorityImplicits
    akka.actor.SuppressedDeadLetter
    akka.actor.SystemGuardian
    //akka.actor.Terminated
    akka.actor.TimerScheduler
    //akka.actor.TimerSchedulerImpl
    //akka.actor.Timers
    //akka.actor.TypedActor
    //akka.actor.TypedActorExtension
    //akka.actor.TypedActorFactory
    //akka.actor.TypedCreatorFunctionConsumer
    //akka.actor.TypedProps
    akka.actor.UnboundedStash
    //akka.actor.UnhandledMessage
    //akka.actor.UnrestrictedStash
    //akka.actor.UnstartedCell
    //akka.actor.UntypedAbstractActor
    //akka.actor.VirtualPathContainer
    akka.actor.WrappedMessage
    //akka.actor.dungeon.Children
    //akka.actor.dungeon.ChildrenContainer
    //akka.actor.dungeon.DeathWatch
    //akka.actor.dungeon.Dispatch
    //akka.actor.dungeon.FaultHandling
    akka.actor.dungeon.LicenseKeySupplier
    //akka.actor.dungeon.ReceiveTimeout
    //akka.actor.dungeon.SerializationCheckFailedException
    //akka.actor.setup.ActorSystemSetup
    akka.actor.setup.Setup
    //akka.compat.Future
    akka.compat.PartialFunction
    //akka.dispatch.BalancingDispatcher
    //akka.dispatch.BalancingDispatcherConfigurator
    akka.dispatch.Batchable
    //akka.dispatch.BatchingExecutor
    //akka.dispatch.BoundedControlAwareMailbox
    akka.dispatch.BoundedControlAwareMessageQueueSemantics
    //akka.dispatch.BoundedDequeBasedMailbox
    akka.dispatch.BoundedDequeBasedMessageQueue
    akka.dispatch.BoundedDequeBasedMessageQueueSemantics
    //akka.dispatch.BoundedMailbox
    akka.dispatch.BoundedMessageQueueSemantics
    //akka.dispatch.BoundedNodeMessageQueue
    //akka.dispatch.BoundedPriorityMailbox
    akka.dispatch.BoundedQueueBasedMessageQueue
    //akka.dispatch.BoundedStablePriorityMailbox
    //akka.dispatch.CachingConfig
    //akka.dispatch.ControlAwareMessageQueueSemantics
    akka.dispatch.ControlMessage
    akka.dispatch.DefaultDispatcherPrerequisites
    //akka.dispatch.DefaultExecutorServiceConfigurator
    //akka.dispatch.DefaultSystemMessageQueue
    akka.dispatch.DequeBasedMessageQueue
    akka.dispatch.DequeBasedMessageQueueSemantics
    //akka.dispatch.Dispatcher
    akka.dispatch.DispatcherConfigurator
    akka.dispatch.DispatcherPrerequisites
    //akka.dispatch.Dispatchers
    akka.dispatch.Envelope
    //akka.dispatch.ExecutionContexts
    //akka.dispatch.ExecutorServiceConfigurator
    //akka.dispatch.ExecutorServiceDelegate
    akka.dispatch.ExecutorServiceFactory
    akka.dispatch.ExecutorServiceFactoryProvider
    //akka.dispatch.Filter
    akka.dispatch.Foreach
    //akka.dispatch.ForkJoinExecutorConfigurator
    //akka.dispatch.Futures
    akka.dispatch.LoadMetrics
    //akka.dispatch.Mailbox
    akka.dispatch.MailboxType
    //akka.dispatch.Mailboxes
    //akka.dispatch.Mapper
    //akka.dispatch.MessageDispatcher
    //akka.dispatch.MessageDispatcherConfigurator
    akka.dispatch.MessageQueue
    //akka.dispatch.MonitorableThreadFactory
    akka.dispatch.MultipleConsumerSemantics
    //akka.dispatch.NodeMessageQueue
    akka.dispatch.NonBlockingBoundedMailbox
    akka.dispatch.OnComplete
    akka.dispatch.OnFailure
    akka.dispatch.OnSuccess
    //akka.dispatch.PinnedDispatcher
    //akka.dispatch.PinnedDispatcherConfigurator
    akka.dispatch.PriorityGenerator
    akka.dispatch.ProducesMessageQueue
    akka.dispatch.ProducesPushTimeoutSemanticsMailbox
    akka.dispatch.QueueBasedMessageQueue
    akka.dispatch.Recover
    akka.dispatch.RequiresMessageQueue
    akka.dispatch.SaneRejectedExecutionHandler
    akka.dispatch.SingleConsumerOnlyUnboundedMailbox
    akka.dispatch.SystemMessageQueue
    //akka.dispatch.TaskInvocation
    //akka.dispatch.ThreadPoolConfig
    //akka.dispatch.ThreadPoolConfigBuilder
    //akka.dispatch.ThreadPoolExecutorConfigurator
    akka.dispatch.UnboundedControlAwareMailbox
    akka.dispatch.UnboundedControlAwareMessageQueueSemantics
    akka.dispatch.UnboundedDequeBasedMailbox
    //akka.dispatch.UnboundedDequeBasedMessageQueue
    akka.dispatch.UnboundedDequeBasedMessageQueueSemantics
    akka.dispatch.UnboundedMailbox
    akka.dispatch.UnboundedMessageQueueSemantics
    //akka.dispatch.UnboundedPriorityMailbox
    //akka.dispatch.UnboundedQueueBasedMessageQueue
    //akka.dispatch.UnboundedStablePriorityMailbox
    //akka.dispatch.affinity.AffinityPool
    //akka.dispatch.affinity.AffinityPoolConfigurator
    //akka.dispatch.affinity.FairDistributionHashCache
    akka.dispatch.affinity.QueueSelector
    akka.dispatch.affinity.QueueSelectorFactory
    akka.dispatch.affinity.RejectionHandler
    akka.dispatch.affinity.RejectionHandlerFactory
    //akka.dispatch.affinity.ThrowOnOverflowRejectionHandler
    akka.dispatch.internal.SameThreadExecutionContext
    //akka.dispatch.internal.ScalaBatchable
    //akka.dispatch.japi
    akka.dispatch.sysmsg.Create
    akka.dispatch.sysmsg.DeathWatchNotification
    //akka.dispatch.sysmsg.EarliestFirstSystemMessageList
    akka.dispatch.sysmsg.Failed
    //akka.dispatch.sysmsg.LatestFirstSystemMessageList
    akka.dispatch.sysmsg.NoMessage
    akka.dispatch.sysmsg.Recreate
    akka.dispatch.sysmsg.Resume
    akka.dispatch.sysmsg.StashWhenFailed
    akka.dispatch.sysmsg.StashWhenWaitingForChildren
    akka.dispatch.sysmsg.Supervise
    akka.dispatch.sysmsg.Suspend
    akka.dispatch.sysmsg.SystemMessage
    akka.dispatch.sysmsg.SystemMessageList
    akka.dispatch.sysmsg.Terminate
    akka.dispatch.sysmsg.Unwatch
    akka.dispatch.sysmsg.Watch
    //akka.event.ActorClassificationUnsubscriber
    akka.event.ActorClassifier
    akka.event.ActorEventBus
    akka.event.ActorWithLogClass
    //akka.event.AddressTerminatedTopic
    //akka.event.BusLogging
    //akka.event.DeadLetterListener
    //akka.event.DefaultLoggingFilter
    //akka.event.DiagnosticLoggingAdapter
    akka.event.DiagnosticMarkerBusLoggingAdapter
    akka.event.DummyClassForStringSources
    akka.event.EventBus
    //akka.event.EventStream
    //akka.event.EventStreamUnsubscriber
    //akka.event.LogMarker
    //akka.event.LogSource
    //akka.event.LoggerMailbox
    //akka.event.LoggerMailboxType
    akka.event.LoggerMessageQueueSemantics
    //akka.event.Logging
    //akka.event.LoggingAdapter
    //akka.event.LoggingBus
    akka.event.LoggingFilter
    akka.event.LoggingFilterWithMarker
    akka.event.LoggingFilterWithMarkerWrapper
    //akka.event.LoggingReceive
    akka.event.LookupClassification
    //akka.event.ManagedActorClassification
    //akka.event.MarkerLoggingAdapter
    akka.event.NoLogging
    akka.event.NoMarkerLogging
    akka.event.PredicateClassifier
    //akka.event.ScanningClassification
    //akka.event.SubchannelClassification
    akka.event.japi.EventBus
    //akka.event.japi.LookupEventBus
    //akka.event.japi.ManagedActorEventBus
    //akka.event.japi.ScanningEventBus
    //akka.event.japi.SubchannelEventBus
    //akka.event.jul.JavaLogger
    //akka.event.jul.JavaLogging
    //akka.event.jul.JavaLoggingFilter
    //akka.event.jul.Logger
    akka.io.BufferPool
    akka.io.ChannelRegistration
    akka.io.ChannelRegistry
    //akka.io.DirectByteBufferPool
    //akka.io.Dns
    //akka.io.DnsExt
    akka.io.DnsProvider
    akka.io.IO
    //akka.io.Inet
    akka.io.InetAddressDnsProvider
    //akka.io.InetAddressDnsResolver
    akka.io.IpVersionSelector
    akka.io.PeriodicCacheCleanup
    //akka.io.SelectionHandler
    //akka.io.SelectionHandlerSettings
    //akka.io.SimpleDnsCache
    //akka.io.SimpleDnsManager
    //akka.io.Tcp
    //akka.io.TcpConnection
    //akka.io.TcpExt
    //akka.io.TcpIncomingConnection
    //akka.io.TcpListener
    //akka.io.TcpManager
    akka.io.TcpMessage
    //akka.io.TcpOutgoingConnection
    akka.io.TcpSO
    //akka.io.Udp
    //akka.io.UdpConnected
    akka.io.UdpConnectedExt
    //akka.io.UdpConnectedManager
    //akka.io.UdpConnectedMessage
    //akka.io.UdpConnection
    akka.io.UdpExt
    //akka.io.UdpListener
    //akka.io.UdpManager
    //akka.io.UdpMessage
    akka.io.UdpSO
    //akka.io.UdpSender
    //akka.io.WithUdpSend
    //akka.io.dns.AAAARecord
    //akka.io.dns.ARecord
    //akka.io.dns.CNameRecord
    //akka.io.dns.CachePolicy
    //akka.io.dns.DnsProtocol
    //akka.io.dns.DnsSettings
    akka.io.dns.RecordClass
    //akka.io.dns.RecordType
    //akka.io.dns.ResourceRecord
    //akka.io.dns.SRVRecord
    //akka.io.dns.UnknownRecord
    //akka.io.dns.internal.AsyncDnsManager
    akka.io.dns.internal.AsyncDnsProvider
    //akka.io.dns.internal.AsyncDnsResolver
    //akka.io.dns.internal.DnsClient
    //akka.io.dns.internal.DomainName
    //akka.io.dns.internal.Message
    //akka.io.dns.internal.MessageFlags
    //akka.io.dns.internal.OpCode
    akka.io.dns.internal.Question
    //akka.io.dns.internal.RecordClassSerializer
    //akka.io.dns.internal.RecordTypeSerializer
    akka.io.dns.internal.ResolvConf
    //akka.io.dns.internal.ResolvConfParser
    //akka.io.dns.internal.ResponseCode
    //akka.io.dns.internal.TcpDnsClient
    akka.japi.Creator
    akka.japi.Effect
    akka.japi.Function
    akka.japi.Function2
    akka.japi.JavaPartialFunction
    //akka.japi.Option
    akka.japi.Pair
    akka.japi.Predicate
    akka.japi.Procedure
    akka.japi.Throwables
    //akka.japi.Util
    akka.japi.function.Creator
    akka.japi.function.Effect
    akka.japi.function.Function
    akka.japi.function.Function10
    akka.japi.function.Function11
    akka.japi.function.Function12
    akka.japi.function.Function13
    akka.japi.function.Function14
    akka.japi.function.Function15
    akka.japi.function.Function16
    akka.japi.function.Function17
    akka.japi.function.Function18
    akka.japi.function.Function19
    akka.japi.function.Function2
    akka.japi.function.Function20
    akka.japi.function.Function21
    akka.japi.function.Function22
    akka.japi.function.Function3
    akka.japi.function.Function4
    akka.japi.function.Function5
    akka.japi.function.Function6
    akka.japi.function.Function7
    akka.japi.function.Function8
    akka.japi.function.Function9
    akka.japi.function.Predicate
    akka.japi.function.Procedure
    akka.japi.function.Procedure10
    akka.japi.function.Procedure11
    akka.japi.function.Procedure12
    akka.japi.function.Procedure13
    akka.japi.function.Procedure14
    akka.japi.function.Procedure15
    akka.japi.function.Procedure16
    akka.japi.function.Procedure17
    akka.japi.function.Procedure18
    akka.japi.function.Procedure19
    akka.japi.function.Procedure2
    akka.japi.function.Procedure20
    akka.japi.function.Procedure21
    akka.japi.function.Procedure22
    akka.japi.function.Procedure3
    akka.japi.function.Procedure4
    akka.japi.function.Procedure5
    akka.japi.function.Procedure6
    akka.japi.function.Procedure7
    akka.japi.function.Procedure8
    akka.japi.function.Procedure9
    akka.japi.pf.CaseStatement
    akka.japi.pf.UnitCaseStatement
    akka.japi.tuple.Tuple10
    akka.japi.tuple.Tuple11
    akka.japi.tuple.Tuple12
    akka.japi.tuple.Tuple13
    akka.japi.tuple.Tuple14
    akka.japi.tuple.Tuple15
    akka.japi.tuple.Tuple16
    akka.japi.tuple.Tuple17
    akka.japi.tuple.Tuple18
    akka.japi.tuple.Tuple19
    akka.japi.tuple.Tuple20
    akka.japi.tuple.Tuple21
    akka.japi.tuple.Tuple22
    akka.japi.tuple.Tuple3
    akka.japi.tuple.Tuple4
    akka.japi.tuple.Tuple5
    akka.japi.tuple.Tuple6
    akka.japi.tuple.Tuple7
    akka.japi.tuple.Tuple8
    akka.japi.tuple.Tuple9
    //akka.pattern.AskPromiseRef
    akka.pattern.AskSupport
    //akka.pattern.AskTimeoutException
    //akka.pattern.AskableActorRef
    //akka.pattern.AskableActorSelection
    akka.pattern.AutoReset
    akka.pattern.BackoffOnFailureOptions
    //akka.pattern.BackoffOnFailureOptionsImpl
    akka.pattern.BackoffOnStopOptions
    //akka.pattern.BackoffOnStopOptionsImpl
    //akka.pattern.BackoffOpts
    akka.pattern.BackoffReset
    //akka.pattern.BackoffSupervisor
    //akka.pattern.CircuitBreaker
    //akka.pattern.CircuitBreakerOpenException
    //akka.pattern.CircuitBreakersRegistry
    akka.pattern.ExplicitAskSupport
    //akka.pattern.ExplicitlyAskableActorRef
    //akka.pattern.ExplicitlyAskableActorSelection
    //akka.pattern.ExtendedBackoffOptions
    akka.pattern.ForwardDeathLetters
    akka.pattern.ForwardTo
    akka.pattern.FutureRef
    akka.pattern.FutureRefImpl
    //akka.pattern.FutureTimeoutSupport
    //akka.pattern.GracefulStopSupport
    //akka.pattern.HandleBackoff
    akka.pattern.HandlingWhileStopped
    akka.pattern.ManualReset
    //akka.pattern.Patterns
    //akka.pattern.PipeToSupport
    //akka.pattern.PromiseActorRef
    //akka.pattern.PromiseRef
    akka.pattern.PromiseRefImpl
    akka.pattern.ReplyWith
    //akka.pattern.RetrySupport
    //akka.pattern.StatusReply
    //akka.pattern.internal.BackoffOnRestartSupervisor
    //akka.pattern.internal.BackoffOnStopSupervisor
    akka.pattern.internal.CircuitBreakerEnsembleTelemetry
    akka.pattern.internal.CircuitBreakerNoopTelemetry
    akka.pattern.internal.CircuitBreakerTelemetry
    //akka.pattern.internal.CircuitBreakerTelemetryProvider
    akka.routing.ActorRefRoutee
    akka.routing.ActorSelectionRoutee
    akka.routing.AddRoutee
    akka.routing.AdjustPoolSize
    //akka.routing.BalancingPool
    akka.routing.BalancingPoolDeploy
    akka.routing.BalancingRoutingLogic
    akka.routing.Broadcast
    //akka.routing.BroadcastGroup
    //akka.routing.BroadcastPool
    akka.routing.BroadcastRoutingLogic
    //akka.routing.ConsistentHash
    //akka.routing.ConsistentHashingGroup
    //akka.routing.ConsistentHashingPool
    //akka.routing.ConsistentHashingRouter
    //akka.routing.ConsistentHashingRoutingLogic
    akka.routing.ConsistentRoutee
    akka.routing.CustomRouterConfig
    akka.routing.Deafen
    //akka.routing.DefaultOptimalSizeExploringResizer
    //akka.routing.DefaultResizer
    //akka.routing.FromConfig
    akka.routing.GetRoutees
    akka.routing.Group
    akka.routing.GroupBase
    akka.routing.Listen
    akka.routing.ListenerMessage
    //akka.routing.Listeners
    //akka.routing.MurmurHash
    akka.routing.NoRoutee
    akka.routing.NoRouter
    //akka.routing.OptimalSizeExploringResizer
    //akka.routing.Pool
    akka.routing.PoolBase
    //akka.routing.PoolOverrideUnsetConfig
    //akka.routing.RandomGroup
    //akka.routing.RandomPool
    akka.routing.RandomRoutingLogic
    akka.routing.RemoveRoutee
    //akka.routing.ResizablePoolActor
    akka.routing.ResizablePoolCell
    akka.routing.Resizer
    akka.routing.ResizerInitializationException
    //akka.routing.RoundRobinGroup
    //akka.routing.RoundRobinPool
    akka.routing.RoundRobinRoutingLogic
    //akka.routing.RoutedActorCell
    //akka.routing.RoutedActorRef
    akka.routing.Routee
    //akka.routing.Routees
    //akka.routing.Router
    //akka.routing.RouterActor
    //akka.routing.RouterConfig
    akka.routing.RouterEnvelope
    akka.routing.RouterManagementMesssage
    //akka.routing.RouterPoolActor
    akka.routing.RoutingLogic
    //akka.routing.ScatterGatherFirstCompletedGroup
    //akka.routing.ScatterGatherFirstCompletedPool
    //akka.routing.ScatterGatherFirstCompletedRoutees
    akka.routing.ScatterGatherFirstCompletedRoutingLogic
    //akka.routing.SeveralRoutees
    //akka.routing.SmallestMailboxPool
    //akka.routing.SmallestMailboxRoutingLogic
    //akka.routing.TailChoppingGroup
    //akka.routing.TailChoppingPool
    //akka.routing.TailChoppingRoutees
    akka.routing.TailChoppingRoutingLogic
    akka.routing.WithListeners
    akka.serialization.AsyncSerializer
    //akka.serialization.AsyncSerializerWithStringManifest
    akka.serialization.AsyncSerializerWithStringManifestCS
    //akka.serialization.BaseSerializer
    //akka.serialization.BooleanSerializer
    //akka.serialization.ByteArraySerializer
    akka.serialization.ByteBufferSerializer
    akka.serialization.ByteStringSerializer
    //akka.serialization.DisabledJavaSerializer
    //akka.serialization.IntSerializer
    akka.serialization.JSerializer
    //akka.serialization.JavaSerializer
    //akka.serialization.LongSerializer
    akka.serialization.NullSerializer
    //akka.serialization.Serialization
    akka.serialization.SerializationExtension
    //akka.serialization.SerializationSetup
    akka.serialization.Serializer
    //akka.serialization.SerializerDetails
    //akka.serialization.SerializerWithStringManifest
    //akka.serialization.Serializers
    //akka.serialization.StringSerializer
    //akka.util.AlwaysIncreasingClock
    //akka.util.Base62
    //akka.util.BoundedBlockingQueue
    //akka.util.BoxedType
    //akka.util.ByteIterator
    //akka.util.ByteString
    //akka.util.ByteStringBuilder
    akka.util.ClassLoaderObjectInputStream
    //akka.util.Clock
    //akka.util.Collections
    //akka.util.CompactByteString
    akka.util.ConcurrentMultiMap
    //akka.util.ConstantFun
    //akka.util.DoubleLinkedList
    akka.util.ErrorMessages
    //akka.util.FastFrequencySketch
    akka.util.FlightRecorderLoader
    //akka.util.FrequencyList
    //akka.util.FrequencySketch
    //akka.util.FrequencySketchUtil
    //akka.util.HashCode
    //akka.util.Helpers
    //akka.util.ImmutableIntMap
    //akka.util.Index
    //akka.util.JavaDurationConverters
    akka.util.JavaVersion
    //akka.util.LineNumbers
    //akka.util.ManifestInfo
    //akka.util.MessageBuffer
    //akka.util.MessageBufferMap
    akka.util.NanoClock
    akka.util.NanoTimeTokenBucket
    //akka.util.OptionVal
    //akka.util.PrettyByteString
    //akka.util.PrettyDuration
    //akka.util.PriorityQueueStabilizer
    //akka.util.RecencyList
    //akka.util.ReentrantGuard
    //akka.util.Reflect
    //akka.util.ScheduledClock
    //akka.util.SegmentedRecencyList
    //akka.util.SerializedSuspendableExecutionContext
    //akka.util.StablePriorityBlockingQueue
    //akka.util.StablePriorityQueue
    akka.util.Subclassification
    //akka.util.SubclassifiedIndex
    //akka.util.Switch
    akka.util.Timeout
    //akka.util.TokenBucket
    //akka.util.TypedMultiMap
    akka.util.UUIDComparator
    //akka.util.Version
    //akka.util.WallClock
    //akka.util.WildcardIndex
    //akka.util.WildcardTree
    akka.util.ccompat.ccompatUsedUntil213
    akka.util.unused
  """)
}