package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.scalaVersion
import org.junit.Test

class AmmoniteSemanticTest extends SemanticTestBase("com.lihaoyi" % "ammonite_3.3.7" % "3.0.6")("ammonite") {
//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    //ammonite.AmmoniteMain
    ammonite.Constants
    //ammonite.Main
    //ammonite.MainRunner
    //ammonite.compiler.AmmonitePhase
    //ammonite.compiler.AsmPositionUpdater
    //ammonite.compiler.CodeClassWrapper
    //ammonite.compiler.CompatibilityParser
    //ammonite.compiler.Compiler
    //ammonite.compiler.CompilerBuilder
    //ammonite.compiler.CompilerExtensions
    //ammonite.compiler.CompilerLifecycleManager
    ammonite.compiler.CompilerUtil
    //ammonite.compiler.DefaultCodeWrapper
    //ammonite.compiler.DottyParser
    //ammonite.compiler.Extensions
    //ammonite.compiler.Parsers
    //ammonite.compiler.SyntaxHighlighting
    //ammonite.compiler.iface.CodeWrapper
    ammonite.compiler.iface.Compiler
    ammonite.compiler.iface.CompilerBuilder
    ammonite.compiler.iface.CompilerLifecycleManager
    //ammonite.compiler.iface.Parser
    ammonite.compiler.iface.Preprocessor
    //ammonite.compiler.internal.CompilerHelper
    ammonite.compiler.tools.desugar
    ammonite.compiler.tools.source
    //ammonite.interp.DependencyLoader
    //ammonite.interp.Interpreter
    //ammonite.interp.PredefInitialization
    //ammonite.interp.Watchable
    ammonite.interp.api.APIHolder
    ammonite.interp.api.AmmoniteExit
    ammonite.interp.api.InterpAPI
    ammonite.interp.api.InterpBridge
    ammonite.interp.api.InterpLoad
    //ammonite.interp.api.IvyConstructor
    ammonite.interp.api.LoadJar
    ammonite.interp.api.ScalaVersion
    //ammonite.interp.script.AmmoniteBuildServer
    ammonite.interp.script.Constants
    ammonite.interp.script.Diagnostic
    //ammonite.interp.script.DummyBuildServerImplems
    //ammonite.interp.script.Script
    //ammonite.interp.script.ScriptCache
    ammonite.interp.script.ScriptCompileResult
    //ammonite.interp.script.ScriptCompiler
    //ammonite.interp.script.ScriptProcessor
    //ammonite.interp.script.SemanticdbProcessor
    //ammonite.interp.script.SingleScriptCompiler
    //ammonite.main.Config
    //ammonite.main.Defaults
    ammonite.main.DefaultsScalaVersionSpecific
    //ammonite.main.ProxyFromEnv
    //ammonite.main.Scripts
    //ammonite.main.TrapExitSecurityManager
    //ammonite.repl.AmmCompleter
    //ammonite.repl.AmmHighlighter
    //ammonite.repl.AmmParser
    //ammonite.repl.AmmoniteFrontEnd
    //ammonite.repl.ClipboardImpl
    ammonite.repl.FrontEndAPIImpl
    //ammonite.repl.FrontEndUtils
    //ammonite.repl.FrontEnds
    //ammonite.repl.FullReplAPI
    ammonite.repl.FullReplAPIScalaVersionSpecific
    //ammonite.repl.PPrints
    //ammonite.repl.Repl
    //ammonite.repl.ReplApiImpl
    ammonite.repl.ReplBridge
    ammonite.repl.Scoped
    //ammonite.repl.SessionApiImpl
    //ammonite.repl.Signaller
    ammonite.repl.SyntaxError
    ammonite.repl.api.Clipboard
    ammonite.repl.api.FrontEnd
    ammonite.repl.api.FrontEndAPI
    ammonite.repl.api.FrontEndBridge
    //ammonite.repl.api.History
    ammonite.repl.api.ReplAPI
    ammonite.repl.api.ReplAPIScalaVersionSpecific
    ammonite.repl.api.ReplLoad
    ammonite.repl.api.Session
    ammonite.repl.api.SessionChanged
    //ammonite.repl.tools.Util
    ammonite.runtime.ForkClassLoader
    //ammonite.runtime.Frame
    //ammonite.runtime.ImportHook
    //ammonite.runtime.SessionChanged
    //ammonite.runtime.SpecialClassLoader
    //ammonite.runtime.Storage
    //ammonite.runtime.tools.GrepResult
    //ammonite.runtime.tools.Grepper
    //ammonite.runtime.tools.IvyThing
    //ammonite.runtime.tools.browse
    //ammonite.runtime.tools.grep
    //ammonite.runtime.tools.tail
    ammonite.runtime.tools.time
    //ammonite.terminal.AnsiNav
    ammonite.terminal.ClearScreen
    //ammonite.terminal.ConsoleDim
    //ammonite.terminal.Debug
    ammonite.terminal.DelegateFilter
    ammonite.terminal.Enum
    ammonite.terminal.Exit
    //ammonite.terminal.Filter
    //ammonite.terminal.FilterTools
    //ammonite.terminal.LazyList
    //ammonite.terminal.LineReader
    ammonite.terminal.Printing
    //ammonite.terminal.Prompt
    ammonite.terminal.Result
    //ammonite.terminal.SpecialKeys
    ammonite.terminal.Strings
    //ammonite.terminal.TTY
    ammonite.terminal.TermAction
    ammonite.terminal.TermInfo
    //ammonite.terminal.TermState
    //ammonite.terminal.Terminal
    //ammonite.terminal.filters.BasicFilters
    //ammonite.terminal.filters.GUILikeFilters
    //ammonite.terminal.filters.HistoryFilter
    //ammonite.terminal.filters.UndoFilter
    //ammonite.terminal.filters.UndoState
    ammonite.util.Bind
    //ammonite.util.Catching
    //ammonite.util.Classpath
    //ammonite.util.CodeColors
    //ammonite.util.Colors
    ammonite.util.CompilationError
    ammonite.util.Evaluated
    //ammonite.util.Ex
    ammonite.util.Frame
    //ammonite.util.ImportData
    ammonite.util.ImportHookInfo
    //ammonite.util.ImportTree
    //ammonite.util.Imports
    //ammonite.util.Name
    ammonite.util.Position
    //ammonite.util.PositionOffsetConversion
    ammonite.util.PredefInfo
    ammonite.util.Printer
    //ammonite.util.Ref
    ammonite.util.ReplClassLoader
    //ammonite.util.Res
    ammonite.util.ScriptOutput
    ammonite.util.StableRef
    ammonite.util.Tag
    //ammonite.util.Util
    //ammonite.util.WhiteListClassLoader
  """)
}