package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.scalaVersion
import org.junit.Test

class CatsEffectSemanticTest extends SemanticTestBase("org.typelevel" %% "cats-effect" % "3.6.3")("cats.effect") {
  override protected def enableKindProjectorPlugin = true

//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    //cats.effect.ArrayStack
    //cats.effect.ByteStack
    //cats.effect.CallbackStack
    //cats.effect.ContState
    //cats.effect.CpuStarvationCheck
    //cats.effect.CpuStarvationCheckPlatform
    //cats.effect.ExitCode
    //cats.effect.IO
    //cats.effect.IOApp
    //cats.effect.IOCompanionPlatform
    //cats.effect.IODeferred
    //cats.effect.IOFiber
    //cats.effect.IOFiberPlatform
    //cats.effect.IOLocal
    //cats.effect.IOLocalPlatform
    //cats.effect.IOLowPriorityImplicits
    //cats.effect.IOPlatform
    //cats.effect.LiftIO
    //cats.effect.NonDaemonThreadLogger
    //cats.effect.Platform
    //cats.effect.PlatformStatics
    //cats.effect.ResourceApp
    //cats.effect.Selector
    //cats.effect.SyncIO
    //cats.effect.SyncIOCompanionPlatform
    cats.effect.SyncIOLowPriorityImplicits
    //cats.effect.SyncStep
    //cats.effect.Trace
    cats.effect.implicits
    cats.effect.instances.AllInstances
    //cats.effect.kernel.Async
    //cats.effect.kernel.AsyncPlatform
    cats.effect.kernel.CancelScope
    //cats.effect.kernel.Clock
    //cats.effect.kernel.ClockPlatform
    cats.effect.kernel.Cont
    //cats.effect.kernel.Deferred
    cats.effect.kernel.DeferredSink
    //cats.effect.kernel.DeferredSource
    //cats.effect.kernel.Fiber
    //cats.effect.kernel.GenConcurrent
    //cats.effect.kernel.GenSpawn
    //cats.effect.kernel.GenTemporal
    //cats.effect.kernel.LowPriorityImplicits
    //cats.effect.kernel.MiniSemaphore
    //cats.effect.kernel.MonadCancel
    //cats.effect.kernel.Outcome
    //cats.effect.kernel.Par
    cats.effect.kernel.Poll
    //cats.effect.kernel.Ref
    cats.effect.kernel.RefSink
    //cats.effect.kernel.RefSource
    //cats.effect.kernel.Resource
    //cats.effect.kernel.ResourceAsync
    cats.effect.kernel.ResourceClock
    //cats.effect.kernel.ResourceConcurrent
    //cats.effect.kernel.ResourceDefer
    //cats.effect.kernel.ResourceFOInstances0
    //cats.effect.kernel.ResourceFOInstances1
    cats.effect.kernel.ResourceHOInstances0
    //cats.effect.kernel.ResourceHOInstances1
    //cats.effect.kernel.ResourceHOInstances2
    cats.effect.kernel.ResourceHOInstances3
    cats.effect.kernel.ResourceHOInstances4
    //cats.effect.kernel.ResourceHOInstances5
    cats.effect.kernel.ResourceMonad
    //cats.effect.kernel.ResourceMonadCancel
    cats.effect.kernel.ResourceMonadError
    cats.effect.kernel.ResourceMonoid
    cats.effect.kernel.ResourcePlatform
    cats.effect.kernel.ResourceSemigroup
    cats.effect.kernel.ResourceSemigroupK
    cats.effect.kernel.ResourceSync
    cats.effect.kernel.ResourceTemporal
    //cats.effect.kernel.Sync
    //cats.effect.kernel.SyncRef
    cats.effect.kernel.Unique
    cats.effect.kernel.implicits
    cats.effect.kernel.instances.AllInstances
    //cats.effect.kernel.instances.GenSpawnInstances
    cats.effect.kernel.syntax.AllSyntax
    //cats.effect.kernel.syntax.AsyncOps
    cats.effect.kernel.syntax.AsyncSyntax
    //cats.effect.kernel.syntax.ClockOps
    cats.effect.kernel.syntax.ClockSyntax
    //cats.effect.kernel.syntax.ConcurrentParSequenceNOps
    //cats.effect.kernel.syntax.ConcurrentParTraverseNOps
    //cats.effect.kernel.syntax.EffectResourceOps
    //cats.effect.kernel.syntax.GenConcurrentOps_
    cats.effect.kernel.syntax.GenConcurrentSyntax
    //cats.effect.kernel.syntax.GenSpawnOps
    //cats.effect.kernel.syntax.GenSpawnOps_
    //cats.effect.kernel.syntax.GenSpawnSyntax
    //cats.effect.kernel.syntax.GenTemporalOps
    cats.effect.kernel.syntax.GenTemporalOpsCompanionCompat
    //cats.effect.kernel.syntax.GenTemporalOps_
    cats.effect.kernel.syntax.GenTemporalOps_CompanionCompat
    //cats.effect.kernel.syntax.GenTemporalSyntax
    //cats.effect.kernel.syntax.MonadCancelOps
    //cats.effect.kernel.syntax.MonadCancelOps_
    //cats.effect.kernel.syntax.MonadCancelSyntax
    cats.effect.kernel.syntax.ResourceSyntax
    cats.effect.metrics.CpuStarvationWarningMetrics
    //cats.effect.metrics.JvmCpuStarvationMetrics
    //cats.effect.std.AtomicCell
    //cats.effect.std.Backpressure
    //cats.effect.std.Console
    //cats.effect.std.ConsoleCompanionCrossPlatform
    //cats.effect.std.ConsoleCompanionPlatform
    //cats.effect.std.ConsoleCrossPlatform
    //cats.effect.std.CountDownLatch
    //cats.effect.std.CyclicBarrier
    //cats.effect.std.Dequeue
    //cats.effect.std.DequeueSink
    //cats.effect.std.DequeueSource
    //cats.effect.std.Dispatcher
    //cats.effect.std.DispatcherPlatform
    //cats.effect.std.Env
    //cats.effect.std.EnvCompanionPlatform
    cats.effect.std.FailureSignal
    //cats.effect.std.Hotswap
    //cats.effect.std.MapRefCompanionPlatform
    //cats.effect.std.Mutex
    //cats.effect.std.PQueue
    //cats.effect.std.PQueueSink
    //cats.effect.std.PQueueSource
    //cats.effect.std.Queue
    //cats.effect.std.QueueSink
    //cats.effect.std.QueueSource
    //cats.effect.std.Random
    cats.effect.std.RandomCompanionPlatform
    //cats.effect.std.SecureRandom
    //cats.effect.std.SecureRandomCompanionPlatform
    //cats.effect.std.Semaphore
    //cats.effect.std.Supervisor
    //cats.effect.std.SystemProperties
    //cats.effect.std.UUIDGen
    cats.effect.std.UUIDGenCompanionPlatform
    cats.effect.std.UUIDGenCompanionPlatformLowPriority
    //cats.effect.std.UnsafeUnbounded
    //cats.effect.std.internal.BankersQueue
    //cats.effect.std.internal.BinomialHeap
    //cats.effect.std.internal.BinomialTree
    cats.effect.std.syntax.AllSyntax
    //cats.effect.std.syntax.BackpressureOps
    cats.effect.std.syntax.BackpressureSyntax
    //cats.effect.std.syntax.SupervisorOps
    cats.effect.std.syntax.SupervisorSyntax
    //cats.effect.std.unsafe.BoundedQueue
    cats.effect.std.unsafe.BoundedQueueSink
    //cats.effect.std.unsafe.UnboundedQueue
    cats.effect.std.unsafe.UnboundedQueueSink
    cats.effect.syntax.AllSyntax
    cats.effect.syntax.DispatcherSyntax
    //cats.effect.tracing.RingBuffer
    //cats.effect.tracing.Tracing
    cats.effect.tracing.TracingEvent
    //cats.effect.tracing.TracingPlatform
    //cats.effect.unsafe.BatchingMacrotaskExecutor
    //cats.effect.unsafe.FiberMonitor
    //cats.effect.unsafe.FiberMonitorShared
    //cats.effect.unsafe.IORuntime
    //cats.effect.unsafe.IORuntimeBuilder
    //cats.effect.unsafe.IORuntimeBuilderPlatform
    //cats.effect.unsafe.IORuntimeCompanionPlatform
    //cats.effect.unsafe.IORuntimeConfig
    //cats.effect.unsafe.IORuntimeConfigCompanionPlatform
    //cats.effect.unsafe.LocalQueue
    //cats.effect.unsafe.NoOpFiberMonitor
    cats.effect.unsafe.ParkedSignal
    cats.effect.unsafe.PollResult
    cats.effect.unsafe.PollingContext
    cats.effect.unsafe.PollingSystem
    //cats.effect.unsafe.ScalQueue
    cats.effect.unsafe.Scheduler
    //cats.effect.unsafe.SchedulerCompanionPlatform
    //cats.effect.unsafe.SelectorSystem
    //cats.effect.unsafe.SleepSystem
    //cats.effect.unsafe.StripedHashtable
    //cats.effect.unsafe.ThreadSafeHashtable
    //cats.effect.unsafe.TimerHeap
    cats.effect.unsafe.UnsafeNonFatal
    cats.effect.unsafe.UnsealedPollingContext
    //cats.effect.unsafe.WeakBag
    //cats.effect.unsafe.WeakList
    //cats.effect.unsafe.WorkStealingThreadPool
    //cats.effect.unsafe.WorkerThread
    cats.effect.unsafe.implicits
    cats.effect.unsafe.metrics.ComputePoolSampler
    cats.effect.unsafe.metrics.ComputePoolSamplerMBean
    cats.effect.unsafe.metrics.CpuStarvation
    cats.effect.unsafe.metrics.CpuStarvationMBean
    cats.effect.unsafe.metrics.CpuStarvationMetrics
    //cats.effect.unsafe.metrics.CpuStarvationSampler
    cats.effect.unsafe.metrics.IORuntimeMetrics
    //cats.effect.unsafe.metrics.IORuntimeMetricsCompanionPlatform
    cats.effect.unsafe.metrics.IORuntimeMetricsPlatform
    //cats.effect.unsafe.metrics.LiveFiberSnapshotTrigger
    cats.effect.unsafe.metrics.LiveFiberSnapshotTriggerMBean
    cats.effect.unsafe.metrics.LocalQueueMetrics
    cats.effect.unsafe.metrics.LocalQueueSampler
    cats.effect.unsafe.metrics.LocalQueueSamplerMBean
    //cats.effect.unsafe.metrics.PollerMetrics
    cats.effect.unsafe.metrics.PollerSampler
    cats.effect.unsafe.metrics.PollerSamplerMBean
    cats.effect.unsafe.metrics.TimerHeapMetrics
    cats.effect.unsafe.metrics.TimerHeapSampler
    cats.effect.unsafe.metrics.TimerHeapSamplerMBean
    //cats.effect.unsafe.metrics.WorkStealingThreadPoolMetrics
    cats.effect.unsafe.metrics.WorkerThreadMetrics
    cats.effect.unsafe.metrics.WorkerThreadSampler
    cats.effect.unsafe.metrics.WorkerThreadSamplerMBean
  """)
}