package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.scalaVersion
import org.junit.Test

class PlaySemanticTest extends SemanticTestBase("com.typesafe.play" %% "play" % "2.9.6")("play") {
//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    play.api.Application
    //play.api.ApplicationLoader
    play.api.ApplicationStoppedReason
    //play.api.BuiltInComponents
    play.api.BuiltInComponentsFromContext
    //play.api.ConfigLoader
    //play.api.Configuration
    play.api.ContextBasedBuiltInComponents
    //play.api.DefaultApplication
    play.api.DefaultMarkerContext
    //play.api.Environment
    //play.api.Logger
    //play.api.LoggerConfigurator
    //play.api.LoggerLike
    //play.api.Logging
    play.api.LowPriorityMarkerContextImplicits
    play.api.MarkerContext
    play.api.MarkerContexts
    play.api.Mode
    play.api.NoHttpFiltersComponents
    play.api.OptionalDevContext
    play.api.OptionalSourceMapper
    //play.api.OptionalSourceMapperProvider
    //play.api.Play
    //play.api.UnexpectedException
    play.api.controllers.TrampolineContextProvider
    //play.api.data.DefaultFormBinding
    //play.api.data.Field
    //play.api.data.FieldMapping
    //play.api.data.Form
    play.api.data.FormBinding
    //play.api.data.FormError
    play.api.data.FormJsonExpansionTooDeep
    play.api.data.FormJsonExpansionTooLarge
    //play.api.data.FormUtils
    //play.api.data.Forms
    //play.api.data.Mapping
    //play.api.data.ObjectMapping
    //play.api.data.ObjectMapping1
    //play.api.data.ObjectMapping10
    //play.api.data.ObjectMapping11
    //play.api.data.ObjectMapping12
    //play.api.data.ObjectMapping13
    //play.api.data.ObjectMapping14
    //play.api.data.ObjectMapping15
    //play.api.data.ObjectMapping16
    //play.api.data.ObjectMapping17
    //play.api.data.ObjectMapping18
    //play.api.data.ObjectMapping19
    //play.api.data.ObjectMapping2
    //play.api.data.ObjectMapping20
    //play.api.data.ObjectMapping21
    //play.api.data.ObjectMapping22
    //play.api.data.ObjectMapping3
    //play.api.data.ObjectMapping4
    //play.api.data.ObjectMapping5
    //play.api.data.ObjectMapping6
    //play.api.data.ObjectMapping7
    //play.api.data.ObjectMapping8
    //play.api.data.ObjectMapping9
    //play.api.data.OptionalMapping
    //play.api.data.RepeatedMapping
    //play.api.data.WrappedMapping
    //play.api.data.format.Formats
    play.api.data.format.Formatter
    play.api.data.format.PlayDate
    //play.api.data.validation.Constraint
    //play.api.data.validation.Constraints
    //play.api.data.validation.Invalid
    //play.api.data.validation.ParameterValidator
    play.api.data.validation.Valid
    play.api.data.validation.ValidationError
    play.api.data.validation.ValidationResult
    //play.api.http.AcceptEncoding
    //play.api.http.ActionCompositionConfiguration
    //play.api.http.ActionCreator
    //play.api.http.ContentEncoding
    play.api.http.ContentTypeOf
    //play.api.http.ContentTypes
    //play.api.http.CookiesConfiguration
    //play.api.http.DefaultContentTypeOfs
    //play.api.http.DefaultFileMimeTypes
    //play.api.http.DefaultFileMimeTypesProvider
    //play.api.http.DefaultHttpErrorHandler
    //play.api.http.DefaultHttpFilters
    //play.api.http.DefaultHttpRequestHandler
    //play.api.http.DefaultWriteables
    //play.api.http.DevHttpErrorHandler
    //play.api.http.EnabledFilters
    //play.api.http.EncodingPreference
    play.api.http.FileMimeTypes
    //play.api.http.FileMimeTypesConfiguration
    //play.api.http.FlashConfiguration
    play.api.http.HeaderNames
    //play.api.http.HtmlOrJsonHttpErrorHandler
    //play.api.http.HttpChunk
    //play.api.http.HttpConfiguration
    //play.api.http.HttpEntity
    //play.api.http.HttpErrorConfig
    play.api.http.HttpErrorHandler
    //play.api.http.HttpErrorHandlerExceptions
    //play.api.http.HttpErrorInfo
    //play.api.http.HttpFilters
    play.api.http.HttpProtocol
    play.api.http.HttpRequestHandler
    play.api.http.HttpVerbs
    //play.api.http.JWTConfiguration
    //play.api.http.JWTConfigurationParser
    //play.api.http.JavaCompatibleHttpRequestHandler
    //play.api.http.JavaHttpErrorHandlerDelegate
    //play.api.http.JavaHttpFiltersAdapter
    //play.api.http.JavaHttpFiltersDelegate
    //play.api.http.JsonHttpErrorHandler
    play.api.http.LowPriorityWriteables
    //play.api.http.MediaRange
    //play.api.http.MediaType
    play.api.http.MimeTypes
    play.api.http.NoHttpFilters
    //play.api.http.NotImplementedHttpRequestHandler
    //play.api.http.ParserConfiguration
    //play.api.http.Port
    play.api.http.PreferredMediaTypeHttpErrorHandler
    //play.api.http.SecretConfiguration
    //play.api.http.SessionConfiguration
    play.api.http.Status
    play.api.http.Writeable
    play.api.http.websocket.BinaryMessage
    play.api.http.websocket.CloseCodes
    //play.api.http.websocket.CloseMessage
    play.api.http.websocket.Message
    play.api.http.websocket.PingMessage
    play.api.http.websocket.PongMessage
    play.api.http.websocket.TextMessage
    //play.api.http.websocket.WebSocketCloseException
    //play.api.i18n.DefaultLangs
    //play.api.i18n.DefaultLangsProvider
    //play.api.i18n.DefaultMessagesApi
    //play.api.i18n.DefaultMessagesApiProvider
    //play.api.i18n.I18NSupportLowPriorityImplicits
    play.api.i18n.I18nComponents
    //play.api.i18n.I18nModule
    play.api.i18n.I18nSupport
    //play.api.i18n.Lang
    play.api.i18n.LangImplicits
    //play.api.i18n.Langs
    //play.api.i18n.Messages
    play.api.i18n.MessagesApi
    play.api.i18n.MessagesImpl
    play.api.i18n.MessagesImplicits
    play.api.i18n.MessagesProvider
    //play.api.inject.ApplicationLifecycle
    //play.api.inject.Binding
    //play.api.inject.BindingKey
    play.api.inject.BindingKeyTarget
    play.api.inject.BindingTarget
    //play.api.inject.BuiltinModule
    //play.api.inject.ConfigProvider
    play.api.inject.ConfigurationProvider
    play.api.inject.ConstructionTarget
    //play.api.inject.ContextClassLoaderInjector
    //play.api.inject.DefaultApplicationLifecycle
    //play.api.inject.EnvironmentProvider
    play.api.inject.Injector
    play.api.inject.Module
    //play.api.inject.Modules
    //play.api.inject.NewInstanceInjector
    play.api.inject.ProviderConstructionTarget
    play.api.inject.ProviderTarget
    play.api.inject.QualifierAnnotation
    play.api.inject.QualifierClass
    play.api.inject.QualifierInstance
    //play.api.inject.RoutesProvider
    //play.api.inject.SimpleInjector
    //play.api.inject.SimpleModule
    //play.api.inject.SourceLocator
    //play.api.internal.libs.concurrent.CoordinatedShutdownSupport
    play.api.libs.Codecs
    //play.api.libs.Collections
    //play.api.libs.Comet
    //play.api.libs.EventSource
    //play.api.libs.Files
    //play.api.libs.JNDI
    //play.api.libs.Jsonp
    //play.api.libs.concurrent.ActorRefProvider
    //play.api.libs.concurrent.ActorSystemProvider
    //play.api.libs.concurrent.Akka
    //play.api.libs.concurrent.AkkaComponents
    //play.api.libs.concurrent.AkkaSchedulerProvider
    play.api.libs.concurrent.AkkaTypedComponents
    //play.api.libs.concurrent.ClassicActorSystemProviderProvider
    //play.api.libs.concurrent.CoordinatedShutdownProvider
    play.api.libs.concurrent.CustomExecutionContext
    //play.api.libs.concurrent.DefaultFutures
    //play.api.libs.concurrent.ExecutionContextProvider
    play.api.libs.concurrent.Futures
    //play.api.libs.concurrent.InjectedActorSupport
    //play.api.libs.concurrent.LowPriorityFuturesImplicits
    //play.api.libs.concurrent.MaterializerProvider
    //play.api.libs.crypto.CSRFTokenSigner
    //play.api.libs.crypto.CSRFTokenSignerProvider
    play.api.libs.crypto.CookieSigner
    //play.api.libs.crypto.CookieSignerProvider
    //play.api.libs.crypto.DefaultCSRFTokenSigner
    //play.api.libs.crypto.DefaultCookieSigner
    play.api.libs.functional.Alternative
    play.api.libs.functional.AlternativeOps
    play.api.libs.functional.Applicative
    //play.api.libs.functional.ApplicativeOps
    play.api.libs.functional.ContravariantFunctor
    play.api.libs.functional.ContravariantFunctorExtractor
    play.api.libs.functional.ContravariantFunctorOps
    //play.api.libs.functional.DeprecatedApplicative
    //play.api.libs.functional.FunctionalBuilder
    //play.api.libs.functional.FunctionalBuilderOps
    play.api.libs.functional.FunctionalCanBuild
    play.api.libs.functional.Functor
    play.api.libs.functional.FunctorExtractor
    play.api.libs.functional.FunctorOps
    play.api.libs.functional.InvariantFunctor
    play.api.libs.functional.InvariantFunctorExtractor
    play.api.libs.functional.InvariantFunctorOps
    //play.api.libs.functional.Monoid
    play.api.libs.functional.MonoidOps
    //play.api.libs.functional.Reducer
    play.api.libs.functional.Variant
    play.api.libs.functional.VariantExtractor
    play.api.libs.functional.~
    play.api.libs.json.BigDecimalParseConfig
    play.api.libs.json.BigDecimalParseConfigImpl
    //play.api.libs.json.BigDecimalParseSettings
    play.api.libs.json.BigDecimalParser
    play.api.libs.json.BigDecimalSerializerConfig
    play.api.libs.json.BigDecimalSerializerSettings
    play.api.libs.json.ConstraintFormat
    //play.api.libs.json.ConstraintReads
    //play.api.libs.json.ConstraintWrites
    play.api.libs.json.DecimalSerializerSettingsImpl
    play.api.libs.json.DefaultFormat
    //play.api.libs.json.DefaultReads
    //play.api.libs.json.DefaultWrites
    //play.api.libs.json.EnumerationWrites
    //play.api.libs.json.EnvKeyReads
    //play.api.libs.json.EnvKeyWrites
    //play.api.libs.json.EnvReads
    //play.api.libs.json.EnvWrites
    play.api.libs.json.Format
    //play.api.libs.json.GeneratedReads
    //play.api.libs.json.GeneratedWrites
    //play.api.libs.json.IdxPathNode
    //play.api.libs.json.ImmutableLinkedHashMap
    //play.api.libs.json.ImplicitResolver
    //play.api.libs.json.JsArray
    //play.api.libs.json.JsBoolean
    //play.api.libs.json.JsDefined
    //play.api.libs.json.JsError
    play.api.libs.json.JsFalse
    //play.api.libs.json.JsLookup
    //play.api.libs.json.JsLookupResult
    //play.api.libs.json.JsMacroImpl
    //play.api.libs.json.JsMacros
    //play.api.libs.json.JsMacrosWithOptions
    //play.api.libs.json.JsNull
    play.api.libs.json.JsNumber
    //play.api.libs.json.JsObject
    //play.api.libs.json.JsObjectBuilder
    //play.api.libs.json.JsPath
    //play.api.libs.json.JsReadable
    //play.api.libs.json.JsResult
    play.api.libs.json.JsResultException
    play.api.libs.json.JsString
    //play.api.libs.json.JsSuccess
    play.api.libs.json.JsTrue
    play.api.libs.json.JsUndefined
    play.api.libs.json.JsValue
    //play.api.libs.json.JsValueMacros
    //play.api.libs.json.Json
    //play.api.libs.json.JsonConfig
    play.api.libs.json.JsonConfigImpl
    //play.api.libs.json.JsonConfiguration
    play.api.libs.json.JsonFacade
    //play.api.libs.json.JsonNaming
    play.api.libs.json.JsonParserSettings
    //play.api.libs.json.JsonValidationError
    //play.api.libs.json.KeyPathNode
    //play.api.libs.json.KeyReads
    play.api.libs.json.KeyWrites
    //play.api.libs.json.LowPriorityDefaultReads
    //play.api.libs.json.LowPriorityKeyReads
    //play.api.libs.json.LowPriorityWrites
    //play.api.libs.json.MacroHelpers
    //play.api.libs.json.MapWrites
    play.api.libs.json.OFormat
    //play.api.libs.json.OWrites
    play.api.libs.json.OptionHandlers
    //play.api.libs.json.OptionSupport
    play.api.libs.json.PathFormat
    play.api.libs.json.PathNode
    //play.api.libs.json.PathReads
    //play.api.libs.json.PathWrites
    //play.api.libs.json.QuotesHelper
    //play.api.libs.json.Reads
    //play.api.libs.json.RecursiveSearch
    play.api.libs.json.ScalaCollectionCompat
    play.api.libs.json.StaticBinding
    //play.api.libs.json.Writes
    play.api.libs.json.jackson.DeserializerContext
    //play.api.libs.json.jackson.JacksonJson
    //play.api.libs.json.jackson.JsValueSerializer
    //play.api.libs.json.jackson.KeyRead
    //play.api.libs.json.jackson.PlayDeserializers
    play.api.libs.json.jackson.PlayJsonMapperModule
    play.api.libs.json.jackson.PlayJsonModule
    //play.api.libs.json.jackson.PlaySerializers
    //play.api.libs.json.jackson.ReadingList
    play.api.libs.json.jackson.ReadingMap
    play.api.libs.json.util.LazyHelper
    //play.api.libs.streams.Accumulator
    //play.api.libs.streams.ActorFlow
    //play.api.libs.streams.AkkaStreams
    //play.api.libs.streams.Execution
    //play.api.libs.streams.FlattenedAccumulator
    //play.api.libs.streams.GzipFlow
    //play.api.libs.streams.Probes
    //play.api.libs.streams.SinkAccumulator
    //play.api.libs.streams.StrictAccumulator
    //play.api.libs.typedmap.DefaultTypedMap
    play.api.libs.typedmap.TypedEntry
    //play.api.libs.typedmap.TypedKey
    //play.api.libs.typedmap.TypedMap
    play.api.mvc.AbstractController
    play.api.mvc.AcceptExtractors
    play.api.mvc.Accepting
    //play.api.mvc.Action
    //play.api.mvc.ActionBuilder
    play.api.mvc.ActionBuilderImpl
    play.api.mvc.ActionFilter
    //play.api.mvc.ActionFunction
    //play.api.mvc.ActionRefiner
    //play.api.mvc.ActionTransformer
    play.api.mvc.AnyContent
    play.api.mvc.AnyContentAsEmpty
    play.api.mvc.AnyContentAsFormUrlEncoded
    play.api.mvc.AnyContentAsJson
    play.api.mvc.AnyContentAsMultipartFormData
    play.api.mvc.AnyContentAsRaw
    play.api.mvc.AnyContentAsText
    play.api.mvc.AnyContentAsXml
    play.api.mvc.BaseController
    //play.api.mvc.BaseControllerHelpers
    //play.api.mvc.BodyParser
    //play.api.mvc.BodyParserUtils
    //play.api.mvc.BodyParsers
    //play.api.mvc.ByteRange
    //play.api.mvc.Call
    play.api.mvc.Codec
    play.api.mvc.ControllerComponents
    //play.api.mvc.ControllerHelpers
    //play.api.mvc.Cookie
    //play.api.mvc.CookieBaker
    play.api.mvc.CookieDataCodec
    //play.api.mvc.CookieHeaderEncoding
    play.api.mvc.CookieHeaderMerging
    //play.api.mvc.Cookies
    play.api.mvc.CookiesModule
    play.api.mvc.DefaultActionBuilder
    //play.api.mvc.DefaultActionBuilderImpl
    //play.api.mvc.DefaultControllerComponents
    //play.api.mvc.DefaultCookieHeaderEncoding
    //play.api.mvc.DefaultFlashCookieBaker
    //play.api.mvc.DefaultJWTCookieDataCodec
    //play.api.mvc.DefaultMessagesActionBuilderImpl
    //play.api.mvc.DefaultMessagesControllerComponents
    //play.api.mvc.DefaultPlayBodyParsers
    //play.api.mvc.DefaultRangeSet
    //play.api.mvc.DefaultSessionCookieBaker
    play.api.mvc.DefaultUrlEncodedCookieDataCodec
    //play.api.mvc.DiscardingCookie
    //play.api.mvc.EssentialAction
    //play.api.mvc.EssentialFilter
    //play.api.mvc.FallbackCookieDataCodec
    //play.api.mvc.Filter
    //play.api.mvc.FilterChain
    play.api.mvc.Filters
    //play.api.mvc.Flash
    play.api.mvc.FlashCookieBaker
    //play.api.mvc.Handler
    //play.api.mvc.Headers
    play.api.mvc.InjectedController
    //play.api.mvc.JWTCookieDataCodec
    //play.api.mvc.JavascriptLiteral
    play.api.mvc.LegacyCookiesModule
    //play.api.mvc.LegacyFlashCookieBaker
    //play.api.mvc.LegacyI18nSupport
    //play.api.mvc.LegacySessionCookieBaker
    play.api.mvc.MaxSizeExceeded
    play.api.mvc.MaxSizeNotExceeded
    play.api.mvc.MaxSizeStatus
    //play.api.mvc.MessagesAbstractController
    play.api.mvc.MessagesActionBuilder
    play.api.mvc.MessagesActionBuilderImpl
    play.api.mvc.MessagesBaseController
    play.api.mvc.MessagesControllerComponents
    play.api.mvc.MessagesInjectedController
    //play.api.mvc.MessagesRequest
    play.api.mvc.MessagesRequestHeader
    //play.api.mvc.MultipartFormData
    play.api.mvc.NoHeaderRangeSet
    //play.api.mvc.PathBindable
    //play.api.mvc.PathBindableMacros
    //play.api.mvc.PlayBodyParsers
    play.api.mvc.PreferredMessagesProvider
    //play.api.mvc.QueryStringBindable
    //play.api.mvc.QueryStringBindableMacros
    //play.api.mvc.Range
    //play.api.mvc.RangeResult
    //play.api.mvc.RangeSet
    //play.api.mvc.RawBuffer
    //play.api.mvc.Request
    play.api.mvc.RequestExtractors
    //play.api.mvc.RequestHeader
    play.api.mvc.RequestHeaderImpl
    play.api.mvc.RequestImpl
    play.api.mvc.RequestImplicits
    //play.api.mvc.ResponseHeader
    //play.api.mvc.Result
    //play.api.mvc.Results
    play.api.mvc.SatisfiableRangeSet
    //play.api.mvc.Security
    //play.api.mvc.Session
    //play.api.mvc.SessionCookieBaker
    //play.api.mvc.UnsatisfiableRangeSet
    //play.api.mvc.UrlEncodedCookieDataCodec
    //play.api.mvc.WebSocket
    //play.api.mvc.WithEntityLengthRange
    //play.api.mvc.WithoutEntityLengthRange
    play.api.mvc.WrappedRequest
    //play.api.mvc.macros.BinderMacros
    play.api.mvc.request.AssignedCell
    play.api.mvc.request.Cell
    //play.api.mvc.request.DefaultRequestFactory
    play.api.mvc.request.LazyCell
    //play.api.mvc.request.RemoteConnection
    play.api.mvc.request.RequestAttrKey
    play.api.mvc.request.RequestFactory
    //play.api.mvc.request.RequestTarget
    //play.api.routing.HandlerDef
    play.api.routing.JavaScriptReverseRoute
    //play.api.routing.JavaScriptReverseRouter
    //play.api.routing.Router
    //play.api.routing.SimpleRouter
    play.api.routing.SimpleRouterImpl
    play.api.routing.sird.OptionalQueryStringParameter
    //play.api.routing.sird.PathBindableExtractor
    play.api.routing.sird.PathBindableExtractors
    //play.api.routing.sird.PathExtractor
    //play.api.routing.sird.PathPart
    //play.api.routing.sird.QueryStringParameterExtractor
    play.api.routing.sird.RequestMethodExtractor
    play.api.routing.sird.RequestMethodExtractors
    play.api.routing.sird.RequiredQueryStringParameter
    play.api.routing.sird.SeqQueryStringParameter
    //play.api.routing.sird.macroimpl.QueryStringParameterMacros
    //play.api.templates.PlayMagic
    play.core.ApplicationProvider
    //play.core.DefaultWebCommands
    play.core.Execution
    play.core.HandleWebCommandSupport
    play.core.NamedThreadFactory
    play.core.PlayVersion
    //play.core.SourceMapper
    play.core.WebCommands
    //play.core.formatters.Multipart
    play.core.j.ClassLoaderExecutionContext
    //play.core.j.DefaultJavaContextComponents
    //play.core.j.DefaultJavaHandlerComponents
    play.core.j.HttpExecutionContext
    //play.core.j.JavaAction
    //play.core.j.JavaActionAnnotations
    play.core.j.JavaContextComponents
    play.core.j.JavaHandler
    play.core.j.JavaHandlerComponents
    //play.core.j.JavaHelpers
    //play.core.j.JavaHttpErrorHandlerAdapter
    //play.core.j.JavaHttpRequestHandlerAdapter
    //play.core.j.JavaHttpRequestHandlerDelegate
    play.core.j.JavaModeConverter
    //play.core.j.JavaParsers
    //play.core.j.JavaRangeResult
    //play.core.j.JavaResultExtractor
    //play.core.j.JavaRouterAdapter
    //play.core.j.RequestHeaderImpl
    //play.core.j.RequestImpl
    //play.core.parsers.FormUrlEncodedParser
    //play.core.parsers.Multipart
    play.core.routing.DynamicPart
    //play.core.routing.GeneratedRouter
    play.core.routing.HandlerInvoker
    //play.core.routing.HandlerInvokerFactory
    play.core.routing.Include
    play.core.routing.Param
    play.core.routing.PathPart
    //play.core.routing.PathPattern
    //play.core.routing.ReverseRouteContext
    //play.core.routing.Route
    //play.core.routing.RouteParams
    play.core.routing.StaticPart
    //play.core.system.RequestIdProvider
    play.core.utils.AsciiBitSet
    //play.core.utils.AsciiChar
    //play.core.utils.AsciiRange
    //play.core.utils.AsciiSet
    play.core.utils.AsciiUnion
    play.core.utils.CaseInsensitiveOrdered
    //play.core.utils.HttpHeaderParameterEncoding
    play.server.api.SSLEngineProvider
    play.twirl.api.Appendable
    //play.twirl.api.BaseScalaTemplate
    //play.twirl.api.BufferedContent
    play.twirl.api.Content
    //play.twirl.api.Format
    play.twirl.api.Formats
    //play.twirl.api.Html
    play.twirl.api.HtmlFormat
    //play.twirl.api.JavaScript
    play.twirl.api.JavaScriptFormat
    play.twirl.api.MimeTypes
    play.twirl.api.Template0
    play.twirl.api.Template1
    play.twirl.api.Template10
    play.twirl.api.Template11
    play.twirl.api.Template12
    play.twirl.api.Template13
    play.twirl.api.Template14
    play.twirl.api.Template15
    play.twirl.api.Template16
    play.twirl.api.Template17
    play.twirl.api.Template18
    play.twirl.api.Template19
    play.twirl.api.Template2
    play.twirl.api.Template20
    play.twirl.api.Template21
    play.twirl.api.Template22
    play.twirl.api.Template3
    play.twirl.api.Template4
    play.twirl.api.Template5
    play.twirl.api.Template6
    play.twirl.api.Template7
    play.twirl.api.Template8
    play.twirl.api.Template9
    //play.twirl.api.TwirlFeatureImports
    //play.twirl.api.TwirlHelperImports
    //play.twirl.api.Txt
    play.twirl.api.TxtFormat
    //play.twirl.api.Xml
    play.twirl.api.XmlFormat
    //play.twirl.api.utils.StringEscapeUtils
    //play.utils.Colors
    play.utils.Conversions
    play.utils.DeserializerContext
    play.utils.ExecCtxUtils
    //play.utils.InlineCache
    play.utils.InvalidUriEncodingException
    //play.utils.JacksonJsonNodeModule
    //play.utils.JsonNodeDeserializer
    //play.utils.KeyRead
    //play.utils.OrderPreserving
    //play.utils.PlayIO
    play.utils.ProxyDriver
    //play.utils.ReadingList
    play.utils.ReadingMap
    //play.utils.Reflect
    //play.utils.Resources
    play.utils.Threads
    //play.utils.UriEncoding
  """)
}