package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.scalaVersion
import org.junit.Test

class QuillSemanticTest extends SemanticTestBase("io.getquill" %% "quill-sql" % "4.8.4", "io.getquill" %% "quill-jdbc-zio" % "4.8.4")("io.getquill") {
//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    io.getquill.Action
    io.getquill.ActionReturning
    //io.getquill.AstPrinter
    //io.getquill.BatchAction
    //io.getquill.CamelCase
    io.getquill.CaseClassLift
    io.getquill.CompositeNamingStrategy
    io.getquill.CompositeNamingStrategy2
    io.getquill.CompositeNamingStrategy3
    io.getquill.CompositeNamingStrategy4
    io.getquill.DateFormats
    io.getquill.Delete
    io.getquill.DynamicAction
    io.getquill.DynamicActionReturning
    io.getquill.DynamicAlias
    io.getquill.DynamicDelete
    io.getquill.DynamicDslModel
    //io.getquill.DynamicEntityQuery
    //io.getquill.DynamicInsert
    //io.getquill.DynamicJoinQuery
    //io.getquill.DynamicQuery
    io.getquill.DynamicSet
    io.getquill.DynamicSetEmpty
    io.getquill.DynamicSetValue
    io.getquill.DynamicUpdate
    io.getquill.EagerEntitiesPlanter
    io.getquill.EagerListPlanter
    io.getquill.EagerPlanter
    io.getquill.Embedable
    io.getquill.Embedded
    //io.getquill.EntityQuery
    io.getquill.EntityQueryModel
    io.getquill.Escape
    io.getquill.FromString
    //io.getquill.H2Dialect
    //io.getquill.H2JdbcContext
    io.getquill.H2ZioJdbcContext
    //io.getquill.IdiomContext
    //io.getquill.InfixInterpolator
    io.getquill.InfixValue
    //io.getquill.InjectableEagerPlanter
    io.getquill.Insert
    io.getquill.InsertMeta
    //io.getquill.JdbcContextConfig
    io.getquill.JoinQuery
    io.getquill.JsonValue
    io.getquill.JsonbValue
    io.getquill.LazyPlanter
    io.getquill.Literal
    io.getquill.LowerCase
    io.getquill.MappedEncoding
    //io.getquill.MirrorColumnResolving
    //io.getquill.MirrorContext
    //io.getquill.MirrorContextBase
    io.getquill.MirrorIdiom
    //io.getquill.MirrorIdiomBase
    io.getquill.MirrorIdiomPrinting
    io.getquill.MirrorSqlDialect
    io.getquill.MirrorSqlDialectWithBooleanLiterals
    io.getquill.MirrorSqlDialectWithNoReturn
    io.getquill.MirrorSqlDialectWithOutputClause
    io.getquill.MirrorSqlDialectWithReturnClause
    io.getquill.MirrorSqlDialectWithReturnMulti
    io.getquill.MySQL5Dialect
    //io.getquill.MySQLDialect
    io.getquill.MysqlEscape
    //io.getquill.MysqlJdbcContext
    io.getquill.MysqlZioJdbcContext
    io.getquill.NamingStrategy
    //io.getquill.OracleDialect
    //io.getquill.OracleJdbcContext
    io.getquill.OracleZioJdbcContext
    io.getquill.Ord
    io.getquill.Planter
    io.getquill.PluralizedTableNames
    //io.getquill.PostgresDialect
    //io.getquill.PostgresEscape
    //io.getquill.PostgresJdbcContext
    io.getquill.PostgresZioJdbcContext
    io.getquill.PseudoAst
    io.getquill.QAC
    //io.getquill.Query
    io.getquill.QueryMeta
    io.getquill.QueryProbing
    //io.getquill.QuotationLot
    io.getquill.QuotationVase
    //io.getquill.Quoted
    //io.getquill.ReplaceAssignmentAliases
    //io.getquill.ReplaceLiftings
    io.getquill.ReturnAction
    //io.getquill.SQLServerDialect
    io.getquill.SchemaMeta
    //io.getquill.SnakeCase
    //io.getquill.SpliceDate
    //io.getquill.SpliceDouble
    //io.getquill.SpliceFloat
    //io.getquill.SpliceInt
    //io.getquill.SpliceLocalDate
    //io.getquill.SpliceLocalDateTime
    //io.getquill.SpliceLong
    //io.getquill.SpliceShort
    //io.getquill.SpliceString
    //io.getquill.SqlInfixInterpolator
    io.getquill.SqlMirrorContext
    //io.getquill.SqlServerJdbcContext
    io.getquill.SqlServerZioJdbcContext
    //io.getquill.SqliteDialect
    //io.getquill.SqliteJdbcContext
    io.getquill.SqliteZioJdbcContext
    //io.getquill.StringCodec
    //io.getquill.ToDynamicAction
    //io.getquill.ToDynamicActionReturning
    //io.getquill.ToDynamicEntityQuery
    //io.getquill.ToDynamicInsert
    //io.getquill.ToDynamicQuery
    //io.getquill.ToDynamicUpdate
    io.getquill.ToSql
    io.getquill.ToString
    io.getquill.Udt
    io.getquill.Unquote
    io.getquill.Unquoteable
    io.getquill.Update
    io.getquill.UpdateMeta
    io.getquill.UpperCase
    //io.getquill.UpperCaseEscapeColumn
    io.getquill.UpperCaseNonDefault
    io.getquill.WithProbing
    //io.getquill.WithProbingPrefix
    //io.getquill.ast.+!=+
    //io.getquill.ast.+&&+
    //io.getquill.ast.+==+
    //io.getquill.ast.+||+
    io.getquill.ast.Action
    //io.getquill.ast.Aggregation
    io.getquill.ast.AggregationOperator
    io.getquill.ast.Asc
    io.getquill.ast.AscNullsFirst
    io.getquill.ast.AscNullsLast
    io.getquill.ast.Assignment
    io.getquill.ast.AssignmentDual
    //io.getquill.ast.Ast
    //io.getquill.ast.BinaryOperation
    io.getquill.ast.BinaryOperator
    io.getquill.ast.Block
    io.getquill.ast.BooleanOperator
    io.getquill.ast.BottomTypedTerminal
    //io.getquill.ast.CaseClass
    io.getquill.ast.CaseClassLift
    //io.getquill.ast.CaseClassQueryLift
    //io.getquill.ast.CaseClassValueLift
    //io.getquill.ast.CollectAst
    io.getquill.ast.ConcatMap
    //io.getquill.ast.Constant
    io.getquill.ast.Core
    io.getquill.ast.Delete
    io.getquill.ast.Desc
    io.getquill.ast.DescNullsFirst
    io.getquill.ast.DescNullsLast
    io.getquill.ast.Distinct
    io.getquill.ast.DistinctOn
    io.getquill.ast.Drop
    //io.getquill.ast.Dynamic
    //io.getquill.ast.Entity
    io.getquill.ast.EqualityOperator
    io.getquill.ast.External
    //io.getquill.ast.ExternalIdent
    io.getquill.ast.Filter
    io.getquill.ast.FilterIfDefined
    io.getquill.ast.FlatJoin
    io.getquill.ast.FlatMap
    io.getquill.ast.Foreach
    io.getquill.ast.FullJoin
    io.getquill.ast.Function
    io.getquill.ast.FunctionApply
    io.getquill.ast.GroupBy
    io.getquill.ast.GroupByMap
    //io.getquill.ast.Ident
    io.getquill.ast.IdentName
    //io.getquill.ast.If
    //io.getquill.ast.IfExist
    //io.getquill.ast.IfExistElseNull
    //io.getquill.ast.Implicits
    //io.getquill.ast.Infix
    io.getquill.ast.InnerJoin
    io.getquill.ast.Insert
    //io.getquill.ast.IsNotNullCheck
    //io.getquill.ast.IsNullCheck
    io.getquill.ast.IterableOperation
    io.getquill.ast.Join
    io.getquill.ast.JoinType
    io.getquill.ast.LeftJoin
    io.getquill.ast.Lift
    io.getquill.ast.ListContains
    io.getquill.ast.Map
    io.getquill.ast.MapContains
    io.getquill.ast.Nested
    io.getquill.ast.NullValue
    io.getquill.ast.NumericOperator
    io.getquill.ast.OnConflict
    io.getquill.ast.Operation
    io.getquill.ast.Operator
    io.getquill.ast.Opinion
    //io.getquill.ast.OpinionValues
    io.getquill.ast.OptionApply
    io.getquill.ast.OptionContains
    io.getquill.ast.OptionExists
    io.getquill.ast.OptionFlatMap
    io.getquill.ast.OptionFlatten
    io.getquill.ast.OptionForall
    io.getquill.ast.OptionGetOrElse
    io.getquill.ast.OptionGetOrNull
    io.getquill.ast.OptionIsDefined
    io.getquill.ast.OptionIsEmpty
    io.getquill.ast.OptionMap
    io.getquill.ast.OptionNonEmpty
    io.getquill.ast.OptionNone
    io.getquill.ast.OptionNoneId
    io.getquill.ast.OptionOperation
    io.getquill.ast.OptionOrElse
    io.getquill.ast.OptionOrNull
    io.getquill.ast.OptionSome
    io.getquill.ast.OptionTableExists
    io.getquill.ast.OptionTableFlatMap
    io.getquill.ast.OptionTableForall
    io.getquill.ast.OptionTableMap
    io.getquill.ast.Ordering
    io.getquill.ast.PostfixUnaryOperator
    io.getquill.ast.PrefixUnaryOperator
    //io.getquill.ast.Property
    io.getquill.ast.PropertyAlias
    io.getquill.ast.PropertyOrCore
    io.getquill.ast.PropertyOrdering
    io.getquill.ast.Query
    //io.getquill.ast.QuotationTag
    io.getquill.ast.QuotationTagId
    io.getquill.ast.QuotedReference
    io.getquill.ast.Renameable
    io.getquill.ast.Returning
    io.getquill.ast.ReturningAction
    io.getquill.ast.ReturningGenerated
    io.getquill.ast.RightJoin
    io.getquill.ast.ScalarLift
    //io.getquill.ast.ScalarQueryLift
    //io.getquill.ast.ScalarTag
    io.getquill.ast.ScalarTagId
    //io.getquill.ast.ScalarValueLift
    io.getquill.ast.SetContains
    io.getquill.ast.SetOperator
    io.getquill.ast.SortBy
    //io.getquill.ast.StatefulTransformer
    //io.getquill.ast.StatefulTransformerWithStack
    //io.getquill.ast.StatelessTransformer
    io.getquill.ast.StringOperator
    io.getquill.ast.Tag
    io.getquill.ast.Take
    io.getquill.ast.Terminal
    //io.getquill.ast.Transform
    io.getquill.ast.Tuple
    io.getquill.ast.TupleOrdering
    io.getquill.ast.UnaryOperation
    io.getquill.ast.UnaryOperator
    io.getquill.ast.Union
    io.getquill.ast.UnionAll
    io.getquill.ast.Update
    io.getquill.ast.Val
    io.getquill.ast.Value
    io.getquill.ast.Visibility
    //io.getquill.compat
    io.getquill.context.ActionEntity
    io.getquill.context.AstSplicing
    io.getquill.context.CanInsertReturningWithMultiValues
    io.getquill.context.CanInsertReturningWithSingleValue
    io.getquill.context.CanInsertWithMultiValues
    io.getquill.context.CanInsertWithSingleValue
    io.getquill.context.CanOutputClause
    io.getquill.context.CanReturnClause
    io.getquill.context.CanReturnField
    io.getquill.context.CanReturnMultiField
    io.getquill.context.CannotReturn
    //io.getquill.context.Context
    io.getquill.context.ContextEffect
    //io.getquill.context.ContextOperation
    io.getquill.context.ContextStandard
    //io.getquill.context.ContextTranslateMacro
    //io.getquill.context.ContextTranslateProto
    //io.getquill.context.ContextVerbPrepare
    //io.getquill.context.ContextVerbPrepareLambda
    //io.getquill.context.ContextVerbStream
    //io.getquill.context.ContextVerbTranslate
    //io.getquill.context.DatasourceContextInjectionMacro
    //io.getquill.context.Execution
    io.getquill.context.ExecutionInfo
    io.getquill.context.ExecutionType
    //io.getquill.context.ExtractLifts
    //io.getquill.context.Extraction
    //io.getquill.context.HasDynamicSplicingHint
    io.getquill.context.IdiomInsertReturningValueCapability
    io.getquill.context.IdiomInsertValueCapability
    io.getquill.context.IdiomReturningCapability
    //io.getquill.context.InsertMetaMacro
    io.getquill.context.InsertReturningValueMulti
    io.getquill.context.InsertReturningValueSingle
    io.getquill.context.InsertReturningValuesCapability
    //io.getquill.context.InsertUpdateMacro
    io.getquill.context.InsertValueMulti
    io.getquill.context.InsertValueSingle
    io.getquill.context.InsertValuesCapability
    //io.getquill.context.LiftMacro
    //io.getquill.context.LiftQueryMacro
    //io.getquill.context.LiftsExtractor
    //io.getquill.context.MetaMacro
    io.getquill.context.OutputClauseSupported
    //io.getquill.context.Particularize
    io.getquill.context.PossiblyInfixAction
    //io.getquill.context.PrepareBatchComponents
    //io.getquill.context.PrepareDynamicExecution
    //io.getquill.context.ProtoContext
    //io.getquill.context.ProtoContextSecundus
    //io.getquill.context.ProtoStreamContext
    //io.getquill.context.ProtoStreamContext
    //io.getquill.context.QueryExecution
    //io.getquill.context.QueryExecutionBatch
    //io.getquill.context.QueryExecutionBatchDynamic
    //io.getquill.context.QueryExecutionBatchIteration
    //io.getquill.context.QueryExecutionBatchModel
    //io.getquill.context.QueryMacro
    //io.getquill.context.QueryMetaExtractor
    //io.getquill.context.QueryMetaMacro
    //io.getquill.context.QuerySingleAsQuery
    //io.getquill.context.QuoteMacro
    //io.getquill.context.ReflectivePathChainLookup
    io.getquill.context.ReturningCapability
    io.getquill.context.ReturningClauseSupported
    io.getquill.context.ReturningMultipleFieldSupported
    io.getquill.context.ReturningNotSupported
    io.getquill.context.ReturningSingleFieldSupported
    //io.getquill.context.RowContext
    //io.getquill.context.RunDynamicExecution
    io.getquill.context.RunnerSummoningBehavior
    //io.getquill.context.SchemaMetaMacro
    io.getquill.context.SplicingBehavior
    io.getquill.context.SplicingBehaviorHint
    //io.getquill.context.StaticSpliceMacro
    //io.getquill.context.StaticState
    //io.getquill.context.StaticTranslationMacro
    //io.getquill.context.SummonDecoderMacro
    //io.getquill.context.Unparticular
    //io.getquill.context.UnquoteMacro
    //io.getquill.context.UpdateMetaMacro
    //io.getquill.context.VerifyFreeVariables
    //io.getquill.context.ZioJdbc
    //io.getquill.context.cassandra.CqlIdiom
    //io.getquill.context.cassandra.CqlNormalize
    //io.getquill.context.cassandra.CqlQuery
    //io.getquill.context.cassandra.ExpandMappedInfixCassandra
    io.getquill.context.cassandra.OrderByCriteria
    //io.getquill.context.jdbc.ArrayDecoders
    //io.getquill.context.jdbc.ArrayEncoders
    //io.getquill.context.jdbc.BasicTimeDecoders
    //io.getquill.context.jdbc.BasicTimeEncoders
    //io.getquill.context.jdbc.BooleanIntEncoding
    //io.getquill.context.jdbc.BooleanObjectEncoding
    //io.getquill.context.jdbc.Decoders
    //io.getquill.context.jdbc.Encoders
    io.getquill.context.jdbc.H2JdbcContextBase
    io.getquill.context.jdbc.H2JdbcTypes
    //io.getquill.context.jdbc.JdbcContext
    //io.getquill.context.jdbc.JdbcContextBase
    io.getquill.context.jdbc.JdbcContextTypes
    //io.getquill.context.jdbc.JdbcContextVerbExecute
    //io.getquill.context.jdbc.JdbcContextVerbPrepare
    io.getquill.context.jdbc.MysqlJdbcContextBase
    io.getquill.context.jdbc.MysqlJdbcTypes
    //io.getquill.context.jdbc.ObjectGenericTimeDecoders
    //io.getquill.context.jdbc.ObjectGenericTimeEncoders
    io.getquill.context.jdbc.OracleJdbcContextBase
    io.getquill.context.jdbc.OracleJdbcTypes
    io.getquill.context.jdbc.PostgresJdbcContextBase
    //io.getquill.context.jdbc.PostgresJdbcTypes
    //io.getquill.context.jdbc.ResultSetExtractor
    //io.getquill.context.jdbc.SqlServerExecuteOverride
    io.getquill.context.jdbc.SqlServerJdbcContextBase
    io.getquill.context.jdbc.SqlServerJdbcTypes
    //io.getquill.context.jdbc.SqliteExecuteOverride
    io.getquill.context.jdbc.SqliteJdbcContextBase
    io.getquill.context.jdbc.SqliteJdbcTypes
    //io.getquill.context.jdbc.UUIDObjectEncoding
    //io.getquill.context.jdbc.UUIDStringEncoding
    //io.getquill.context.json.PostgresJsonExtensions
    //io.getquill.context.mirror.ArrayMirrorEncoding
    //io.getquill.context.mirror.MirrorDecoders
    //io.getquill.context.mirror.MirrorEncoders
    io.getquill.context.mirror.MirrorSession
    //io.getquill.context.mirror.Row
    //io.getquill.context.qzio.ImplicitSyntax
    //io.getquill.context.qzio.ResultSetIterator
    //io.getquill.context.qzio.ZioContext
    //io.getquill.context.qzio.ZioJdbcContext
    //io.getquill.context.qzio.ZioJdbcUnderlyingContext
    //io.getquill.context.qzio.ZioPrepareContext
    //io.getquill.context.qzio.ZioTranslateContext
    //io.getquill.context.sql.CaseClassMake
    io.getquill.context.sql.DistinctKind
    io.getquill.context.sql.FlatJoinContext
    //io.getquill.context.sql.FlattenSqlQuery
    io.getquill.context.sql.FromContext
    io.getquill.context.sql.InfixContext
    io.getquill.context.sql.JoinContext
    io.getquill.context.sql.OrderByCriteria
    io.getquill.context.sql.QueryContext
    //io.getquill.context.sql.SelectValue
    io.getquill.context.sql.SetOperation
    io.getquill.context.sql.SetOperationSqlQuery
    io.getquill.context.sql.SqlContext
    //io.getquill.context.sql.SqlQuery
    //io.getquill.context.sql.SqlQueryApply
    io.getquill.context.sql.TableContext
    //io.getquill.context.sql.TakeDropFlatten
    io.getquill.context.sql.UnaryOperationSqlQuery
    io.getquill.context.sql.UnionAllOperation
    io.getquill.context.sql.UnionOperation
    io.getquill.context.sql.idiom.ConcatSupport
    io.getquill.context.sql.idiom.Error
    //io.getquill.context.sql.idiom.InvalidSqlQuery
    //io.getquill.context.sql.idiom.NoConcatSupport
    //io.getquill.context.sql.idiom.OnConflictSupport
    //io.getquill.context.sql.idiom.PositionalBindVariables
    io.getquill.context.sql.idiom.QuestionMarkBindVariables
    //io.getquill.context.sql.idiom.SqlIdiom
    //io.getquill.context.sql.idiom.VerifySqlQuery
    //io.getquill.context.sql.norm.AddDropToNestedOrderBy
    //io.getquill.context.sql.norm.ExpandDistinct
    //io.getquill.context.sql.norm.ExpandJoin
    //io.getquill.context.sql.norm.ExpandMappedInfix
    //io.getquill.context.sql.norm.ExpandNestedQueries
    //io.getquill.context.sql.norm.ExpandSelection
    //io.getquill.context.sql.norm.FlattenGroupByAggregation
    io.getquill.context.sql.norm.SimplifyFilterTrue
    //io.getquill.context.sql.norm.SqlNormalize
    //io.getquill.context.sql.norm.nested.Elements
    //io.getquill.context.sql.norm.nested.FindUnexpressedInfixes
    //io.getquill.dsl.DateOps
    //io.getquill.dsl.InfixDsl
    io.getquill.dsl.OrdDsl
    io.getquill.dsl.UnlimitedTuple
    //io.getquill.extras
    io.getquill.generic.AnyValDecoderContext
    io.getquill.generic.AnyValEncoderContext
    //io.getquill.generic.AnyValToValMacro
    //io.getquill.generic.ArrayEncoding
    //io.getquill.generic.ConstructDecoded
    //io.getquill.generic.ConstructType
    io.getquill.generic.DecodeAlternate
    //io.getquill.generic.DecodeSum
    io.getquill.generic.DecodingType
    //io.getquill.generic.ElaborateStructure
    io.getquill.generic.ElaborateTrivial
    //io.getquill.generic.EncodingDsl
    io.getquill.generic.GenericColumnResolver
    //io.getquill.generic.GenericDecoder
    //io.getquill.generic.GenericEncoder
    //io.getquill.generic.GenericEncoderWithStringFallback
    io.getquill.generic.GenericNullChecker
    io.getquill.generic.GenericRowTyper
    //io.getquill.generic.LowPriorityImplicits
    //io.getquill.generic.MappedEncoderMaker
    //io.getquill.generic.Summon
    //io.getquill.generic.TupleMember
    io.getquill.generic.TupleMemberUse
    //io.getquill.generic.ValToAnyValMacro
    //io.getquill.generic.WarnMac
    io.getquill.idiom.Idiom
    //io.getquill.idiom.LoadNaming
    //io.getquill.idiom.QuotationTagToken
    //io.getquill.idiom.ReifyStatement
    //io.getquill.idiom.ReifyStatementWithInjectables
    //io.getquill.idiom.ScalarLiftToken
    //io.getquill.idiom.ScalarTagToken
    //io.getquill.idiom.SetContainsToken
    io.getquill.idiom.Statement
    //io.getquill.idiom.StatementInterpolator
    io.getquill.idiom.StringToken
    io.getquill.idiom.TagToken
    io.getquill.idiom.Token
    //io.getquill.idiom.Tokens
    io.getquill.idiom.ValuesClauseToken
    //io.getquill.jdbczio.Quill
    //io.getquill.jdbczio.QuillBaseContext
    //io.getquill.metaprog.DeserializeAstInstances
    //io.getquill.metaprog.EagerEntitiesPlanterExpr
    //io.getquill.metaprog.EagerListPlanterExpr
    //io.getquill.metaprog.EagerPlanterExpr
    //io.getquill.metaprog.ExprAccumulate
    io.getquill.metaprog.ExprModel
    //io.getquill.metaprog.Extractors
    //io.getquill.metaprog.InjectableEagerPlanterExpr
    //io.getquill.metaprog.Is
    //io.getquill.metaprog.LazyPlanterExpr
    //io.getquill.metaprog.QuotationLotExpr
    //io.getquill.metaprog.QuotedExpr
    //io.getquill.metaprog.SummonParser
    //io.getquill.metaprog.SummonSerializationBehaviors
    //io.getquill.metaprog.SummonTraceTypeUse
    //io.getquill.metaprog.SummonTranspileConfig
    //io.getquill.metaprog.TranspileConfigLiftable
    //io.getquill.metaprog.TypeExtensions
    //io.getquill.metaprog.etc.ColumnsFlicer
    //io.getquill.metaprog.etc.ColumnsFlicerMacro
    //io.getquill.metaprog.etc.ListFlicer
    //io.getquill.metaprog.etc.MapFlicer
    //io.getquill.metaprog.etc.MapFlicerMacro
    io.getquill.metaprog.etc.StringOrNull
    //io.getquill.norm.AdHocReduction
    //io.getquill.norm.ApplyMap
    //io.getquill.norm.ApplyRenamesToProps
    //io.getquill.norm.AttachToEntity
    //io.getquill.norm.BetaReduction
    //io.getquill.norm.CompleteRenames
    io.getquill.norm.ConcatBehavior
    io.getquill.norm.ConfigList
    io.getquill.norm.DisablePhase
    io.getquill.norm.DisablePhaseNone
    io.getquill.norm.EmptyProductQuatBehavior
    io.getquill.norm.EnableTrace
    io.getquill.norm.EnableTraceNone
    io.getquill.norm.EqualityBehavior
    //io.getquill.norm.ExpandReturning
    //io.getquill.norm.FlattenOptionOperation
    //io.getquill.norm.Normalize
    //io.getquill.norm.NormalizeCaching
    //io.getquill.norm.NormalizeNestedStructures
    //io.getquill.norm.NormalizeReturning
    //io.getquill.norm.NormalizeStringConcat
    io.getquill.norm.OptionalPhase
    //io.getquill.norm.OrderTerms
    io.getquill.norm.ProductAggregationToken
    //io.getquill.norm.PropertyMatryoshka
    //io.getquill.norm.RenameProperties
    //io.getquill.norm.RepropagateQuats
    //io.getquill.norm.SeedRenames
    //io.getquill.norm.SheathLeafClauses
    io.getquill.norm.SheathLeafClausesApply
    //io.getquill.norm.SimplifyNullChecks
    //io.getquill.norm.StabilizeLifts
    //io.getquill.norm.SymbolicReduction
    io.getquill.norm.TranspileConfig
    io.getquill.norm.TypeBehavior
    //io.getquill.norm.capture.AvoidAliasConflict
    //io.getquill.norm.capture.AvoidAliasConflictApply
    io.getquill.norm.capture.AvoidCapture
    //io.getquill.norm.capture.Dealias
    //io.getquill.norm.capture.DealiasApply
    //io.getquill.norm.capture.DemarcateExternalAliases
    io.getquill.norm.capture.TemporaryIdent
    //io.getquill.parser.ActionParser
    //io.getquill.parser.AstPicklers
    //io.getquill.parser.BatchActionParser
    //io.getquill.parser.BlockParser
    //io.getquill.parser.BooSerializer
    //io.getquill.parser.CasePatMatchParser
    //io.getquill.parser.ComplexValueParser
    io.getquill.parser.DoSerialize
    //io.getquill.parser.ExtrasParser
    //io.getquill.parser.FunctionApplyParser
    //io.getquill.parser.FunctionParser
    //io.getquill.parser.GenericExpressionsParser
    //io.getquill.parser.IfElseParser
    //io.getquill.parser.InfixParser
    //io.getquill.parser.Lifter
    //io.getquill.parser.Lifters
    //io.getquill.parser.OperationsParser
    //io.getquill.parser.OptionParser
    //io.getquill.parser.OrderingParser
    //io.getquill.parser.ParserFactory
    //io.getquill.parser.ParserHelpers
    //io.getquill.parser.ParserLibrary
    //io.getquill.parser.QuatPicklers
    //io.getquill.parser.QueryParser
    //io.getquill.parser.QueryScalarsParser
    //io.getquill.parser.QuotationParser
    //io.getquill.parser.SerialHelper
    io.getquill.parser.SerializationBehavior
    //io.getquill.parser.SetOperationsParser
    //io.getquill.parser.TraversableOperationParser
    io.getquill.parser.UnlifterType
    //io.getquill.parser.ValParser
    //io.getquill.parser.ValueParser
    //io.getquill.parser.engine.History
    io.getquill.parser.engine.HistoryPart
    //io.getquill.parser.engine.Parser
    //io.getquill.parser.engine.ParserChain
    //io.getquill.parser.engine.failParse
    //io.getquill.quat.BooQuatSerializer
    //io.getquill.quat.FindBranches
    //io.getquill.quat.LinkedHashMapOps
    //io.getquill.quat.Quat
    //io.getquill.quat.QuatMaking
    //io.getquill.quat.QuatMakingBase
    //io.getquill.quat.QuatNestingHelper
    //io.getquill.quat.QuatOps
    //io.getquill.quat.VerifyNoBranches
    //io.getquill.quotation.FreeVariables
    //io.getquill.quotation.NonQuotedException
    io.getquill.quotation.QuatException
    //io.getquill.quotation.QuatExceptionOps
    io.getquill.quotation.State
    //io.getquill.sql.Common
    //io.getquill.sql.idiom.BooleanLiteralSupport
    //io.getquill.sql.norm.HideInnerProperties
    //io.getquill.sql.norm.HideTopLevelFilterAlias
    //io.getquill.sql.norm.InContext
    //io.getquill.sql.norm.NormalizeFilteredActionAliases
    //io.getquill.sql.norm.ProtractQuat
    //io.getquill.sql.norm.QueryLevel
    //io.getquill.sql.norm.References
    //io.getquill.sql.norm.RemoveExtraAlias
    //io.getquill.sql.norm.RemoveUnusedSelects
    //io.getquill.sql.norm.SelectPropertyProtractor
    io.getquill.sql.norm.State
    io.getquill.sql.norm.StatelessQueryTransformer
    //io.getquill.sql.norm.VendorizeBooleans
    //io.getquill.util.Cache
    //io.getquill.util.CollectTry
    //io.getquill.util.CommonExtensions
    //io.getquill.util.ContextLogger
    //io.getquill.util.Format
    io.getquill.util.Genie
    io.getquill.util.GetTraces
    //io.getquill.util.GroupByOps
    //io.getquill.util.IndentUtil
    //io.getquill.util.Interleave
    //io.getquill.util.Interpolator
    //io.getquill.util.Interpolator2
    //io.getquill.util.Load
    //io.getquill.util.LoadConfig
    //io.getquill.util.Messages
    //io.getquill.util.ProtoMessages
    //io.getquill.util.ScalafmtFormat
    //io.getquill.util.Show
    io.getquill.util.SingleGenie
    //io.getquill.util.StringOps
    //io.getquill.util.StringUtil
    //io.getquill.util.SummonMac
    //io.getquill.util.ThreadUtil
    //io.getquill.util.ThrowableOps
    //io.getquill.util.TraceConfig
    //io.getquill.util.TraceConfig
    //io.getquill.util.UseSummonMac
    //io.getquill.util.Using
    //io.getquill.util.debug.PrintMac
    io.getquill.util.prep.Inst
    io.getquill.util.prep.Mod
  """)
}