package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.scalaVersion
import org.junit.Test

class ScalazCoreSemanticTest extends SemanticTestBase("org.scalaz" %% "scalaz-core" % "7.3.8")("scalaz") {
  override protected def enableKindProjectorPlugin = true

//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    scalaz.-\/
    //scalaz./~\
    //scalaz.:+:
    //scalaz.==>>
    //scalaz.Adjunction
    //scalaz.AdjunctionInstances
    //scalaz.Align
    //scalaz.Alpha
    scalaz.AlphaInstances
    //scalaz.Alt
    scalaz.Alter
    scalaz.AlterInstances
    scalaz.AlterInstances0
    scalaz.AlterMonoid
    scalaz.AlterSemigroup
    scalaz.Ap
    scalaz.ApInstances
    scalaz.ApInstances0
    scalaz.ApMonoid
    //scalaz.ApSemigroup
    //scalaz.Applicative
    //scalaz.ApplicativeError
    //scalaz.ApplicativePlus
    //scalaz.Apply
    //scalaz.Arrow
    //scalaz.Associative
    //scalaz.Band
    scalaz.BiConstrainedNaturalTransformation
    scalaz.BiNaturalTransformation
    //scalaz.Bifoldable
    //scalaz.Bifunctor
    //scalaz.BijectionT
    scalaz.BijectionTCategory
    scalaz.BijectionTInstances
    scalaz.BijectionTInstances0
    //scalaz.BijectionTSplit
    //scalaz.Bind
    //scalaz.BindRec
    //scalaz.Bitraverse
    //scalaz.CaseInsensitive
    //scalaz.CaseInsensitiveInstances
    //scalaz.Catchable
    //scalaz.Category
    //scalaz.Choice
    //scalaz.Cobind
    //scalaz.Codensity
    scalaz.CodensityInstances
    //scalaz.CodensityMonad
    //scalaz.Cofree
    //scalaz.CofreeBind
    //scalaz.CofreeComonad
    scalaz.CofreeEqual
    //scalaz.CofreeFoldable
    scalaz.CofreeFoldable1
    scalaz.CofreeInstances
    //scalaz.CofreeInstances0
    scalaz.CofreeInstances1
    //scalaz.CofreeInstances2
    scalaz.CofreeInstances3
    scalaz.CofreeInstances4
    //scalaz.CofreeInstancesVersionSpecific
    //scalaz.CofreeInstancesVersionSpecific0
    scalaz.CofreeMonad
    //scalaz.CofreeTraverse
    //scalaz.CofreeTraverse1
    scalaz.CofreeZipApplicative
    //scalaz.CofreeZipApply
    //scalaz.CofreeZipFunctor
    //scalaz.Cohoist
    //scalaz.Cokleisli
    //scalaz.CokleisliArrow
    //scalaz.CokleisliCompose
    //scalaz.CokleisliInstances
    scalaz.CokleisliInstances0
    //scalaz.CokleisliMonad
    //scalaz.CokleisliProfunctor
    //scalaz.Comonad
    scalaz.ComonadStore
    //scalaz.ComonadTrans
    //scalaz.Compose
    scalaz.CompositionApplicative
    scalaz.CompositionApplicativePlus
    scalaz.CompositionApply
    //scalaz.CompositionBifoldable
    //scalaz.CompositionBifoldableFoldables
    scalaz.CompositionBifunctor
    scalaz.CompositionBifunctorFunctors
    scalaz.CompositionBitraverse
    scalaz.CompositionBitraverseTraverses
    scalaz.CompositionDistributive
    //scalaz.CompositionFoldable
    //scalaz.CompositionFoldable1
    //scalaz.CompositionFoldableBifoldable
    scalaz.CompositionFunctor
    scalaz.CompositionFunctorBifunctor
    scalaz.CompositionPlus
    scalaz.CompositionPlusEmpty
    scalaz.CompositionTraverse
    scalaz.CompositionTraverse1
    scalaz.CompositionTraverseBitraverse
    scalaz.CompositionUnzip
    //scalaz.CompositionZip
    scalaz.Const
    scalaz.ConstApplicativeDivisible
    //scalaz.ConstApplyDivide
    scalaz.ConstContravariant
    scalaz.ConstEqual
    //scalaz.ConstInstances
    //scalaz.ConstInstances0
    //scalaz.ConstInstances1
    scalaz.ConstMonoid
    scalaz.ConstOrder
    scalaz.ConstSemigroup
    //scalaz.ConstShow
    //scalaz.ConstTraverse
    scalaz.ConstrainedNaturalTransformation
    //scalaz.Cont
    //scalaz.ContT
    //scalaz.Contravariant
    //scalaz.ContravariantCoyoneda
    //scalaz.ContravariantCoyonedaInstances
    scalaz.Conts
    scalaz.ContsT
    scalaz.ContsTBind
    scalaz.ContsTMonad
    scalaz.ContsTMonadPlus
    //scalaz.Coproduct
    //scalaz.CoproductCobind
    //scalaz.CoproductComonad
    //scalaz.CoproductContravariant
    //scalaz.CoproductFoldable
    //scalaz.CoproductFoldable1
    //scalaz.CoproductFunctor
    scalaz.CoproductInstances
    scalaz.CoproductInstances0
    scalaz.CoproductInstances1
    scalaz.CoproductInstances2
    //scalaz.CoproductInstances3
    //scalaz.CoproductTraverse
    //scalaz.CoproductTraverse1
    //scalaz.Cord
    //scalaz.CorecursiveList
    //scalaz.CorecursiveListEqual
    scalaz.CorecursiveListInstances
    //scalaz.Corepresentable
    //scalaz.Coyoneda
    //scalaz.CoyonedaFoldable
    //scalaz.CoyonedaFoldable1
    //scalaz.CoyonedaInstances
    //scalaz.CoyonedaInstances0
    //scalaz.CoyonedaInstances1
    //scalaz.CoyonedaInstances10
    //scalaz.CoyonedaInstances2
    //scalaz.CoyonedaInstances3
    //scalaz.CoyonedaInstances4
    //scalaz.CoyonedaInstances5
    //scalaz.CoyonedaInstances6
    //scalaz.CoyonedaInstances7
    //scalaz.CoyonedaInstances8
    //scalaz.CoyonedaInstances9
    //scalaz.Cozip
    //scalaz.DList
    //scalaz.DListInstances
    //scalaz.Day
    //scalaz.DayApplicative
    //scalaz.DayApply
    scalaz.DayCobind
    scalaz.DayComonad
    scalaz.DayFunctor
    //scalaz.DayInstances
    //scalaz.DayInstances1
    scalaz.DayInstances2
    scalaz.DayInstances3
    //scalaz.DayInstances4
    //scalaz.Decidable
    //scalaz.Density
    scalaz.DensityComonad
    //scalaz.DensityInstances
    //scalaz.DensityInstances0
    //scalaz.Dequeue
    scalaz.DequeueEqual
    //scalaz.DequeueInstances
    scalaz.DiNaturalTransformation
    //scalaz.Diev
    //scalaz.DievImplementation
    //scalaz.DievInstances
    //scalaz.DievInterval
    //scalaz.Digit
    //scalaz.DigitInstances
    //scalaz.DisjunctionInstances
    //scalaz.DisjunctionInstances0
    //scalaz.DisjunctionInstances1
    scalaz.DisjunctionInstances2
    //scalaz.Distributive
    //scalaz.Divide
    //scalaz.Divisible
    scalaz.Dual
    //scalaz.DualInstances
    scalaz.DualInstances0
    scalaz.DualMonoid
    scalaz.DualSemigroup
    //scalaz.Either3
    //scalaz.EitherT
    //scalaz.EitherTBifoldable
    scalaz.EitherTBifunctor
    //scalaz.EitherTBind
    //scalaz.EitherTBindRec
    scalaz.EitherTBitraverse
    //scalaz.EitherTFoldable
    //scalaz.EitherTFunctor
    //scalaz.EitherTHoist
    //scalaz.EitherTInstances
    //scalaz.EitherTInstances0
    scalaz.EitherTInstances1
    scalaz.EitherTInstances2
    scalaz.EitherTInstances3
    scalaz.EitherTInstances4
    scalaz.EitherTInstances5
    scalaz.EitherTMonad
    //scalaz.EitherTMonadError
    //scalaz.EitherTMonadListen
    scalaz.EitherTMonadPlus
    scalaz.EitherTMonadReader
    scalaz.EitherTMonadTell
    //scalaz.EitherTNondeterminism
    //scalaz.EitherTPlus
    //scalaz.EitherTTraverse
    //scalaz.EmptyDequeue
    //scalaz.Endo
    //scalaz.EndoByName
    //scalaz.EndoByNameInstances
    //scalaz.EndoInstances
    scalaz.Endomorphic
    //scalaz.EndomorphicInstances
    //scalaz.EndomorphicInstances0
    //scalaz.EndomorphicInstances1
    scalaz.EndomorphicInstances2
    scalaz.EndomorphicSemigroup
    //scalaz.Enum
    //scalaz.EphemeralStream
    //scalaz.EphemeralStreamInstances
    //scalaz.Equal
    scalaz.Failure
    //scalaz.FingerTree
    //scalaz.FingerTreeInstances
    scalaz.FoldCase
    scalaz.FoldCaseInstances
    //scalaz.Foldable
    //scalaz.Foldable1
    scalaz.Forall
    scalaz.Foralls
    //scalaz.Free
    //scalaz.FreeAp
    //scalaz.FreeBind
    //scalaz.FreeFoldable
    //scalaz.FreeFoldable1
    //scalaz.FreeFunctions
    //scalaz.FreeInstances
    scalaz.FreeInstances0
    scalaz.FreeInstances1
    scalaz.FreeInstances2
    scalaz.FreeInstances3
    //scalaz.FreeInstances4
    //scalaz.FreeT
    scalaz.FreeTBind
    //scalaz.FreeTFoldable
    //scalaz.FreeTInstances
    //scalaz.FreeTInstances0
    //scalaz.FreeTInstances1
    //scalaz.FreeTInstances2
    //scalaz.FreeTInstances3
    //scalaz.FreeTInstances4
    //scalaz.FreeTInstances5
    //scalaz.FreeTInstances6
    scalaz.FreeTMonad
    //scalaz.FreeTPlus
    //scalaz.FreeTTraverse
    //scalaz.FreeTraverse
    //scalaz.FreeTraverse1
    scalaz.FullDequeue
    //scalaz.Functor
    scalaz.Generator
    //scalaz.Generators
    //scalaz.Heap
    //scalaz.HeapInstances
    //scalaz.Hoist
    scalaz.ICons
    //scalaz.IList
    //scalaz.IListEqual
    scalaz.IListInstance0
    //scalaz.IListInstances
    scalaz.IListOrder
    //scalaz.INil
    //scalaz.ISet
    scalaz.ISetEqual
    //scalaz.ISetInstances
    //scalaz.IStream
    scalaz.Id
    //scalaz.IdInstances
    //scalaz.IdT
    scalaz.IdTHoist
    //scalaz.IdTInstances
    //scalaz.IdTInstances0
    //scalaz.IdTInstances1
    //scalaz.IdTInstances2
    //scalaz.IdTInstances3
    //scalaz.IdTInstances4
    //scalaz.IdTInstances5
    //scalaz.IdTInstances6
    //scalaz.IdTagKind
    //scalaz.ImmutableArray
    //scalaz.ImmutableArrayInstances
    //scalaz.IndSeq
    //scalaz.IndSeqInstances
    //scalaz.IndexedCont
    //scalaz.IndexedContT
    scalaz.IndexedConts
    //scalaz.IndexedContsT
    scalaz.IndexedContsTBifunctor
    scalaz.IndexedContsTContravariant
    //scalaz.IndexedContsTFunctions
    scalaz.IndexedContsTFunctorLeft
    scalaz.IndexedContsTFunctorRight
    //scalaz.IndexedContsTInstances
    scalaz.IndexedContsTInstances0
    scalaz.IndexedContsTInstances1
    scalaz.IndexedContsTInstances2
    //scalaz.IndexedReaderWriterState
    //scalaz.IndexedReaderWriterStateT
    //scalaz.IndexedReaderWriterStateTFunctor
    scalaz.IndexedReaderWriterStateTInstances
    scalaz.IndexedReaderWriterStateTInstances0
    scalaz.IndexedReaderWriterStateTInstances1
    scalaz.IndexedReaderWriterStateTPlus
    //scalaz.IndexedReaderWriterStateTPlusEmpty
    scalaz.IndexedState
    //scalaz.IndexedStateFunctions
    //scalaz.IndexedStateT
    scalaz.IndexedStateTBifunctor
    scalaz.IndexedStateTContravariant
    //scalaz.IndexedStateTFunctions
    scalaz.IndexedStateTFunctorLeft
    scalaz.IndexedStateTFunctorRight
    //scalaz.IndexedStateTInstances
    scalaz.IndexedStateTInstances0
    scalaz.IndexedStateTInstances1
    scalaz.IndexedStateTInstances2
    scalaz.IndexedStateTInstances3
    scalaz.IndexedStateTPlus
    scalaz.IndexedStore
    //scalaz.IndexedStoreT
    //scalaz.IndexedStoreTBifunctor
    //scalaz.IndexedStoreTContravariant
    //scalaz.IndexedStoreTFunctions
    //scalaz.IndexedStoreTFunctorLeft
    //scalaz.IndexedStoreTFunctorRight
    scalaz.IndexedStoreTInstances
    scalaz.IndexedStoreTInstances0
    //scalaz.IndexedStoreTInstances1
    scalaz.IndexedStoreTInstances2
    //scalaz.Inject
    //scalaz.InjectInstances
    scalaz.Injective
    scalaz.Injective2
    scalaz.Injective3
    scalaz.Injective4
    scalaz.Injective5
    //scalaz.Injectivity
    //scalaz.InvariantAlt
    //scalaz.InvariantApplicative
    //scalaz.InvariantFunctor
    //scalaz.IsContravariant
    //scalaz.IsCovariant
    //scalaz.IsEmpty
    scalaz.IsoBifunctorTemplate0
    scalaz.IsoFunctorTemplate0
    scalaz.Isomorphism
    //scalaz.IsomorphismAlign
    //scalaz.IsomorphismAlt
    //scalaz.IsomorphismApplicative
    scalaz.IsomorphismApplicativeError
    scalaz.IsomorphismApplicativePlus
    scalaz.IsomorphismApply
    scalaz.IsomorphismArrow
    //scalaz.IsomorphismAssociative
    scalaz.IsomorphismBand
    //scalaz.IsomorphismBifoldable
    scalaz.IsomorphismBifunctor
    //scalaz.IsomorphismBind
    //scalaz.IsomorphismBindRec
    //scalaz.IsomorphismBitraverse
    scalaz.IsomorphismCatchable
    scalaz.IsomorphismCategory
    scalaz.IsomorphismChoice
    //scalaz.IsomorphismCobind
    scalaz.IsomorphismComonad
    scalaz.IsomorphismComonadStore
    scalaz.IsomorphismCompose
    scalaz.IsomorphismContravariant
    //scalaz.IsomorphismCozip
    //scalaz.IsomorphismDecidable
    scalaz.IsomorphismDistributive
    scalaz.IsomorphismDivide
    //scalaz.IsomorphismDivisible
    scalaz.IsomorphismEnum
    scalaz.IsomorphismEqual
    //scalaz.IsomorphismFoldable
    //scalaz.IsomorphismFoldable1
    scalaz.IsomorphismFunctor
    scalaz.IsomorphismInvariantAlt
    scalaz.IsomorphismInvariantApplicative
    scalaz.IsomorphismInvariantFunctor
    scalaz.IsomorphismIsEmpty
    scalaz.IsomorphismMonad
    scalaz.IsomorphismMonadError
    scalaz.IsomorphismMonadPlus
    scalaz.IsomorphismMonadReader
    scalaz.IsomorphismMonadState
    scalaz.IsomorphismMonadTell
    scalaz.IsomorphismMonoid
    //scalaz.IsomorphismNondeterminism
    //scalaz.IsomorphismOptional
    //scalaz.IsomorphismOrder
    scalaz.IsomorphismPlus
    scalaz.IsomorphismPlusEmpty
    scalaz.IsomorphismProChoice
    scalaz.IsomorphismProfunctor
    scalaz.IsomorphismSemiLattice
    scalaz.IsomorphismSemigroup
    scalaz.IsomorphismShow
    scalaz.IsomorphismSplit
    scalaz.IsomorphismStrong
    //scalaz.IsomorphismTraverse
    //scalaz.IsomorphismTraverse1
    scalaz.IsomorphismUnzip
    scalaz.IsomorphismZip
    //scalaz.Isomorphisms
    //scalaz.Kleisli
    scalaz.KleisliApplicative
    //scalaz.KleisliApply
    //scalaz.KleisliArrow
    //scalaz.KleisliBind
    scalaz.KleisliBindRec
    //scalaz.KleisliCatchable
    //scalaz.KleisliCompose
    //scalaz.KleisliContravariant
    scalaz.KleisliDecidable
    //scalaz.KleisliDistributive
    //scalaz.KleisliDivisible
    //scalaz.KleisliFunctor
    //scalaz.KleisliHoist
    //scalaz.KleisliInstances
    scalaz.KleisliInstances0
    scalaz.KleisliInstances1
    scalaz.KleisliInstances10
    scalaz.KleisliInstances11
    scalaz.KleisliInstances12
    scalaz.KleisliInstances13
    scalaz.KleisliInstances14
    scalaz.KleisliInstances15
    scalaz.KleisliInstances2
    scalaz.KleisliInstances3
    scalaz.KleisliInstances4
    //scalaz.KleisliInstances5
    //scalaz.KleisliInstances6
    scalaz.KleisliInstances7
    scalaz.KleisliInstances8
    //scalaz.KleisliInstances9
    scalaz.KleisliMonad
    //scalaz.KleisliMonadError
    scalaz.KleisliMonadPlus
    scalaz.KleisliMonadReader
    scalaz.KleisliMonoid
    scalaz.KleisliPlus
    scalaz.KleisliPlusEmpty
    //scalaz.KleisliProChoice
    scalaz.KleisliSemigroup
    //scalaz.KleisliStrong
    scalaz.Konst
    //scalaz.Lan
    //scalaz.LanApply
    //scalaz.LanFunctor
    scalaz.LanInstances
    //scalaz.LanInstances0
    //scalaz.LazyEither
    //scalaz.LazyEitherInstances
    //scalaz.LazyEitherT
    //scalaz.LazyEitherTBifoldable
    //scalaz.LazyEitherTBifunctor
    //scalaz.LazyEitherTBindRec
    //scalaz.LazyEitherTBitraverse
    //scalaz.LazyEitherTFoldable
    //scalaz.LazyEitherTFunctor
    //scalaz.LazyEitherTInstances
    //scalaz.LazyEitherTInstances0
    //scalaz.LazyEitherTInstances1
    //scalaz.LazyEitherTMonad
    //scalaz.LazyEitherTMonadError
    scalaz.LazyEitherTMonadPlus
    //scalaz.LazyEitherTPlus
    //scalaz.LazyEitherTTraverse
    scalaz.LazyLeft
    //scalaz.LazyNone
    //scalaz.LazyOption
    //scalaz.LazyOptionInstances
    //scalaz.LazyOptionT
    //scalaz.LazyOptionTBindRec
    //scalaz.LazyOptionTFunctor
    scalaz.LazyOptionTHoist
    //scalaz.LazyOptionTInstances
    //scalaz.LazyOptionTInstances0
    scalaz.LazyOptionTInstances1
    //scalaz.LazyOptionTMonad
    scalaz.LazyRight
    scalaz.LazySome
    //scalaz.LazyTuple
    scalaz.LazyTuple2
    scalaz.LazyTuple2Equal
    scalaz.LazyTuple2Functor
    scalaz.LazyTuple2Instances
    //scalaz.LazyTuple2Instances0
    scalaz.LazyTuple2Monad
    scalaz.LazyTuple2Monoid
    scalaz.LazyTuple2Order
    scalaz.LazyTuple2Semigroup
    //scalaz.LazyTuple2Show
    scalaz.LazyTuple3
    scalaz.LazyTuple3Equal
    scalaz.LazyTuple3Functor
    scalaz.LazyTuple3Instances
    //scalaz.LazyTuple3Instances0
    scalaz.LazyTuple3Monad
    scalaz.LazyTuple3Monoid
    scalaz.LazyTuple3Order
    scalaz.LazyTuple3Semigroup
    //scalaz.LazyTuple3Show
    scalaz.LazyTuple4
    scalaz.LazyTuple4Equal
    scalaz.LazyTuple4Functor
    scalaz.LazyTuple4Instances
    //scalaz.LazyTuple4Instances0
    scalaz.LazyTuple4Monad
    scalaz.LazyTuple4Monoid
    scalaz.LazyTuple4Order
    scalaz.LazyTuple4Semigroup
    //scalaz.LazyTuple4Show
    scalaz.Left3
    //scalaz.LeftFoldable
    //scalaz.LeftFunctor
    //scalaz.LeftTraverse
    //scalaz.Leibniz
    //scalaz.LeibnizF
    //scalaz.LeibnizInstances
    //scalaz.Lens
    //scalaz.LensCategory
    //scalaz.LensFamily
    //scalaz.LensFamilyFunctions
    //scalaz.LensFunctions
    //scalaz.LensInstances
    //scalaz.LensInstances0
    //scalaz.Liskov
    //scalaz.LiskovF
    //scalaz.LiskovInstances
    //scalaz.ListT
    //scalaz.ListTDecidable
    //scalaz.ListTFunctor
    //scalaz.ListTHoist
    //scalaz.ListTInstances
    scalaz.ListTInstances1
    scalaz.ListTInstances2
    //scalaz.ListTMonadPlus
    scalaz.ListTMonoid
    //scalaz.ListTSemigroup
    scalaz.MapEqual
    //scalaz.MapInstances
    //scalaz.MapInstances0
    //scalaz.MapInstances1
    //scalaz.MapInstances2
    //scalaz.Maybe
    //scalaz.MaybeEqual
    //scalaz.MaybeInstances
    //scalaz.MaybeInstances0
    //scalaz.MaybeInstances1
    //scalaz.MaybeMonoid
    //scalaz.MaybeT
    //scalaz.MaybeTBindRec
    //scalaz.MaybeTDecidable
    //scalaz.MaybeTFoldable
    //scalaz.MaybeTFunctor
    //scalaz.MaybeTHoist
    //scalaz.MaybeTInstances
    scalaz.MaybeTInstances0
    scalaz.MaybeTInstances1
    scalaz.MaybeTInstances2
    scalaz.MaybeTInstances3
    //scalaz.MaybeTMonad
    //scalaz.MaybeTMonadError
    //scalaz.MaybeTMonadListen
    //scalaz.MaybeTMonadPlus
    scalaz.MaybeTMonadTell
    //scalaz.MaybeTTraverse
    //scalaz.Memo
    scalaz.MemoInstances
    scalaz.Middle3
    //scalaz.Monad
    //scalaz.MonadError
    //scalaz.MonadListen
    //scalaz.MonadPlus
    //scalaz.MonadReader
    //scalaz.MonadState
    //scalaz.MonadTell
    //scalaz.MonadTrans
    //scalaz.Monoid
    //scalaz.Name
    //scalaz.NaturalTransformation
    scalaz.NaturalTransformations
    //scalaz.Need
    //scalaz.NonEmptyList
    //scalaz.NonEmptyListInstances
    //scalaz.NonEmptyListInstances0
    //scalaz.Nondeterminism
    //scalaz.NotNothing
    //scalaz.NullArgument
    //scalaz.NullArgumentInstances
    //scalaz.NullArgumentInstances0
    scalaz.NullArgumentMonoid
    //scalaz.NullArgumentSemigroup
    //scalaz.NullResult
    //scalaz.NullResultInstances
    //scalaz.NullResultInstances0
    scalaz.NullResultMonoid
    //scalaz.NullResultSemigroup
    //scalaz.OneAnd
    //scalaz.OneAndAlign
    scalaz.OneAndAlt
    scalaz.OneAndApplicative
    //scalaz.OneAndApply
    //scalaz.OneAndBind
    scalaz.OneAndEqual
    //scalaz.OneAndFoldable
    //scalaz.OneAndFoldable1
    scalaz.OneAndFunctor
    //scalaz.OneAndInstances
    scalaz.OneAndInstances0
    scalaz.OneAndInstances1
    //scalaz.OneAndInstances2
    //scalaz.OneAndInstances3
    //scalaz.OneAndInstances4
    scalaz.OneAndInstances5
    scalaz.OneAndMonad
    scalaz.OneAndPlus
    //scalaz.OneAndTraverse
    //scalaz.OneAndTraverse1
    //scalaz.OneOr
    //scalaz.OneOrApplicative
    //scalaz.OneOrCobind
    //scalaz.OneOrComonad
    //scalaz.OneOrEqual
    //scalaz.OneOrFoldable
    //scalaz.OneOrFoldable1
    //scalaz.OneOrFunctor
    scalaz.OneOrInstances
    scalaz.OneOrInstances0
    scalaz.OneOrInstances1
    scalaz.OneOrInstances2
    scalaz.OneOrInstances3
    scalaz.OneOrInstances4
    scalaz.OneOrInstances5
    scalaz.OneOrInstances6
    //scalaz.OneOrOrder
    //scalaz.OneOrShow
    //scalaz.OneOrTraverse
    //scalaz.OneOrTraverse1
    //scalaz.OptionT
    //scalaz.OptionTApply
    //scalaz.OptionTBind
    //scalaz.OptionTBindRec
    //scalaz.OptionTDecidable
    //scalaz.OptionTFoldable
    //scalaz.OptionTFunctor
    //scalaz.OptionTHoist
    //scalaz.OptionTInstances
    scalaz.OptionTInstances0
    //scalaz.OptionTInstances1
    scalaz.OptionTInstances2
    scalaz.OptionTInstances3
    scalaz.OptionTMonad
    scalaz.OptionTMonadError
    //scalaz.OptionTMonadListen
    //scalaz.OptionTMonadPlus
    scalaz.OptionTMonadTell
    //scalaz.OptionTPoint
    //scalaz.OptionTTraverse
    //scalaz.Optional
    //scalaz.OrdSeq
    //scalaz.Order
    scalaz.Ordering
    //scalaz.OrderingInstances
    //scalaz.PLens
    //scalaz.PLensCategory
    //scalaz.PLensFamily
    //scalaz.PLensFamilyFunctions
    //scalaz.PLensFunctions
    //scalaz.PLensInstances
    //scalaz.Plus
    //scalaz.PlusEmpty
    //scalaz.PrioritySearchQueue
    //scalaz.ProChoice
    //scalaz.ProductAlign
    scalaz.ProductApplicative
    scalaz.ProductApplicativePlus
    scalaz.ProductApply
    //scalaz.ProductBifoldable
    scalaz.ProductBifunctor
    scalaz.ProductBind
    scalaz.ProductBindRec
    scalaz.ProductBitraverse
    scalaz.ProductDistributive
    //scalaz.ProductFoldable
    //scalaz.ProductFoldable1
    //scalaz.ProductFoldable1L
    //scalaz.ProductFoldable1R
    scalaz.ProductFunctor
    scalaz.ProductMonad
    scalaz.ProductMonadPlus
    scalaz.ProductPlus
    scalaz.ProductPlusEmpty
    scalaz.ProductTraverse
    //scalaz.ProductTraverse1
    //scalaz.ProductTraverse1L
    //scalaz.ProductTraverse1R
    //scalaz.ProductUnzip
    scalaz.ProductZip
    //scalaz.Profunctor
    //scalaz.Ran
    scalaz.Reader
    scalaz.ReaderT
    //scalaz.ReaderWriterState
    //scalaz.ReaderWriterStateT
    //scalaz.ReaderWriterStateTBind
    //scalaz.ReaderWriterStateTBindRec
    scalaz.ReaderWriterStateTFunctions
    //scalaz.ReaderWriterStateTHoist
    //scalaz.ReaderWriterStateTInstances
    //scalaz.ReaderWriterStateTInstances0
    //scalaz.ReaderWriterStateTMonad
    //scalaz.ReaderWriterStateTMonadError
    scalaz.ReaderWriterStateTMonadPlus
    //scalaz.Reducer
    //scalaz.ReducerInstances
    //scalaz.Representable
    //scalaz.RepresentableInstances
    scalaz.Right3
    //scalaz.RightFoldable
    //scalaz.RightFunctor
    //scalaz.RightTraverse
    scalaz.Scalaz
    scalaz.ScalazBuildInfo
    //scalaz.Select
    //scalaz.SelectT
    //scalaz.SelectTBind
    //scalaz.SelectTFunctor
    //scalaz.SelectTInstances
    scalaz.SelectTInstances1
    //scalaz.SelectTInstances2
    scalaz.SelectTInstances3
    scalaz.SelectTInstances4
    scalaz.SelectTInstances5
    scalaz.SelectTInstances6
    scalaz.SelectTInstances7
    //scalaz.SelectTMonad
    scalaz.SelectTMonadPlus
    scalaz.SelectTPlus
    //scalaz.SelectTPlusEmpty
    //scalaz.SemiLattice
    //scalaz.Semigroup
    //scalaz.Show
    scalaz.SingletonDequeue
    //scalaz.Split
    //scalaz.State
    //scalaz.StateFunctions
    //scalaz.StateT
    scalaz.StateTBind
    //scalaz.StateTBindRec
    scalaz.StateTDecidable
    //scalaz.StateTDivisible
    //scalaz.StateTFunctions
    //scalaz.StateTHoist
    scalaz.StateTInstances
    //scalaz.StateTInstances0
    scalaz.StateTInstances1
    scalaz.StateTInstances2
    scalaz.StateTInstances3
    scalaz.StateTInstances4
    //scalaz.StateTMonadError
    //scalaz.StateTMonadState
    scalaz.StateTMonadStateMonadPlus
    scalaz.Store
    //scalaz.StoreT
    //scalaz.StoreTCobind
    //scalaz.StoreTCohoist
    //scalaz.StoreTComonad
    //scalaz.StoreTComonadStore
    //scalaz.StoreTFunctions
    //scalaz.StoreTInstances
    scalaz.StoreTInstances0
    scalaz.StoreTInstances1
    scalaz.StoreTInstances2
    //scalaz.StreamT
    //scalaz.StreamTHoist
    //scalaz.StreamTInstance1
    //scalaz.StreamTInstances
    //scalaz.StreamTInstances0
    //scalaz.StreamTMonadPlus
    scalaz.StreamTMonoid
    //scalaz.StreamTSemigroup
    //scalaz.StrictTree
    //scalaz.StrictTreeEqual
    //scalaz.StrictTreeInstances
    //scalaz.StrictTreeUnzip
    //scalaz.Strong
    scalaz.Success
    //scalaz.Tag
    //scalaz.TagKind
    scalaz.Tags
    scalaz.Tannen
    //scalaz.TannenInstances
    //scalaz.TannenInstances0
    //scalaz.TheseInstances
    //scalaz.TheseInstances0
    //scalaz.TheseInstances1
    //scalaz.TheseT
    //scalaz.TheseTFunctor
    //scalaz.TheseTInstances
    //scalaz.TheseTInstances0
    scalaz.TheseTInstances1
    //scalaz.TracedT
    //scalaz.TracedTApplicative
    //scalaz.TracedTApply
    //scalaz.TracedTCobind
    //scalaz.TracedTComonad
    //scalaz.TracedTDistributive
    //scalaz.TracedTFunctor
    //scalaz.TracedTInstances
    //scalaz.TracedTInstances0
    scalaz.TracedTInstances1
    scalaz.TracedTInstances2
    scalaz.TracedTInstances3
    scalaz.TracedTInstances4
    //scalaz.TracedTInstances5
    scalaz.Trampoline
    //scalaz.Traverse
    //scalaz.Traverse1
    //scalaz.Tree
    //scalaz.TreeEqual
    //scalaz.TreeInstances
    //scalaz.TreeLoc
    //scalaz.TreeLocEqual
    //scalaz.TreeLocInstances
    //scalaz.UFoldable
    scalaz.UFunctor
    scalaz.UTraverse
    //scalaz.Unapply
    //scalaz.Unapply2
    //scalaz.Unapply21
    //scalaz.UnapplyProduct
    //scalaz.Unapply_0
    //scalaz.Unapply_2
    //scalaz.Unapply_3
    //scalaz.Unapply_4
    //scalaz.UnitReducer
    scalaz.Unwriter
    //scalaz.UnwriterComonad
    //scalaz.UnwriterT
    //scalaz.UnwriterTApply
    scalaz.UnwriterTBifunctor
    //scalaz.UnwriterTBind
    scalaz.UnwriterTBitraverse
    //scalaz.UnwriterTFoldable
    scalaz.UnwriterTFunctions
    //scalaz.UnwriterTFunctor
    //scalaz.UnwriterTInstances
    scalaz.UnwriterTInstances0
    scalaz.UnwriterTInstances1
    scalaz.UnwriterTInstances2
    //scalaz.UnwriterTTraverse
    //scalaz.Unzip
    //scalaz.Validation
    //scalaz.ValidationFlatMap
    scalaz.ValidationInstances
    //scalaz.ValidationInstances0
    //scalaz.ValidationInstances1
    //scalaz.ValidationInstances2
    //scalaz.ValidationInstances3
    //scalaz.Value
    scalaz.Writer
    //scalaz.WriterComonad
    //scalaz.WriterT
    //scalaz.WriterTApplicative
    //scalaz.WriterTApply
    scalaz.WriterTBifunctor
    //scalaz.WriterTBind
    //scalaz.WriterTBindRec
    scalaz.WriterTBitraverse
    scalaz.WriterTDecidable
    scalaz.WriterTDivisible
    //scalaz.WriterTFoldable
    //scalaz.WriterTFunctions
    //scalaz.WriterTFunctor
    //scalaz.WriterTHoist
    scalaz.WriterTInstance5
    //scalaz.WriterTInstances
    scalaz.WriterTInstances0
    scalaz.WriterTInstances1
    scalaz.WriterTInstances10
    scalaz.WriterTInstances11
    scalaz.WriterTInstances12
    scalaz.WriterTInstances13
    scalaz.WriterTInstances14
    scalaz.WriterTInstances15
    scalaz.WriterTInstances16
    scalaz.WriterTInstances2
    //scalaz.WriterTInstances3
    scalaz.WriterTInstances4
    scalaz.WriterTInstances6
    scalaz.WriterTInstances7
    scalaz.WriterTInstances8
    scalaz.WriterTInstances9
    scalaz.WriterTMonad
    scalaz.WriterTMonadError
    //scalaz.WriterTMonadListen
    scalaz.WriterTMonadPlus
    scalaz.WriterTPlus
    scalaz.WriterTPlusEmpty
    //scalaz.WriterTTraverse
    //scalaz.Yoneda
    //scalaz.Zap
    //scalaz.ZapInstances
    //scalaz.Zip
    //scalaz.Zipper
    //scalaz.ZipperInstances
    //scalaz.\&/
    //scalaz.\/
    scalaz.\/-
    scalaz.compat
    scalaz.std.AllFunctions
    scalaz.std.AllInstances
    //scalaz.std.AnyValInstances
    scalaz.std.BooleanFunctions
    //scalaz.std.DoubleFunctions
    scalaz.std.EitherEqual
    //scalaz.std.EitherInstances
    scalaz.std.EitherInstances0
    scalaz.std.EitherOrder
    //scalaz.std.FloatFunctions
    //scalaz.std.Function1Cobind
    scalaz.std.Function1Comonad
    //scalaz.std.Function1Monoid
    //scalaz.std.Function1Semigroup
    //scalaz.std.FunctionFunctions
    //scalaz.std.FunctionInstances
    //scalaz.std.FunctionInstances0
    scalaz.std.FunctionInstances1
    //scalaz.std.FutureInstance
    //scalaz.std.FutureInstances
    //scalaz.std.FutureInstances1
    scalaz.std.IntFunctions
    //scalaz.std.IterableBindRec
    //scalaz.std.IterableInstances
    //scalaz.std.IterableSubtypeFoldable
    //scalaz.std.LazyListEqual
    //scalaz.std.LazyListFunctions
    //scalaz.std.LazyListInstances
    //scalaz.std.ListEqual
    //scalaz.std.ListFunctions
    //scalaz.std.ListInstances
    scalaz.std.ListInstances0
    scalaz.std.ListOrder
    //scalaz.std.LongFunctions
    //scalaz.std.MapFunctions
    //scalaz.std.MapInstances
    //scalaz.std.MapInstances0
    scalaz.std.OptionEqual
    //scalaz.std.OptionFunctions
    //scalaz.std.OptionInstances
    //scalaz.std.OptionInstances0
    //scalaz.std.OptionInstances1
    scalaz.std.OptionOrder
    scalaz.std.OptionSemigroup
    //scalaz.std.PartialFunctionInstances
    scalaz.std.SetFunctions
    //scalaz.std.SetInstances
    scalaz.std.ShortFunctions
    //scalaz.std.SortedMapFunctions
    //scalaz.std.SortedMapInstances
    //scalaz.std.SortedMapInstances0
    //scalaz.std.StreamEqual
    //scalaz.std.StreamFunctions
    //scalaz.std.StreamInstances
    //scalaz.std.StringFunctions
    //scalaz.std.StringInstances
    //scalaz.std.TryFunctions
    //scalaz.std.TryInstances
    //scalaz.std.Tuple1Cozip
    //scalaz.std.Tuple1Equal
    //scalaz.std.Tuple1Functor
    //scalaz.std.Tuple1Monad
    //scalaz.std.Tuple1Monoid
    //scalaz.std.Tuple1Order
    //scalaz.std.Tuple1Semigroup
    //scalaz.std.Tuple1Show
    //scalaz.std.Tuple2BindRec
    scalaz.std.Tuple2Cozip
    scalaz.std.Tuple2Equal
    //scalaz.std.Tuple2Functor
    scalaz.std.Tuple2Monad
    scalaz.std.Tuple2Monoid
    scalaz.std.Tuple2Order
    scalaz.std.Tuple2Semigroup
    //scalaz.std.Tuple2Show
    //scalaz.std.Tuple3BindRec
    scalaz.std.Tuple3Cozip
    scalaz.std.Tuple3Equal
    //scalaz.std.Tuple3Functor
    scalaz.std.Tuple3Monad
    scalaz.std.Tuple3Monoid
    scalaz.std.Tuple3Order
    scalaz.std.Tuple3Semigroup
    //scalaz.std.Tuple3Show
    //scalaz.std.Tuple4BindRec
    scalaz.std.Tuple4Cozip
    scalaz.std.Tuple4Equal
    //scalaz.std.Tuple4Functor
    scalaz.std.Tuple4Monad
    scalaz.std.Tuple4Monoid
    scalaz.std.Tuple4Order
    scalaz.std.Tuple4Semigroup
    //scalaz.std.Tuple4Show
    //scalaz.std.Tuple5BindRec
    scalaz.std.Tuple5Cozip
    scalaz.std.Tuple5Equal
    //scalaz.std.Tuple5Functor
    scalaz.std.Tuple5Monad
    scalaz.std.Tuple5Monoid
    scalaz.std.Tuple5Order
    scalaz.std.Tuple5Semigroup
    //scalaz.std.Tuple5Show
    //scalaz.std.Tuple6BindRec
    scalaz.std.Tuple6Cozip
    scalaz.std.Tuple6Equal
    //scalaz.std.Tuple6Functor
    scalaz.std.Tuple6Monad
    scalaz.std.Tuple6Monoid
    scalaz.std.Tuple6Order
    scalaz.std.Tuple6Semigroup
    //scalaz.std.Tuple6Show
    //scalaz.std.Tuple7BindRec
    scalaz.std.Tuple7Cozip
    scalaz.std.Tuple7Equal
    //scalaz.std.Tuple7Functor
    scalaz.std.Tuple7Monad
    scalaz.std.Tuple7Monoid
    scalaz.std.Tuple7Order
    scalaz.std.Tuple7Semigroup
    //scalaz.std.Tuple7Show
    //scalaz.std.Tuple8BindRec
    scalaz.std.Tuple8Cozip
    scalaz.std.Tuple8Equal
    //scalaz.std.Tuple8Functor
    scalaz.std.Tuple8Monad
    scalaz.std.Tuple8Monoid
    scalaz.std.Tuple8Order
    scalaz.std.Tuple8Semigroup
    //scalaz.std.Tuple8Show
    scalaz.std.TupleInstances
    //scalaz.std.TupleInstances0
    //scalaz.std.TupleInstances1
    //scalaz.std.TupleInstances2
    //scalaz.std.TupleInstances3
    //scalaz.std.TypeConstraintInstances
    //scalaz.std.VectorEqual
    //scalaz.std.VectorFunctions
    //scalaz.std.VectorInstances
    scalaz.std.VectorInstances0
    //scalaz.std.VectorOrder
    //scalaz.std.`try`
    scalaz.std.anyVal
    scalaz.std.boolean
    scalaz.std.double
    scalaz.std.either
    scalaz.std.float
    scalaz.std.function
    scalaz.std.int
    scalaz.std.iterable
    //scalaz.std.java.EnumInstances
    scalaz.std.java.ThrowableInstances
    //scalaz.std.java.TimeInstances
    //scalaz.std.java.`enum`
    //scalaz.std.java.math.BigDecimalInstances
    //scalaz.std.java.math.BigIntegerInstances
    scalaz.std.java.math.bigDecimal
    scalaz.std.java.math.bigInteger
    scalaz.std.java.throwable
    scalaz.std.java.time
    //scalaz.std.java.util.MapInstances
    scalaz.std.java.util.concurrent.CallableInstances
    scalaz.std.java.util.concurrent.callable
    scalaz.std.java.util.map
    scalaz.std.lazylist
    scalaz.std.list
    scalaz.std.long
    scalaz.std.map
    //scalaz.std.math.BigDecimalInstances
    //scalaz.std.math.BigInts
    scalaz.std.math.OrderingFunctions
    //scalaz.std.math.OrderingInstances
    scalaz.std.math.bigDecimal
    scalaz.std.math.bigInt
    scalaz.std.math.ordering
    scalaz.std.option
    scalaz.std.partialFunction
    scalaz.std.scalaFuture
    scalaz.std.set
    scalaz.std.short
    scalaz.std.sortedMap
    scalaz.std.stream
    scalaz.std.string
    scalaz.std.tuple
    scalaz.std.typeConstraint
    scalaz.std.vector
    //scalaz.syntax.AlignOps
    //scalaz.syntax.AlignSyntax
    //scalaz.syntax.AltOps
    //scalaz.syntax.AltSyntax
    //scalaz.syntax.ApplicativeBuilder
    //scalaz.syntax.ApplicativeErrorOps
    //scalaz.syntax.ApplicativeErrorSyntax
    //scalaz.syntax.ApplicativeOps
    //scalaz.syntax.ApplicativePlusOps
    //scalaz.syntax.ApplicativePlusSyntax
    //scalaz.syntax.ApplicativeSyntax
    //scalaz.syntax.ApplyOps
    //scalaz.syntax.ApplySyntax
    //scalaz.syntax.ArrowOps
    //scalaz.syntax.ArrowSyntax
    //scalaz.syntax.AssociativeOps
    //scalaz.syntax.AssociativeSyntax
    //scalaz.syntax.BandOps
    //scalaz.syntax.BandSyntax
    //scalaz.syntax.BifoldableOps
    //scalaz.syntax.BifoldableSyntax
    //scalaz.syntax.BifunctorOps
    //scalaz.syntax.BifunctorSyntax
    //scalaz.syntax.BindOps
    //scalaz.syntax.BindRecOps
    //scalaz.syntax.BindRecSyntax
    //scalaz.syntax.BindSyntax
    //scalaz.syntax.BitraverseOps
    //scalaz.syntax.BitraverseSyntax
    //scalaz.syntax.CatchableOps
    //scalaz.syntax.CatchableSyntax
    //scalaz.syntax.CategoryOps
    //scalaz.syntax.CategorySyntax
    //scalaz.syntax.ChoiceOps
    //scalaz.syntax.ChoiceSyntax
    //scalaz.syntax.CobindOps
    //scalaz.syntax.CobindSyntax
    //scalaz.syntax.ComonadOps
    //scalaz.syntax.ComonadSyntax
    //scalaz.syntax.ComposeOps
    //scalaz.syntax.ComposeSyntax
    //scalaz.syntax.ConstOps
    //scalaz.syntax.ContTOps
    //scalaz.syntax.ContravariantOps
    //scalaz.syntax.ContravariantSyntax
    //scalaz.syntax.CozipOps
    //scalaz.syntax.CozipSyntax
    //scalaz.syntax.DecidableOps
    //scalaz.syntax.DecidableSyntax
    //scalaz.syntax.DistributiveOps
    //scalaz.syntax.DistributiveSyntax
    //scalaz.syntax.DivideOps
    //scalaz.syntax.DivideSyntax
    //scalaz.syntax.DivisibleOps
    //scalaz.syntax.DivisibleSyntax
    //scalaz.syntax.EitherOps
    //scalaz.syntax.EitherTOps
    //scalaz.syntax.EnumOps
    //scalaz.syntax.EnumSyntax
    //scalaz.syntax.EqualOps
    //scalaz.syntax.EqualSyntax
    //scalaz.syntax.Foldable1Ops
    //scalaz.syntax.Foldable1Syntax
    //scalaz.syntax.FoldableOps
    //scalaz.syntax.FoldableSyntax
    //scalaz.syntax.FunctorOps
    //scalaz.syntax.FunctorSyntax
    //scalaz.syntax.IdOps
    //scalaz.syntax.InvariantAltOps
    //scalaz.syntax.InvariantAltSyntax
    //scalaz.syntax.InvariantApplicativeOps
    //scalaz.syntax.InvariantApplicativeSyntax
    //scalaz.syntax.InvariantFunctorOps
    //scalaz.syntax.InvariantFunctorSyntax
    //scalaz.syntax.IsContravariantOps
    //scalaz.syntax.IsContravariantSyntax
    //scalaz.syntax.IsCovariantOps
    //scalaz.syntax.IsCovariantSyntax
    //scalaz.syntax.IsEmptyOps
    //scalaz.syntax.IsEmptySyntax
    //scalaz.syntax.KleisliFAOps
    //scalaz.syntax.KleisliIdOps
    //scalaz.syntax.MaybeOps
    //scalaz.syntax.MonadErrorIdOps
    //scalaz.syntax.MonadErrorOps
    //scalaz.syntax.MonadErrorSyntax
    //scalaz.syntax.MonadListenOps
    //scalaz.syntax.MonadListenSyntax
    //scalaz.syntax.MonadOps
    //scalaz.syntax.MonadPlusOps
    //scalaz.syntax.MonadPlusSyntax
    //scalaz.syntax.MonadSyntax
    //scalaz.syntax.MonadTellOps
    //scalaz.syntax.MonadTellSyntax
    //scalaz.syntax.MonadTransGFGA
    //scalaz.syntax.MonoidOps
    //scalaz.syntax.MonoidSyntax
    //scalaz.syntax.NelOps
    //scalaz.syntax.NondeterminismOps
    //scalaz.syntax.NondeterminismSyntax
    scalaz.syntax.Ops
    //scalaz.syntax.OptionalOps
    //scalaz.syntax.OptionalSyntax
    //scalaz.syntax.OrderOps
    //scalaz.syntax.OrderSyntax
    //scalaz.syntax.PlusEmptyOps
    //scalaz.syntax.PlusEmptySyntax
    //scalaz.syntax.PlusOps
    //scalaz.syntax.PlusSyntax
    //scalaz.syntax.ProChoiceOps
    //scalaz.syntax.ProChoiceSyntax
    //scalaz.syntax.ProfunctorOps
    //scalaz.syntax.ProfunctorSyntax
    //scalaz.syntax.ReducerOps
    //scalaz.syntax.SemiLatticeOps
    //scalaz.syntax.SemiLatticeSyntax
    //scalaz.syntax.SemigroupOps
    //scalaz.syntax.SemigroupSyntax
    //scalaz.syntax.ShowOps
    //scalaz.syntax.ShowSyntax
    //scalaz.syntax.SplitOps
    //scalaz.syntax.SplitSyntax
    //scalaz.syntax.StateOps
    //scalaz.syntax.StrictTreeOps
    //scalaz.syntax.StrongOps
    //scalaz.syntax.StrongSyntax
    //scalaz.syntax.Syntaxes
    //scalaz.syntax.TagOps
    //scalaz.syntax.TheseOps
    //scalaz.syntax.ThesePairOps
    //scalaz.syntax.ToAlignOps
    //scalaz.syntax.ToAlignOps0
    //scalaz.syntax.ToAlignOpsU
    //scalaz.syntax.ToAltOps
    //scalaz.syntax.ToAltOps0
    //scalaz.syntax.ToAltOpsU
    //scalaz.syntax.ToApplicativeErrorOps
    //scalaz.syntax.ToApplicativeErrorOps0
    //scalaz.syntax.ToApplicativeOps
    //scalaz.syntax.ToApplicativeOps0
    //scalaz.syntax.ToApplicativeOpsU
    //scalaz.syntax.ToApplicativePlusOps
    //scalaz.syntax.ToApplicativePlusOps0
    //scalaz.syntax.ToApplicativePlusOpsU
    //scalaz.syntax.ToApplyOps
    //scalaz.syntax.ToApplyOps0
    //scalaz.syntax.ToApplyOpsU
    //scalaz.syntax.ToArrowOps
    //scalaz.syntax.ToArrowOps0
    //scalaz.syntax.ToArrowOpsU
    //scalaz.syntax.ToAssociativeOps
    //scalaz.syntax.ToAssociativeOps0
    //scalaz.syntax.ToAssociativeOpsU
    scalaz.syntax.ToBandOps
    //scalaz.syntax.ToBifoldableOps
    //scalaz.syntax.ToBifoldableOps0
    //scalaz.syntax.ToBifoldableOpsU
    //scalaz.syntax.ToBifunctorOps
    //scalaz.syntax.ToBifunctorOps0
    //scalaz.syntax.ToBifunctorOpsU
    //scalaz.syntax.ToBindOps
    //scalaz.syntax.ToBindOps0
    //scalaz.syntax.ToBindOpsU
    //scalaz.syntax.ToBindRecOps
    //scalaz.syntax.ToBindRecOps0
    //scalaz.syntax.ToBindRecOpsU
    //scalaz.syntax.ToBitraverseOps
    //scalaz.syntax.ToBitraverseOps0
    //scalaz.syntax.ToBitraverseOpsU
    //scalaz.syntax.ToCatchableOps
    //scalaz.syntax.ToCatchableOps0
    //scalaz.syntax.ToCatchableOpsU
    //scalaz.syntax.ToCategoryOps
    //scalaz.syntax.ToCategoryOps0
    //scalaz.syntax.ToCategoryOpsU
    //scalaz.syntax.ToChoiceOps
    //scalaz.syntax.ToChoiceOps0
    //scalaz.syntax.ToChoiceOpsU
    //scalaz.syntax.ToCobindOps
    //scalaz.syntax.ToCobindOps0
    //scalaz.syntax.ToCobindOpsU
    //scalaz.syntax.ToComonadOps
    //scalaz.syntax.ToComonadOps0
    //scalaz.syntax.ToComonadOpsU
    //scalaz.syntax.ToComposeOps
    //scalaz.syntax.ToComposeOps0
    //scalaz.syntax.ToComposeOpsU
    scalaz.syntax.ToConstOps
    scalaz.syntax.ToContTOps
    //scalaz.syntax.ToContravariantOps
    //scalaz.syntax.ToContravariantOps0
    //scalaz.syntax.ToContravariantOpsU
    //scalaz.syntax.ToCozipOps
    //scalaz.syntax.ToCozipOps0
    //scalaz.syntax.ToCozipOpsU
    scalaz.syntax.ToDataOps
    //scalaz.syntax.ToDecidableOps
    //scalaz.syntax.ToDecidableOps0
    //scalaz.syntax.ToDecidableOpsU
    //scalaz.syntax.ToDistributiveOps
    //scalaz.syntax.ToDistributiveOps0
    //scalaz.syntax.ToDistributiveOpsU
    //scalaz.syntax.ToDivideOps
    //scalaz.syntax.ToDivideOps0
    //scalaz.syntax.ToDivideOpsU
    //scalaz.syntax.ToDivisibleOps
    //scalaz.syntax.ToDivisibleOps0
    //scalaz.syntax.ToDivisibleOpsU
    scalaz.syntax.ToEitherOps
    scalaz.syntax.ToEitherTOps
    scalaz.syntax.ToEnumOps
    scalaz.syntax.ToEqualOps
    //scalaz.syntax.ToFoldable1Ops
    //scalaz.syntax.ToFoldable1Ops0
    //scalaz.syntax.ToFoldable1OpsU
    //scalaz.syntax.ToFoldableOps
    //scalaz.syntax.ToFoldableOps0
    //scalaz.syntax.ToFoldableOpsU
    //scalaz.syntax.ToFunctorOps
    //scalaz.syntax.ToFunctorOps0
    //scalaz.syntax.ToFunctorOpsU
    scalaz.syntax.ToIdOps
    //scalaz.syntax.ToInvariantAltOps
    //scalaz.syntax.ToInvariantAltOps0
    //scalaz.syntax.ToInvariantAltOpsU
    //scalaz.syntax.ToInvariantApplicativeOps
    //scalaz.syntax.ToInvariantApplicativeOps0
    //scalaz.syntax.ToInvariantApplicativeOpsU
    //scalaz.syntax.ToInvariantFunctorOps
    //scalaz.syntax.ToInvariantFunctorOps0
    //scalaz.syntax.ToInvariantFunctorOpsU
    //scalaz.syntax.ToIsContravariantOps
    //scalaz.syntax.ToIsContravariantOps0
    //scalaz.syntax.ToIsContravariantOpsU
    //scalaz.syntax.ToIsCovariantOps
    //scalaz.syntax.ToIsCovariantOps0
    //scalaz.syntax.ToIsCovariantOpsU
    //scalaz.syntax.ToIsEmptyOps
    //scalaz.syntax.ToIsEmptyOps0
    //scalaz.syntax.ToIsEmptyOpsU
    scalaz.syntax.ToKleisliOps
    scalaz.syntax.ToKleisliOps0
    scalaz.syntax.ToMaybeOps
    //scalaz.syntax.ToMonadErrorOps
    //scalaz.syntax.ToMonadErrorOps0
    //scalaz.syntax.ToMonadListenOps
    //scalaz.syntax.ToMonadListenOps0
    //scalaz.syntax.ToMonadOps
    //scalaz.syntax.ToMonadOps0
    //scalaz.syntax.ToMonadOpsU
    //scalaz.syntax.ToMonadPlusOps
    //scalaz.syntax.ToMonadPlusOps0
    //scalaz.syntax.ToMonadPlusOpsU
    //scalaz.syntax.ToMonadTellOps
    //scalaz.syntax.ToMonadTellOps0
    //scalaz.syntax.ToMonadTransOps
    scalaz.syntax.ToMonoidOps
    scalaz.syntax.ToNelOps
    //scalaz.syntax.ToNondeterminismOps
    //scalaz.syntax.ToNondeterminismOps0
    //scalaz.syntax.ToNondeterminismOpsU
    //scalaz.syntax.ToOptionalOps
    //scalaz.syntax.ToOptionalOps0
    //scalaz.syntax.ToOptionalOpsU
    scalaz.syntax.ToOrderOps
    //scalaz.syntax.ToPlusEmptyOps
    //scalaz.syntax.ToPlusEmptyOps0
    //scalaz.syntax.ToPlusEmptyOpsU
    //scalaz.syntax.ToPlusOps
    //scalaz.syntax.ToPlusOps0
    //scalaz.syntax.ToPlusOpsU
    //scalaz.syntax.ToProChoiceOps
    //scalaz.syntax.ToProChoiceOps0
    //scalaz.syntax.ToProChoiceOpsU
    //scalaz.syntax.ToProfunctorOps
    //scalaz.syntax.ToProfunctorOps0
    //scalaz.syntax.ToProfunctorOpsU
    scalaz.syntax.ToReducerOps
    scalaz.syntax.ToSemiLatticeOps
    scalaz.syntax.ToSemigroupOps
    scalaz.syntax.ToShowOps
    //scalaz.syntax.ToSplitOps
    //scalaz.syntax.ToSplitOps0
    //scalaz.syntax.ToSplitOpsU
    scalaz.syntax.ToStateOps
    scalaz.syntax.ToStrictTreeOps
    //scalaz.syntax.ToStrongOps
    //scalaz.syntax.ToStrongOps0
    //scalaz.syntax.ToStrongOpsU
    scalaz.syntax.ToTagOps
    scalaz.syntax.ToTheseOps
    //scalaz.syntax.ToTraverse1Ops
    //scalaz.syntax.ToTraverse1Ops0
    //scalaz.syntax.ToTraverse1OpsU
    //scalaz.syntax.ToTraverseOps
    //scalaz.syntax.ToTraverseOps0
    //scalaz.syntax.ToTraverseOpsU
    scalaz.syntax.ToTreeOps
    scalaz.syntax.ToTypeClassOps
    //scalaz.syntax.ToUnzipOps
    //scalaz.syntax.ToUnzipOps0
    //scalaz.syntax.ToUnzipOpsU
    scalaz.syntax.ToValidationOps
    scalaz.syntax.ToWriterOps
    //scalaz.syntax.ToZipOps
    //scalaz.syntax.ToZipOps0
    //scalaz.syntax.ToZipOpsU
    //scalaz.syntax.Traverse1Ops
    //scalaz.syntax.Traverse1Syntax
    //scalaz.syntax.TraverseOps
    //scalaz.syntax.TraverseSyntax
    //scalaz.syntax.TreeOps
    //scalaz.syntax.UnzipOps
    //scalaz.syntax.UnzipSyntax
    //scalaz.syntax.ValidationOps
    //scalaz.syntax.WriterOps
    //scalaz.syntax.ZipOps
    //scalaz.syntax.ZipSyntax
    //scalaz.syntax.std.BooleanOps
    //scalaz.syntax.std.BooleanOps2
    //scalaz.syntax.std.EitherOps
    //scalaz.syntax.std.Function1Ops
    //scalaz.syntax.std.Function2Ops
    //scalaz.syntax.std.LazyListOps
    //scalaz.syntax.std.ListOps
    //scalaz.syntax.std.MapOps
    //scalaz.syntax.std.OptionIdOps
    //scalaz.syntax.std.OptionOps
    //scalaz.syntax.std.OptionOps2
    //scalaz.syntax.std.SortedMapOps
    //scalaz.syntax.std.StreamOps
    //scalaz.syntax.std.StringOps
    scalaz.syntax.std.ToAllStdOps
    scalaz.syntax.std.ToBooleanOps
    scalaz.syntax.std.ToEitherOps
    scalaz.syntax.std.ToFunction1Ops
    scalaz.syntax.std.ToFunction2Ops
    scalaz.syntax.std.ToLazyListOps
    scalaz.syntax.std.ToListOps
    scalaz.syntax.std.ToMapOps
    scalaz.syntax.std.ToOptionIdOps
    scalaz.syntax.std.ToOptionOps
    scalaz.syntax.std.ToSortedMapOps
    scalaz.syntax.std.ToStreamOps
    scalaz.syntax.std.ToStringOps
    scalaz.syntax.std.ToTryOps
    scalaz.syntax.std.ToTupleOps
    scalaz.syntax.std.ToVectorOps
    //scalaz.syntax.std.TryOps
    //scalaz.syntax.std.Tuple10Ops
    //scalaz.syntax.std.Tuple11Ops
    //scalaz.syntax.std.Tuple12Ops
    //scalaz.syntax.std.Tuple2Ops
    //scalaz.syntax.std.Tuple3Ops
    //scalaz.syntax.std.Tuple4Ops
    //scalaz.syntax.std.Tuple5Ops
    //scalaz.syntax.std.Tuple6Ops
    //scalaz.syntax.std.Tuple7Ops
    //scalaz.syntax.std.Tuple8Ops
    //scalaz.syntax.std.Tuple9Ops
    //scalaz.syntax.std.VectorOps
    //scalaz.syntax.std.`try`
    scalaz.syntax.std.all
    scalaz.syntax.std.boolean
    scalaz.syntax.std.either
    scalaz.syntax.std.function1
    scalaz.syntax.std.function2
    scalaz.syntax.std.list
    scalaz.syntax.std.map
    scalaz.syntax.std.option
    scalaz.syntax.std.sortedMap
    scalaz.syntax.std.stream
    scalaz.syntax.std.string
    scalaz.syntax.std.tuple
    scalaz.syntax.std.vector
    scalaz.unused
  """)
}