package org.jetbrains.plugins.scala.semantic

import org.jetbrains.plugins.scala.DependencyManagerBase.RichStr
import org.jetbrains.plugins.scala.semantic.SemanticTestBase.scalaVersion
import org.junit.Test

class ScalacticSemanticTest extends SemanticTestBase("org.scalactic" %% "scalactic" % "3.2.19")("org.scalactic") {
//  @Test def single(): Unit = doTest("")

  @Test def test(): Unit = doTest("""
    org.scalactic.AbstractStringUniformity
    //org.scalactic.Accumulation
    //org.scalactic.AccumulationLowPriorityImplicits
    org.scalactic.AndBool
    //org.scalactic.AnyDiffer
    //org.scalactic.ArrayHelper
    //org.scalactic.Bad
    //org.scalactic.BasicPrettifier
    //org.scalactic.BinaryMacroBool
    //org.scalactic.Bool
    //org.scalactic.BooleanMacro
    org.scalactic.CanEqual
    org.scalactic.Catcher
    //org.scalactic.ColCompatHelper
    org.scalactic.ComposedNormalizingEquality
    org.scalactic.ComposedNormalizingEquivalence
    //org.scalactic.DefaultEquality
    //org.scalactic.DefaultPrettifier
    //org.scalactic.Differ
    //org.scalactic.EitherSugar
    //org.scalactic.Equality
    org.scalactic.Equivalence
    //org.scalactic.Every
    org.scalactic.ExistsMacroBool
    org.scalactic.Explicitly
    org.scalactic.Fail
    org.scalactic.FailureMessages
    //org.scalactic.FutureSugar
    //org.scalactic.GenMapDiffer
    //org.scalactic.GenSeqDiffer
    //org.scalactic.GenSetDiffer
    //org.scalactic.Good
    org.scalactic.IsInstanceOfMacroBool
    org.scalactic.LengthSizeMacroBool
    org.scalactic.LowPriorityTypeCheckedConstraint
    //org.scalactic.Many
    //org.scalactic.MapEqualityConstraints
    //org.scalactic.NameUtil
    org.scalactic.NormMethods
    org.scalactic.Normalization
    //org.scalactic.NormalizingEquality
    //org.scalactic.NormalizingEquivalence
    org.scalactic.NotBool
    org.scalactic.NumericEqualityConstraints
    //org.scalactic.ObjectDiffer
    //org.scalactic.One
    //org.scalactic.OptionSugar
    //org.scalactic.Or
    org.scalactic.OrBool
    org.scalactic.Pass
    //org.scalactic.Prettifier
    //org.scalactic.PrettyMethods
    org.scalactic.PrettyPair
    //org.scalactic.Requirements
    //org.scalactic.RequirementsMacro
    //org.scalactic.Resources
    org.scalactic.ScalacticVersions
    //org.scalactic.SeqEqualityConstraints
    //org.scalactic.SetEqualityConstraints
    //org.scalactic.SimpleBool
    org.scalactic.SimpleMacroBool
    org.scalactic.SizeLimit
    org.scalactic.Snapshot
    //org.scalactic.SnapshotSeq
    //org.scalactic.Snapshots
    //org.scalactic.SnapshotsMacro
    //org.scalactic.StringDiffer
    org.scalactic.StringNormalizations
    org.scalactic.TimesOnInt
    //org.scalactic.Tolerance
    //org.scalactic.TolerantNumerics
    org.scalactic.TraversableEqualityConstraints
    org.scalactic.TripleEquals
    //org.scalactic.TripleEqualsSupport
    //org.scalactic.TruncatingPrettifier
    //org.scalactic.TrySugar
    org.scalactic.TypeCheckedTripleEquals
    org.scalactic.UnaryMacroBool
    org.scalactic.Uniformity
    org.scalactic.UnquotedString
    org.scalactic.Validation
    //org.scalactic.anyvals.CompileTimeAssertions
    org.scalactic.anyvals.End
    //org.scalactic.anyvals.FiniteDouble
    //org.scalactic.anyvals.FiniteDoubleMacro
    //org.scalactic.anyvals.FiniteFloat
    //org.scalactic.anyvals.FiniteFloatMacro
    //org.scalactic.anyvals.NegDouble
    //org.scalactic.anyvals.NegDoubleMacro
    //org.scalactic.anyvals.NegFiniteDouble
    //org.scalactic.anyvals.NegFiniteDoubleMacro
    //org.scalactic.anyvals.NegFiniteFloat
    //org.scalactic.anyvals.NegFiniteFloatMacro
    //org.scalactic.anyvals.NegFloat
    //org.scalactic.anyvals.NegFloatMacro
    //org.scalactic.anyvals.NegInt
    //org.scalactic.anyvals.NegIntMacro
    //org.scalactic.anyvals.NegLong
    //org.scalactic.anyvals.NegLongMacro
    //org.scalactic.anyvals.NegZDouble
    //org.scalactic.anyvals.NegZDoubleMacro
    //org.scalactic.anyvals.NegZFiniteDouble
    //org.scalactic.anyvals.NegZFiniteDoubleMacro
    //org.scalactic.anyvals.NegZFiniteFloat
    //org.scalactic.anyvals.NegZFiniteFloatMacro
    //org.scalactic.anyvals.NegZFloat
    //org.scalactic.anyvals.NegZFloatMacro
    //org.scalactic.anyvals.NegZInt
    //org.scalactic.anyvals.NegZIntMacro
    //org.scalactic.anyvals.NegZLong
    //org.scalactic.anyvals.NegZLongMacro
    //org.scalactic.anyvals.NonEmptyArray
    //org.scalactic.anyvals.NonEmptyList
    //org.scalactic.anyvals.NonEmptyMap
    //org.scalactic.anyvals.NonEmptySet
    //org.scalactic.anyvals.NonEmptyString
    //org.scalactic.anyvals.NonEmptyVector
    //org.scalactic.anyvals.NonZeroDouble
    //org.scalactic.anyvals.NonZeroDoubleMacro
    //org.scalactic.anyvals.NonZeroFiniteDouble
    //org.scalactic.anyvals.NonZeroFiniteDoubleMacro
    //org.scalactic.anyvals.NonZeroFiniteFloat
    //org.scalactic.anyvals.NonZeroFiniteFloatMacro
    //org.scalactic.anyvals.NonZeroFloat
    //org.scalactic.anyvals.NonZeroFloatMacro
    //org.scalactic.anyvals.NonZeroInt
    //org.scalactic.anyvals.NonZeroIntMacro
    //org.scalactic.anyvals.NonZeroLong
    //org.scalactic.anyvals.NonZeroLongMacro
    //org.scalactic.anyvals.NumericChar
    //org.scalactic.anyvals.NumericCharMacro
    //org.scalactic.anyvals.NumericString
    //org.scalactic.anyvals.NumericStringMacro
    //org.scalactic.anyvals.PercentageInt
    //org.scalactic.anyvals.PercentageIntMacro
    //org.scalactic.anyvals.PosDouble
    //org.scalactic.anyvals.PosDoubleMacro
    //org.scalactic.anyvals.PosFiniteDouble
    //org.scalactic.anyvals.PosFiniteDoubleMacro
    //org.scalactic.anyvals.PosFiniteFloat
    //org.scalactic.anyvals.PosFiniteFloatMacro
    //org.scalactic.anyvals.PosFloat
    //org.scalactic.anyvals.PosFloatMacro
    //org.scalactic.anyvals.PosInt
    //org.scalactic.anyvals.PosIntMacro
    //org.scalactic.anyvals.PosLong
    //org.scalactic.anyvals.PosLongMacro
    //org.scalactic.anyvals.PosZDouble
    //org.scalactic.anyvals.PosZDoubleMacro
    //org.scalactic.anyvals.PosZFiniteDouble
    //org.scalactic.anyvals.PosZFiniteDoubleMacro
    //org.scalactic.anyvals.PosZFiniteFloat
    //org.scalactic.anyvals.PosZFiniteFloatMacro
    //org.scalactic.anyvals.PosZFloat
    //org.scalactic.anyvals.PosZFloatMacro
    //org.scalactic.anyvals.PosZInt
    //org.scalactic.anyvals.PosZIntMacro
    //org.scalactic.anyvals.PosZLong
    //org.scalactic.anyvals.PosZLongMacro
    //org.scalactic.anyvals.RegexString
    //org.scalactic.anyvals.RegexStringMacro
    org.scalactic.exceptions.NullArgumentException
    org.scalactic.exceptions.ValidationFailedException
    //org.scalactic.source.ObjectMeta
    //org.scalactic.source.Position
    //org.scalactic.source.TypeInfo
    //org.scalactic.source.TypeInfoMacro
  """)
}