package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_11.scalatest2_1_7

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestWholeSuiteTest

class Scalatest2_11_2_1_7_WholeSuiteTest extends Scalatest2_11_2_1_7_Base with ScalaTestWholeSuiteTest
