package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_11.scalatest2_1_7

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestNestedSameNamesTest

class Scalatest2_11_2_1_7_NestedSameNamesTest extends Scalatest2_11_2_1_7_Base with ScalaTestNestedSameNamesTest
