package org.jetbrains.plugins.scala.compiler.highlighting.core

import com.intellij.openapi.vfs.VirtualFile
import org.jetbrains.plugins.scala.compiler.highlighting.core.{FileCompilerGeneratedState, HighlightingState}

/**
 * Compiler results accumulated per file, across compilations: `files` keeps an entry for every file any
 * compilation has reported on, each stamped with the compilation that last touched it, so entries for
 * different files can come from different compilations.
 *
 * How far the compilation currently running has got is not part of this: it belongs to one compilation
 * rather than accumulating, and lives in
 * [[org.jetbrains.plugins.scala.compiler.highlighting.services.ProjectProgressService]].
 *
 * @param files state for each file generated by compiler
 * @param highlightOnCompilationFinished files that we must highlight only when compilation finished
 */
case class CompilerGeneratedState(files: Map[VirtualFile, FileCompilerGeneratedState],
                                  highlightOnCompilationFinished: Set[VirtualFile]) {

  def toHighlightingState: HighlightingState = HighlightingState(files)
}
