package org.jetbrains.plugins.scala.testingSupport.utest.scala2_12

import org.jetbrains.plugins.scala.testingSupport.utest.UTestNewSyntaxSimpleTest

class UTestSimpleTest_2_12 extends UTestTestBase_2_12 with UTestNewSyntaxSimpleTest