package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_11.scalatest3_0_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestWholeSuiteTest

class Scalatest2_11_3_0_1_WholeSuiteTest extends Scalatest2_11_3_0_1_Base with ScalaTestWholeSuiteTest
