package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_11.scalatest3_0_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestIgnoredSpecTest

class Scalate2_11_3_0_1_IgnoredTestTest extends Scalatest2_11_3_0_1_Base with ScalaTestIgnoredSpecTest
