package org.jetbrains.plugins.scala.worksheet.ui.dialog;

import com.intellij.psi.PsiFile;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * User: Dmitry.Naydanov
 */
public class WorksheetAllSettingsForm {
  private JTabbedPane tabbedPane;
  private JPanel panel1;

  private final WorksheetSettingsSetForm currentFileSettingsForm;
  private final WorksheetSettingsSetForm defaultSettingsForm;

  public WorksheetAllSettingsForm(PsiFile myFile, WorksheetSettingsData currentSettings, WorksheetSettingsData defaultSettings) {
    currentFileSettingsForm = new WorksheetSettingsSetForm(myFile, currentSettings);
    defaultSettingsForm = new WorksheetSettingsSetForm(myFile.getProject(), defaultSettings);

    tabbedPane.removeAll();

    tabbedPane.addTab("Settings for " + myFile.getName(), currentFileSettingsForm.getMainPanel());
    tabbedPane.addTab("Default settings", defaultSettingsForm.getMainPanel());
  }

  public JPanel getMainPanel() {
    return panel1;
  }

  public WorksheetSettingsData getFileSettings() {
    return currentFileSettingsForm.getSettings();
  }

  public WorksheetSettingsData getDefaultSettings() {
    return defaultSettingsForm.getSettings();
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    final JTabbedPane tabbedPane1 = new JTabbedPane();
    panel1.add(tabbedPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    tabbedPane1.addTab("Untitled", panel2);
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    tabbedPane1.addTab("Untitled", panel3);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return panel1;
  }
}
