package org.jetbrains.plugins.scala.codeInspection.feature

import org.jetbrains.plugins.scala.codeInspection.ScalaInspectionTestBase

abstract class LanguageFeatureInspectionTestBase extends ScalaInspectionTestBase