package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_10.scalatest2_1_7

import org.jetbrains.plugins.scala.testingSupport.scalatest.ScalaTestDuplicateConfigTest

class Scalatest2_10_2_1_7_DuplicateConfigTest extends Scalatest2_10_2_1_7_Base with ScalaTestDuplicateConfigTest
