package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_10.scalatest2_1_7

import org.jetbrains.plugins.scala.testingSupport.scalatest.ScalaTestWholeSuiteTest

class Scalatest2_10_2_1_7_WholeSuiteTest extends Scalatest2_10_2_1_7_Base with ScalaTestWholeSuiteTest