package org.jetbrains.bsp.protocol

import com.intellij.openapi.progress.ProgressIndicator
import com.intellij.platform.eel.EelDescriptor
import org.jetbrains.bsp.{BspBundle, BspJdkUtil}
import org.jetbrains.bsp.project.importing.bspConfigSteps
import org.jetbrains.bsp.project.importing.bspConfigSteps.{ConfigSetup, ScalaCliSetup}
import org.jetbrains.bsp.project.importing.experimental.GenerateBspConfig
import org.jetbrains.bsp.project.importing.setup.{BspConfigSetup, NoConfigSetup}
import org.jetbrains.bsp.protocol.BspCommunication.SessionContext
import org.jetbrains.bsp.settings.BspProjectSettings
import org.jetbrains.plugins.scala.build.BuildReporter

import java.nio.file.Path

private[protocol] object BspConfigRegeneration {

  /**
   * Regenerates the BSP connection file if a suitable [[BspConfigSetup]] is detected.
   *
   * After regeneration, adjusts [[BspProjectSettings.serverConfig]] so that it points to the
   * correct connection file. This is necessary because regeneration may create a new file
   * and a stale `serverConfig` reference could cause BSP session startup to fail anyway (see [[BspCommunication.prepareSession]]).
   *
   * @see [[GenerateBspConfig#adjustServerConfigAfterRegeneration]]
   * @return new hash calculated for the BSP connection files after regeneration (see [[BspConnectionConfig.workspaceBspConfigsHash]]),
   *         `None` if skipped
   */
  def regenerateBspConfig(base: Path, reason: RegenerationReason)(using ctx: SessionContext)(using BuildReporter, EelDescriptor): Option[Int] = {
    if (ctx.indicator.isEmpty || ctx.serverConfig == BspProjectSettings.BloopConfig) return None

    resolveSetup(base).map { (setupChoice, setup) =>
      val snapshot = GenerateBspConfig.ConnectionFileSnapshot(base)

      val bspConnectionFiles = snapshot.filesBefore.toSeq
      val newHash = runGeneration(base, setupChoice, setup, bspConnectionFiles, ctx.indicator.get, reason)

      val changes = snapshot.complete()
      // NOTE: adjusting BSP project settings inside `BspCommunication` comes with a trade-off.
      // Since `BspCommunication` instances are stored in `BspCommunicationService.comms`
      // by project base path and config type, changing the `serverConfig` type
      // in the settings will cause a new `BspCommunication` instance to be created on the next session acquisition.
      // I don't see a benefit in storing communication instances per config type. We do not support
      // switching between sessions or using multiple sessions for the same external project anyway.
      // `BspCommunication` instances should probably be stored only by project path to ensure that there is
      // at most one communication instance per external project.
      ctx.bspProjectSettings.foreach(GenerateBspConfig.adjustServerConfigAfterRegeneration(_, changes))

      newHash
    }
  }

  /**
   * Resolves the BSP config setup to use for generation.
   * Returns `None` if there isn't exactly one setup choice, no JDK is available, or the resolved setup is [[NoConfigSetup]].
   */
  private def resolveSetup(base: Path)(using ctx: SessionContext, eelDescriptor: EelDescriptor): Option[(ConfigSetup, BspConfigSetup)] = {
    val setupChoices = bspConfigSteps.workspaceSetupChoices(base)
    if (setupChoices.size != 1) return None

    for {
      jdk <- BspJdkUtil.findOrCreateBestJdkForProject(ctx.project, eelDescriptor)
      setupChoice = setupChoices.head
      (setup, _) = bspConfigSteps.getBspConfigurationForRegeneration(jdk, base, setupChoice)
      if setup != NoConfigSetup
    } yield (setupChoice, setup)
  }

  /**
   * Runs the BSP config generation using the given [[BspConfigSetup]].
   *
   * After generation completes, displays a notification if all the following conditions are met:
   *  - BSP connection files already existed before generation
   *  - the connection file content was changed externally since the last recorded hash,
   *    or the config wasn't generated by the plugin  ([[BspProjectSettings#bspConfigGenerated]] is `false`)
   *  - the generation actually changes the files (the hash before and after differs).
   *
   * @return new hash calculated for the BSP connection files after regeneration (see [[BspConnectionConfig.workspaceBspConfigsHash]])
   */
  private def runGeneration(
    base: Path,
    setupChoice: ConfigSetup,
    setup: BspConfigSetup,
    bspConnectionFiles: Seq[Path],
    indicator: ProgressIndicator,
    reason: RegenerationReason
  )(using ctx: SessionContext, reporter: BuildReporter): Int = {
    val beforeGenerationHash = BspConnectionConfig.workspaceBspConfigsHash(base)
    val hasBspConfigs = bspConnectionFiles.nonEmpty
    val showNotification = hasBspConfigs && ctx.bspProjectSettings.exists { s =>
      // If the `beforeGenerationHash` is different from the saved hash, it means that the connection file was changed externally (e.g., by the user)
      val isHashDifferent = Option(s.connectionFileHash).exists(_ != beforeGenerationHash)
      isHashDifferent || !s.bspConfigGenerated
    }

    val targetConnectionFileName =
      if (setupChoice == ScalaCliSetup && hasBspConfigs) resolveTargetConnectionFileName(bspConnectionFiles)
      else None

    if reason == RegenerationReason.ServerFailure then
      reporter.log(BspBundle.message("bsp.protocol.server.failed"))

    setup.run(indicator, targetConnectionFileName)

    val afterGenerationHash = BspConnectionConfig.workspaceBspConfigsHash(base)
    val hashChanged = beforeGenerationHash != afterGenerationHash

    if (showNotification && hashChanged) {
      ctx.project.foreach: project =>
        val service = BspConnectionFileNotificationService.getInstance(project)
        service.showConfigChangedNotification(base, reason)
    }

    afterGenerationHash
  }

  /**
   * Resolves the name of the BSP connection file that should be preserved during regeneration.
   *
   * This is only relevant for Scala CLI, which has two installation kinds (Bundled and Standalone)
   * that produce different connection file names (`scala.json`/`scala-cli.json`).
   *
   * @see [[org.jetbrains.bsp.project.importing.setup.CommandBasedBspConfigSetup#ConnectionTarget]]
   */
  private def resolveTargetConnectionFileName(bspConnectionFiles: Seq[Path])(using ctx: SessionContext): Option[String] =
    ctx.serverConfig match {
      case BspProjectSettings.BspConfigFile(path) =>
        Some(path.getFileName.toString)
      // When config == AutoConfig, we can only derive the target connection file name
      // if a single file is present. When multiple connection files exist,
      // the BSP logic picks the first one when creating a BSP session, but it is not clear which file that will be.
      case BspProjectSettings.AutoConfig if bspConnectionFiles.size == 1 =>
        Some(bspConnectionFiles.head.getFileName.toString)
      case _ => None
    }

  /**
   * Describes why BSP config regeneration was triggered.
   *
   * Used by [[BspConnectionFileNotificationService.showConfigChangedNotification]] to customize the notification.
   */
  sealed trait RegenerationReason
  object RegenerationReason {
    /** [[BspProjectSettings#autoRegenerateBspConfigOnServerStartup]] is enabled. */
    case object BeforeServerStartup extends RegenerationReason
    /** BSP server failed to start. */
    case object ServerFailure extends RegenerationReason
  }
}
