package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_13.scalatest3_0_8

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestSpecialCharactersTest

class Scalatest2_13_3_0_8_SpecialCharactersTest extends Scalatest2_13_3_0_8_Base with ScalaTestSpecialCharactersTest
