package org.jetbrains.plugins.scala.bazel

import org.jetbrains.bazel.java.ui.gutters.BazelJavaRunLineMarkerContributor

class BazelScalaRunLineMarkerContributor extends BazelJavaRunLineMarkerContributor
