package org.jetbrains.plugins.scala.testingSupport.utest.scala2_12.utest_0_7_4.old_syntax

import org.jetbrains.plugins.scala.testingSupport.utest.UTestSimpleTest
import org.jetbrains.plugins.scala.testingSupport.utest.scala2_12.utest_0_7_4

class UTestSimpleTest_2_12_0_7_4_old_syntax extends utest_0_7_4.UTestTestBase_2_12_0_7_4 with UTestSimpleTest