package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_12.scalatest3_0_4

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestDuplicateConfigTest

class Scalatest2_12_3_0_4_DuplicateConfigTest extends Scalatest2_12_3_0_4_Base with ScalaTestDuplicateConfigTest
