package org.jetbrains.plugins.scala.uast

import com.intellij.lang.Language
import com.intellij.platform.uast.testFramework.common.AllUastTypesKt.allUElementSubtypes
import junitparams.JUnitParamsRunner
import org.jetbrains.plugins.scala.base.SdkFileSetTestBase
import org.jetbrains.plugins.scala.extensions._
import org.jetbrains.plugins.scala.lang.psi.uast.withPossibleSourceTypesCheck
import org.jetbrains.plugins.scala.util.{Annotations, TestUtils}
import org.jetbrains.plugins.scala.{Scala3Language, ScalaLanguage, ScalaVersion}
import org.jetbrains.uast.UElement
import org.junit.Ignore
import org.junit.runner.{Computer, JUnitCore, RunWith, Runner}
import org.junit.runners.model.{FrameworkMethod, RunnerBuilder}

import java.nio.file.{Files, Path, Paths}
import java.text.SimpleDateFormat
import java.util.Calendar
import scala.collection.mutable
import scala.jdk.CollectionConverters.IterableHasAsScala
import scala.util.Try

/**
 * Run this to generate [[org.jetbrains.plugins.scala.uast.ScalaUastSourceTypeMapping]]
 */
object GeneratePossibleSourceTypesMapping {
  private val format = new SimpleDateFormat("HH:mm:ss.SSS")

  private def log(message: String): Unit =
    println(s"[${format.format(Calendar.getInstance().getTime)}] $message")

  val mappingOutputPath: Path =
    Paths.get(TestUtils.findCommunityRoot)
      .resolve("scala/uast/src/org/jetbrains/plugins/scala/uast/ScalaUastSourceTypeMapping.scala")

  def main(args: Array[String]): Unit = {
    try run()
    finally System.exit(0)
  }

  private def run(): Unit = {
    log("Gather mapping...")
    val mappings = gatherMapping()
    log(s"Finished. Found ${mappings.size} mappings.")

    val mappingsText = new StringBuilder

    for ((from, to) <- mappings.toSeq.sortBy(_._1)) {
      mappingsText ++= s"    classOf[$from] -> ClassSetKt.classSetOf(\n"

      for (toElem <- to.toSeq.sorted) {
        val txt = toElem match {
          case "ScFunctionDeclarationImpl" => "ScFunctionDeclarationImpl[_]"
          case "ScFunctionDefinitionImpl" => "ScFunctionDefinitionImpl[_]"
          case txt => txt
        }
        mappingsText ++= s"      classOf[$txt],\n"
      }

      mappingsText ++= s"    ),\n"
    }

    log("Print...")
    Files.writeString(
      mappingOutputPath,
      s"""package org.jetbrains.plugins.scala.uast
         |
         |import com.intellij.psi._
         |import com.intellij.psi.impl.source.tree.LeafPsiElement
         |import org.jetbrains.plugins.scala.lang.psi.impl._
         |import org.jetbrains.plugins.scala.lang.psi.impl.base._
         |import org.jetbrains.plugins.scala.lang.psi.impl.base.literals._
         |import org.jetbrains.plugins.scala.lang.psi.impl.base.patterns._
         |import org.jetbrains.plugins.scala.lang.psi.impl.base.types._
         |import org.jetbrains.plugins.scala.lang.psi.impl.expr._
         |import org.jetbrains.plugins.scala.lang.psi.impl.statements._
         |import org.jetbrains.plugins.scala.lang.psi.impl.statements.params._
         |import org.jetbrains.plugins.scala.lang.psi.impl.toplevel.imports._
         |import org.jetbrains.plugins.scala.lang.psi.impl.toplevel.templates._
         |import org.jetbrains.plugins.scala.lang.psi.impl.toplevel.typedef._
         |import org.jetbrains.plugins.scala.lang.scaladoc.psi.impl._
         |import org.jetbrains.uast._
         |import org.jetbrains.uast.expressions.UInjectionHost
         |import org.jetbrains.uast.util.{ClassSet, ClassSetKt}
         |
         |/**
         | * !!! ATTENTION !!!<br>
         | * This file is generated by org.jetbrains.plugins.scala.uast.GeneratePossibleSourceTypesMapping
         | */
         |object ScalaUastSourceTypeMapping {
         |  def canConvert(element: PsiElement, targets: Array[Class[_ <: UElement]]): Boolean = {
         |    val clazz = element.getClass
         |    targets.exists(target => possibleSourceTypes(target).contains(clazz))
         |  }
         |
         |  def possibleSourceTypes(uastType: Class[_ <: UElement]): ClassSet[PsiElement] =
         |    mapping.getOrElse(uastType, ClassSetKt.emptyClassSet())
         |
         |  private val mapping: Map[Class[_ <: UElement], ClassSet[PsiElement]] = Map(
         |$mappingsText
         |  )
         |}
         |""".stripMargin
    )
    log("Done.")
  }

  // This is essentially a static reference to a mutable map.
  // This is a way to return a result from a Unit method (runTest).
  // The map cannot be provided as a class parameter because each of the GatheringTestSuite implementations
  //  needs to be a proper JUnit class with a zero-argument constructor.
  object GatheringTestSuiteMapping {
    val mapping: mutable.Map[String, Set[String]] = mutable.Map.empty

    def add(classOfUElement: String, classOfElement: String): Unit = {
      mapping.updateWith(classOfUElement) { set =>
        if (!set.exists(_.contains(classOfElement))) {
          log(s"    Found $classOfUElement -> $classOfElement")
        }
        Some(set.getOrElse(Set.empty) + classOfElement)
      }
    }
  }

  private def gatherMapping(): Map[String, Set[String]] = {
    abstract class GatheringTestSuite(path: Path, lang: Language, extensions: String*) extends SdkFileSetTestBase {
      private val excluded: Set[String] = Set(
        "large.test", "large2.test" // they're just very large with ~10k references/definitions
      )

      override protected def supportedIn(version: ScalaVersion): Boolean =
        version == ScalaVersion.Latest.Scala_2_13

      override protected def relativeTestDataPath: Path = path

      override protected def transform(testName: String, fileText: String): String = fileText

      override protected def language: Language = lang

      override protected def testFileExtensions: Seq[String] = extensions.toSeq

      override protected def runTest(testName: String, fileText: String): Unit = if (!excluded(testName)) {
        withPossibleSourceTypesCheck {
          log(s"Gathering from $testName")
          val file = createLightFile(fileText)
          val plugin = new ScalaUastLanguagePlugin
          for (element <- file.depthFirst()) {
            val classOfElement = element.getClass.getSimpleName
            for {
              expectedUClass <- allUElementSubtypes.asScala
              uElement <- Try(plugin.convertElementWithParent[UElement](element, Array(expectedUClass))).toOption
              uClass <- allUElementSubtypes.asScala if uClass.isInstance(uElement)
            } {
              val classOfUElement = uClass.getSimpleName
              GatheringTestSuiteMapping.add(classOfUElement, classOfElement)
            }
          }
        }
      }
    }

    @Ignore("for local running only")
    class Scala2ParserData extends GatheringTestSuite(Path.of("parser", "data"), ScalaLanguage.INSTANCE, ".test")

    @Ignore("for local running only")
    class Scala2Sources extends GatheringTestSuite(Path.of("..", "src"), ScalaLanguage.INSTANCE, ".scala")

    @Ignore("for local running only")
    class Scala3ParserLts extends GatheringTestSuite(Path.of("parser", "scala3Import", "lts", "success"), Scala3Language.INSTANCE, ".test")

    @Ignore("for local running only")
    class Scala3ParserNewest extends GatheringTestSuite(Path.of("parser", "scala3Import", "newest", "success"), Scala3Language.INSTANCE, ".test")

    def runScript(testClass: Class[?]): Unit = {
      Annotations.findAnnotation(testClass, classOf[RunWith]) match {
        case Some(annotation) =>
          val correct = annotation.value() == classOf[JUnitParamsRunner]
          if (!correct) {
            sys.error(s"The test class ${testClass.getName} must be annotated with `@RunWith(classOf[JUnitParamsRunner])`")
          }
        case None =>
          sys.error(s"The test class ${testClass.getName} must be annotated with `@RunWith(classOf[JUnitParamsRunner])`")
      }

      // A hack to ignore the @Ignore annotation, otherwise the test class would not be executed by the JUnit 4 machinery.
      val computer = new Computer() {
        override def getRunner(builder: RunnerBuilder, testClass: Class[_]): Runner = new JUnitParamsRunner(testClass) {
          override def isIgnored(child: FrameworkMethod): Boolean = false
        }
      }

      val result = JUnitCore.runClasses(computer, testClass)
      result.getFailures.asScala.headOption match {
        case Some(failure) => throw failure.getException
        case None =>
      }
    }

    try {
      runScript(classOf[Scala2ParserData])
      runScript(classOf[Scala2Sources])
      runScript(classOf[Scala3ParserLts])
      runScript(classOf[Scala3ParserNewest])
    } catch {
      case t: Throwable =>
        t.printStackTrace()
    }

    if (GatheringTestSuiteMapping.mapping.sizeIs < 10) {
      System.err.println(
        """#####################################################################################
          |# Inner tests were not run...
          |# After creating the GeneratePossibleSourceTypesMapping run configuration, it needs to be edited
          |# to be properly configured. Please do the following steps:
          |#   1. Run any other test in the IDE to generate a Run Configuration for it. For example, run
          |#      `org.jetbrains.plugins.scala.uast.ScalaPossibleSourceTypesTest` which is in the same directory as
          |#      this script.
          |#   2. Set JBR as the JDK used for running the GeneratePossibleSourceTypesMapping. JBR needs to be used
          |#      because the script runs the whole IDE.
          |#   3. Choose scalaUltimate.test in the -cp dropdown.
          |#   4. From the Run Configuration of the other test you just ran, copy the whole contents of the VM Options
          |#      field. It looks something like: -cp "" @<some path on your machine>/junit_template_argfile.txt into
          |#      the VM Options field of the GeneratePossibleSourceTypesMapping Run Configuration. If the VM Options
          |#      field is not visible, you need to make it visible by clicking the Modify Options link and selecting
          |#      Add VM Options. Then simply paste the contents inside.
          |#####################################################################################
          |""".stripMargin.trim
      )
      System.exit(1)
    }

    GatheringTestSuiteMapping.mapping.toMap
  }
}
