package org.jetbrains.bsp.projectHighlighting

import org.jetbrains.plugins.scala.projectHighlighting.base.ScalaProjectHighlightingTestBase

abstract class SbtOverBspProjectHighlightingTestBase
  extends ScalaProjectHighlightingTestBase
    with SbtOverBspExternalSystemImportingTestCase
