package org.jetbrains.plugins.scala.testingSupport.scalatest.scala2_13.scalatest3_1_1

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestDuplicateConfigTest

class Scalatest2_13_3_1_1_DuplicateConfigTest extends Scalatest2_13_3_1_1_Base
  with ScalaTestDuplicateConfigTest
