package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_2.scala_3

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestPackageTest

class Scalatest_3_2_Scala_3_PackageTest extends Scalatest_3_2_Scala_3_Base
  with ScalaTestPackageTest

class Scalatest_3_2_Scala_3_RC_PackageTest extends Scalatest_3_2_Scala_3_RC_Base
  with ScalaTestPackageTest
