package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_2.scala_3

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestWholeSuiteTest

class Scalatest_3_2_Scala_3_WholeSuiteTest extends Scalatest_3_2_Scala_3_Base
  with ScalaTestWholeSuiteTest

class Scalatest_3_2_Scala_3_RC_WholeSuiteTest extends Scalatest_3_2_Scala_3_RC_Base
  with ScalaTestWholeSuiteTest
