package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_2.scala_3

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestSpecialCharactersTest

class Scalatest_3_2_Scala_3_SpecialCharactersTest extends Scalatest_3_2_Scala_3_Base
  with ScalaTestSpecialCharactersTest

class Scalatest_3_2_Scala_3_RC_SpecialCharactersTest extends Scalatest_3_2_Scala_3_RC_Base
  with ScalaTestSpecialCharactersTest
