package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_2.scala_3

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestIgnoredSpecTest

class Scalatest_3_2_Scala_3_IgnoredTestTest extends Scalatest_3_2_Scala_3_Base
  with ScalaTestIgnoredSpecTest

class Scalatest_3_2_Scala_3_RC_IgnoredTestTest extends Scalatest_3_2_Scala_3_RC_Base
  with ScalaTestIgnoredSpecTest
