package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_2.scala_3

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestGoToSourceTest

class Scalatest_3_2_Scala_3_GoToSourceTest extends Scalatest_3_2_Scala_3_Base
  with ScalaTestGoToSourceTest

class Scalatest_3_2_Scala_3_RC_GoToSourceTest extends Scalatest_3_2_Scala_3_RC_Base
  with ScalaTestGoToSourceTest
