package org.jetbrains.plugins.scala.testingSupport.scalatest.scalatest_3_2.scala_3

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestDuplicateConfigTest

class Scalatest_3_2_Scala_3_DuplicateConfigTest extends Scalatest_3_2_Scala_3_Base
  with ScalaTestDuplicateConfigTest

class Scalatest_3_2_Scala_3_RC_DuplicateConfigTest extends Scalatest_3_2_Scala_3_RC_Base
  with ScalaTestDuplicateConfigTest
