package org.jetbrains.plugins.scala.testingSupport.scalatest.scala3_1.scalatest3_2

import org.jetbrains.plugins.scala.testingSupport.scalatest.base.ScalaTestNestedSameNamesTest

class Scalatest3_1_3_2_NestedSameNamesTest extends Scalatest3_1_3_2_Base
  with ScalaTestNestedSameNamesTest
